### ISSUE TITLE
UnhandledRejection in /explore

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1008]
## Error in Plant-for-the-Planet App

**UnhandledRejection** in **/explore**
Rejection reason was not an Error. See "Promise" tab for more detail.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d05f81ab3cb100019330da9?event_id=5d17ec2c00461dd351550000&i=gh&m=ci)

## Stacktrace

    unknown file:0 - unknown method

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d05f81ab3cb100019330da9?event_id=5d17ec2c00461dd351550000&i=gh&m=ci)

*Created by Norbert Schuler via Bugsnag*

**Comment by Plant-for-the-Planet** [comment]
probably more try/catch statements or .then().catch() constructs should be used for catching reje...

Comment added in Bugsnag by Norbert Schuler
[**UnhandledRejection** in **/signup**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d05f81ab3cb100019330da9?event_id=5d40bb8d004bd1fbf3d10000&i=gh&m=cm)

**Comment by norbertschuler** [comment]
Promises get caught now.
