### ISSUE TITLE
Invariant Violation in /app_dev.php/my-trees

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1011]
## Error in Plant-for-the-Planet App

**Invariant Violation** in **/app_dev.php/my-trees**
ContributionCardList(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d1533b457bdd100183e4f75?event_id=5d1533b40046028461bd0000&i=gh&m=ci)

## Stacktrace

    http://localhost:8080/bundle.js:70044 - invariant

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d1533b457bdd100183e4f75?event_id=5d1533b40046028461bd0000&i=gh&m=ci)

*Created by Norbert Schuler via Bugsnag*

**Comment by norbertschuler** [comment]
this was on a dev server - do not debug this
