### ISSUE TITLE
InvalidPointerId in /register-trees

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1016]
## Error in Plant-for-the-Planet App

**InvalidPointerId** in **/register-trees**
Invalid pointer id.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d19e5b282179c001810d185?event_id=5d19e5b200464420173f0000&i=gh&m=ci)

## Stacktrace

    https://js.arcgis.com/4.7/esri/views/MapView.js:687 - esri/views/input/BrowserEventSource/</p</b.prototype.setPointerCapture

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d19e5b282179c001810d185?event_id=5d19e5b200464420173f0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Similar to #1023

**Comment by Plant-for-the-Planet** [comment]
ignoring Arcgis errors

Comment added in Bugsnag by Norbert Schuler
[**InvalidPointerId** in **/explore**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d19e5b282179c001810d185?event_id=5d612941004db6c578a60000&i=gh&m=cm)

**Comment by Plant-for-the-Planet** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**InvalidPointerId** in **/explore**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d19e5b282179c001810d185?event_id=5d612941004db6c578a60000&i=gh&m=fx)
