### ISSUE TITLE
Error in /pledge/kirchentag

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1018]
## Error in Plant-for-the-Planet App

**Error** in **/pledge/kirchentag**
Network Error

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d1a3f0712aa860018bf43b4?event_id=5d1a3f070046881758f30000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/bundle.js:28 - e.exports

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d1a3f0712aa860018bf43b4?event_id=5d1a3f070046881758f30000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Already have other network error where I wrote these shouldn't result into Bugsnag issues.
