### ISSUE TITLE
Pages are not all responsive on small screens.

### ISSUE THREAD

**Issue by bansallakshi** [Plant-for-the-Planet-org/treecounter-app#104]
Update: The site is already partially responsive, but some page still have problems, e.g.

1 . The project liste if you want to donate and scroll down below the featured projects:

<img width="225" alt="Bildschirmfoto 2019-11-01 um 09 12 16" src="https://user-images.githubusercontent.com/1532418/68011517-d7093480-fc87-11e9-9d3f-dce1039147c6.png">

2. The "modal" display of a chosen project from the above list before you select it to display its details:

<img width="225" alt="Bildschirmfoto 2019-11-01 um 08 58 05" src="https://user-images.githubusercontent.com/1532418/68011587-f99b4d80-fc87-11e9-9760-49cf596df012.png">

Maybe there are also other pages with problems on small screens.

**Comment by norbertschuler** [comment]
There are still non responsive pages, e.g. this "modal" project dialog:

![Simulator Screen Shot - iPhone X - 2019-09-23 at 16 26 04](https://user-images.githubusercontent.com/1532418/65434578-51d86780-de1f-11e9-983f-800e86185d13.png)

**Comment by sagararyal** [comment]
Closing this, we'll redesign the web
