### ISSUE TITLE
InvalidStateError in /manage-plant-projects

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1061]
## Error in Plant-for-the-Planet App

**InvalidStateError** in **/manage-plant-projects**
InvalidStateError

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d2438ecc3e4c2001bd6b136?event_id=5d2438ec004884dc0bcb0000&i=gh&m=ci)

## Stacktrace

    https://js.arcgis.com/4.7/esri/views/MapView.js:694 - f

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d2438ecc3e4c2001bd6b136?event_id=5d2438ec004884dc0bcb0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Plant-for-the-Planet** [comment]
Problem might result from 404 error before: POST https://www.trilliontreecampaign.org/api/v1.1/de...

Comment added in Bugsnag by Norbert Schuler
[**InvalidStateError** in **/manage-plant-projects**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d2438ecc3e4c2001bd6b136?event_id=5d2438ec004884dc0bcb0000&i=gh&m=cm)

**Comment by norbertschuler** [comment]
won’t fix error in Argis code
