### ISSUE TITLE
Mobile: Pledge Events

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1062]
The Feature enables option to make Pledges through the Mobile App.

Tasks in this Feature include:
**1. Develop a carousel, to display multiple events**
<img width="633" alt="Screen Shot 2019-07-09 at 12 27 17 PM" src="https://user-images.githubusercontent.com/5401575/60880913-e5e55a80-a244-11e9-85ef-892847444b89.png">

**2. A page to display recent and biggest pledges**
Include Swipe to refresh.
<img width="294" alt="Screen Shot 2019-07-09 at 12 27 48 PM" src="https://user-images.githubusercontent.com/5401575/60880953-feee0b80-a244-11e9-9a5d-cba0d83eb0b8.png">

**3. A page with Form to make pledges**
<img width="298" alt="Screen Shot 2019-07-09 at 12 28 33 PM" src="https://user-images.githubusercontent.com/5401575/60880989-13320880-a245-11e9-86c2-2997ab82bd0b.png">

**4. A snack bar like message box with option to jump to contextual donations.**

<img width="304" alt="Screen Shot 2019-07-09 at 12 29 09 PM" src="https://user-images.githubusercontent.com/5401575/60881035-280e9c00-a245-11e9-9cfe-519c04e6a7bb.png">

API and Docs
API 1.
https://staging.trilliontreecampaign.org/public/v1.1/en/pledgeEvents
```
[{
    "slug": "esri-user-conference",
    "name": "ESRI User Conference",
    "description": "ESRI User Conference",
    "image": "5ccb34f8580ed977738769.png",
    "position": 1
}, {
    "slug": "bmz-zukunftskongress",
    "name": "BMZ Zukunftskongress",
    "description": "BMZ Zukunftskongress",
    "image": "5ccb34f865c31556544327.jpg",
    "position": 2
}]

```
@jmiridis please upgrade the version and add following

totalPledge = (count)
date: = form field in backend to add the date of the event.

API 2. Display 
`GET /public/v1.1/en/pledgeEvent/{event-name}`
```
{
    "total": 5000,
    "latest": [
        {
            "id": 231,
            "token": "TZBGC4P7",
            "firstname": "Name",
            "lastname": "2",
            "treeCount": 5000,
            "status": "pending"
        }
    ],
    "highest": [
        {
            "id": 231,
            "token": "TZBGC4P7",
            "firstname": "Name",
            "lastname": "2",
            "treeCount": 5000,
            "status": "pending"
        }
    ]
}
```

**API 3. Add a Pledge**
`POST /public/v1.1/en/pledgeEvent/esri-user-conference/eventPledge HTTP/1.1`
```
{"firstname":"name1","lastname":"name2","email":"test@example.com","treeCount":5000}
```

Api Response
Use the token to forward the user to contextual donations.

Page should be updated constantly. so that it the pledgeEvent page is uptodate.

**Comment by jmiridis** [comment]
Event date and total amount of pledged trees is now part of the API responses.

To support previous versions, all versions up to and including v1.1. will receive only the pledge as the response.

```json
{
  "id": 396,
  "token": "EP-AO4MEIU9",
  "firstname": "Kyle",
  "lastname": "Kong",
  "treeCount": 950,
  "status": "pending"
}
```
Versions higher than that, will obtain a schema response that will include both pledge and updated event:
*schema definitions must be updated from:*
`https://staging.trilliontreecampaign.org/schema.js`

```json
{
    "merge": {
        "eventPledge": [
            {
                "id": 396,
                "token": "EP-AO4MEIU9",
                "firstname": "Kyle",
                "lastname": "Kong",
                "treeCount": 950,
                "status": "pending"
            }
        ],
        "pledgeEvent": [
            {
                "slug": "esri-user-conference",
                "name": "ESRI User Conference",
                "description": "ESRI User Conference",
                "total": 1111538,
                "image": "5ba69f4c39cd1358874810.png",
                "position": 1,
                "eventDate": null
            }
        ]
    }
}```

AFAIK, fulfillment of a pledge, is not yet supported by the application.
The token provided in the pledge must be used as the context parameter for the route `app_donateTrees_context` 
![image](https://user-images.githubusercontent.com/1295390/61151339-5392c000-a4ab-11e9-82e1-d1f1fc6045cd.png)

The application must then retrieve additional parameters as pre-sets for the donation using this token.
The API for this will be provided as soon as it is clear how the application will implement those pre-sets (supported treecounter, amount of trees, etc.)

**Comment by norbertschuler** [comment]
@jmiridis why does the v1.2 still return the same as v1.1 and we have to use v1.3 to get the new results?

**Comment by norbertschuler** [comment]
@jmiridis this issue in in the _done_ column of the project board. Can it be closed?

**Comment by harshvitra** [comment]
Once https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1555 this is done we can close this.
