### ISSUE TITLE
Activation screen links do not react correctly

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1068]
<img width="533" alt="Screen Shot 2019-07-10 at 11 47 44 AM" src="https://user-images.githubusercontent.com/6512255/60959540-a97b3280-a308-11e9-800a-db9ae5cb2fcf.png">

Customize your Profile should take the user to Edit Profile.

Set Target should take user to Set Target page.

Currently it redirects user to /home

**Comment by norbertschuler** [comment]
For the web client:
https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/f1aded6c89a8b529ae8d30595ce87579bf3b8445/app/components/Authentication/SuccessfullyActivated/index.js#L12-L20

For the native apps:
https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/f1aded6c89a8b529ae8d30595ce87579bf3b8445/app/components/Authentication/SuccessfullyActivated/index.native.js#L11-L19

**Comment by norbertschuler** [comment]
Closing as related to old web client.
