### ISSUE TITLE
TypeError in /app_dev.php/explore

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1084]
## Error in Plant-for-the-Planet App

**TypeError** in **/app_dev.php/explore**
Cannot read property '0' of undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d2883f761bc1d0019963544?event_id=5d2883f7004a52b6bdfc0000&i=gh&m=ci)

## Stacktrace

    http://0.0.0.0:8080/bundle.js:188615 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d2883f761bc1d0019963544?event_id=5d2883f7004a52b6bdfc0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
This cannot be fixed as a stack trace is missing.
