### ISSUE TITLE
donateTrees: final payment screen submits despite validation errors

### ISSUE THREAD

**Issue by crucialfelix** [Plant-for-the-Planet-org/treecounter-app#1086]
- Donate Trees
- Fill out each form page in the slider
- Don't fill out CC information
- Hit PAY

The form flashes red **!** noting that the CC is missing, but submits the payment request anyway.

See discussion here: https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1085

I propose refactoring the form to solve these problems.

**Comment by norbertschuler** [comment]
@crucialfelix Final payment screen was rebuild for PSD2. Can we close this?
