### ISSUE TITLE
Backend Payment throws 500

### ISSUE THREAD

**Issue by crucialfelix** [Plant-for-the-Planet-org/treecounter-app#1087]
When submitting a payment request with a blank form, the server returns a 500 error, when it should have returned 400

5xx means the server had an unexpected error
4xx means the client or user submitted something wrong 

[HTTP status codes](https://www.restapitutorial.com/httpstatuscodes.html)

The app displays:

   An error has occurred processing your payment
   Must provide source or customer.

which is fine.

This is fairly minor, but as a dev I did think that something was broken on the server. Usually you get those when a backend raises an exception.

**Comment by jmiridis** [comment]
@crucialfelix could you provide the API entry point please.
