### ISSUE TITLE
ReferenceError in /app_dev.php/

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1088]
## Error in Plant-for-the-Planet App

**ReferenceError** in **/app_dev.php/**
TreeCounter is not defined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d289399851576001bcdc8bd?event_id=5d289399004a95437eba0000&i=gh&m=ci)

## Stacktrace

    http://0.0.0.0:8080/bundle.js:56544 - App.render

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d289399851576001bcdc8bd?event_id=5d289399004a95437eba0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
deleted on bugsnag
