### ISSUE TITLE
Pending Donations resulting undefined cards in My Trees

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1097]
When a user initiates a donation in mobile apps,
Instead of the pending cards, 
The My Trees card show undefined entries. ( #1096 is related) 
<img width="379" alt="Screen Shot 2019-07-13 at 7 40 13 PM" src="https://user-images.githubusercontent.com/5401575/61174828-0d6e5700-a5a6-11e9-8f0c-690bb34e2fc7.png">
bug_video: from 3:00 - 4:00

**Comment by sagararyal** [comment]
At 11:13 it shows the correct behavior.

<img width="374" alt="Screen Shot 2019-07-13 at 7 56 00 PM" src="https://user-images.githubusercontent.com/5401575/61174987-427ba900-a5a8-11e9-9715-9f49d3afb42b.png">

**Comment by norbertschuler** [comment]
@sagararyal is this fixed?
