### ISSUE TITLE
In donations, Support state does not clear

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1098]
If a user chooses to support a user in competition, 

User cannot override it and make direct donation.
clicking Donate menu, does not change the state.

This problem does not exist when a user attempts to gift trees to another user.

bug_video: 4:37 - 5:19

**Comment by norbertschuler** [comment]
@sagararyal can we close this issue?

**Comment by harshvitra** [comment]
@sagararyal @norbertschuler with New Donations PR - #1908  we will be able to fix this
