### ISSUE TITLE
Competitions should not show in featured list after end date

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1102]
Competition with End Date = yesterday should not show up in Featured Projects.

They should still appear in My Competitions.

**Comment by norbertschuler** [comment]
Still found two examples of expired competitions:

(1) for a favorite one:

![IMG_6448](https://user-images.githubusercontent.com/1532418/65831105-22f64180-e2b6-11e9-97ab-74efb1282ebf.PNG)

(2) for one in the "all" tab:

![IMG_6447](https://user-images.githubusercontent.com/1532418/65831106-22f64180-e2b6-11e9-93b1-809815aabc82.PNG)

**Comment by jmiridis** [comment]
Competition are filtered out by backend if end date has passed.
Closing issue.
