### ISSUE TITLE
When competition joined by private tree counter ...

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1103]
A private tree counter has `maypublish= false` in userprofile.

In the participant list of the user who joined the competition,
User's name, apper as: Anonymous Account, and the button appears as Support.

Instead it should be as below:
The userName = `User's name` and button = `Plant Trees`

vid_bug: 12:50 min

<img width="380" alt="Screen Shot 2019-07-13 at 8 07 47 PM" src="https://user-images.githubusercontent.com/5401575/61175085-e9147980-a5a9-11e9-8f4b-2560979da785.png">

**Comment by harshvitra** [comment]
Can #1422 fix this, I clearly couldn't understand the issue.

Currently - The button Plant trees shows when the user himself is a participant, and instead of name there we have 'Me'
