### ISSUE TITLE
Donation API called with failed Stripe response

### ISSUE THREAD

**Issue by jmiridis** [Plant-for-the-Planet-org/treecounter-app#1106]
@all there are quite a few donation requests that are sent to the server, although the credit card was already rejected by the Stripe client API call. Even though the card is rejected, the response is sent to the server as if it were valid:
```
"paymentResponse": {
        "gateway": "stripe_cc",
        "accountName": "stripe",
        "error": {
            "code": "incomplete_number",
            "type": "validation_error",
            "message": "Your card number is incomplete."
        }
    }
```
I imagine that fixing this by displaying an error message to the user so he corrects his input, could save us a lot of trouble with clients.

**Comment by norbertschuler** [comment]
I think this is obsolete now the donation process was rebuild for PSD2.
