### ISSUE TITLE
TypeError in /apis/site/proxy

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1118]
## Error in Plant-for-the-Planet App

**TypeError** in **/apis/site/proxy**
Cannot read property 'open' of undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d2d151f8f307e001b47d799?event_id=5d2d151f004aa0e44b950000&i=gh&m=ci)

## Stacktrace

    https://papago.naver.net/13.1a1b6f42d1fba58221f4.chunk.js:1 - t.tooltipOpen

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d2d151f8f307e001b47d799?event_id=5d2d151f004aa0e44b950000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Website does not work through Korean proxy e.g. https://papago.naver.net/apis/site/proxy?data=rlW1pzjvBvWbqUEjczovL3d3dy5wbGFudC1mb3ItdGhlLXBsYW5ldC5vcmcvZW4vdHJlZWNvdW50ZXIvYmlsbGlvbi10cmVlLWNhbXBhaWduLTIifQ%3D%3D

**Comment by Plant-for-the-Planet** [comment]
I don’t think we have to make the site work through any third party proxy, do we?

Comment added in Bugsnag by Norbert Schuler
[**TypeError** in **/apis/site/proxy**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d2d151f8f307e001b47d799?event_id=5d2d151f004aa0e44b950000&i=gh&m=cm)
