### ISSUE TITLE
Remove unused npm packages

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1119]
I'd like to minimize the size of the bundle and wondered if cleaning up the npm dependencies might be useful. I found a npm module to check for dependencies, but I am unsure if the result can blindly be trusted and the below listed modules deleted? Also I do not know what the `Missing dependencies` means to us? I have not seen any errors because of these missing dependencies yet.

```
$ npx depcheck

Unused dependencies
* autosuggest-highlight
* css-loader
* liform-react
* number-to-words
* react-i18next
* react-native-paypal-wrapper
* react-native-recaptcha-v3
* slick-carousel
Unused devDependencies
* babel-jest
* babel-plugin-transform-class-properties
* babel-polyfill
* babel-preset-es2015
* babel-preset-react
* babel-preset-react-native
* babel-preset-stage-2
* eslint-loader
* html-loader
* husky
* jest
* license-checker
* node-sass
* prettier
* prettier-eslint
* react-native-global-props
* sass-loader
* style-loader
Missing dependencies
* prop-types
* redux
* history
* react-router
* react-dom
* redux-form
* uuid
* stacktrace-parser

```

**Comment by norbertschuler** [comment]
@crucialfelix do you have experience with node module `depcheck`?

**Comment by crucialfelix** [comment]
The apps are built with webpack, so only actually used code is included. It even does tree shaking, so if a function in a module is not called then the code isn't shipped.

So removing dependencies won't shrink the bundle.

All the `*-loader` are webpack loaders and are used, they just aren't ever imported or required.

`number-to-words` is perhaps vestigial.

slick-carousel:
```css
@import "~slick-carousel/slick/slick.css";
```

You won't win much, you might break the build.

**Comment by norbertschuler** [comment]
Ok, then I won’t try to optimize this. I lately added an bundle analyzer (run `npm run analyze`) to inspect the generated bundle, but you have to create it before with `npm run build:server`.
