### ISSUE TITLE
Usage of Reactotron?

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1124]
Who has installed the tool Reactotron and is it still used for the native apps?

https://github.com/infinitered/reactotron/blob/master/docs/quick-start-react-native.md

In index.native.js there is an import 

`import './ReactotronConfig';`

and the node package is still installed.

**Comment by hkurra** [comment]
Initially, we were using this to debug network call when there was not good support for this in RN.
You can remove this now...

**Comment by norbertschuler** [comment]
O.k., we keep this.
