### ISSUE TITLE
Title Text Cut off

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1129]
These are several pages on OnePlus 6

On the page heading Donate is cut off at 4 characters, about at 3 characters, whereas Register trees is cut off at 20 characters.

![IMG-628c209c2f6fe40bfd98a17c3d27cb12-V](https://user-images.githubusercontent.com/5401575/61390367-f471e880-a8ba-11e9-9f6b-5c342f3bceca.jpg)
![IMG-b6b26530512bf31f815a4be98afc49b0-V (1)](https://user-images.githubusercontent.com/5401575/61390373-f6d44280-a8ba-11e9-9c1d-3d055cffce45.jpg)
![IMG-b6b26530512bf31f815a4be98afc49b0-V](https://user-images.githubusercontent.com/5401575/61390380-f9cf3300-a8ba-11e9-8ec1-0923a72f90bc.jpg)
![IMG-4f8b9d37e03bc77f403217dfdac1ca95-V](https://user-images.githubusercontent.com/5401575/61390384-fc318d00-a8ba-11e9-8509-c8d898ddfd6f.jpg)

**Comment by norbertschuler** [comment]
Tested on a Nexus S with 480x800px - not good, but quite o.k. - can you test your device again? We can shorten the headline "Register Planted Trees" if you want.

![Nexus S - About](https://user-images.githubusercontent.com/1532418/65425630-b212dd80-de0e-11e9-9f42-7a84308002df.png)
![Nexus S - Donate](https://user-images.githubusercontent.com/1532418/65425631-b212dd80-de0e-11e9-8226-410e4b98daae.png)
![Nexus S - Register Planted Trees](https://user-images.githubusercontent.com/1532418/65425632-b2ab7400-de0e-11e9-992a-e3f61a69ce31.png)
