### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException in Path.java:231

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1130]
## Error in Plant-for-the-Planet App

**java.lang.ArrayIndexOutOfBoundsException** in **Path.java:231**
length=4; index=24

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d2f85f8a536970019c5cd3c?event_id=5d2f85f8004af98e86000000&i=gh&m=ci)

## Stacktrace

    Path.java:231 - android.graphics.Path.getFillType

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d2f85f8a536970019c5cd3c?event_id=5d2f85f8004af98e86000000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
can not fix react-native error (maybe caused by some of our images or layouts)
