### ISSUE TITLE
Fix unhandled rejection in getAccessToken

### ISSUE THREAD

**Issue by crucialfelix** [Plant-for-the-Planet-org/treecounter-app#1134]
This PR needs to be redone:
https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1090

to add changes to `localStorage.native.js` as well.

The new PR needs to be properly tested.

Possibly add jest tests.

**Comment by niteshgrg** [comment]
@crucialfelix This will be done by #1133 rigth or am i missing something here. The link in above comment is broken.
