### ISSUE TITLE
Wrong grey color value for two menu items of native app navigation

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1141]
![Screenshot_1563688368](https://user-images.githubusercontent.com/1532418/61587568-c809e500-abb6-11e9-9a83-b1121976c2f0.png)

"Competition" and "World" are not having the same color value for the grey icons as the other icons which does not look correctly.

**Comment by sagararyal** [comment]
All icons with correct colors are available in Zeplin:
https://zpl.io/anymgZn

Including svg formats

<img width="1050" alt="Screen Shot 2019-07-21 at 2 01 10 PM" src="https://user-images.githubusercontent.com/5401575/61590941-0e177680-abc0-11e9-91bc-efb6a585fd21.png">
