### ISSUE TITLE
Not matching icons in personal navigation

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1147]
I think the icons in the personal navigation also do not match together very nicely and should be rebuild as I did for the navigation in #1141 :

![Screenshot_1563860708](https://user-images.githubusercontent.com/1532418/61686426-d1778680-ad49-11e9-884e-2923b15f82d3.png)

(Internally some icons are only 50px while others are 512px - it's kind of a patchwork.)

**Comment by norbertschuler** [comment]
@sagararyal do we have SVG files for all the above icons?

**Comment by sagararyal** [comment]
@norbertschuler 

Icons with 24dp, available at:

https://zpl.io/aRGPQgp

**Comment by norbertschuler** [comment]
Great, thank you @sagararyal - some are different from the current ones. I assume I can replace them with the ones in Zeplin. Anyway I will of course create a pull request before.

**Comment by norbertschuler** [comment]
@sagararyal I am searching for a red version of these three icons as I need them for the web client:

<img width="178" alt="Bildschirmfoto 2019-07-26 um 12 42 25" src="https://user-images.githubusercontent.com/1532418/61928516-e1d66e00-afa2-11e9-85cc-a50a60b551fc.png">

**Comment by harshvitra** [comment]
1. Can we add a thin line below profile
2. The icons should be lighter than the text

**Comment by norbertschuler** [comment]
> * Can we add a thin line below profile
> * The icons should be lighter than the text

Let’s do this in a new issue as the associated pull request got already merged: https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1154
