### ISSUE TITLE
Add Maps to Tree Registration Form

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1156]
Designs:
https://app.zeplin.io/project/5cad97d9b33d0b5931d90a9b/dashboard?seid=5d39738c908a512da8dc6a3c

Todo:

### In the Single Tree Registration, 
Implement way to capture a single coordinate `geoLocation` from user.

### In Multiple Tree Registration

When tree count > x number (defined by server)
Ask user to submit a polygon `geometry`.

Else submit a coordinate `geoLocation`.

### API Documentation on the Forms:
https://staging.trilliontreecampaign.org/api/doc/plant_contribution

Please refer to 

<img width="491" alt="Screen Shot 2019-07-28 at 9 58 00 AM" src="https://user-images.githubusercontent.com/5401575/62003894-3c480980-b11e-11e9-8eea-c529827e0887.png">

### Example data from a tree registration
```
{
  "treeCount": "12",
  "treeSpecies": "string",
  "plantDate": "2018-07-12",
  "geoLocation": "geoLatitude=37.234894&geoLongitude=-115.81082",
  "contributionImages": [
    {
      "imageFile": "data:image/png;base64,iVBORw..."
    }
  ],
  "geometry": "{\"type\":\"Polygon\",\"coordinates\":[[[-90.7199639081955,18.646778840374814],[-90.71995854377747,18.646778840374814],[-90.71995854377747,18.646789006029096],[-90.7199639081955,18.646789006029096],[-90.7199639081955,18.646778840374814]]]}"
}
```

**Comment by sanjayradadiya** [comment]
@sagararyal  Invite me in **zeplin** so I can take a look of designs for this.

**Comment by sagararyal** [comment]
<img width="1093" alt="Screen Shot 2019-11-02 at 1 49 15 PM" src="https://user-images.githubusercontent.com/5401575/68071152-ea93c880-fd77-11e9-9732-2bd61c885281.png">

**Comment by sagararyal** [comment]
#1587 draft PR for Map Integration and Register Tree Map

Link to Designs:

https://app.zeplin.io/project/5cad97d9b33d0b5931d90a9b/dashboard?seid=5d39738c908a512da8dc6a3c
