### ISSUE TITLE
Verifying domain with Apple Pay

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1159]
To prepare for the Apple Pay Integration in the application:

To use Apple Pay, you need to register with Apple all of your web domains that will show an Apple Pay button. This includes both top-level domains (e.g., stripe.com) and subdomains (e.g., shop.stripe.com). You need to do this for domains you use in both production and testing. When testing locally, use a tool like ngrok to get an HTTPS domain.

Important note: Apple's documentation for Apple Pay on the Web describes their process of "merchant validation", which Stripe handles for you behind the scenes. You do not need to create an Apple Merchant ID, CSR, etc., as described in their documentation, and should instead just follow these steps: 

More at:
https://stripe.com/docs/stripe-js/elements/payment-request-button#verifying-your-domain-with-apple-pay

**Comment by norbertschuler** [comment]
Related to #1908
