### ISSUE TITLE
Implement Contextual Donations

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1160]
Initiating a donation:

**Always Override Donations with Dedication:**

If a user has _**person**_ dedicated trees, (and the donation is not a gift or support) 

Add the **_person_** as the supported tree-counter in the donation.

----
If no dedication:

Start the donation via project page.

----

If the donation originates from 

Contextual Donations allow the app to predefine the variables
The variables are stored in the database and are retrieved using a token.

### The context token can be created

- manually, on the backend
- using a Widget, based on parameters
- for an eventPledge to fulfill the pledge
- by app to recommend donations to previous donors

### Variables
1. Tree Count (min trees a user can plant)
2. Supported plantProject
3. Supported TreeCounter (can be `gift`, `support`, `dedicate`)
4. Type
5. Locale (override if not logged in)

## Any donations made anonymously can be redeemed by the user.

Example: 
url.org/c/`token` is a route to handle contextual donations.

On the Mobile Applications, it is the first page of the donations.

Designs pending & `issue creation in progress`

**Comment by sagararyal** [comment]
Similar Issue, User should be able to add, edit, and delete payment methods.
#899

**Comment by norbertschuler** [comment]
Related to #1908
