### ISSUE TITLE
std::__1::system_error in unknown method

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1161]
## Error in Plant-for-the-Planet App

**std::__1::system_error** in **unknown method**
mutex lock failed: Invalid argument

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d3dbdc6cc46c3001a2dcbfd?event_id=5d3dbdc6004b4eab8c660000&i=gh&m=ci)

## Stacktrace

    unknown file:0 - unknown method

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d3dbdc6cc46c3001a2dcbfd?event_id=5d3dbdc6004b4eab8c660000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
can not fix native crash
