### ISSUE TITLE
SecurityError in /donate-trees

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1163]
## Error in Plant-for-the-Planet App

**SecurityError** in **/donate-trees**
Permission denied to access property "dispatchEvent" on cross-origin object

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d3edb00b00c260019a635ab?event_id=5d3edb00004b624dd68d0000&i=gh&m=ci)

## Stacktrace

    moz-extension://33f6aa1c-5517-411c-9d07-a7531e23c733/js/inject.js:65 - onUserInput/<

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d3edb00b00c260019a635ab?event_id=5d3edb00004b624dd68d0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
I think we do not have to make sure the client works with all browser addons.
