### ISSUE TITLE
Allow TPOs to mention Tax Deductible Status in Projects

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1166]
<img width="578" alt="Screen Shot 2019-07-29 at 5 17 29 PM" src="https://user-images.githubusercontent.com/5401575/62060094-caa6b300-b224-11e9-9d49-bf5822485e95.png">

Q: 1, Is your organization charity / non profit?

if yes,
Q 2, Countries that issue tax deductions

Flags:

If ≠ charity --> Is not tax deductible / don't show selector)

If = charity --> allow select countries 

If countries = null ( project is not tax deductible)

**Comment by jmiridis** [comment]
Need more input on this.

**Comment by jmiridis** [comment]
Nikola is working on this.
