### ISSUE TITLE
TPO fix projects management

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1172]
When you add or edit projects as a TPO I found the following issues:

- Price per tree shouldn't be negative, should it?
- URLs for profile and video should be valid URLs (use a URL checker in the frontend)
- Editing the project shows two images, but only one is added to projects (compare the backend)
- If you add a project on your local develop server using IP 0.0.0.0 the map and the location chooser won't work as Argis got problems (probably this can not get fixed)

![TPO_add-new-plant-projects](https://user-images.githubusercontent.com/1532418/62181040-2899de80-b37c-11e9-8b6f-d334dd363157.png)
![TPO_edit-plant-projects](https://user-images.githubusercontent.com/1532418/62181042-2899de80-b37c-11e9-9d15-f13fd76c67a8.png)

**Comment by norbertschuler** [comment]
Donation projects with negative price per tree could probably break the app, e.g. if you try to donate to such a project it does not work but the spinner runs forever.

Broken video urls also can crash the Android app as described in #906.

**Comment by norbertschuler** [comment]
Also I found out the action to save the projects does not yet correctly handle the response data from the API in https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/develop/app/actions/plantProjectAction.js.

**Comment by mahmed0715** [comment]
@norbertschuler in my PR https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1781 handle all these..

**Comment by norbertschuler** [comment]
> @norbertschuler in my PR #1781 handle all these..

@mahmed0715 I do not see you doing anything in https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/develop/app/actions/plantProjectAction.js in your PR?

**Comment by norbertschuler** [comment]
Closing as related to old web client.
