### ISSUE TITLE
Participant Leaderboard in Competition

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1173]
In the participation leaderboard in Competition  Participants needs to be sorted by ones with highest Tree Count.

+ clicking the name of the people should take user to their tree counter.

![Screenshot_20190731-124952_Plant](https://user-images.githubusercontent.com/5401575/62206594-73265580-b392-11e9-8118-707234314938.jpg)

**Comment by norbertschuler** [comment]
Sorting already looks all right for me testing this. Clicking the names to navigate to the treecounter is not a bug, but a feature request, therefore I delete the bug label from this issue now:
![Screenshot_1569243317](https://user-images.githubusercontent.com/1532418/65427258-34e96780-de12-11e9-88b3-2737e2737a85.png)

**Comment by sagararyal** [comment]
#1422 should fix the clicking issue.
