### ISSUE TITLE
Application crashes on direct donation to project

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1176]
Loading https://www.trilliontreecampaign.org/donate-trees/1
on application crashes

![Screenshot_20190731-160143_Plant](https://user-images.githubusercontent.com/5401575/62218495-e046e480-b3ac-11e9-90aa-83b3d6254b8a.jpg)

**Comment by rarawal** [comment]
@niteshgrg : can we look into this on priority

**Comment by norbertschuler** [comment]
similar to #1175

**Comment by norbertschuler** [comment]
I once got this bug while I was building the Android app (see the issue #1175), but I can not reproduce it any more. I uploaded source maps for version 1.0.5 to Bugsnag in case someone can reproduce the bug so we maybe see a better stack trace. (The source maps of course need to get uploaded again if we do any more changes / commits to the release branch with version 1.0.5.)

**Comment by norbertschuler** [comment]
The only place in our sources close to the above error would be https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/28d62bbadd6653d996b8bcd33e0d252036ff30ba/app/selectors/index.js#L90

**Comment by norbertschuler** [comment]
I was wrong about getting the bug while I was building the Android release. It was just a coincidence that the bug occurred at Sagars device while I was building the app. The report on Bugsnag clearly shows that only Sagar is experiences this bug on his Samsung SM-G950U1: https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d419f3ca6160a001e40813a?event_id=5d419f54004bccc9e8f20000&i=sk&m=cm&pivot_tab=event&filters[device.manufacturer][0]=samsung&filters[device.model][0]=SM-G950U1

**Comment by norbertschuler** [comment]
Bug can be reproduced with the latest version by logging in with a TPO account.

**Comment by norbertschuler** [comment]
@niteshgrg Maybe this bug results from the fact @sagararyal and me are both TPOs not listed in the result of the TPOs API call https://staging.trilliontreecampaign.org/public/v1.1/de/loadTpos which is as following while my test account id is `id:44` and therefore not in the list of TPOs.:

```json
{
  "41": {
    "id": 41,
    "type": "tpo",
    "fullname": "Plant-for-the-Planet",
    "name": "Plant-for-the-Planet",
    "image": "5d3868331cc8d780614517.jpg",
    "synopsis1": "Cupiditate rerum ratione rerum repellendus ducimus. Voluptatem aperiam ipsa eius repellat adipisci reiciendis voluptas.",
    "synopsis2": "Dolor qui illo placeat harum voluptatem.",
    "url": "https://www.plant-for-the-planet.org",
    "linkText": "Plant-for-the-Planet",
    "isDeleted": false,
    "locale": null,
    "plantProjects": [ ...],
    "isVerified": true,
    "isCertified": false
  },
  "43": {
    "id": 43,
    "type": "tpo",
    "fullname": "One Tree Planted",
    "name": "One Tree Planted",
    "image": null,
    "synopsis1": "Ea voluptatem aut cum vitae nostrum non maiores. Omnis aut quos ut ad est quidem eum rerum.",
    "synopsis2": "Ea porro blanditiis eos enim non. Quas sunt eligendi sapiente et et fuga recusandae voluptatem.",
    "url": "http://www.hackett.com/assumenda-dolore-explicabo-nisi-a-aut-architecto-et",
    "linkText": "example.net",
    "isDeleted": false,
    "locale": null,
    "plantProjects": [ ... ],
    "isVerified": true,
    "isCertified": false
  }
}
```

So is this a bug that the API call does not return Sagar and me or is this a bug that the code cannot deal with not public visible TPOs?

**Comment by norbertschuler** [comment]
So if I change the line of code as following a crash is avoided but I will find the project in the list of possible projects to donate to with `-` as the TPOs name:
```javascript
    let tpoNameExpandedProjects = normalisedProjects.map(project => {
-->   project.tpo_name = tpos[project.tpoId]? tpos[project.tpoId].name : '-';
      return project;
    });
```
![Simulator Screen Shot - iPhone X - 2019-08-01 at 11 28 18](https://user-images.githubusercontent.com/1532418/62265737-77fd0f00-b44f-11e9-925d-2be510f148e5.png)

I think it is a bug that I am not part of the results of the API call loading the TPOs, but the software could be build more robust when such errors happen.
