### ISSUE TITLE
Optimize Loading gif size

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1182]
https://staging.trilliontreecampaign.org/c33d4dd2234fb1721a4ac0baa3bfb3c0.gif

Currently this gif which we use for loading screens uses 424.5KB 

We should to reduce this to less than 10-20kb, or find alternate loading animations.

**Comment by norbertschuler** [comment]
With https://ezgif.com/optimize using Lossy GIF compression you can reduce the size to 242.76KiB: 
![ezgif-4-d02bd5ecfdd3](https://user-images.githubusercontent.com/1532418/62407847-5768bc80-b5e9-11e9-93df-c7d66b2aa156.gif)

If you run the tool again with the above compressed GIF skipping every second frame, the result has 123.85KiB but the animation also runs faster as the tool does not adapt the waiting time between each frame:
![ezgif-4-c3a5a5769841](https://user-images.githubusercontent.com/1532418/62407851-5df73400-b5e9-11e9-828a-6a1bff3a62ee.gif)

**Comment by norbertschuler** [comment]
If you want to replace this loading animation please be aware we have an extra resource in the android app which probably also should be changed:

```
$ find . -name "*.gif"
./app/assets/images/loading-bar.gif
./android/app/build/generated/res/react/release/drawable-mdpi/app_assets_images_loadingbar.gif
```

**Comment by sagararyal** [comment]
@norbertschuler I made this svg. Takes 2Kb size.
It is a spinner, uses our tree and has a smoother animation

uploading zip as git doesn't allow svg uploads.

[Tree Spinner.svg.zip](https://github.com/Plant-for-the-Planet-org/treecounter-app/files/3464159/Tree.Spinner.svg.zip)

https://codepen.io/sagararl/pen/VoMBrw

**Comment by norbertschuler** [comment]
It works in the web client, but I cannot make it work in the native apps as I think animations in the SVG file are not supported. (The animation in the treecounter consisting of several SVG files is done outside the SVG files.) I would need some help here to build an animated spinner in React from your SVG file.

**Comment by norbertschuler** [comment]
I tried using https://svg2jsx.com/ and afterwards https://www.smooth-code.com/open-source/svgr/playground/ (using react-native), but the converter skipped the animation as it does not support it.

**Comment by norbertschuler** [comment]
I haven't found a solution to show the animated SVG in the native apps. I just put in the half size GIF animation for now until we want to do anything else.

**Comment by crucialfelix** [comment]
Generally speaking you should let webpack do this with an image loader: https://github.com/tcoopman/image-webpack-loader

See issue: https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1430

**Comment by sagararyal** [comment]
I think we should implement Lottie across the app for better animations
https://lottiefiles.com
