### ISSUE TITLE
Load zaehler-bg-himmel.png from domain (3x size reduction)

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1183]
zaehler-bg-himmel.png takes 522.1KB

and is loaded from
https://www.plant-for-the-planet.org/bundles/pftpbilliontree/images/zaehler-bg-himmel.png

Please use the file with reduced size of 198kb (in the zip below) and host it in the domain.

[zaehler-bg-himmel.png.zip](https://github.com/Plant-for-the-Planet-org/treecounter-app/files/3456795/zaehler-bg-himmel.png.zip)

**Comment by norbertschuler** [comment]
I changed the web client not to load this file from the plant-for-the-planet.org website but from the app as the native app also is doing it.

**Comment by sagararyal** [comment]
@harshvitra maybe you can pick this.

**Comment by norbertschuler** [comment]
@sagararyal maybe you misunderstood me: the native apps already are doing it right. I made the web client using the same file as the native apps and exchanged the file with your optimized version. The PR is ready to be reviewed (and merged).

**Comment by sagararyal** [comment]
@norbertschuler Okay, I did understand the way around, then we can close this once merged.
