### ISSUE TITLE
TypeError in /t/weforest

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1193]
## Error in Plant-for-the-Planet App

**TypeError** in **/t/weforest**
Cannot read property 'max' of null

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d450a12a06fb4001861f98c?event_id=5d450a12004c28482e160000&i=gh&m=ci)

## Stacktrace

    http://0.0.0.0:8080/bundle.js:126501 - NDVI.render

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d450a12a06fb4001861f98c?event_id=5d450a12004c28482e160000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
this was locally in a developer sandbox
