### ISSUE TITLE
ReferenceError in /

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1194]
## Error in Plant-for-the-Planet App

**ReferenceError** in **/**
svgBackground is not defined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d451f1d50b54b00186101e3?event_id=5d451f1d004c205106e40000&i=gh&m=ci)

## Stacktrace

    http://0.0.0.0:8080/bundle.js:98395 - SvgContainer.render

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d451f1d50b54b00186101e3?event_id=5d451f1d004c205106e40000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
while developping
