### ISSUE TITLE
Improving Search Presence

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1201]
Block Search engines from indexing test and staging environments.

For test and staging environments add HTTP Header
`<META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">`

<img width="1017" alt="Screen Shot 2019-08-06 at 10 36 39 PM" src="https://user-images.githubusercontent.com/5401575/62575482-1f88a000-b89b-11e9-857f-5182e691e2f9.png">

– This should be thought for accounts who are anonymous as well.

**Comment by norbertschuler** [comment]
Blocking search engines and others accessing non production systems could also be archived by using server authorization which `.htaccess`, but of course then the access credentials have to be shared with all developers using the project.

**Comment by sagararyal** [comment]
@norbertschuler google no longer plans to use the robot.txt; so we have to implement the meta tags.

**Comment by norbertschuler** [comment]
Then we have the challenge to implement environmental awareness into our different deployments in order to render different meta tags for them as currently the web client always thinks to be `production`.

**Comment by norbertschuler** [comment]
Closing as related to old web client.
