### ISSUE TITLE
TypeError in /t/sagar-aryal

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1204]
## Error in Plant-for-the-Planet App

**TypeError** in **/t/sagar-aryal**
_this2.props.deleteContribution is not a function. (In '_this2.props.deleteContribution(contribution.id)', '_this2.props.deleteContribution' is undefined)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d4c35a093da20001b2799de?event_id=5d4c35a0004cc731cebb0000&i=gh&m=ci)

## Stacktrace

    http://0.0.0.0:8080/bundle.js:171795 - handleDeletion

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d4c35a093da20001b2799de?event_id=5d4c35a0004cc731cebb0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by sagararyal** [comment]
ignore this.
