### ISSUE TITLE
TypeError in /challenge

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1211]
## Error in Plant-for-the-Planet App

**TypeError** in **/challenge**
Cannot read property 'data' of undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d4df1d946b74d00188543ed?event_id=5d4df1d9004cda1212e50000&i=gh&m=ci)

## Stacktrace

    web/server/webpack:/app/actions/challengeActions.js:39 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d4df1d946b74d00188543ed?event_id=5d4df1d9004cda1212e50000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
related to #1210
