### ISSUE TITLE
User complains about problem entering mail at login

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1215]
**Describe the bug**
User complaints when he clicks on the field for entering his mail address in the login form, the keyboard only shows up for a very short time frame and then vanishes again, so he can not login: German original feedback "Leider funktioniert der Login nicht. Sobald man in das Feld für die eMail klickt, erscheint für einen Bruchteil einer Sekunde die Tastatur und ist sofort wieder weg. Somit ist keine Eingabe möglich..."

**Is it on a Production or Development Build?**
Production

**To Reproduce**
Have not tried to reproduce yet. One probably would need a similar device to test this.

**Expected behavior**
Show the keyboard for entering a mail address.

**What actually happens**
The user complains that the keyboard is only shortly shown and then disappears when trying to enter his mail address.

**Screenshots**
<img width="967" alt="Bildschirmfoto 2019-08-11 um 09 53 29" src="https://user-images.githubusercontent.com/1532418/62831360-2fe3a680-bc1e-11e9-8235-b3d8e2d0705c.png">

**Smartphone (please complete the following information):**
- Device: Samsung Galaxy S8
 - OS: Android 9
 - Plant-for-the-Planet App Version 1.0.3 (300010)

**Comment by crucialfelix** [comment]
Samsung Galaxy A3 worked fine. Sometimes it's an alternate keyboard (Gboard vs default) that causes this disappearing. I've seen it on other apps, then it mysteriously resolves.

One big annoyance though is that if you tap Submit, it only unfocuses the password field. you have to click again to get it to actually submit.

We are replacing the whole login flow now anyway, so all this will be moot.

**Comment by norbertschuler** [comment]
This is outdated as we changed the login form.
