### ISSUE TITLE
Gift trees to existing user does not work on staging (2)

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1216]
## Error in Plant-for-the-Planet App

**TypeError** in **/gift-trees**
Cannot read property 'treecounter' of undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d500a32bb4b07001a13569c?event_id=5d500a32004cd8f0da060000&i=gh&m=ci)

## Stacktrace

    web/server/webpack:/app/components/GiftTrees/index.js:343 - GiftTrees.t.checkValidation
    web/server/webpack:/app/components/GiftTrees/index.js:480 - validated

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d500a32bb4b07001a13569c?event_id=5d500a32004cd8f0da060000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
The stack trace in Bugsnag is wrong as the source maps are outdated - the correct stack trace looks like this:

```
Uncaught TypeError: Cannot read property 'treecounter' of undefined
    at GiftTrees.t.checkValidation (index.js:184)
    at validated (index.js:347)
    at a.default.createElement.onClick (PrimaryButton.js:7)
    at Object.ia (react-dom.production.min.js:15)
    at Object.invokeGuardedCallback (react-dom.production.min.js:16)
    at Object.invokeGuardedCallbackAndCatchFirstError (react-dom.production.min.js:16)
    at za (react-dom.production.min.js:20)
    at Da (react-dom.production.min.js:22)
    at Fa (react-dom.production.min.js:22)
    at Ba (react-dom.production.min.js:21)
```

And the related source code looks like this:

```javascript
  checkValidation = [
    () => {
      if (this.state.modeUser === 'direct') {
        let returnValue;
-->     returnValue = this.state.form.directGift.treecounter ? true : false;
        this.setState({
          form: {
            ...this.state.form
          }
        });
        return returnValue;
      } else {

```

**Comment by Plant-for-the-Planet** [comment]
stack trace is wrong, see GitHub

Comment added in Bugsnag by Norbert Schuler
[**TypeError** in **/gift-trees**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d500a32bb4b07001a13569c?event_id=5d500a33004cd94e908a0000&i=gh&m=cm)

**Comment by norbertschuler** [comment]
This bug happens if you try to press "Next" ("Weiter") in the process of gifting a tree without having choosen a recipient.
