### ISSUE TITLE
RCTFatalException: unrecognized selector sent was thrown while invoking multiSet on target AsyncLocalStorage

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1236]
## Error in Plant-for-the-Planet App

**RCTFatalException: Exception '-[NSNull length]: unrecognized selector sent to instance 0x24931d7f0' was thrown while invoking multiSet on target AsyncLocalStorage with params (         (                 (             AuthenticatedSideMenuSchema,             "<null>"         )     ),     48843 ) callstack: ( 	0   CoreFoundation                      0x000000021924a9a4 <redacted> + 252 	1   libobjc.A.dylib                     0x00000002184239f8 objc_exception_throw + 56 	2   CoreFoundation      ...** in **facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)**
Exception '-[NSNull length]: unrecognized selector sent to instance 0x24931d7f0' was thrown while invoking multiSet on target AsyncLocalStorage with params (
        (
       ...

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d54977082615d001a6fbd59?event_id=5d549770004cd9e916510000&i=gh&m=ci)

## Stacktrace

    TreecounterApp:0 - facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)
    TreecounterApp:0 - facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)
    TreecounterApp:0 - facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d54977082615d001a6fbd59?event_id=5d549770004cd9e916510000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
native error - cannot reproduce
