### ISSUE TITLE
Pots and trees animation should restart when you navigate to a different user

### ISSUE THREAD

**Issue by crucialfelix** [Plant-for-the-Planet-org/treecounter-app#1238]
Go to the production site:

https://www.trilliontreecampaign.org

search for a user or campaign in the top right navigation:

https://www.trilliontreecampaign.org/t/goal-ireland

Then another user eg sagar 

The initial pots => trees animation doesn't happen.

Reload the page and you will see the full animation.

**Comment by norbertschuler** [comment]
Right, and also Sagar Circle get's closed though it shouldn't - here is the related bug issue #487

**Comment by norbertschuler** [comment]
Closing as related to old web client.
