### ISSUE TITLE
Add webpack hashed file names for cache busting

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1250]
To better deal with caching, append app version number to the js and css files during build process.

Example:
https://staging.trilliontreecampaign.org/bundle.js `?v1.0`

**Comment by crucialfelix** [comment]
Better to do it with webpack hashed file names. When the index.html page is built then bundle.js is replaced with bundle.uniqueHash123.js

Then the only thing you have to flush your CDN for is index.html

**Comment by crucialfelix** [comment]
This also works for images, icons, fonts, svg files, css, js:

https://webpack.js.org/guides/caching/

It is content based hashing. So you don't need to bust everything just because there is a new app released.

**Comment by mahmed0715** [comment]
https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1595
