### ISSUE TITLE
Assign unique name for static files after each deployment & Clear Cloudflare Cache automatically

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1252]
During the deployment process, 
Automatically purge the js and css files.
It is best to avoid purging user /project Images, as they increase immediate load in server.

### To Purge All Files
```
curl -X POST "https://api.cloudflare.com/client/v4/zones/{zoneid}/purge_cache" \
     -H "X-Auth-Email: user@example.com" \
     -H "X-Auth-Key: {secret-auth-key}" \
     -H "Content-Type: application/json" \
     --data '{"purge_everything":true}'
```

### To Purge Selected Files
[Details on Cloudflare Site](https://api.cloudflare.com/#zone-purge-files-by-url)

```
curl -X POST "https://api.cloudflare.com/client/v4/zones/{zoneid}/purge_cache" \
     -H "X-Auth-Email: user@example.com" \
     -H "X-Auth-Key: {secret-auth-key}" \
     -H "Content-Type: application/json" \
     --data '{"files":["http://www.example.com/css/styles.css",{"url":"http://www.example.com/cat_picture.jpg","headers":{"Origin":"cloudflare.com","CF-IPCountry":"US","CF-Device-Type":"desktop"}}]}'

```

It should be possible to purge a subdomain eg: `staging.ttc.org/*`

Contact Sagar or Norbert for Auth Keys.

**Comment by crucialfelix** [comment]
Best practice would be: 
when the index html file is built, it should insert `bundle.xyz123hash.js` rather than `bundle.js`.

Then the bundles always have unique file names, and you only have to purge index.html

But for now just purge everything.

**Comment by sagararyal** [comment]
#1593 can be fixed by this.
