### ISSUE TITLE
Blank page opening staging website

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1256]
**Describe the bug**

I just came back home and opened https://staging.trilliontreecampaign.org/ for the first time on my home computer today (yesterday was last time). In between I worked on my other computer in the office with staging today. Now the first time I accessed the page it was blank. Reloading the page shows the normal website and I am not logged in. (I am sorry, but I am not sure if I was logged in yesterday.)

**Is it on a Production or Development Build?**
staging system

**To Reproduce**
Do not know yet, will have to try again.

**Expected behavior**
Showing the website.

**What actually happens**
The website was blank on first loading, showing the logged out version if reloading.

**Screenshots**
Blank page with Console open:
<img width="921" alt="Bildschirmfoto 2019-08-16 um 18 34 59" src="https://user-images.githubusercontent.com/1532418/63183488-5ad25e00-c055-11e9-92cf-4ea09bc1d301.png">

Same blank page with content of local storage (only having a `session_id`):
<img width="921" alt="Bildschirmfoto 2019-08-16 um 18 35 38" src="https://user-images.githubusercontent.com/1532418/63183465-4aba7e80-c055-11e9-8ffa-51432818b936.png">

**Desktop (please complete the following information):**
- OS: MacOS latest
 - Browser: Chrome latest
 - Plant-for-the-Planet App Version 1.0.5 staging branch at commit 91987039243acbb41dec06fe2864b8f839f2f84c

**Comment by norbertschuler** [comment]
Has not yet happened again to me up until now.

**Comment by crucialfelix** [comment]
Never happened to me, though I did notice if the API server times out then you the first view is left hanging till it resolves. 

Menu and currencies could be shipped with the app, then fetched live, then cached to localStorage. This would avoid many re-renders and would eliminate waiting time.
