### ISSUE TITLE
Link to TPOs from Project Card is broken.

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1261]
<img width="1133" alt="Screen Shot 2019-08-19 at 10 28 13 AM" src="https://user-images.githubusercontent.com/5401575/63251388-eaeaf000-c26d-11e9-8e42-8e3ced656bd8.png">

clicking (by Project Name)

redirects to homepage.

instead it should redirect user to `/t/{slug of tpo}`

**Comment by norbertschuler** [comment]
Where should the web client get the slug name of a TPO from? It does not seem to be included in in the loadTpos API call:

<img width="1291" alt="Bildschirmfoto 2019-08-22 um 15 46 59" src="https://user-images.githubusercontent.com/1532418/63519933-1c74ed00-c4f4-11e9-9bf6-7ae5cdf812d6.png">

**Comment by norbertschuler** [comment]
As far as I can see the web client just links to the TPO name (in urlencoded form): https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/acaf00ac42ca19002961697277e84944cfb536dd/app/components/PlantProjects/PlantProjectFull.js#L146

**Comment by norbertschuler** [comment]
This kind of link was introduced 5 month ago with https://github.com/Plant-for-the-Planet-org/treecounter-app/commit/cb681bb65ba34f62522e96e4cde36a5bf00e3b3a

**Comment by mahmed0715** [comment]
I am on it.

**Comment by mahmed0715** [comment]
This seems to be an api call/response issue. 
![Screenshot from 2019-08-23 21-46-37](https://user-images.githubusercontent.com/2967789/63605354-98a02b00-c5ef-11e9-9329-1ec86c0d7219.png)

**Comment by norbertschuler** [comment]
I think it's just a coincidence that for this TPO the name "Plant-for-the-Planet" matches the slug "plant-for-the-planet" with the backend uses to retrieve and show a tree counter. For the other TPOs is does not match and so the link does not work. Either the API call `loadTpos` have to return the slug so it can be used to create the right link in the frontend or the backend would have to support searching and loading a TPO for it's name (even with weird characters in it if possible). In both cases this is a task which require backend support (so I add the "backend" label now).

**Comment by jmiridis** [comment]
TPOs are linked now their treecounter which contains the slug.
Backend part is hereby done.

![image](https://user-images.githubusercontent.com/1295390/65845821-409cc880-e301-11e9-97d2-e41fdb6af8bb.png)
