### ISSUE TITLE
Error in /account-activation

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1264]
## Error in Plant-for-the-Planet App

**Error** in **/account-activation**
email not in localStorage

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d5ac378192703001931ba55?event_id=5d5ac378004cc32a7c2e0000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/bundle.js:31 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d5ac378192703001931ba55?event_id=5d5ac378004cc32a7c2e0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
We should retest if account activation is still working.

**Comment by norbertschuler** [comment]
bug expired
