### ISSUE TITLE
Improve Language of Counting Trees

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1265]
In the user tree counter, implement the following method to count trees.

### Counting Examples
0.2
0.8
1
10
100
1,000
9,999
10 Thousand
10.50 Thousand
100 Thousand
998.70 Thousand
1 Million
9.60 Million
10 Million
100 Million
1 Billion
10 Billion
100 Billion
998.30 Billion
1 Trillion

Decimal examples:

1.2 Billion ( is fine)
120 Million (is fine)

.12 Billion (is not fine)
.012 Trillion (is not fine)

Never use `0.x` when count > 1

**Comment by mahmed0715** [comment]
I think i was working on it. The web part was done last week.

**Comment by mahmed0715** [comment]
@sagararyal please check the pr related to localization. I think what ever this ticket needs to do we can yhink after that pr

**Comment by norbertschuler** [comment]
related to #880

**Comment by sagararyal** [comment]
@mahmed0715 

does it fix issues like this?

instead of `0.6 Million` it should show `600 Thousand`
<img width="431" alt="Screen Shot 2019-08-20 at 3 57 25 PM" src="https://user-images.githubusercontent.com/5401575/63353574-3df29f00-c363-11e9-9ace-b3730ecd03e1.png">

**Comment by norbertschuler** [comment]
Last thing described by Sagar is not yet programmed. So let’s keep this issue as an optimization task.

**Comment by mahmed0715** [comment]
I should take care of this optimization task now? @norbertschuler or is it fine to go

**Comment by norbertschuler** [comment]
This should be resolved by now.
