### ISSUE TITLE
Improve Login Pages with SSO.

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1267]
Primary goal: Enable users go sign up or login with Google, Apple, FB etc.

Migrating the auth system to Auth0 will take more than one PR, and involves people on various teams (react, react-native, backend, design)

Project: https://github.com/Plant-for-the-Planet-org/treecounter-app/projects/5

Both the web and react-native versions need to change. For the most part it gets simpler as the Auth0 api makes a lot of things easier. The reference app uses a lot of react hooks which makes state management and auth a lot less verbose.

We will setup a custom API connection from Auth0 to our staging | production db. This supports existing user accounts and creates a user record for all new user accounts.  Auth0 will make a POST request to staging | production (Symfony backend server) for: 
- Login
- Create
- Verify
- Change Password
- Get User
- Delete

This means the user is stored in both Auth0 and our own db. Existing Users can still login with email/password, but they will see a new form.

Auth flow:
- Click login / signup => Auth0 Universal Login page
- User logs in or signs up with email/password OR an Identity Provider (Google et al)
- Authenticated user is relocated to `{localhost:8080|staging.trilliontrees.com}/auth0-callback`
- A newly created user needs to specify user type: individual | company and update some details.
- We relocate them to any page in the app.

All of the templates and emails that they use can be customized by us.

---
original issue:

Integrate SSO on Mobile + Web apps
to enable login with Google & Apple Accounts.

Auth0 can be used an Identity Manager to facilitate all the SSO and login.

Inspiration for the new login flow is Airbnb App.

Someone has wrote it In react, older, but could be helpful.
https://github.com/imandyie/react-native-airbnb-clone

We could modify Auth0 UI, or use the default.

Backend will need some changes to accommodate these:
– as we wont send activation email with SSO users.
– we still need to be able to authenticate users through database/ migrate them to Auth0

**Comment by norbertschuler** [comment]
Own project with https://github.com/Plant-for-the-Planet-org/treecounter-app/projects/5
