### ISSUE TITLE
Leaderboard top entry of India tree counters displays an empty line

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1270]
**Describe the bug**

The No.1 entry of tree counter in the country India has no name to display as no name is returned from the backend API call.

**Is it on a Production or Development Build?**
production

**To Reproduce**
https://www.trilliontreecampaign.org/leaderboard/country/IN

**Expected behavior**
Show a name similar to the one displayed if you click on the entry and view the tree counter details.

**What actually happens**
The name of the entry is empty.

**Screenshots**
Here you can see the empty line and the result of the API call below:
<img width="1148" alt="Bildschirmfoto 2019-08-20 um 10 17 38" src="https://user-images.githubusercontent.com/1532418/63330679-821a7b00-c334-11e9-9253-6cfb6558be57.png">
Compare with the detail page of this tree counter (https://www.trilliontreecampaign.org/t/ministry-of-environment-and-forests-government-of-india-2) where we get a name to be displayed:
<img width="1149" alt="Bildschirmfoto 2019-08-20 um 10 19 19" src="https://user-images.githubusercontent.com/1532418/63330751-aa09de80-c334-11e9-883d-245993a470cf.png">

**Desktop (please complete the following information):**
- OS: MacOS latest
 - Browser Chrome latest
 - Plant-for-the-Planet App Version 1.0.5

**Comment by norbertschuler** [comment]
There are also other empty entries, e.g. for Turkey https://www.trilliontreecampaign.org/leaderboard/country/TR

**Comment by crucialfelix** [comment]
And maybe use contributor slug as a backup caption.

**Comment by norbertschuler** [comment]
Closing as related to old web client.
