### ISSUE TITLE
Native apps and project selection in web client are broken

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1281]
## Error in Plant-for-the-Planet App

**TypeError** in **app/components/PlantProjects/PlantProjectSnippet.native.js:100**
TypeError: TypeError: TypeError: TypeError: null is not an object (evaluating 'k.taxDeduction')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d5dbfd650c01c0019f5b6d6?event_id=5d5dbfd6004d67bb51d30000&i=gh&m=ci)

## Stacktrace

    app/components/PlantProjects/PlantProjectSnippet.native.js:100 - value
    app/components/TreecounterGraphics/Trillion.native.js:67 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d5dbfd650c01c0019f5b6d6?event_id=5d5dbfd6004d67bb51d30000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
I assume the error is cause by the fact, that the API call `https://www.trilliontreecampaign.org/public/v1.1/de/loadTpos` now is returning TPOs with a list of plant projects with an empty "paymentSetup" field which the native apps do not check for.

<img width="758" alt="Bildschirmfoto 2019-08-22 um 11 29 07" src="https://user-images.githubusercontent.com/1532418/63503806-7a8fd900-c4d0-11e9-8970-c14ba2a8b0c9.png">

**Comment by norbertschuler** [comment]
I thought about writing checks but the application is relying very much on the availability of these data:

<img width="544" alt="Bildschirmfoto 2019-08-22 um 13 55 52" src="https://user-images.githubusercontent.com/1532418/63512623-92715800-c4e4-11e9-97ab-469196f4237e.png">

**Comment by Plant-for-the-Planet** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**TypeError** in **app/components/PlantProjects/PlantProjectSnippet.native.js:100**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d5dbfd650c01c0019f5b6d6?event_id=5d5e9126004d7dfe794b0000&i=gh&m=fx)
