### ISSUE TITLE
Add Icons to download app in the web menu

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1293]
Add icons on the Web Menu to download the apps.

These icons need to be localized as well.

<img width="309" alt="Screen Shot 2019-08-23 at 5 40 22 PM" src="https://user-images.githubusercontent.com/5401575/63604866-1868ce00-c5cd-11e9-9572-b73a42aaa5e5.png">

https://zpl.io/awO95rj

`Ignore the Language and Currency dropdown for this task.`

**Comment by mahmed0715** [comment]
can be closed as the pr merged. @norbertschuler

**Comment by mahmed0715** [comment]
@sagararyal is it still pending? I think the pr related to this was merged.

**Comment by norbertschuler** [comment]
should be closed
