### ISSUE TITLE
Add eslint to circleci testing

### ISSUE THREAD

**Issue by crucialfelix** [Plant-for-the-Planet-org/treecounter-app#1301]
Since there are currently large numbers of errors, edit .eslintrc.json to decrease most of those to warnings. 

Then one by one (in separate PRs):
- increase from warning -> error
- fix all cases in code

Let's disable the hound.

Should include plugins for:
- css
- css in js (react native)
- json

**Comment by norbertschuler** [comment]
If you don't know any reason why someone named it `.eslintrc.json`, we maybe can rename it to `.eslintrc` which I think if the default name for such a file. Just have to change the reference in the` .hound.yml` config file.
