### ISSUE TITLE
Add TypeScript support

### ISSUE THREAD

**Issue by crucialfelix** [Plant-for-the-Planet-org/treecounter-app#1303]
Let's consider adding TypeScript via babel. This can be done gradually: Write new components in .ts / .tsx, port the most used components.

Most of the reported bugs are run time Type Errors that can easily be eliminated when using TypeScript.

Development is also much faster as React components prop types are typed and VSCode makes working with those components much easier.

**Comment by norbertschuler** [comment]
Already done with e.g. app/containers/Menu/StaticTabbar.tsx
