### ISSUE TITLE
Unification of Currency in the Application

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1304]
# The Goal

- Show all tree costs in one single currency
- Auto detect location and set currency
- Allow users to change the default currency

Currency Selection —> Default ( —> last used, set by location, IP) user can Override
- [ ] Provide API to update the currency of the user,  when changed. @jmiridis 
## To Do

- [ ] Provide Currency Exchange Rate: https://www.trilliontreecampaign.org/public/1.3/de/currencies
@jmiridis need to update these exchange rates every day, or develop new way to communicate exchange rates.

- [ ] Dropdown that allows user to set global currency
<img width="203" alt="Screen Shot 2019-08-26 at 1 27 29 PM" src="https://user-images.githubusercontent.com/5401575/63687583-42a4d080-c805-11e9-8b95-9207383e0a86.png">

- [ ] Get currency in plantProject and convert it to global currency in project cards
  

- [ ] Same for Native Apps (I'll provide design)

**Comment by mahmed0715** [comment]
I am on it.
but "Get the global currency but ; still allow the user to overridden the currency during the donation process." please explain a  bit @sagararyal  ?

**Comment by sagararyal** [comment]
userCurrency = Currency (set by user, or defined by Location


Currently All projects have price as following in the APIs

eg Yucatan – 1 EUR
eg Project X - 2 CHF
eg Project Y - .2 USD


if userCurrency = CHF (Swiss Francs)

we want to use the exchange rate to convert and show all these prices in 
Exchange rate is provided in currency API.

eg Yucatan – 1.x CHF
eg Project X - 2 CHF
eg Project Y - .23 CHF

---
You can ignore my message about overriding the currency during donation.

My idea behind overriding was there, because I thought, maybe the user is not aware that they can change the currency. I think we can solve this by putting a card that informs them currency is set globally.

**Comment by mahmed0715** [comment]
Okay , so in summery,
1. Default Currency: Be default there will be a currency already set(either our provided default, or from user location, or if there are settings for that in user profile) and always shown as selected in the dropdown(we use this as base currency), so everywhere this will reflect.

2. User can change from the dropdown any time and the change should reflect everywhere(every currency related thing should follow the change)
@sagararyal please correct me.

**Comment by mahmed0715** [comment]
@sagararyal  @jmiridis Please let me know what api we can use to update currency, I tried /api/{version}/{_locale}/profileUpdate and profileAboutMe but not updating the field.
Please let me know...

**Comment by mahmed0715** [comment]
@sagararyal we want to do the change for native app also in the same PR?
