### ISSUE TITLE
Competition Native App Enhancements

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1305]
# This task contains several features

## Description

- [x] Add info card on top of Competition page.
<img width="492" alt="Screen Shot 2019-08-26 at 1 38 17 PM" src="https://user-images.githubusercontent.com/5401575/63688155-d1feb380-c806-11e9-8f38-f0b49326ee2b.png">

**Mine** 

whenEmpty-> `It seems you have not joined or started any competitions. Any Competitions you join or start will appear here` 
else -> Here's a list of competitions you have created or joined. Donate to plant trees and see your competitions reach their goal.

add two button [create competition] [View All Competitions]

**Featured**
always -> `Select a competition to join and start planting trees`
sorted by recently added

**List All**
Sorted by recently added

**Closed**
sorted by recently closed (end date)

## Allow competitionOwner to Join or Leave Competition

- [x] currently only Join/Leave/Edit button shows up

Show two buttons 
<img width="448" alt="Screen Shot 2019-08-26 at 1 47 57 PM" src="https://user-images.githubusercontent.com/5401575/63688659-47b74f00-c808-11e9-8f1c-13d7de8cade0.png">

**Button 1**
Request to Join - can request
Join - isPublic
no button - inviteOnly
leave - isJoined

**Button 2** - if user = competionOwner
Edit - allows to edit competition

## Add Clean UI to Competition

- [x] update UI from Zeplin

## Add Start Competition button

<img width="395" alt="Screen Shot 2019-08-26 at 1 51 11 PM" src="https://user-images.githubusercontent.com/5401575/63688787-949b2580-c808-11e9-96cb-d40009964c55.png">

- [x] Add a floating button (on feature, All Competition and Closed Pages) Exact design may change in Zeplin.

**Comment by harshvitra** [comment]
#1422 will solve this
