### ISSUE TITLE
Functional Issues in Widget

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1309]
- [ ] Commas in numbers 
_(should exist and be locale aware 1,000,000 in us is 1.000.000 in german)_
<img width="592" alt="Screen Shot 2019-08-26 at 5 34 19 PM" src="https://user-images.githubusercontent.com/5401575/63702705-bce64c80-c827-11e9-89a3-0b376c9229dd.png">

- [ ] Fix request to invalid URL

the request should be to `{host}` instead of local-path.

- For image and 
- treecounterwidget.css
this also occurs when hosted in server.
  
<img width="880" alt="Screen Shot 2019-08-26 at 5 44 23 PM" src="https://user-images.githubusercontent.com/5401575/63703401-3468ab80-c829-11e9-9555-2ea932b8b019.png">

- [ ] include planted actual number below the rounded number
  
<img width="442" alt="Screen Shot 2019-08-26 at 5 35 59 PM" src="https://user-images.githubusercontent.com/5401575/63703568-89a4bd00-c829-11e9-86b2-779adac6dea1.png">

- I believe the font will be fixed when it can load planet `treecounterwidget.css`
- The tree count shows nothing planted, could that be css issue as well?

Q: why is the treecounterwidget.js loading all config, while it does not need any of these:
example:

it is 2.3 MB

<img width="1679" alt="Screen Shot 2019-08-26 at 5 50 28 PM" src="https://user-images.githubusercontent.com/5401575/63703847-16e81180-c82a-11e9-9539-d78094a183ae.png">

<img width="1329" alt="Screen Shot 2019-08-26 at 5 52 20 PM" src="https://user-images.githubusercontent.com/5401575/63703952-4bf46400-c82a-11e9-88b1-77f21fa474b7.png">

**Comment by norbertschuler** [comment]
Closing as related to old web client.
