### ISSUE TITLE
Free donation amount not visible while entering values on Android device

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1317]
**Describe the bug**
On an Android device the amount of trees or money to donate to a project is hidden while the keyboard is opened to enter the amount.

**Is it on a Production or Development Build?**
both

**To Reproduce**
1. Donate to a project up to the page to choose the amount of trees
2. Click the radio button to donate 150 trees.
3. Click on the input field for the trees to change the amount.

**Expected behavior**
Scroll up the layout to see the input field while typing on the keyboard.

**What actually happens**
The page is not scrolled up, but the keyboard is hiding the input field.

**Screenshots**
![Screenshot_20190827-170953](https://user-images.githubusercontent.com/1532418/63783883-04cfa700-c8ee-11e9-84b8-af2d54a53bb5.png)

**Smartphone (please complete the following information):**
- Device: Samsung Galaxy S6 Edge
 - OS: Android 7.0
 - Plant-for-the-Planet App Version 1.0.6

**Comment by crucialfelix** [comment]
Why is the bottom menu visible there? It should be under the key pad.
