### ISSUE TITLE
TypeError in /pledge/e-wald

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1322]
## Error in Plant-for-the-Planet App

**TypeError** in **/pledge/e-wald**
Cannot read property 'map' of undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d663b83af60ff001b252bf5?event_id=5d663b83004dcfa3f9c70000&i=gh&m=ci)

## Stacktrace

    http://0.0.0.0:8080/bundle.js:184263 - Pledge.render

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d663b83af60ff001b252bf5?event_id=5d663b83004dcfa3f9c70000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
development
