### ISSUE TITLE
Update react-native to latest version 0.60.x

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1327]
We are currently using version 0.59.8 and therefore already need patches like the postinstall script in `package.json` to make the Android build possible.

To better support the latest versions of Android and iOS we should upgrade to react-native 0.60.x (0.61.x is still a release candidate). Unfortunately this upgrade might be quite painful if the Android and iOS project structure has changed and we would have to adapt our individual changes to the Android and iOS project again if they get lost by upgrading (I am not sure about that).

Also while doing so we could upgrade other react-native node modules which are linked in the iOS or Android project:
- react-native-linear-gradient
- bugsnag-react-native
- react-native-device-info
- react-native-image-picker
- react-native-i18n
- react-native-svg
- react-native-youtube
- ...

A helper tool proposed by @harshvitra https://react-native-community.github.io/upgrade-helper/?from=0.59.10&to=0.61.4

Read more about what you should be aware when doing the upgrade at https://facebook.github.io/react-native/blog/2019/07/03/version-60

**Comment by crucialfelix** [comment]
I was trying to update react-native-tab-view. This requires everybody to reinstall and run pod update usw. It might be good to have all react-native updates in one single annoying merge.
