### ISSUE TITLE
Setup Auth0 custom db connection handlers

### ISSUE THREAD

**Issue by crucialfelix** [Plant-for-the-Planet-org/treecounter-app#1336]
These will make POST requests from Auth0 to our backend for user create, authenticate, changePassword, etc.

- [x] devel
- [x] test
- [x] staging
- [x] www master

The handlers are implemented in this issue:
https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1291

**Comment by norbertschuler** [comment]
No custom handlers for creating users or changing password have been build. Users get created by another API call after Auth0 signup in the our apps and password management does not take place for the backend, only in Auth0.
