### ISSUE TITLE
Smart Banners Logo [404]

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1341]
<img width="649" alt="Screen Shot 2019-08-29 at 11 08 11 AM" src="https://user-images.githubusercontent.com/5401575/63927072-4b87e300-ca4d-11e9-860e-9d6b0224a032.png">

The Logo on the banner returns 404.
https://www.trilliontreecampaign.org/web/assets/icons/planet_icon.png

– Also correct Plant-for-the-planet to `Plant-for-the-Planet` App
the capitalization of `Planet`

**Comment by norbertschuler** [comment]
Text change will be done if we reimport the LingoHub resources.
