### ISSUE TITLE
Branding - The Plant-for-the-Planet App

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1342]
This is a checklist for migration of `trilliontreecampaign.org` to `weplant.app`

### Reasons for Migration

– Trillion Tree Campaign is long to communicate.
– Reduce Confusion, Trillion in German is actually written as `Billion`
– wePlant is easy to communicate. and easy to remember.

- [ ] Check when Migration Completed

### What is the app going to be called?

Plant-for-the-Planet App

The App is a call to action, to Plant Trees. Many people around already know Plant-for-the-Planet as a campaign. The App will serve as an easy solution to act along with the trust.

- [ ] Update Translations
- [ ] Add FAQs and Check for inconsistencies
- [ ] Develop a Terms of Service / Use for the App
- [ ] Revisit Data Protection Policy (for names)

### Will this change the way the app operates?

No. This change only is to improve communication and reach wider audience. We pledge to keep the App Open Source and take no commissions from any donations.

### Communications

- [ ] All emails after the migration will be sent from `plant-for-the-planet.org` domain, (check emails)

– Statement descriptors for Donations will continue to mention ` Tree Donation` or `Tree Gift`

### Additional Domains:
The following domains will forward to WePlant.app

- trilliontreecamapign.org
- [ ] TTC needs to redirect all urls
however, it could be maintained in parallel for a month or so, during the communication process. 

- startplanting.org
- plant-for-the-planet.app
- plant-for-the-planet.org/app
-- Any potential domains someone wants to gift, or we should acquire?

**Comment by norbertschuler** [comment]
Closing as related to old web client.
