### ISSUE TITLE
Differ between singular and plural form of numbers

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1346]
A Treecounter can display e.g.
- 1 Thousand
- 0.1 or 1.2 or 10 Thousand <-- exception not using a plural form
- 1 Million
- 0.1 or 1.2 or 10 Millions
- 1 Billion
- 0.1 or 1.2 or 10 Billions
- 1 Trillion
- 0.1 or 1.2 or 10 Trillions

(As I am no native speaker, I am not so sure about English.)

In German:
- 1 Tausend
- 0,1 or 1,2, or 10 Tausend <-- exception not using a plural form
- 1 Million
- 0,1 or 1,2, or 10 Millionen
- 1 Milliarde
- 0,1 or 1,2, or 10 Milliarden
- 1 Billion
- 0,1 or 1,2, or 10 Billionen

So the rules are:
- use singular form for just exactly 1
- use only singular form for Thousand
- use plural form else

Don't know what rules apply for other languages. This could be a very complicated issue.

**Comment by sagararyal** [comment]
@norbertschuler What if we show the amount below

eg: 

Planted
10.2 Million
10.200.501

Does that work with German?


Else we'll have to document the translation keys carefully: 
In English 10.2 Million is totally fine.

**Comment by norbertschuler** [comment]
@sagararyal thanks for clarifying the English version. For German it sounds wrong to say "2 Million" - it has two be "2 Millionen". It's really just the "1" which says "1 Million", anything else is plural. So now I know different languages do it differently an implementation would be even more complicated :-(

**Comment by sagararyal** [comment]
In Nepali / Hindi for example, 

1 thousand = 1 Hajar 
100 thousand = 1 lakh
10 million = 1 crore
1 billion = 1 arab
![western_eastern_numerical_conversion_table](https://user-images.githubusercontent.com/5401575/64034517-2085b800-cb4f-11e9-9f8c-aaf87eb2b05d.jpg)



**I suggest the key scheme to be:**

`1_million`
`2-9_million`
`10-99_million`
`100-999_million`
`1_billion`
...

@norbertschuler thoughts?
