### ISSUE TITLE
Integrate Donation Flow in Mobile

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1356]
All this has to be done in 1 PR. 

Page 1 and 2 exist in the current app, they are not context aware.

### Donation page can be Reached from:

- Single Project 
- Context Token (Widgets, Pledges, Links.. etc)

# Donation Page Step 1

- [x] Design in Code Ready @harshvitra 

– Title: `Tree Donation`
If the donation is a type `gift` change title to `Tree Gift` ; All other conditions, keep Tree Donation.

– Donation can only be made to verified project that accept donations.

– Clicking on card about the project should link the user to the Project, and clicking Donate, or back from that page should bring to this page again, without clearing any selected data.

– Each project can have three pre set values of `tree-count` they can advertise.
eg: `10` `50` `150`  and custom amount.
Second amount is always preselected, 

-- // In case of Pledge Events, the default count is overridden by the pledge count, and the pledged amount becomes the minimum tree count. 
second count is 2x the initial pledge count, and third the 3x the amount.
This can be cleared when the user goes back reaches the homepage. ( in this case, a new card about the pledge will be kept there to bring user to this screen again) 
This is more related to contextual donations.  //--

– The numeric value is unique to each project and are defined by the Organizations.

– Each project can set a min amount of trees they accept. (this will be shown when a user enters tree count < minAcceptedAmount ; below the circles. // todo @sagararyal  add the text in design.

– Section `How Often` should only show up is the user is logged In. This is to ensure that we do not create subscription for users without an account.

The default choice is `One Time Donation`, additional options include `Every 3 Months`, `Every Six Months`, and `Every Year`.

– Regarding Tree Gift To, Dedicated to, Pledged on
If the Donation Type Is Tree Gift; 
Heading = Tree Gift

`By default, users can have trees dedicated to someone` show the name of the person. Tree Gift overrides it.

Trees Pledged on `Event` can be dedicated to some other tree counter set by the Event.
in this case.

first show the Heading Pledged On, Event Name, Date (get details from pledge events API

and repeat the same for Dedicated to, TreeCounter DisplayName, (email field should be hidden when gift/dedication to existing App users). get this data from pledge event API incase of pledge.

<img width="472" alt="Screen Shot 2019-09-01 at 8 43 32 PM" src="https://user-images.githubusercontent.com/5401575/64080878-33d48700-ccf9-11e9-8aaf-fd0f5b8e834b.png">

Below the page is a card, that sticks to the bottom and updates with any changes made to the page. (content of these cards change based on screen.)

On Click Continue, take the user to Step 2 of the donation. (Donation Billing Details).

# Donation Page Step 2

- [x] Design in Code Ready @harshvitra 

If the user is logged-in always pre fill the details.

Save them as, Individual Address, And Company Address in the Backend
- [ ] @jmiridis APIs might need to be updated.

Allow the customer with two options here:

1.  Save the Address in Profile (if user.state = logged.in)
Client Should call an API on background, to update the user address after clicking `Continue`.

2. Share details with Plant Projects
If unchecked, Stripe or any Payment Provider should not receive more than FirstName, Last Name of the Donor. We could identify the user with Donation ID, but a token can be created (backend)?

In places where we show the donation details to TPO, in future, this should be shown as Anonymous Donation.

<img width="324" alt="Screen Shot 2019-09-01 at 9 12 19 PM" src="https://user-images.githubusercontent.com/5401575/64081148-31742c00-ccfd-11e9-96e4-dba964407c6a.png">

# Donation Page Step 3 (Payment)

We accept several payment methods:

– Through Stripe: Credit Card, Apple Pay, Google Pay (SEPA)
Hide Apple Pay in Android, and Google Pay in Apple devices.

– SEPA : Plant-for-the-Planet (We) will accept donations using Stripe SEPA for all projects.
– PayPal: We will accept donations using PayPal for all verified projects in the app.

Apple Pay and Google Pay Integration might need additional work in the Backend.
https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1165

<img width="330" alt="Screen Shot 2019-09-01 at 9 28 08 PM" src="https://user-images.githubusercontent.com/5401575/64081310-7305d680-ccff-11e9-9f1c-fdd65ef27fb2.png">

`Links to design files will be added soon, to each section and feature, if missing please contact me.`

**Comment by harshvitra** [comment]
Will be fixed in #1908
