### ISSUE TITLE
RCTFatalException: Un in unknown method

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1357]
## Error in Plant-for-the-Planet App

**RCTFatalException: Un** in **unknown method**

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d6d164f9db5cc001a5c708b?event_id=5d6d164f004e7d043a060006&i=gh&m=ci)

## Stacktrace

    unknown file:0 - unknown method

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d6d164f9db5cc001a5c708b?event_id=5d6d164f004e7d043a060006&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
native error - cannot reproduce
