### ISSUE TITLE
Cannot Change Currency during donation

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1364]
This has been notified in Slack couple of months ago, but I cannot select any other currency during donation. 

The screen freeze, both on iOS and Android.

account: sagar@aryal.me in production
<img width="461" alt="Screen Shot 2019-09-03 at 1 32 14 PM" src="https://user-images.githubusercontent.com/5401575/64170287-0f3ef300-ce50-11e9-9aff-e19ead0a8278.png">

**Comment by norbertschuler** [comment]
Can you check if this is still happening with the current develop version?

**Comment by norbertschuler** [comment]
@sagararyal still can not reproduce this neither in my iPhone X simulator nor on my real device. Which version of the app are you using (check information in menu)?

**Comment by norbertschuler** [comment]
Issue can be reproduce in English, not happening in German where currencies are localized.

**Comment by norbertschuler** [comment]
This is an UI issue where the currency chooser is display at the top of the screen and can not be selected:
![Simulator Screen Shot - iPhone X - 2019-09-19 at 09 53 06](https://user-images.githubusercontent.com/1532418/65224525-a1d3c900-dac3-11e9-8cdf-722a92371991.png)
