### ISSUE TITLE
Custom Symfony AuthenticationProvider to accept JWT from auth0 as well as current JWT

### ISSUE THREAD

**Issue by crucialfelix** [Plant-for-the-Planet-org/treecounter-app#1368]
Authenticated requests should accept JWT either generated by our own backend or from Auth0.

Decoding this JWT should provide a user object:

```js
{
  "nickname": "nick+name",
  "name": "nick.name@gmail.com",
  "picture": "https://s.gravatar.com/avatar/66225cba7438f0770aa67434c5494051?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fcr.png",
  "updated_at": "2019-08-29T09:43:27.355Z",
  "email": "nick.name@gmail.com",
  "email_verified": false,
  "iss": "https://planetapp.eu.auth0.com/",
  "sub": "auth0|5d679e3f27d8600d452182ec",
  "aud": "f87fcw2Tt0A9TAinILwtfSiD4QnQilph",
  "iat": 1567080562,
  "exp": 1567116562,
  "nonce": "wJeQ0-0~_Pd0ofinyCptRtcNFN_fv91buURqkdgvDQp"
}
```

The user id is the "sub" field.

Also make sure that the decoded public key is:
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1a4ntka/rh/QybFN38dW
giPwJfy3uHI6HMZ15ENsySjQQe1j1k8hp0xV4cxWYI0AtyyA2yjF2s/24xU0vX67
E969KzIKbpuc7FCzNk0zYuw/WxMRyirEedURBruA9hnF5tjOGds5yg+SKhoat1G9
a5l1apjYQ7beHyybTn8gB9wdnDDP45GQpDm8nVQasUFQYIBLFUW56R49lrmgUuQA
isVlIZdRB1OkhZ2NIv7j/PAUMlS+y/DkXIuQTP2Il9IUInJKBU4DhV3dO/ANfZBM
568O7XtLbigo0ZZqkky8+UGma6pVhbIAIUmigFWvZhs2YxH+jNLA8BNUfZFKoDfD
dwIDAQAB
-----END PUBLIC KEY-----

We do not yet have the custom db connection set up (which would create users in our db in response to account creation on auth0).  Even when we do have that set up, there can be race conditions, so the user may not yet exist in our db.

**Comment by jmiridis** [comment]
#### Authenticating a JWT provided by Auth0 has been solved. 
The bundle `https://github.com/auth0/jwt-auth-bundle` installs as a requisite the bundle https://github.com/auth0/auth0-PHP which provides methods to decode an Auth0 provided JWT by fetching the secret key from the Auth0 account. This key can be cached but the default is that it is being looked up on every JWT verification.

#### New Backend Features
These are the features I visualize being necessary for the final solution:

1. Restricted API calls can be authenticated via backend-generated and Auth0-generated JWT (solved). Protection can be achieved using 1 or both of the following options:
    1. Basic Authentication
    1. IP restriction

1. New Public API call to create a user profile providing:
    1. Auth0 JWT identifying the user that has already sign-up with Auth0
    1. form data including the profile type and further information that has not been captured during Auth0 sign-up. 

    This API call will:
    1. Fetch the profile from Auth0 using the JWT
    1. Use the form data and the profile data to create a backend UserProfile/Treecounter, etc.

    This means, that the authentication mechanism must some kind of special response in case:
    1. The Auth0 provided JWT is valid
    1. and no UserProfile can be matched to it

    so the application can display the 'create profile' page.

1. API to allow Auth0 to authenticate existing users (solved).

    ![image](https://user-images.githubusercontent.com/1295390/65380755-d30cee80-dca7-11e9-93fb-87d23c9f3a82.png)

**Comment by crucialfelix** [comment]
1. Restricted API calls

Protection is the Auth0 JWT token, just as it is currently with the backed generated token. 
IP address could be anything - these are users out there in userland. It's not Auth0 making requests.

2. New Public API call to create a user profile providing

Auth0 (and only Auth0) will send requests as per this issue: https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1291

Our applications do make these requests at all.

Further discussion of these API calls should go here: https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1291

**Comment by crucialfelix** [comment]
Here is the code from that package for decoding the JWT:

https://github.com/auth0/auth0-PHP/blob/master/src/JWTVerifier.php

The rest of that package is for a full php website that uses Auth0 for authentication.

> fetching the secret key from the Auth0 account. This key can be cached but the default is that it is being looked up on every JWT verification.

I have the `client_secret`. It cannot be transmitted by Auth0 ever. I can give it to you though. You can trust me.

https://github.com/auth0/auth0-PHP/blob/600dd3c7e5de1ba006278c85587ef542e65369ad/src/JWTVerifier.php#L69-L76

That is something that you will have in your config. Not in source code.

Have you got the JWTVerifier working in a Symfony Authentication Provider?

**Comment by jmiridis** [comment]
I have it all up and running ready for client activity. Maybe we should have a talk, not sure how much to document.

**Comment by crucialfelix** [comment]
ok, let's talk. give me a bit. I need a cookie.

After auth0 calls create (createUser) https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1291  then you should have a new user in the database.  

Subsequent requests eg. `loadUserProfile` will be called with an Auth0 JWT that contains the user profile. 

I guess this means that you look up the user using `email` each time. Is that what you did?
