### ISSUE TITLE
Add sharing possibility to single projects

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1381]
**Describe the feature you'd like to see included in Plant-for-the-Planet App.**
We want to have an individual share link for every single project. The link should also be able to open the app (with a deep-link) or web site again showing this project.

This issue was already discussed in this pull request: https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1311

**Comment by otmezger** [comment]
Hi @norbertschuler  is this feature already available? I wanted to do just this now but could not find any option to do so.

**Comment by norbertschuler** [comment]
No, an unique share link for a single project is not yet implemented in our native apps.
