### ISSUE TITLE
Android build broken by SVG assets

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1383]
Android does not build as assets folder does not allow SVG files. Would have to be put in another folder or converted into PNG files:
```
> Task :app:mergeReleaseResources FAILED
/Users/norbertschuler/Development/PFTP/treecounter-app/android/app/build/generated/res/react/release/drawable-mdpi/app_assets_images_en_applestorebadge.svg: Resource and asset merger: The file name must end with .xml or .png
```

The SVG files added from https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1354 make a problem.

**Comment by sagararyal** [comment]
Android supports vector drawables.

https://developer.android.com/guide/topics/graphics/vector-drawable-resources

Android Studio can convert svg to vector drawables.

Same with Xcode.
