### ISSUE TITLE
TypeError in app/components/Leaderboard/categoryTypes/index.native.js

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1389]
## Error in Plant-for-the-Planet App

**TypeError** in **MainActivity**
null is not an object (evaluating 'this.scrollView.scrollToEnd')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d75d0ec635f0c001a801d01?event_id=5d75d0ec004f25c4d06d0000&i=gh&m=ci)

## Stacktrace

    app/components/Leaderboard/categoryTypes/index.native.js:28 - value
    app/components/Leaderboard/categoryTypes/categoryType.native.js:13 - value

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d75d0ec635f0c001a801d01?event_id=5d75d0ec004f25c4d06d0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
bug expired
