### ISSUE TITLE
Add new auth routes backend and fos_js_routes.json

### ISSUE THREAD

**Issue by crucialfelix** [Plant-for-the-Planet-org/treecounter-app#1390]
To support new Auth flow, we need the following GET routes added:

- `/auth0-callback` Where auth0 relocates the user to after authenticating
- `/authorize`  The app redirects any non-authorized user who arrives here to auth0

```js
      <Route
        path="/auth0-callback"
        component={Auth0Callback}
      />
      <PublicRoute path="/authorize" component={Auth0Authorize} />
```

**Comment by jmiridis** [comment]
I have added the following 2 routes to the feature branch so that they will load the application which can handle them. This feature branch has not yet been deployed to any server environment.

```
@Route("/auth0-callback", name="app_auth0Callback", options={"expose"=true})
@Route("/authorize", name="app_auth0Authorize ", options={"expose"=true})
```

**Comment by crucialfelix** [comment]
When and how does that generate the `fos_js_routes.json` ?

**Comment by crucialfelix** [comment]
When does that get deployed to at least devel?

**Comment by norbertschuler** [comment]
@crucialfelix should be deployed to https://devel.trilliontreecampaign.org/ now.  I assume you could copy the https://github.com/Plant-for-the-Planet-org/treecounter-platform/blob/feature/old_devel_branch_for_auth0/web/js/fos_js_routes.json  file from the backend repository of the branch `feature/old_devel_branch_for_auth0` into you app repository branch.

**Comment by norbertschuler** [comment]
This should be solved with https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/2568.
