### ISSUE TITLE
Leaderboard entry for Pakistan not clickable

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1406]
**Describe the bug**
When you open https://www.trilliontreecampaign.org/leaderboard/country/PK and try to click on the first entry "Ein Baumpflanzer" nothing happens.

**Is it on a Production or Development Build?**
production and development

**To Reproduce**
1. Go to https://www.trilliontreecampaign.org/leaderboard/country/PK
2. Click on first entry named "Ein Baumpflanzer"

**Expected behavior**
The treecounter should be loaded and displayed as for other entries in the leaderboard.

**What actually happens**
Nothing happens, but on a local development environment you can see errors in the console, one error when loading the page in step 1, another error when clicking on the first entry in step 2.

```
1. SyntaxError: Unexpected token } in JSON at position 3
    at JSON.parse (<anonymous>)
    at queryParamsToObject (utils.js:111)
    at LeaderBoardContainer.getDefaultQuery (index.js:48)
    at index.js:219

2. SyntaxError: Unexpected token } in JSON at position 3
    at JSON.parse (<anonymous>)
    at queryParamsToObject (utils.js:111)
    at LeaderBoardContainer.getDefaultQuery (index.js:48)
    at LeaderBoardContainer.componentWillReceiveProps (index.js:144)
    at callComponentWillReceiveProps (react-dom.development.js:13388)
    at updateClassInstance (react-dom.development.js:13598)
    at updateClassComponent (react-dom.development.js:16992)
    at beginWork$1 (react-dom.development.js:18505)
    at beginWork$$1 (react-dom.development.js:23193)
    at performUnitOfWork (react-dom.development.js:22211)

```
**Screenshots**
<img width="720" alt="Bildschirmfoto 2019-09-11 um 15 27 12" src="https://user-images.githubusercontent.com/1532418/64701223-a5a29280-d4a8-11e9-8760-51ddc4acf9e0.png">

**Desktop (please complete the following information):**
- OS: latest MacOS
 - Browser latest Chrome
 - Plant-for-the-Planet App Version 1.0.7

**Comment by norbertschuler** [comment]
I just recognized the property `mayPublish: false` for the first entry while the other entries have `mayPublish: true` in the result of the API call https://www.trilliontreecampaign.org/public/v1.1/de/exploreQuery/country/PK?orderBy=planted&period=all used to load the data for this page.

**Comment by jmiridis** [comment]
This does not seem to me that it is backend related.
@norbertschuler Thanks for unassignment.

**Comment by norbertschuler** [comment]
@jmiridis O.k., then I will removed the backend label. But before please help me clarify the question: When the backend returns an entry with the property `mayPublish: false`, what exactly should the frontend do with this entry (how should it be displayed)?

**Comment by crucialfelix** [comment]
I would think it should not display or publish it. The backend should not have returned it, but regardless the frontend should do the right thing and not publish it.
