### ISSUE TITLE
Design enhancements for payment process

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1411]
**1. Credit Card number can not be displayed completely - so the user can not check the input:**
![Simulator Screen Shot - iPhone X - 2019-09-12 at 10 11 34](https://user-images.githubusercontent.com/1532418/64768288-7859f100-d549-11e9-8ca0-bfa3afc77c69.png)

**2. Make the PayPal button smaller so it's not cut:**
![Simulator Screen Shot - iPhone X - 2019-09-12 at 10 19 42](https://user-images.githubusercontent.com/1532418/64768290-78f28780-d549-11e9-97f4-b858609ac201.png)

**3. Use more horizontal layout to avoid scrolling**
![Simulator Screen Shot - iPhone X - 2019-09-12 at 10 11 52](https://user-images.githubusercontent.com/1532418/64768289-78f28780-d549-11e9-8e90-c8c078e0bdff.png)
![Simulator Screen Shot - iPhone X - 2019-09-12 at 10 26 40](https://user-images.githubusercontent.com/1532418/64768291-78f28780-d549-11e9-866b-0c4de826c057.png)

**Comment by harshvitra** [comment]
@norbertschuler check this [PR](https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1372). 

We are changing the way donations work, I'll add the screenshots of the new design there.

**Comment by norbertschuler** [comment]
@harshvitra that PR would definitely fix this issue.

**Comment by harshvitra** [comment]
The PR is now at #1908

**Comment by norbertschuler** [comment]
Closing as related to old web client.
