### ISSUE TITLE
Crash displaying payment chooser page

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1413]
## Error in Plant-for-the-Planet App

**TypeError** in **/donate-trees**
Cannot read property 'contribution' of null

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d7a54c266418300197df46f?event_id=5d7a54c2004fcd76d3f80000&i=gh&m=ci)

## Stacktrace

    http://0.0.0.0:8080/bundle.js:158011 - CheckoutForm._this.handlePayment

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d7a54c266418300197df46f?event_id=5d7a54c2004fcd76d3f80000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Got this error several times today while testing when I changed from the page where you enter your address to the page where you enter your payment details:
https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/d4a05e953f50f2d61d48166a6921f4e9c9dda99d/app/components/Payment/PaymentSelector.js#L70

```
backend.js:1 TypeError: Cannot read property 'contribution' of null
    at PaymentSelector.value (PaymentSelector.js:70)
    at PaymentSelector.js:275
```

**Comment by norbertschuler** [comment]
One way I was able to reproduce this bug is to enter a company address instead of using my private address before I enter the payment chooser dialog.

**Comment by norbertschuler** [comment]
Here is the other case #1439 as a bugsnag issue.

**Comment by norbertschuler** [comment]
I checked that running the code at one point `this.props.donationId` does not exists and `this.props.paymentStatus` is empty:

<img width="1360" alt="Bildschirmfoto 2019-09-19 um 14 07 59" src="https://user-images.githubusercontent.com/1532418/65242701-f9376080-dae6-11e9-96a5-1dc3f701a429.png">

**Comment by niteshgrg** [comment]
@norbertschuler so this happens when you change back to address page and then come back and make the payment right ?

**Comment by norbertschuler** [comment]
@niteshgrg Start a donation in the web client, enter a company address and then continue to payment.
