### ISSUE TITLE
Improve Donation & Gift Email to include more details on Project

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1426]
Dear {receiver's name},

[infographic gift
] 
{giver} has gifted 55 trees to you.

These trees will be planted in {Country} by {TPO Name}.

To know more about the tree planting project, please click here.

[message] a tree captures 10 kg of co2, which is about ---

You can create your own Tree Counter to add these trees.
IIf you do not currently have a Tree Counter, you can create one during the redemption process.

Feel free to write us with any questions.

All the best,
The Trillion Tree Campaign

**Comment by norbertschuler** [comment]
Mails are send from the backend.

**Comment by jmiridis** [comment]
I assume we are talking about template `e12-gift-notification`.
For further such requirements, this link displays what variables are available for which template:
https://www.trilliontreecampaign.org/backend/emails

If I understand correctly, the following 2 additional variable should be available to the template:

- countryPlanted
- tpoName

@sagararyal please confirm

**Comment by norbertschuler** [comment]
@jmiridis I can not see these new variables?

<img width="812" alt="Bildschirmfoto 2019-09-30 um 09 39 39" src="https://user-images.githubusercontent.com/1532418/65858529-758f3680-e366-11e9-97f9-dcadbbd57132.png">

**Comment by norbertschuler** [comment]
@sagararyal is this still an issue?

**Comment by norbertschuler** [comment]
Closing as related to old web client.
