### ISSUE TITLE
Webpack: add image optimization

### ISSUE THREAD

**Issue by crucialfelix** [Plant-for-the-Planet-org/treecounter-app#1430]
Add https://github.com/tcoopman/image-webpack-loader

to 

https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/develop/web/config/webpack.prod.config.js

Note: we do not use webpack on react-native currently.

**Comment by norbertschuler** [comment]
https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/develop/web/config/webpack.prod.config.js is unused, but https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/develop/web/config/webpack.server.config.js is used instead. Is this issue still an issue if we upgrade to webpack 4?

**Comment by crucialfelix** [comment]
It is entirely separate from webpack 4 #1320 

Though first I would switch to webpack 4, then add the image loaders. Or if Haider feels comfortable, do them together in one PR.
