### ISSUE TITLE
Code Splitting: Use React.lazy to reduce web bundle size

### ISSUE THREAD

**Issue by crucialfelix** [Plant-for-the-Planet-org/treecounter-app#1432]
https://reactjs.org/docs/code-splitting.html

Each page / view can easily be split into its own bundle by wrapping the Lazy into the Routes. 

Better yet make a LazyRoute that wraps it in and use this for all the pages.

**Comment by norbertschuler** [comment]
A nice short article related to this topic: https://blog.bitsrc.io/lazy-loading-react-components-with-react-lazy-and-suspense-f05c4cfde10c
