### ISSUE TITLE
Fix display of my trees

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1436]
**Describe the bug**
The my-tress section also shows failed and pending donations.

**Is it on a Production or Development Build?**
both

**To Reproduce**
1. Go to `My Trees`

**Expected behavior**
Either see only successful donations and gifts or see a proper status of the pending and failed donations.

**What actually happens**
Displaying also failed donations the same as successful donations. Showing a wrong date for failed and pending donations compare to the TTC backend data.

**Screenshots**
![Bildschirmfoto 2019-09-18 um 09 41 19](https://user-images.githubusercontent.com/1532418/65129508-b5b3f800-d9fb-11e9-9ec1-b5ffff840d57.png)
![Simulator Screen Shot - iPhone X - 2019-09-18 at 09 45 04](https://user-images.githubusercontent.com/1532418/65129514-bc426f80-d9fb-11e9-98b1-fa82330565c4.png)
<img width="1107" alt="Bildschirmfoto 2019-09-18 um 09 41 34" src="https://user-images.githubusercontent.com/1532418/65129642-062b5580-d9fc-11e9-9350-37d80a4850c6.png">

**Desktop (please complete the following information):**
- OS: latest MacOS
 - Browser latest Chrome
 - Plant-for-the-Planet App Version 1.0.8

**Smartphone (please complete the following information):**
- Device: iPhoneX
 - OS: iOS 12.4
 - Plant-for-the-Planet App Version 1.0.8

**Comment by norbertschuler** [comment]
If we are working in the API call, maybe we can also add a translation for the status field returned from the API, e.g. "Gift" or "Donation" or "Pending" et al to fix https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/853.

**Comment by norbertschuler** [comment]
`pending` donations are now already suppressed by the backend in the results of the API call.

**Comment by jmiridis** [comment]
`loadUserProfile` will now only return paid donations. 
Not sure if this solves all issues expressed above. Please confirm or correct me.

Solved problem: The `isVerified` status for contributions did not match the `isPaid` status for donations.
Running this query fixed this inconsistency:
```update contribution set is_verified = is_paid where contribution_type='donation' and origin='ttc' and deleted_at is null```

**Comment by norbertschuler** [comment]
Thanks, now I only more see the things I really paid for.
