### ISSUE TITLE
Imagine picker for competition crashes in iOS 13

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1443]
## Error in Plant-for-the-Planet App

**TypeError** in **app/components/Competition/Tabs/mine.native.js:72**
A.showImagePicker is not a function. (In 'A.showImagePicker(T,function(o){o.didCancel||o.error||o.customButton||(o.uri,t.onChange('data:image/jpeg;base64,'+o.data))})', 'A.showImagePicker' is undefined)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d853205c0e755001b27b737?event_id=5d85320500504e43d14c0000&i=gh&m=ci)

## Stacktrace

    app/components/Competition/Tabs/mine.native.js:72 - template

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d853205c0e755001b27b737?event_id=5d85320500504e43d14c0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Image picker in creating competition crashes the iOS with iOS 13:

![DA9671A7-69CA-41D1-8104-9AFB219BBBA4](https://user-images.githubusercontent.com/1532418/65356055-c5962c80-dbf3-11e9-9b8c-25aa1cbfa9a1.png)
