### ISSUE TITLE
Pledge Events crash due to API change

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1463]
## Error in Plant-for-the-Planet App

**TypeError** in **/pledge/mandoki-soulmates**
Cannot read property 'map' of undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d8b1a134caed4001a9e3870?event_id=5d8b1a1300504e6b9da90000&i=gh&m=ci)

## Stacktrace

    http://0.0.0.0:8080/bundle.js:174606 - Pledge.render

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d8b1a134caed4001a9e3870?event_id=5d8b1a1300504e6b9da90000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
API change got reverted
