### ISSUE TITLE
Crash in NVDI component if min property is missing in API response

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1464]
## Error in Plant-for-the-Planet App

**TypeError** in **/donate-trees**
Cannot read property 'min' of null

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d8b1b82a9f0e000199ac192?event_id=5d8b1b8200503a1883490000&i=gh&m=ci)

## Stacktrace

    http://0.0.0.0:8080/bundle.js:147348 - GradientResultLine.calculateHighlightLineColor

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d8b1b82a9f0e000199ac192?event_id=5d8b1b8200503a1883490000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Should be fixed by https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1449
