### ISSUE TITLE
TypeError in /my-trees

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1465]
## Error in Plant-for-the-Planet App

**TypeError** in **/my-trees**
Cannot read property 'map' of undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d8b43666b548d001bfeaebd?event_id=5d8b436600504586b8e20000&i=gh&m=ci)

## Stacktrace

    http://0.0.0.0:8080/bundle.js:173412 - ContributionCard.render

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d8b43666b548d001bfeaebd?event_id=5d8b436600504586b8e20000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Plant-for-the-Planet** [comment]
occurred after registering a new tree and trying to look at it in the web client

Comment added in Bugsnag by Norbert Schuler
[**TypeError** in **/my-trees**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d8b43666b548d001bfeaebd?event_id=5d8b438c00503e1e47a80000&i=gh&m=cm)

**Comment by Plant-for-the-Planet** [comment]
occurred after registering a new tree and trying to look at it in the Android app

Comment added in Bugsnag by Norbert Schuler
[**TypeError** in **/my-trees**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d8b43666b548d001bfeaebd?event_id=5d8b438c00503e1e47a80000&i=gh&m=cm)

**Comment by norbertschuler** [comment]
bug expired
