### ISSUE TITLE
Invariant Violation in /register-trees

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1468]
## Error in Plant-for-the-Planet App

**Invariant Violation** in **/register-trees**
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Textbox`.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d8b48613f9f2f0018c95182?event_id=5d8b4861005040c4b02b0000&i=gh&m=ci)

## Stacktrace

    http://0.0.0.0:8080/bundle.js:92467 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d8b48613f9f2f0018c95182?event_id=5d8b4861005040c4b02b0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
development
