### ISSUE TITLE
RangeError in /register-trees

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1469]
## Error in Plant-for-the-Planet App

**RangeError** in **/register-trees**
locale must contain localize property

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d8b4c50baa7160019c96e1f?event_id=5d8b4c5000504306aa000000&i=gh&m=ci)

## Stacktrace

    http://0.0.0.0:8080/bundle.js:158449 - format

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d8b4c50baa7160019c96e1f?event_id=5d8b4c5000504306aa000000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
development
