### ISSUE TITLE
Translation of menu not changed in web client

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1474]
**Describe the bug**
Menu items names got changed for the native apps but not yet in the backend which created the menu for the web client, so the user will have a different experience in web and native app.

**Is it on a Production or Development Build?**
staging, soon on production

**Expected behavior**
Have the same wording for web and native apps.

**Screenshots**
![Menu App](https://user-images.githubusercontent.com/1532418/65683290-322e8280-e05d-11e9-8600-a3aaf8c34161.png)
<img width="277" alt="Menu Website" src="https://user-images.githubusercontent.com/1532418/65683291-322e8280-e05d-11e9-8fd8-e20a60de4239.png">

**Comment by jmiridis** [comment]
Not sure was has to be done here. Do we need new menu items or have translations to be modified.
This is the current web menu for German:
https://staging.trilliontreecampaign.org/public/v1.3/de/menu/web.main

**Comment by norbertschuler** [comment]
Translations have been modified. I have not checked, but maybe also the English wording.

**Comment by norbertschuler** [comment]
No menu item have been removed or added here yet.

**Comment by norbertschuler** [comment]
@jmiridis I think it's not your task to change the English and German translation for the menu now in the backend, but if we want to have a consistent UI for the users we should adapt the translations for the web client menu to the native apps menus. The task would just be to identify the resources which need to get changed from the backend in LingoHub. Maybe I can try doing that myself.

**Comment by norbertschuler** [comment]
Translation seem to be adapted. We just have to export them from LingoHub once more.

**Comment by norbertschuler** [comment]
This is what they made our menu looks like now:
<img width="267" alt="Bildschirmfoto 2019-09-30 um 16 16 47" src="https://user-images.githubusercontent.com/1532418/65887170-ce2df600-e39d-11e9-9da9-1cced1a406a1.png">
