### ISSUE TITLE
Do not hide support button in responsive view

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1483]
Currennt: 

In small screens the support button disappears.

<img width="566" alt="Screen Shot 2019-09-27 at 3 30 27 PM" src="https://user-images.githubusercontent.com/5401575/65760661-231f0180-e13d-11e9-8e09-168e214870cf.png">

Expected: It should not disappear, gift icon can be shown instead.

**Comment by mahmed0715** [comment]
This can be closed as the related PR merged. #https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1486
