### ISSUE TITLE
EXC_BAD_ACCESS in _mh_execute_header

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1490]
## Error in Plant-for-the-Planet App

**EXC_BAD_ACCESS** in **_mh_execute_header**
Attempted to dereference garbage pointer 0x113b1940.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d90c0fd3e7383001af2420a?event_id=5d90c0fd00503f634beb0000&i=gh&m=ci)

## Stacktrace

    TreecounterApp:0 - _mh_execute_header

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d90c0fd3e7383001af2420a?event_id=5d90c0fd00503f634beb0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
native crash

**Comment by Plant-for-the-Planet** [comment]
An error linked to this issue has been reopened in Bugsnag
[**EXC_BAD_ACCESS** in **_mh_execute_header**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d90c0fd3e7383001af2420a?event_id=5de3b4170053baa75b0b0000&i=gh&m=ra)

**Comment by norbertschuler** [comment]
native error, cannot debug
