### ISSUE TITLE
Leaderboard numbers are incorrect in API

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1492]
<img width="336" alt="Screen Shot 2019-09-30 at 8 03 56 AM" src="https://user-images.githubusercontent.com/5401575/65845190-f0e9eb80-e358-11e9-92a1-04392ef8efeb.png">

<img width="595" alt="Screen Shot 2019-09-30 at 8 03 25 AM" src="https://user-images.githubusercontent.com/5401575/65845193-f3e4dc00-e358-11e9-95f0-a73e80857c9c.png">

https://www.trilliontreecampaign.org/leaderboard/country/NL

Planted and Target are off in Leaderboard. Same issue exists for some other tree-counters  as well

It seems to be a calculation or ElasticSearch error.

**Comment by harshvitra** [comment]
@norbertschuler 

Maybe we can close this too

**Comment by norbertschuler** [comment]
Should be outdated. Closing it.
