### ISSUE TITLE
Cannot delete own competition

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1493]
**Describe the bug**
I don't find any way to delete my own competition again.

**Is it on a Production or Development Build?**
production

**To Reproduce**
1. Go to 'Competition' menu in bottom navigation
2. Click on 'Mine' tab
4. Try do find a delete option once you created a competition

**Expected behavior**
Allow a user to delete a competition again

**What actually happens**
No delete button or link can be found

**Screenshots**
![Simulator Screen Shot - iPhone 11 - 2019-09-30 at 09 18 04](https://user-images.githubusercontent.com/1532418/65856993-36abb180-e363-11e9-905e-c629ee8b9da3.png)

**Smartphone (please complete the following information):**
- Device: iPhone X
 - OS: iOS 13
 - Plant-for-the-Planet App Version 1.1.0

**Comment by harshvitra** [comment]
#1422 will fix it
