### ISSUE TITLE
Creating competition with (+) action button can not be cancelled

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1494]
**Describe the bug**
If you already have a competition and want to create a second one, you have to press the action button with the plus sign (+) to open a dialog to create another competition. This dialog can only be close by pressing "Create Competition" and has not cancel option.
Therefore it's not possible to get back to the list of your own competitions, even if switching the navigation with the tabs and other navigation items. The dialog for creating a new competition stays active in the "mine" tabs until you restart the app.

**Is it on a Production or Development Build?**
production

**To Reproduce**
1. Go to 'Competion'
2. Click on 'Mine'
3. Click the action button (+) to create a new competition (you already need to have one)
4. Try to cancel the creation process.

**Expected behavior**
Have a cancel option (either back navigation in the menu or cancel button)

**What actually happens**
No option to cancel the process is offered.

**Screenshots**
![Simulator Screen Shot - iPhone 11 - 2019-09-30 at 09 30 55](https://user-images.githubusercontent.com/1532418/65857861-0238f500-e365-11e9-90ec-7b1b17844ec0.png)

**Smartphone (please complete the following information):**
- Device: iPhone X
 - OS: iOS 13
 - Plant-for-the-Planet App Version 1.1.0

**Comment by sagararyal** [comment]
#1422 should fix this.
