### ISSUE TITLE
Use App-IDs from meta-tags for app store links

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1498]
**Describe the feature you'd like to see included in Plant-for-the-Planet App.**
It would be great if we could use the Apple App-ID from our meta-tags as the Smartbanner component also does it:
```
  <meta name="apple-itunes-app" content="app-id=1444740626">
  <meta name="google-play-app" content="app-id=org.pftp">
```
So we do not have to store the App-ID twice in our app. The source code of the Smartbanner component we have imported from an external module works like this: https://github.com/patw0929/react-smartbanner/blob/a45823ad085b6e1ee9f0f575fadf4931e7a02be7/src/components/SmartBanner.js#L256

**What are the use cases for this feature?**
So we do not have to store the App-IDs twice in our codebase and avoid redundancy.

**Comment by mahmed0715** [comment]
Can we put all our configuration things in a config file like app/config.index.js.dist and use these everywhere possible. is it possible? @norbertschuler

**Comment by norbertschuler** [comment]
The Smartbanner component isn't yet part of our project, so we can not modify the way it retrieves these values from the META-Tags to our config file. Either we completely fork this component to make our own adaptions or we adapt our code for the app store links in the menu to also use the META-Tags as this component does it.

**Comment by mahmed0715** [comment]
Actually we added smartbanner into our components, there is a method in that component that we need to move to utils and use anywhere we need that. @norbertschuler will do that.
