### ISSUE TITLE
RangeError in /register-trees

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1503]
## Error in Plant-for-the-Planet App

**RangeError** in **/register-trees**
locale must contain localize property

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d949bb41e22ea001aed7268?event_id=5d949bb400504dbc4ace0000&i=gh&m=ci)

## Stacktrace

    http://0.0.0.0:8080/bundle.js:158405 - format

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d949bb41e22ea001aed7268?event_id=5d949bb400504dbc4ace0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
develop
