### ISSUE TITLE
RangeError in /challenge

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1504]
## Error in Plant-for-the-Planet App

**RangeError** in **/challenge**
Invalid time value

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d949de7945880001a39ccce?event_id=5d949de700504fa7db320000&i=gh&m=ci)

## Stacktrace

    http://0.0.0.0:8080/bundle.js:137157 - format

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d949de7945880001a39ccce?event_id=5d949de700504fa7db320000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Develop
