### ISSUE TITLE
Sorting Projects Tabs do not work on Android

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1513]
On Android, On Donate Flow, Selection List, Price and Country tabs do not sort , and does not behave as expected.

**Comment by mahmed0715** [comment]
We need to have a specific label for RN app/web cleint etc to classify easily @sagararyal 
Is this RN issue with android? @sagararyal

**Comment by norbertschuler** [comment]
I added label for `Web`, `Android` and `iOS` in the same color as `client` if you want to add a more specified label to an issue. We already have issue templates which should make people structure their reports a little bit better. Please use them! ;-)

**Comment by norbertschuler** [comment]
> On Android, On Donate Flow, Selection List, Price and Country tabs do not sort , and does not behave as expected.

@mahmed0715 fixed the price sorting. @sagararyal What else is broken, e.g. for the country sorting? What is the expected behavior?

**Comment by mahmed0715** [comment]
Country sorting is working for ASC, I checked the country codes and they are sorted ascending while we go country tab. [This is based on country code, that might be the case @sagararyal, this looks not sorted with full country name, but its sorted based on country code]
Please let us know what more left on this PR.

**Comment by mahmed0715** [comment]
@norbertschuler can you please merge this PR as this fixes the price sorting issue and I checked the Country soring, its fine(sorted based on country code)..

**Comment by norbertschuler** [comment]
PR is already merged. I kept this issue open as I wanted to ask @sagararyal if anything else needs to be fixed. Otherwise please close this issue.

**Comment by norbertschuler** [comment]
Closing this now.
