### ISSUE TITLE
android.content.res.Resources$NotFoundException in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1517]
## Error in Plant-for-the-Planet App

**android.content.res.Resources$NotFoundException** in **MainActivity**
Unable to find resource ID #0x248d

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d98f2d54f37a300197f10e5?event_id=5d98f2d50050b37c3c1d0000&i=gh&m=ci)

## Stacktrace

    Resources.java:3216 - android.content.res.Resources.getResourceName

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d98f2d54f37a300197f10e5?event_id=5d98f2d50050b37c3c1d0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
can not fix native issue
