### ISSUE TITLE
Error in unknown method

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1518]
## Error in Plant-for-the-Planet App

**Error** in **unknown method**

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d991f4c09c29d001aee9e5f?event_id=5d991f4c0050a29ff7c20000&i=gh&m=ci)

## Stacktrace

    unknown file:0 - unknown method

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d991f4c09c29d001aee9e5f?event_id=5d991f4c0050a29ff7c20000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
can not reproduce that
