### ISSUE TITLE
Show loading indicator while search

### ISSUE THREAD

**Issue by mahmed0715** [Plant-for-the-Planet-org/treecounter-app#1520]
Currently while you search for user/project in search bar either on top or gift tree it takes time to show suggestions but meanwhile there is no indicator that shows user about we are fetching information to show,

We need to have an indicator/loading wheel or some statuses to notify user that its loading data meanwhile..

@sagararyal @norbertschuler please suggest

**Comment by norbertschuler** [comment]
Of course best would be the response time is so fast we do not need any loading indicator at all. A loading indicator for an autocomplete field is quite unusual.

**Comment by mahmed0715** [comment]
this is not needed as we are focused on reducing response time.
