### ISSUE TITLE
Next button does not work for logged in user on donate tree, gift tree.

### ISSUE THREAD

**Issue by mahmed0715** [Plant-for-the-Planet-org/treecounter-app#1521]
How to reproduce
- login web client
- donate trees
- select project
- on Donor details form the next button does not work.

**Comment by norbertschuler** [comment]
Works for me (at least in German on production). Can you give us more details of the steps you took and the environment you used? Have you checked the console to see if an error has been thrown? Can you use the bug issue template for reporting bugs (sometimes I feel like I am the only trying to use the template ;-)).

**Comment by norbertschuler** [comment]
Happened to me now too while testing the PR #1506. (Probably this does not always happen.)
