### ISSUE TITLE
android.content.res.Resources$NotFoundException in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1528]
## Error in Plant-for-the-Planet App

**android.content.res.Resources$NotFoundException** in **MainActivity**
Unable to find resource ID #0x5e9f

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d9d4c659760c4001a4a7af7?event_id=5d9d4c650050bb83aba10000&i=gh&m=ci)

## Stacktrace

    Resources.java:2208 - android.content.res.Resources.getResourceName

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d9d4c659760c4001a4a7af7?event_id=5d9d4c650050bb83aba10000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
can not fix native issue
