### ISSUE TITLE
Stuck on Gift (Pay screen)

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1531]
Initiate Gift Trees:
https://test.trilliontreecampaign.org/gift-trees

Select German language (haven't tested with English)

gift to Jorgo, select easy treesie,
select 10 trees, random address,
pay with stripe, click Pay
payment method is submitted, but request to pay is not submitted to stripe.
stuck with loading gif.

  
<img width="1446" alt="Screen Shot 2019-10-09 at 8 22 53 PM" src="https://user-images.githubusercontent.com/5401575/66491815-1d2d0700-ead3-11e9-8826-47236b8b1200.png">

**Comment by mahmed0715** [comment]
Backend has some recent issues, 
Amount is missing @jmiridis can solve this. 
And test.trilliontreecampaign.org doesnt have the latest changes from develop @sagararyal

**Comment by mahmed0715** [comment]
![missing-amount](https://user-images.githubusercontent.com/2967789/66505158-95ec8d00-eaec-11e9-9b4f-78145d61b145.PNG)
![sent-params](https://user-images.githubusercontent.com/2967789/66505161-95ec8d00-eaec-11e9-9a25-4e1c446ab801.PNG)

**Comment by norbertschuler** [comment]
test.trilliontreecampaign.org is up to date now.

**Comment by norbertschuler** [comment]
I just tested this on test.trilliontreecampaign.org and had no problem. Is this still a problem or can this issue get closed? @sagararyal please test again!

**Comment by mahmed0715** [comment]
@sagararyal is this still needed or we can close this.
please confirm.
