### ISSUE TITLE
TreeCounter Page is crashing

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1534]
Except of TPOs, the tree counter page for all users are crashing.

– For a logged in user, his/her treecounter does not crash, 

Besides all public tree counter displays the error.

example: http://trilliontreecampaign.org/t/sagar-aryal

**Comment by norbertschuler** [comment]
<img width="355" alt="Bildschirmfoto 2019-10-10 um 09 55 16" src="https://user-images.githubusercontent.com/1532418/66549685-22766a00-eb44-11e9-8917-2cf27d8a7e47.png">

**Comment by norbertschuler** [comment]
<img width="1135" alt="Bildschirmfoto 2019-10-10 um 09 54 32" src="https://user-images.githubusercontent.com/1532418/66549692-27d3b480-eb44-11e9-9d88-4e6914337b12.png">

**Comment by norbertschuler** [comment]
https://github.com/Plant-for-the-Planet-org/treecounter-app/tree/hotfix/missing_gift_icon

**Comment by norbertschuler** [comment]
https://www.trilliontreecampaign.org/t/sagar-aryal works again

**Comment by crucialfelix** [comment]
Ah damn, that was a mistake. It's because there is a `/* eslint-disable no-undef */` added to the top of the page so eslint could not catch it.  We didn't notice that one.

https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1487/files#diff-cc8ea51492a7168460e9b349d5fbb9f6L20-L21

**Comment by norbertschuler** [comment]
Can we get rid of `/* eslint-disable no-undef */` in our code?

**Comment by norbertschuler** [comment]
Killed it: https://github.com/Plant-for-the-Planet-org/treecounter-app/compare/78795aaed680...1985d18dc426
