### ISSUE TITLE
My forest: links to tree counter do not work (correctly)

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1537]
**Describe the bug**
The mentioned tree counter (TPO) in the cards of 'My forest' should link and open tree counter of the TPO, but in the web client they just do not work and in the native apps there no do not seem to work correctly.

**Is it on a Production or Development Build?**
production

**To Reproduce**
1. Go to 'My Forest'
2. Click on some linked tree counters / TPOs

**Expected behavior**
Open the linked tree counter.

**What actually happens**
Link does not work in web client and does not open the tree counter (but redirect to start page) in the native app.

**Desktop (please complete the following information):**
- OS: latest MacOS
 - Browser latest Chrome
 - Plant-for-the-Planet App Version 1.1.0

**Smartphone (please complete the following information):**
- Device: iPhone 11
 - OS: iOS 13
 - Plant-for-the-Planet App Version 1.1.0

**Additional context**
*Add any other context about the problem here.*

**Comment by mahmed0715** [comment]
@norbertschuler can you provide some screenshot and more details. i got lost reproducing the issue on web and native app.

**Comment by norbertschuler** [comment]
@mahmed0715 check this methods where some onPress events are defined which should work, but does not:

https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/bc638adc687a8bf1b6917cb793a0306e2b05290b/app/components/UserContributions/ContributionCard.js#L48

https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/bc638adc687a8bf1b6917cb793a0306e2b05290b/app/components/UserContributions/ContributionCard.js#L88

https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/bc638adc687a8bf1b6917cb793a0306e2b05290b/app/components/UserContributions/ContributionCard.js#L108

Also in the native app (where the link work, but do not show the right tree counter):

https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/bc638adc687a8bf1b6917cb793a0306e2b05290b/app/components/UserContributions/ContributionCard.native.js#L128

https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/bc638adc687a8bf1b6917cb793a0306e2b05290b/app/components/UserContributions/ContributionCard.native.js#L169

https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/bc638adc687a8bf1b6917cb793a0306e2b05290b/app/components/UserContributions/ContributionCard.native.js#L190

**Comment by norbertschuler** [comment]
This is the list of trees you donated or gifted or anything else. On staging I have some random data generated for my test account showing different kind of data for **My Forest** (formerly named **My-trees**)

**Comment by mahmed0715** [comment]
I am not sure on our new design on my forest which is https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1614 has indications about the linking.. @norbertschuler  @sagararyal there should be link on the text donate/dedicate

**Comment by harshvitra** [comment]
@norbertschuler 
I believe this is fixed for the app

**Comment by norbertschuler** [comment]
@harshvitra yes, probably, but we have not yet changed anything for the web client as we dismissed the PR of @mahmed0715 to change it in favor of a later redesign. As currently the staging backend with the mockup data is not existing any more (staging uses a copy of our database like test), I have no test data to check if the errors for the web client still exists.
