### ISSUE TITLE
Incomplete Gift Donations appearing in Recipient Tree Counter 

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1540]
**Describe the bug**

https://www.trilliontreecampaign.org/t/david-nolte
only has 33 paid gifts, others failed. 
But the app shows 330 Trees.

Customer Email:
https://startplanting.atlassian.net/projects/PLANT/queues/custom/7/PLANT-18

**Is it on a Production or Development Build?**
Production

**Comment by norbertschuler** [comment]
Actually the other payment are shown in the status `initiated`, not `failed`. So this status shouldn't be counted on the tree counter? 
@sagararyal To make the fix complete, please let's specify which of the following states should be summed up be shown in the tree counter - just `success` or anything else?

<img width="103" alt="Bildschirmfoto 2019-10-11 um 11 18 23" src="https://user-images.githubusercontent.com/1532418/66640267-f37df800-ec18-11e9-9026-1d8ab7ade277.png">

**Comment by sagararyal** [comment]
@norbertschuler

correct, 

`initiated` = user started the process, but left. or had errors.

only `success` should summed up in the tree counter

`failed` can show in log (under my trees) or some other place, but should not count.
`refunded` should decrease tree count, but still be visible for the user as log.
`referred` can be used (with contextual donations tokens) to allow users to complete the donation.
`pending` should show in log, we can sum the tree count, but if fails, need to decrease it.

**Comment by norbertschuler** [comment]
@sagararyal is this still an issue. Please close otherwise.
