### ISSUE TITLE
Duplicate code for getting suggestions?

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1545]
I wondered it this code 

https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/036c155d790d6a59749ec934dbd8e70db223360c/app/components/Header/SearchAutosuggest.js#L33

is duplicated and could be replaced with:

https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/036c155d790d6a59749ec934dbd8e70db223360c/app/helpers/utils.js#L167

The rejection of the Promise from the later code isn't yet caught.

**Comment by rabiul042** [comment]
@mahmed0715 I'm able to solve this issue. can I take this?

**Comment by mahmed0715** [comment]
Sure @rabiul042 please let me know if any help needed.
@norbertschuler @sagararyal He is my friend trying to get started.

**Comment by mahmed0715** [comment]
@rabiul042 this is just a question. @norbertschuler is this something we need to solve?

**Comment by norbertschuler** [comment]
Yes, this is an optimization task. (1) check out if it is possible to reduce the the duplicate code and (2) if possible reduce it ;-) But this task has no high priority, but maybe good as an first issue to learn.

**Comment by mahmed0715** [comment]
Thanks @norbertschuler 
@rabiul042 you can do this.

**Comment by norbertschuler** [comment]
Code will be cleaned up soon as we do not support the old web client anymore.
