### ISSUE TITLE
Edit competition failed on test backend

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1549]
On the test backend I have created two competitions. One of them I can edit, the other one not, but I can not see why there should be a problem?

# This one works:

### Endpoint

`PUT` https://test.trilliontreecampaign.org/api/v1.1/en/competition/62

### Data Sent

```json
{
  "name": "Second try",
  "goal": 111,
  "endDate": "2019-11-15",
  "access": "invitation",
  "description": "test 2",
  "contact": null,
  "email": null
}
```

### Status Code

`200`

### Data Received

```json
{
  "merge": {
    "competition": [
      {
        "id": 62,
        "name": "Second try",
        "description": "test 2",
        "contact": null,
        "email": null,
        "access": "invitation",
        "endDate": "2019-11-15",
        "goal": 111,
        "image": null
      }
    ]
  }
}
```

# And this one fails:

### Endpoint

`PUT` https://test.trilliontreecampaign.org/api/v1.1/en/competition/60

### Data Sent

```json
{
  "name": "Norbert",
  "goal": 101,
  "endDate": "2019-12-08",
  "access": "invitation",
  "description": "test",
  "contact": null,
  "email": null
}
```

### Status Code

`400`

### Data Received

```json
{
  "code": 400,
  "message": "Validation Failed",
  "errors": {
    "errors": [
      "This value should be greater than Oct 13, 2019, 10:50 AM."
    ],
    "children": {
      "name": {},
      "goal": {},
      "endDate": {},
      "access": {},
      "imageFile": {},
      "description": {},
      "contact": {},
      "email": {}
    }
  }
}
```

**Comment by jmiridis** [comment]
This issue has been fixed. The competition's startDate was being validated to not be older than the current date during update. This should only be the case when the competition is created. The error occurred only when user tries to update a competition that was created more than 2 days ago.
