### ISSUE TITLE
Put version and other static config data into config file rather than hardcoded in code

### ISSUE THREAD

**Issue by mahmed0715** [Plant-for-the-Planet-org/treecounter-app#1553]
I see some code has backend api version hardcoded in code, 
We need to put all that kind of data to config file and use anywhere needed.
@norbertschuler

**Comment by norbertschuler** [comment]
I totally agree with you. Normally the used API version was only defined here:
https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/01f4514299eaf445d4b4f430593e423397340e5c/app/actions/apiRouting.js#L15

But as we changed some API calls to a higher version, there seem to be more and more exceptions of API calls with another version number as seen on this screenshot from the PR https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1454 (as that seems to have the most newest API changes we currently have implemented):

<img width="444" alt="Bildschirmfoto 2019-10-16 um 23 00 34" src="https://user-images.githubusercontent.com/1532418/66958749-2d139080-f069-11e9-9bd9-e80c9896a593.png">

I don't know yet what would be the best strategy to store different API versions for every API call. We already have the routes copied from the backend in https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/develop/app/server/routes/fos_js_routes.json - but that just contains formal API definitions without any concrete version and I think the version would not fit into this file.

For me the best software design strategy would be to completely migrate **ALL** API calls to version 1.3 - but that requires support from the backend checking if every call of the backend currently not called with version 1.3 would deliver exactly the same result for 1.3 as for the current version used.

**Comment by mahmed0715** [comment]
Yes, We need to move all the api to v1.3(latest) and change the default version to call is the latest and store this in a config file.
I think I can come up on this way to adapt api respond as current version to be called using latest version. @norbertschuler @jmiridis what do you think
