### ISSUE TITLE
Registration with existing email not handled correctly

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1558]
**Describe the bug**
When a user tries to register with an email already existing in the database, the registration form can not be sent without showing any error message.

**Is it on a Production or Development Build?**
production

**To Reproduce**
1. Go to 'Register'
2. Register as e.g. a TPO
3. Use an email you know there is already an account existing for.
4. See the error

**Expected behavior**
Show an error message to the user about the fact that the email is already used by another user. The API must return a proper error (form) and the client must handle it.

**What actually happens**
The API call return an 500 error with the message "An exception occurred while executing 'INSERT INTO [truncated] : Integrity constraint violation: 1062 Duplicate entry 'xxx@xxx.de' for key 'UNIQ_xxx'" (https://sentry.io/organizations/plant-for-the-planet/issues/1034207235/?project=1293762) - the client does react on it at all. So both parties does not handle it correctly.

**Screenshots**
<img width="1132" alt="Bildschirmfoto 2019-10-21 um 15 16 35" src="https://user-images.githubusercontent.com/1532418/67208592-188f1980-f416-11e9-96b6-8117d58b7568.png">

**Desktop (please complete the following information):**
- OS: latest MacOS
 - Browser lates Chrome
 - Plant-for-the-Planet App Version 1.1.0

**Comment by mahmed0715** [comment]
Is this issue still there or work in progeess @norbert

**Comment by norbertschuler** [comment]
@mahmed0715 yes, still is still an open issue. But it requires support from the backend.

**Comment by jmiridis** [comment]
@mahmed0715 @norbertschuler 
This issue has been solved server side as it will now trigger a form error (400) instead of a server error (500).
