### ISSUE TITLE
Translation missing for error when changing email address

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1559]
**Describe the bug**
An error message from the backend when trying to change your email to an address which is already used by another user is not localized.

**Is it on a Production or Development Build?**
production and develop

**To Reproduce**
1. Change email to an email address already used by another user.

**Expected behavior**
Return error message with localized error message.

**What actually happens**
```
{
  "code": 400,
  "message": "Validation Failed",
  "errors": {
    "children": {
      "newEmail": {
        "errors": [
          "someone else is already using this email address"
        ],
        "children": {
          "first": {
          },
          "second": {
          }
        }
      }
    }
  }
}

```

**Comment by jmiridis** [comment]
Resolved via commit 
https://github.com/Plant-for-the-Planet-org/treecounter-platform/commit/f77e5264adc998cd961a404f9ee0df01aaaafd60

**Comment by norbertschuler** [comment]
As the code change got reverted in the backend, this issue is open again.
