### ISSUE TITLE
Revert change in backend API

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1573]
Since we were able to fix #1261 without the API change introduced by @jmiridis as described here https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1261#issuecomment-536377241 this change can be reverted again.

**Comment by jmiridis** [comment]
@norbertschuler do you know how to revert this using git?

**Comment by norbertschuler** [comment]
@jmiridis `git revert SHA` can do it if it was only one commit, but if you don’t remember the change significantly increased CPU usage or database load, we do not have to revert it.
