### ISSUE TITLE
Decrease interval for refreshing pledge event by calling API

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1574]
**Describe the feature you'd like to see included in Plant-for-the-Planet App.**
Too much frequent API calls to fetch a pledge event creates too much load on our platform (as currently every API call results into a MySQL database request). Let's decrease the refresh interval to reduce load.

**Examples of this feature or functionality.**
One solution would be to change the interval from 10sec to 30sec at
https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/59a9e98587d970b1155fc2aa0ad1372b6ebc2b6a/app/actions/pledgeAction.js#L30

**Comment by harshvitra** [comment]
What we need to establish Server-Sent Events. 

Sending data via Web socket to all the connected clients when any pledge is changed. 

Whenever any client connects we have to push a message to server using that Server has to store an array of all the connected clients.

**Comment by harshvitra** [comment]
@jmiridis 
Found this - 
https://symfony.com/blog/symfony-gets-real-time-push-capabilities

It matches with our stack - Symfony + React + React Native

**Comment by jmiridis** [comment]
@harshvitra @norbertschuler 
I totally support integrating this technology. It will take some time though as we should first upgrade the project to Symfony4 which will take a considerable amount of time.

**Comment by harshvitra** [comment]
#1613  fixed this
