### ISSUE TITLE
Change Loading Animation on App to Skeleton Loading

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1575]
Currently the pages in the app use loading animations with a gif.

Instead of this we want to be able to use loading animations that will show context of what the user can expect next. 

Eg: 

<img width="323" alt="Screen Shot 2019-10-29 at 3 08 27 PM" src="https://user-images.githubusercontent.com/5401575/67774638-05a3c700-fa5e-11e9-94f7-2c56eee11676.png">

Task has to be done in multiple steps:

- [x] First implement this on the Homepage

And then we can integrate it into 

- [x] Competition Pages
and other pages.

**Comment by sagararyal** [comment]
@harshvitra please add your findings here including the tools to integrate 
so @haideralishah can implement it.

**Comment by haideralishah** [comment]
I am using https://www.npmjs.com/package/react-native-content-loader

**Comment by harshvitra** [comment]
http://danilowoz.com/create-content-loader/

I tested this for competitions - Got an issue which I have reported it might get resolved if we upgrade the React Native
https://github.com/danilowoz/react-content-loader/issues/164
