### ISSUE TITLE
Donation amount is cut for large number of donated trees

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1576]
**Describe the bug**
The field for the donation amount when freely entering a number of trees to donate is not large enough for big spenders :-) So the amount can be cut.

**Is it on a Production or Development Build?**
production

**To Reproduce**
1. Go to 'Donates trees'
2. Click on 'Donate'
3. Click on 'Next'
4. Enter a large number of trees to donate in the input field in the third row.
5. See error (amount of money is cut)

**Expected behavior**
We should provide enough place in the layout to also display huge amounts of donations.

**What actually happens**
The text for the donation amount is cut.

**Screenshots**
<img width="834" alt="Bildschirmfoto 2019-10-30 um 09 55 31" src="https://user-images.githubusercontent.com/1532418/67843184-c926a880-fafb-11e9-9fed-c2ab0a88294c.png">

**Desktop (please complete the following information):**
- OS: latest MacOS
 - Browser latest Chrome
 - Plant-for-the-Planet App Version 1.1.0

**Comment by mahmed0715** [comment]
Yah I also noticed that, its a simple css change.
