### ISSUE TITLE
Register trees: Don't show errors for valid input if other input is missing

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1577]
**Describe the bug**
If you do not specify a location for registering a tree, but already entered a valid date, next to the error for specifying a location also an error for the date is shown.

**Is it on a Production or Development Build?**
production and develop

**To Reproduce**
1. Go to 'Register trees'
2. Enter a valid date
3. Click button to register

**Expected behavior**
Just show an error for the missing location, but not for the date

**What actually happens**
Showing errors for the date and the location.

**Screenshots**
<img width="649" alt="Bildschirmfoto 2019-10-30 um 12 04 40" src="https://user-images.githubusercontent.com/1532418/67853010-d5b3fc80-fb0d-11e9-876d-fa7eab2a3107.png">

**Desktop (please complete the following information):**
- OS: latest MacOS
- Browser latest Chrome
- Plant-for-the-Planet App Version 1.1.0

**Comment by norbertschuler** [comment]
There is a similar error with registering multiple trees as the entered values are not transferred to the backend at all and therefore the backend returns errors for all missing mandatory input fields:

<img width="538" alt="Bildschirmfoto 2019-10-30 um 12 30 00" src="https://user-images.githubusercontent.com/1532418/67854668-09dcec80-fb11-11e9-856d-61eb429ff28e.png">

**Comment by rabiul042** [comment]
@mahmed0715  I'm able to solve this issue. can I take this?

**Comment by rabiul042** [comment]
@mahmed0715  I'm trying to solve this issue but in case of a single tree, I entered a valid date in the plant date field and click on submit button error showing as attached file in the description by @norbertschuler. I think that it's the JSON response problem from the backend.

The actual Json response is given below.  Here plantDate should not show an error.
{"code":400,
 "message":"Validation Failed",
 "errors":{"children":{"treeCount":{"errors":["This value should be \"1\" or more."]},
                                 "treeSpecies":{},
                                  "plantDate":{"errors":["This value should not be null."]},
                                  "geoLocation":{},
                                  "geometry":{},
                                  "contributionImages":{},
                                  "treeClassification":{},
                                 "treeScientificName":{},
                                 "contributionMeasurements":{}
}}}

The expected Json response is given below. here plantDate is null.
{"code":400,
 "message":"Validation Failed",
 "errors":{"children":{"treeCount":{"errors":["This value should be \"1\" or more."]},
                                 "treeSpecies":{},
                                  "plantDate":{},
                                  "geoLocation":{},
                                  "geometry":{},
                                  "contributionImages":{},
                                  "treeClassification":{},
                                 "treeScientificName":{},
                                 "contributionMeasurements":{}
}}}

The same case occurs in multiple trees.
