### ISSUE TITLE
Language & currency dropdown and store button always visible mobile

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1579]
The pull requests https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1571 lead to an error for looking at the website on smaller screens as following (Safari mobile on iPhone X simulator):

![Simulator Screen Shot - iPhone 11 - 2019-10-30 at 16 25 24](https://user-images.githubusercontent.com/1532418/67872175-e24a4c00-fb31-11e9-9d5c-26b40ecf4c99.png)

**Comment by mahmed0715** [comment]
on it.
