### ISSUE TITLE
java.lang.AssertionError in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1584]
## Error in Plant-for-the-Planet App

**java.lang.AssertionError** in **MainActivity**
Pausing an activity that is not the current activity, this is incorrect! Current activity: MainActivity Paused activity: MainActivity

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5dbbf77540eb730019bd24f0?event_id=5dbbf775005239356cc40000&i=gh&m=ci)

## Stacktrace

    Assertions.java:72 - com.facebook.infer.annotation.Assertions.assertCondition

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5dbbf77540eb730019bd24f0?event_id=5dbbf775005239356cc40000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Plant-for-the-Planet** [comment]
There shouldn't be two MainActivity in our app :-(

Comment added in Bugsnag by Norbert Schuler
[**java.lang.AssertionError** in **MainActivity**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5dbbf77540eb730019bd24f0?event_id=5dbbf775005239356cc40000&i=gh&m=cm)

**Comment by norbertschuler** [comment]
closing error for now
