### ISSUE TITLE
java.lang.IndexOutOfBoundsException in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1586]
## Error in Plant-for-the-Planet App

**java.lang.IndexOutOfBoundsException** in **MainActivity**
Index: 1, Size: 1

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5dbc718ecd75d00019927fac?event_id=5dbc718e00523d1673810000&i=gh&m=ci)

## Stacktrace

    ArrayList.java:427 - java.util.ArrayList.set

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5dbc718ecd75d00019927fac?event_id=5dbc718e00523d1673810000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
framework error
