### ISSUE TITLE
Check formatNumber function not always returning a string

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1588]
## Error in Plant-for-the-Planet App

**TypeError** in **MainActivity**
TypeError: TypeError: TypeError: (0,T.formatNumber)(1,null,l).replace is not a function. (In '(0,T.formatNumber)(1,null,l).replace(/[\d.,]/g,'')', '(0,T.formatNumber)(1,null,l).replace' is undefined)

This error is located at https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/33311ed8d32d39cb81fe42738e83d04328f9a630/app/components/Currency/TreeCountSelector.js#L163 and at https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/33311ed8d32d39cb81fe42738e83d04328f9a630/app/components/Currency/TreeCountSelector.native.js#L239 as the code relies on a string to be returned from the function formatNumber https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/33311ed8d32d39cb81fe42738e83d04328f9a630/app/utils/utils.js#L47

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5dbd81cefa513b00183b45fc?event_id=5dbd81ce00525d5915880000&i=gh&m=ci)

## Stacktrace

    app/components/Currency/TreeCountSelector.native.js:240 - value
    app/components/Currency/TreeCountCurrencySelector.native.js:69 - value
    app/components/Currency/TreeCountCurrencySelector.native.js:40 - value
    app/components/Currency/CurrencySelector.native.js:54 - onChangeText

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5dbd81cefa513b00183b45fc?event_id=5dbd81ce00525d5915880000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by mahmed0715** [comment]
I am working on it.
