### ISSUE TITLE
Donation Not Working!!

### ISSUE THREAD

**Issue by Chiagozie-Udeh** [Plant-for-the-Planet-org/treecounter-app#1593]
**Donation is not working on the "Donate tree" feature**   @P1

I tried to donate to Yucatan Reforestation project and it is not successful. Tried other projects and getting the same response as in the screenshot below. 

**Is it on a Production or Development Build?**
Production 

**To Reproduce**
1. Go to 'https://www.trilliontreecampaign.org/donate-trees'
2. Click on 'donate icon of any project'
3. Scroll down to 'next' and click'

**Expected behavior**
When I click donate, it should take me to next and then the donation platform before payment option

**What actually happens**

When I click donate, it took me to next and then on clicking next it poped up the message on the screenshot 

**Screenshots**
![Cap-2](https://user-images.githubusercontent.com/57354853/68121951-80129200-ff09-11e9-8829-58ecefc0e0eb.PNG)

**Desktop (please complete the following information):**
 - Browser: chrome
 - https://www.trilliontreecampaign.org/

**Comment by sagararyal** [comment]
Could this be because of cache? Do you want to try in incognito? @Chiagozie-Udeh

**Comment by Chiagozie-Udeh** [comment]
Yes! Just logged in through the incognito mode and it is working just fine. Thank you!
