### ISSUE TITLE
"Gift trees" for new users not working

### ISSUE THREAD

**Issue by Max-Planet** [Plant-for-the-Planet-org/treecounter-app#1594]
**Describe the bug**
I have a customer who is creating a gift invitation and claims that a regular donations is being created by the system. Could anyone with an android device test if gift donations, inviting a new user, work correctly?

**Is it on a Production or Development Build?**
Production

**To Reproduce**
1. App via Android
2. Login
3. Gift tree
4. type Email
5. Type name, Email and personal message
6. Forward
7. chose project
8. Add my data
9. pay via PayPal

**Expected behavior**
by sending a gift, the recipient should get an invitation email, which is not working. 

**What actually happens**
The donation is completed successfully, but not as a gift, but as a "normal" donation

**Screenshots**
no screenshot availbable, as the request comes from the donor. 

**Smartphone (please complete the following information):**
"gift tree" for iOS and Android was working for existing users (tried it twice), but it might be a probem with newly invited users

**Comment by sagararyal** [comment]
#1596  related issue
