### ISSUE TITLE
Support button does not add supported treecounter do donation

### ISSUE THREAD

**Issue by jmiridis** [Plant-for-the-Planet-org/treecounter-app#1596]
**Describe the bug**
Donations supporting a Treecounter does not work on WEB app.

Happens on Production Build

**To Reproduce**
1. Go to 'https://www.trilliontreecampaign.org/t/marc-opolo-international-gmbh'
2. Click on 'Support' button
3. Finish the donation 
4. The request being sent does not contain the field 'communityTreeCounter'

**Expected behavior**
The request `/api/en/v1.3/donation/1/create` must contain the field 'communityTreeCounter'

**What actually happens**
The request `/api/en/v1.3/donation/1/create` does not contain the field 'communityTreeCounter'

**Screenshots**
*Wrong request:*
![image](https://user-images.githubusercontent.com/1295390/68218794-e43d6080-ffb2-11e9-882b-248122ce86a0.png)

*This is how it should look like:*
![image](https://user-images.githubusercontent.com/1295390/68219486-113e4300-ffb4-11e9-87e5-c68ad9e3b627.png)

**Desktop (please complete the following information):**
 - OS: Win7
 - Browser all
 - Plant-for-the-Planet App Version [e.g. 1.3]

**Smartphone (please complete the following information):**
 - Plant-for-the-Planet App Version [e.g. 1.0.3]

**Additional context**
*Add any other context about the problem here.*

**Comment by mahmed0715** [comment]
Same issue as donation for gift tree?
