### ISSUE TITLE
Competition Enrollment for the Owner

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1601]
**Describe the bug**
Currently if the competition owner wants to join their competition that is `Request to Join` or `Invite Only`

They are placed in Requests to Join.

Instead they should be able to auto enroll.

**Comment by jmiridis** [comment]
Owners are already auto-enrolled. Not clear what should change.

**Comment by sagararyal** [comment]
@jmiridis 

Owners are auto enrolled, but a new feature now allows **owners to leave the competition.**

For a competition that is not Open for all,

If the owner then tries to join the competition, they are placed in (Requests to Join)
