### ISSUE TITLE
Challenge missing form validation

### ISSUE THREAD

**Issue by jmiridis** [Plant-for-the-Planet-org/treecounter-app#1604]
**Describe the bug**
Challenges are submitted without form validation.

It is on a Production Build

**To Reproduce**
1. Go to 'Challenge'
2. Click on 'Challenge Friends' without filling in any other data
3. Form gets submitted which it shouldn't
4. This happens for both tabs `Existing user` and `Email`

**Expected behavior**
It should not be possible to submit the form with incomplete data

**What actually happens**
The user sees a red error popup without knowing what the problem is.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*
![image](https://user-images.githubusercontent.com/1295390/68425366-f3b7d780-0173-11ea-9002-7ce173d278f8.png)

![image](https://user-images.githubusercontent.com/1295390/68424787-c4549b00-0172-11ea-845d-b161474e0882.png)

**Sample SessionLog**
https://www.trilliontreecampaign.org/backend/requestLog/de9f7f61-0006-11ea-93c0-f72414928f70

**Desktop (please complete the following information):**
 - Win7
 - Browser Firefox

**Comment by rabiul042** [comment]
@mahmed0715  I'm able to solve this issue. can I take this?

**Comment by mahmed0715** [comment]
Sure @rabiul042

**Comment by mahmed0715** [comment]
@rabiul042 do this asap
