### ISSUE TITLE
Integrate React.lazy for Competitions 

### ISSUE THREAD

**Issue by harshvitra** [Plant-for-the-Planet-org/treecounter-app#1609]
Implement Code Splitting, combining React.lazy with Content loader to load contents dynamically. 
https://reactjs.org/docs/code-splitting.html

**Comment by norbertschuler** [comment]
Related to #1432

**Comment by norbertschuler** [comment]
Content-Loader also in #1575

**Comment by harshvitra** [comment]
Yes related to first one, but Content loader being applied by Haider are different, He is implementing for entire screens, this will be rather for each small component. 

For eg. load 5 competitions on first render, when user scrolls down other competitions will load only then (Using react lazy load). if the content is not ready of that competitions then show Content loader.

**Comment by norbertschuler** [comment]
@harshvitra Lazy is done already - should we close this issue? https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/8d666b93db57578cc0ff8b5a291996c2978ed8b7/app/components/App/TreeCounter.js#L76

**Comment by harshvitra** [comment]
This is not container level loader, this is a single component level loader

I will try to implement this in competitions and show what we want

**Comment by norbertschuler** [comment]
@harshvitra will this issue we fixed with #2068?

**Comment by harshvitra** [comment]
> @harshvitra will this issue we fixed with #2068?

Yes it will be solved there
