### ISSUE TITLE
Minor issues for unfulfilled pledge events

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1610]
For the pull request https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1555 some minor issues were still open and not solved yet:

- [x] If you are a logged in user and you are looking the the home page with the global tree counter and the pledge events and then logout, the home page is shown without any pledge event. After reloading the page, the pledge events are shown again.
- [x] Due to the design of the software waiting for updates from the backend after modifying data with the API calls, the user sometimes sees outdated data, e.g. making a donation, but still seeing the "make a pledge" button or increasing his pledge, but still seeing the old number on the "increase button" 
- [x] Due to the design of the software the user sometimes sees the wrong buttons for a pledge event if switching between two events with different state (one for which he already did a pledge, one he didn't)
- [won't fix] Users not logged in are able to make more than one pledge if they use different devices and browsers or clear the caches
- [x] Error in browser console: 
```
backend.js:6 Warning: react-modal: App element is not defined. Please use `Modal.setAppElement(el)` or set `appElement={el}`. This is needed so screen readers don't see main content when modal is opened. It is not recommended, but you can opt-out by setting `ariaHideApp={false}`.
```
- [x] Errors in browser console:
```
Error: pledgedEvent not in localStorage
    at localStorage.js:32
    at new Promise (<anonymous>)
    at fetchItem (localStorage.js:29)
    at Pledge.componentDidUpdate (index.js:88)
    at commitLifeCycles (react-dom.development.js:17349)
    at commitAllLifeCycles (react-dom.development.js:18736)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
    at invokeGuardedCallback (react-dom.development.js:256)
    at commitRoot (react-dom.development.js:18948)
```
- [x] Be aware unfulfilled pledges are even shown if the pledge event is not any more, e.g. as on this screen shot taken on our test backend where no pledge events are currently active, but I still have an unfulfilled pledge: 
![Simulator Screen Shot - iPhone 11 - 2019-11-18 at 10 27 44](https://user-images.githubusercontent.com/1532418/69040608-5c157d00-09ee-11ea-9db3-fcd0890cd6ef.png)
(the endless loop clicking on this pledge due to missing pledge event slug is already part of #1630)

Some of these issues could be solved with either calling the API faster then only every 30 seconds (which we don't do yet due to load on the server) or by not using API calls, but building a backend solution having direct connections with the clients and pushing update events to them.

**Comment by harshvitra** [comment]
> Users not logged in are able to make more than one pledge if they use different devices and browsers or clear the caches

How can we probably solve this. -> The user is completely anonymous if he is not logging in. 
How can we track a user who is completely anonymous to us and restrict actions by that user. ->
If the user is on the same device we can probably try getting his/her IP/IMEI number and track the user. 

But if the user is changing devices then there is nothing we can do. 

One solution which comes to my mind would be when user makes a pledge he/she enters Email ID. If the user is not logged in we ask for an OTP sent to the user on the email and only then add their pledge to DB. 

Now when they use the same Email ID we can prompt them that they have already made a pledge. Also we can give pledge url in mail, when they click on that it will be stored in their local storage.

**Comment by norbertschuler** [comment]
> How can we probably solve this. -> The user is completely anonymous if he is not logging in.

We won't solve this. It's not worth the effort.

**Comment by norbertschuler** [comment]
- [ ] While testing #1613 I managed to create a browser crash pledging and then logging out afterwards as following:
```
Uncaught TypeError: Cannot read property 'name' of null
    at Pledge.render (index.js:284)
    at finishClassComponent (react-dom.development.js:18451)
    at updateClassComponent (react-dom.development.js:18404)
    at beginWork$1 (react-dom.development.js:20161)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:385)
    at invokeGuardedCallback (react-dom.development.js:440)
    at beginWork$$1 (react-dom.development.js:25738)
    at performUnitOfWork (react-dom.development.js:24665)
    at workLoopSync (react-dom.development.js:24638)
```
