### ISSUE TITLE
Add verified or self-reported status to Survival Rate

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1615]
As we allow projects to report the survival rate themselves, it is important to convey the users a message whether the information is correct or not. 

As we have started to see projects reporting 100% survival rates, 

The goal is to show which are self-reported, and which are certified by trusted organisations.

TPOs can submit the reports to have the certification status added.

In project cards

If a project is certified:
<img width="577" alt="Screen Shot 2019-11-09 at 11 05 31 AM" src="https://user-images.githubusercontent.com/5401575/68526881-ebc97600-02e0-11ea-8172-cbec51c4eafc.png">

if it is not certified:

<img width="595" alt="Screen Shot 2019-11-09 at 11 05 40 AM" src="https://user-images.githubusercontent.com/5401575/68526889-fe43af80-02e0-11ea-849f-629b07248e7b.png">

Opening the card 

<img width="747" alt="Screen Shot 2019-11-09 at 11 25 34 AM" src="https://user-images.githubusercontent.com/5401575/68527112-a8bcd200-02e3-11ea-8f0a-67440dcd767e.png">

**Comment by mahmed0715** [comment]
@sagararyal I am doing this, currently we are getting 3 related params in the projects data
```
survivalRateStatus:"self-reported",
isVerified:true,
isCertified:false
```
so to confirm, depending on these params we will change the view, right?
The opening the card means details view of the project will show verified , Self reported status?(will not show in the card/list view)

**Comment by sagararyal** [comment]
@mahmed0715 

this does not concern `isverified` or `iscertified` flags

display them based on:
```
survivalRateStatus:"self-reported",
survivalRateStatus:"verified",
```

**Comment by mahmed0715** [comment]
This can be closed @sagararyal ?

**Comment by norbertschuler** [comment]
> This can be closed @sagararyal ?

I thought we keep this issue as we maybe also want to add this to the web client and maybe we want to implement the alternative view when looking at the details of a project?
