### ISSUE TITLE
Remove TTC Beta logo from Apps in Login Screen

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1619]
target fix for v1.2

<img width="331" alt="Screen Shot 2019-11-09 at 2 22 25 PM" src="https://user-images.githubusercontent.com/5401575/68529212-779ccb80-02fc-11ea-9093-a8daeac39abc.png">

**Comment by norbertschuler** [comment]
Should the place just be empty or show the Plant-For-The-Planet Logo as following?

![Screenshot_1573374273](https://user-images.githubusercontent.com/1532418/68541136-1e847480-039c-11ea-8def-35e10af8ac4a.png)
