### ISSUE TITLE
java.lang.IllegalArgumentException in FragmentManager.java:987

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1621]
## Error in Plant-for-the-Planet App

**java.lang.IllegalArgumentException** in **FragmentManager.java:987**
No view found for id 0x2f8d (unknown) for fragment VideoFragment{fd662b1 #1 id=0x2f8d}

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5dc811023c69910019e51a2f?event_id=5dc811020052bc50b0c30000&i=gh&m=ci)

## Stacktrace

    FragmentManager.java:987 - android.app.FragmentManagerImpl.moveToState

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5dc811023c69910019e51a2f?event_id=5dc811020052bc50b0c30000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
must be related to Youtube which we replaced now by a webview
