### ISSUE TITLE
shared link from competition results into 404 on web client

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1626]
A shared linked for a competition from the app results into 404 error: https://www.trilliontreecampaign.org/competition/55 if opened with mobile Chrome browser on iOS. 

Opening it from the mail app correctly opens the deep link in the app. 

Maybe we later on want to support our web client not to show 404 errors for some deep links which could not be opened with the app on a phone.

All other currently used share links are also supported URI for the web client.

**Comment by mahmed0715** [comment]
@rabiul042 can you do this please.

**Comment by rabiul042** [comment]
@mahmed0715 Okay
