### ISSUE TITLE
Enable Czech Language

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1628]
- [ ] Enable `Czech` Language Support on the Apps.

<img width="134" alt="Screen Shot 2019-11-10 at 9 45 32 PM" src="https://user-images.githubusercontent.com/5401575/68550500-891ccb00-0403-11ea-8417-ae91fe165c5a.png">

language code is `cs`

**Comment by norbertschuler** [comment]
Czech language is back to only 68% done (and only 6% of the backend resources):

<img width="1334" alt="Bildschirmfoto 2020-04-13 um 12 15 50" src="https://user-images.githubusercontent.com/1532418/79094084-89d5d680-7d80-11ea-9f6a-1ed9659012b2.png">

First language ready to being deployed would be Spanish which I prepared as a PR https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/2074 but need some help for decisions there!

Closing this for now.
