### ISSUE TITLE
Major issues for unfulfilled pledge events

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1630]
The native apps has **two** issues with showing pledges events:

- [ ] Just looking at the homepage with the pledge events and unfulfilled pledges trigger API requests as https://staging.trilliontreecampaign.org/public/v1.3/de/eventPledge/byToken/EP-IE6BQN5K%2CEP-CDHS2RUR about every second - we limited the number of API calls for the web to avoid to much load on our backend, so this is the same problem even worse. This API calls won't stop until the app is killed:

<img width="835" alt="Bildschirmfoto 2019-11-13 um 15 15 56" src="https://user-images.githubusercontent.com/1532418/68771935-3d4b6b00-0629-11ea-8c1b-938d240c29f2.png">

- [ ]  If you click on a unfulfilled pledge already done (e.g. to increase it) and never before opened a pledge event the API call done is https://staging.trilliontreecampaign.org/public/v1.3/de/pledgeEvent/undefined and you see an endless spinner trying to load this unfulfilled pledge. If you once already opened a pledge event, your unfulfilled pledge to this event is shown even you try to open another unfulfilled pledge (if you have done more than one):

<img width="412" alt="Bildschirmfoto 2019-11-13 um 15 27 04" src="https://user-images.githubusercontent.com/1532418/68772514-41c45380-062a-11ea-904c-998ef94b895b.png">

**Comment by harshvitra** [comment]
Cannot code right now, going to leave town for an event tomorrow morning. 
But I saw the code and analysed the issues, writing my thoughts here so I can directly jump

1. The API call is caused due to - 

`this.props.fetchPublicPledgesAction(stringPledges);`

 However it has a condition - 
   `if (prevProps.entities.eventPledge !== this.props.entities.eventPledge) { }` 

So I'll check why it needs to send this API call as the object wont change until a new pledge made or it is freshly being loaded.

Can you test again with your debugger off. 

Because even though I'm using the app right now I can see in [Sessions](https://staging.trilliontreecampaign.org/backend/sessionIds) that this API is not being called at all after initial run. 

2. Something which might cause the 2nd bug is that in the code I have written -  `slug: unfulfilledEvent.slug` 

and in response from the postman I'm getting - 
```
{
    "EP-IE6BQN5K": {
        "token": "EP-IE6BQN5K",
        "eventSlug": "esri-user-conference",
```

So mostly changing from slug to eventSlug should solve it, I'll test it once I get time.

**Comment by norbertschuler** [comment]
> Can you test again with your debugger off.

I tested with my Android emulator today where the frequent API calls did not happen. I will test again with my iOS simulator tomorrow.

**Comment by norbertschuler** [comment]
> 1. The API call is caused due to -
> 
> `this.props.fetchPublicPledgesAction(stringPledges);`

For me it happens for a logged out user at https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/d5fc23379b78e02c22e7009639023957aa2c5795/app/components/TreecounterGraphics/Trillion.native.js#L133

> However it has a condition -
> `if (prevProps.entities.eventPledge !== this.props.entities.eventPledge) { }`

If logged this condition is the method `componentDidUpdate` gets called more then once and once the condition is true, while the other time it's false and the API gets called.

> Can you test again with your debugger off.

How can I see if the API gets called without running the debugger?

**Comment by norbertschuler** [comment]
> > However it has a condition -
> > `if (prevProps.entities.eventPledge !== this.props.entities.eventPledge) { }`

I think you mixed up usage of properties and state for `componentDidUpdate` - read https://medium.com/@ashleywnj/componentdidupdate-prevstate-prevprops-and-a-silly-mistake-38afc72f5abc and try this patch at https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/d5fc23379b78e02c22e7009639023957aa2c5795/app/components/TreecounterGraphics/Trillion.native.js#L121

```
-  componentDidUpdate(prevProps) {
-    if (prevProps.entities.eventPledge !== this.props.entities.eventPledge) {
+  componentDidUpdate(prevProps, prevState) {
+    if (prevState.userPledges !== this.state.userPledges) {
```

I am not yet so experienced with react-native, so what do you think?

**Comment by harshvitra** [comment]
> How can I see if the API gets called without running the debugger?

Sessions in backend - https://staging.trilliontreecampaign.org/backend/sessionIds 

This is for staging so try it with staging only

**Comment by harshvitra** [comment]
> ```
> -  componentDidUpdate(prevProps) {
> -    if (prevProps.entities.eventPledge !== this.props.entities.eventPledge) {
> +  componentDidUpdate(prevProps, prevState) {
> +    if (prevState.userPledges !== this.state.userPledges) {
> ```

The data comes into the props first and then we are setting it to the state. So this condition will never call the api as the state never changes in this case.

**Comment by norbertschuler** [comment]
> The data comes into the props first and then we are setting it to the state. So this condition will never call the api as the state never changes in this case.

O.k., I close my PR. Maybe you have another idea how to solve this?

**Comment by norbertschuler** [comment]
> So this condition will never call the api as the state never changes in this case.

Have you tested my version. I thought it once was called successfully?

**Comment by harshvitra** [comment]
> > So this condition will never call the api as the state never changes in this case.
> 
> Have you tested my version. I thought it once was called successfully?

Yes, it runs once because the API is being called in componentDidMount which happens when the app starts and comes to home page.

**Comment by norbertschuler** [comment]
> > > So this condition will never call the api as the state never changes in this case.
> > 
> > 
> > Have you tested my version. I thought it once was called successfully?
> 
> Yes, it runs once because the API is being called in componentDidMount which happens when the app starts and comes to home page.

What is the reason to write something in the state value `userPledges` in the Trillion component? I can not see where the state is used later on? Is it intentionally to change the state as that triggers another call of the `componentDidMount` method?

**Comment by norbertschuler** [comment]
> The data comes into the props first and then we are setting it to the state. So this condition will never call the api as the state never changes in this case.

I continued testing and as I could not understand why the prevProps and new props always where compared as not equal though the content is equal (use case is a non logged in user who has already done a pledge) I came to the conclusion to try it with explicitly comparing the array for its values by:
```
-    if (prevProps.entities.eventPledge !== this.props.entities.eventPledge) {
+    if (
+      JSON.stringify(prevProps.entities.eventPledge) !==
+      JSON.stringify(this.props.entities.eventPledge)
+    ) {
```
What do you think about this solution I posted as #1642?

**Comment by norbertschuler** [comment]
> Sessions in backend - https://staging.trilliontreecampaign.org/backend/sessionIds

I checked the backend sessions disabling all debugging and the API loop was also visible there:

<img width="1004" alt="Bildschirmfoto 2019-11-19 um 09 58 55" src="https://user-images.githubusercontent.com/1532418/69131904-4d44ce00-0ab3-11ea-931f-fc04ca46bd07.png">

**Comment by norbertschuler** [comment]
@harshvitra In #1642 I also fixed the wrong slug value for unfulfilled pledge events in Trillion component now. Please have a look.
