### ISSUE TITLE
Loading all treecounters of followers when loading a single treecounter

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1631]
**Describe the bug**
When you look a the tree counter all the tree counters the person of this tree counter is following are loaded by the API too triggering a lot of unnecessary API calls and blocking the UI and making the app slow. 
- Are these additional API calls necessary?
- Why are API calls not done asynchronously in the background updating the frontend using observer pattern?

**Is it on a Production or Development Build?**
production

**To Reproduce**
1. Go to a tree counter of someone following other tree counters
4. See API calls made

**Expected behavior**
Load only data needed to be shown.

**Screenshots**
![Simulator Screen Shot - iPhone 11 - 2019-11-14 at 09 32 56](https://user-images.githubusercontent.com/1532418/68840618-602a5d80-06c3-11ea-86b8-7ded7fb83bd3.png)

**Smartphone (please complete the following information):**
- Device: iPhone X simulator
 - OS: iOS 13.2
 - Plant-for-the-Planet App Version 1.1.1

**Comment by norbertschuler** [comment]
This also happens when you open the page to add a new competition and thus blocking the user input for the loading time. That's why I added this issue to the project https://github.com/Plant-for-the-Planet-org/treecounter-app/projects/9

**Comment by norbertschuler** [comment]
The apps still triggers a lot of treecounter API calls!

**Comment by mahmed0715** [comment]
I could not find this issue with newly implemented project api(replacing old loadTpos api).
Please confirm @norbertschuler @sagararyal

**Comment by norbertschuler** [comment]
@mahmed0715 the issue is still there. As an example click "Challenge friends" in the native app. In my app I already challenged Sagar and therefore opening this page loads a lot of treecounter of the people he is following (example from production system):

![Simulator Screen Shot - iPhone 11 - 2020-01-29 at 11 07 03](https://user-images.githubusercontent.com/1532418/73347337-b7ce7300-4287-11ea-9e3a-4a35ad3337ab.png)

**Comment by mahmed0715** [comment]
Could  you please test with develop branch.  @norbertschuler

**Comment by norbertschuler** [comment]
> Could you please test with develop branch. @norbertschuler

I did use the develop branch of our app. I just used production backend for the API to have proper test data. I now also tested with the test backend and got the same results.

**Comment by norbertschuler** [comment]
I investigated the code and found out, this line of code in the `EditUserProfileContainer` get called for every screen having our old top navigation. I have not clue why this code within `componentDidMount` of the component is called despite I think it's not shown, is it?

https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/aaffdf808fc58e09a85b22f65501db37ebc683da/app/containers/EditUserProfile/index.js#L69

I assume I need a react-native professionell here to answer this question.

**Comment by niteshgrg** [comment]
@norbertschuler I have fixed the issue mentioned in last comment should i commit to feature/mergeHomeMyTrees ?
