### ISSUE TITLE
Show full name of User in Tree Counter

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1632]
<img width="695" alt="Screen Shot 2019-11-14 at 12 05 04 PM" src="https://user-images.githubusercontent.com/5401575/68851964-2ebb8d00-06d7-11ea-8568-f91fb447c07e.png">
eg:

/t/adra-india-andaman-and-nicobar-islands

**Comment by mahmed0715** [comment]
this can be closed.
