### ISSUE TITLE
Donation create request contains invalid data

### ISSUE THREAD

**Issue by jmiridis** [Plant-for-the-Planet-org/treecounter-app#1639]
**Describe the bug**
The field `receiptCompany` contains the huge userProfile object, instead of specific properties.

**It is on a Production**

**To Reproduce**
1. Do not reproduce
2. Check code for bug

**Real world example **
```
{
    "amount": 20,
    "currency": "EUR",
    "recipientType": "individual",
    "receiptCompany": {
        "id": 52280,
        "type": "company",
        "subType": null,
        "currency": null,
        "fullname": "************,
        "name": "************",
        "gender": null,
        "title": null,
        "firstname": null,
        "lastname": null,
        "address": "************",
        "zipCode": "60314",
        "city": "Frankfurt",
        "country": "DE",
        "email": "************",
        "phone": null,
        "image": "5dbacc8a02d57833522002.png",
        "synopsis1": null,
        "synopsis2": null,
        "url": null,
        "linkText": null,
        "mayPublish": true,
        "mayContact": true,
        "isDeleted": false,
        "treecounter": {
            "id": 139467,
            "displayName": "************",
            "slug": "************",
            "countPlanted": 0,
            "countPersonal": 0,
            "countDonated": 0,
            "countRegistered": 0,
            "countReceived": 0,
            "countTarget": 1000000,
            "implicitTarget": 1000000,
            "targetYear": null,
            "followerIds": "128807",
            "followeeIds": "",
            "userProfile": null,
            "countCommunity": "0.00",
            "contributions": [],
            "challenges": [],
            "competitions": [],
            "competitionEnrollments": [],
            "gifts": [],
            "mayPublish": true,
            "countProjectDonated": 0
        },
        "reviews": [],
        "isReviewer": false,
        "supportedTreecounter": null,
        "eventPledges": [],
        "locale": null,
        "newEmail": null
    },
    "treeCount": 20,
    "receiptIndividual": {
        "firstname": "************",
        "lastname": "************",
        "email": "************",
        "address": "************",
        "zipCode": "60435",
        "city": "Frankfurt",
        "country": "DE"
    }
}
```

**Comment by norbertschuler** [comment]
What is the correct value to use for `receiptCompany`? Can you give an example or link to the documentation?

**Comment by mahmed0715** [comment]
If the request has the reuqired fileds in it, isnt it possible to take only those requried fileds and ignore others?
in production I do not see any issue like this. Any idea where/how can I reporduce this? 
@jmiridis @norbertschuler

**Comment by norbertschuler** [comment]
Of course the backend could try correcting this frontend error for wrongly using the API, but it would be far better to fix it in the client. 

Maybe filling the form of the web client with values from `props.currentUserProfile` is not the right idea?
https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/bf4eec2c6656ab82950b5ec80bc6889d167c76a7/app/components/DonateTrees/index.js#L86

**Comment by norbertschuler** [comment]
Similar stuff is done for the native apps, but there only the required values seem to get copied from the userProfile object and only these values get extracted from the form afterwards:
https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/1d835aac05e6596830a2dd949ba29a0d19d2db2f/app/components/DonateTrees/receiptTabs.native.js#L115
