### ISSUE TITLE
Currency drop-down in web app does have a default value

### ISSUE THREAD

**Issue by jmiridis** [Plant-for-the-Planet-org/treecounter-app#1640]
**Describe the bug**
The currency drop-down in web-app does not have a default value.

**It is on a Production**

**To Reproduce**
1. Unfortunately this comes from a user provided issue and no further information is available.

**Expected behavior**
The currency drop-down should always have a default value.

**What actually happens**
The currency drop-down has no default value.

**Screenshots**
![index](https://user-images.githubusercontent.com/1295390/69060173-e953d400-09e4-11ea-81ef-4101aff577a7.png)

**Comment by mahmed0715** [comment]
@jmiridis I think by merging the https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1635 PR fixes the issue, its difficult to reproduce in production system on my end.
But now the develop branch should not have any issue like this.
How can we be sure? @jmiridis can you check on this please..

**Comment by norbertschuler** [comment]
I just merged #1635 and the backend are currently build. Please check if CircleCI is done.
