### ISSUE TITLE
label.donate is defined twice

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1644]
**Describe the bug**
The resource `label.donate` is defined twice with different translations.

<img width="286" alt="Bildschirmfoto 2019-11-19 um 11 03 24" src="https://user-images.githubusercontent.com/1532418/69159516-57cd8a80-0ae8-11ea-9c9f-c94d591e7940.png">

We will have to check all `label.donate` usages and decide at which place “donate” is wanted and at which place “projects” is wanted and change the places for “projects” e.g. by renaming one of these resources to `label.projects`.

**Is it on a Production or Development Build?**
development

**Comment by mahmed0715** [comment]
on it

**Comment by norbertschuler** [comment]
@mahmed0715 maybe you can do it together with #1666
