### ISSUE TITLE
Implement image display for reviews

### ISSUE THREAD

**Issue by mahmed0715** [Plant-for-the-Planet-org/treecounter-app#1648]
----Update Nov 20----
Link to design:  https://app.zeplin.io/project/5cad97d9b33d0b5931d90a9b/screen/5dd58f390248170b6469bdb9

<img width="448" alt="Screen Shot 2019-11-20 at 11 11 01 AM" src="https://user-images.githubusercontent.com/5401575/69269710-77b38b80-0b86-11ea-8a16-d7360e9a33ba.png">

-------
@sagararyal 
Please provide design for the display...

**Comment by haideralishah** [comment]
@mahmed0715 mention fixes #ISSUE_NUMBER in your PR it'll automatically close the issue once the PR is merged.

**Comment by norbertschuler** [comment]
Closing this now.
