### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'sortedQueryResults[sortedQueryResults.length - 1].planted')

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1653]
**Describe the bug**
Occasionally this error appears, but not always:
```
TypeError: undefined is not an object (evaluating 'sortedQueryResults[sortedQueryResults.length - 1].planted')
This error is located at:
    in Leaderboard (at Leaderboard/index.js:235)
    in LeaderBoardContainer (at Trillion.native.js:353)
```
https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/4c739552773e8663847575d7fe5daef8f8d33bff/app/components/Leaderboard/index.native.js#L70

**Is it on a Production or Development Build?**
not sure

**To Reproduce**
1. Go to 'World'
2. Click on Tab 'Leaderboard'
3. Click on Subnavigation 'Organisation'

**Smartphone (please complete the following information):**
- Device: iPhone X simulator
 - OS: iOS 13
 - Plant-for-the-Planet App Version 1.1.1

**Comment by haideralishah** [comment]
@norbertschuler  This issue may be in the previous version.
Currently, we are using `LeaderboardRefresh` folder for mobile screens
I think this issue should be close.
![image](https://user-images.githubusercontent.com/9020813/76743486-8147ab80-6794-11ea-9125-4a27d6236bc7.png)

**Comment by norbertschuler** [comment]
@haideralishah you  are right, I close it. Eventually we could clean up (delete) the old code.
