### ISSUE TITLE
Register tree: app crashes on register

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1662]
**Describe the bug**
When you try to register a tree with the native app, the app crashes as following:

```
_this.refs.registerTrees.refs.registerTreeForm.validate is not a function. 
(In '_this.refs.registerTrees.refs.registerTreeForm.validate()', 
'_this.refs.registerTrees.refs.registerTreeForm.validate' is undefined)
<unknown>
    index.js:29:4
onClick
    RegisterTreeTab.native.js:113:18
onPress
    PrimaryButton.native.js:15:26
touchableHandlePress
    TouchableOpacity.js:235:45
```
https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/bf81cfdcf8e6288706bc462e692255165c04664a/app/containers/RegisterTrees/index.js#L29

**Is it on a Production or Development Build?**
develop

**To Reproduce**
1. Go to navigation item 'Trees'
2. Click on button 'Register'

**Expected behavior**
Register a tree or show an error message

**What actually happens**
The app crashes.

**Smartphone (please complete the following information):**
- Device: iOS Simulator for iPhone X
 - OS: iOS 13.2
 - Plant-for-the-Planet App Version 1.1.1

**Comment by mahmed0715** [comment]
Checking on it.

**Comment by norbertschuler** [comment]
it got broken with this commit: https://github.com/Plant-for-the-Planet-org/treecounter-app/commit/40f4e9ade84f6c3a63ef3d7f96025ab640e8ffe4
