### ISSUE TITLE
Translation issues v1.2

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1672]
I found several translation issues with the current Alpha-Version in the Google Play Store. For some resources I thought German translations already exist:

- [x] translation for tab item is to big, so it get wrapped. If we don't find a shorter translation, we might need to have the tabs horizontal scrollable as for the user profile: 

![Screenshot_2019-11-27-19-37-06](https://user-images.githubusercontent.com/1532418/69751248-fd1ed900-114e-11ea-918f-148b7229da2f.png)

- [x] The screen title "pledges" is not translated and the number "2,131" not localized to German as "2.131" with our formatting function:

![Screenshot_2019-11-27-19-36-13](https://user-images.githubusercontent.com/1532418/69751250-fd1ed900-114e-11ea-88f1-aee5f8fe727e.png)

- [x] The screen title and the hint are not translated:

![Screenshot_2019-11-27-19-36-37](https://user-images.githubusercontent.com/1532418/69751252-fdb76f80-114e-11ea-9b9f-761856c6915e.png)

- [x] The error messages are not translated:

![Screenshot_2019-11-27-19-37-41](https://user-images.githubusercontent.com/1532418/69751254-fdb76f80-114e-11ea-8d1e-a89a772e9255.png)

- [x] The number "2,131" is not localized to "2.131" with our number formatting method:

![Screenshot_2019-11-27-19-35-57](https://user-images.githubusercontent.com/1532418/69751255-fdb76f80-114e-11ea-9851-8c16dc75cc0e.png)

**Comment by harshvitra** [comment]
> * The error messages are not translated:
> 
> ![Screenshot_2019-11-27-19-37-41](https://user-images.githubusercontent.com/1532418/69751254-fdb76f80-114e-11ea-8d1e-a89a772e9255.png)

@sanjayradadiya can you help me where can I find the code for rendering the error messages ?

**Comment by harshvitra** [comment]
Rest are fixed in #1696 1696

**Comment by norbertschuler** [comment]
- [ ] I found one more text with the number of trees which is not formatted and therefore also not localized here:

![Simulator Screen Shot - iPhone 6 - 2019-12-06 at 10 23 02](https://user-images.githubusercontent.com/1532418/70312180-5f44a180-1813-11ea-8ade-9f605752b0be.png)

**Comment by norbertschuler** [comment]
> @sanjayradadiya can you help me where can I find the code for rendering the error messages ?

I fixed the error messages. Two issues happened: (1) the resources got initialized when the app didn't yet know about the right locale to use and (2) the new resources file `formValidationErrors.json` was not imported for the German language.
