### ISSUE TITLE
Define Test framework, Define code indentation and others config

### ISSUE THREAD

**Issue by mahmed0715** [Plant-for-the-Planet-org/treecounter-app#1677]
Anyone discussed about what will be the test framework we should use, pros and cons? We should have discussed about any new tools to use in project.

This happens to others as well I believe: when just save a file without changing anything its contents gets changed because of indentation mismatch between previous commiter and current. 
Thus I think its better we define some indentation and other rules across project so that everyone should set these config in their code editor to prevent some annoying issues like that.
We can create a config file that sets editors config,

@norbertschuler what do you think?

**Comment by norbertschuler** [comment]
I have no opinion about the test framework to use as I no experience with writing tests for react-native yet. @crucialfelix made a suggestion I would follow with #1302 

There is a configuration file at https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/develop/.editorconfig defining these basic values for editor for our project. It supports a lot of different editors: https://editorconfig.org/

**Comment by norbertschuler** [comment]
I also adding the information about the .editorconfig in our contribution guide: https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/develop/CONTRIBUTING.md

**Comment by norbertschuler** [comment]
I think we can close this now.
