### ISSUE TITLE
Redeem trees: layouts broken and not updating "my forest"

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1683]
**Describe the bug**
When you enter a code to redeem trees (e.g. from the chocolate), you get redirected to a page not looking very good in the native app. The map is missing and the design of "my forest" is also not very nice. Also the trees you just redeemed with your voucher code are not yet displayed in the list of your contributions.
**Update**: The bug that the new contribution is not shown in "My forest" is also happening on the web client probably causing confusion for a lot of users.

**Is it on a Production or Development Build?**
production

**To Reproduce**
1. Go to 'Redeem trees'
2. Enter a voucher code
3. Confirm to redeem the trees for the voucher code

**Expected behavior**
Show some pages suitable for the native app and update the user contributions for "my forest".

**Screenshots**
![Screenshot_2019-11-30-12-03-25](https://user-images.githubusercontent.com/1532418/69899709-b1487b80-136a-11ea-8d4a-d5ad0fa30d71.png)

![Screenshot_2019-11-30-12-03-47](https://user-images.githubusercontent.com/1532418/69899708-b1487b80-136a-11ea-8a85-4ddcc2cc4f56.png)

**Smartphone (please complete the following information):**
- Device: Honor 6
 - OS: Android 6.0
 - Plant-for-the-Planet App Version 1.1.1

**Comment by norbertschuler** [comment]
Some more improvement possible for https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1743#issuecomment-576209456

**Comment by norbertschuler** [comment]
Updates of the data for "My forest" should be working now.

**Comment by norbertschuler** [comment]
Ugly screens still exist, do they? We should remove them and redirect to other screens after code redemption.

**Comment by harshvitra** [comment]
https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/2046
