### ISSUE TITLE
Competition v1.2

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1684]
- [ ] Currently All and Archived use same API Call, it seems this does not work in production.
Jorgo will provide api for archived

**Comment by harshvitra** [comment]
Any reasons for the Archived to not work in Production. 

The object of each competition has endDate so there is no extra API call needed. 

### But yes there is a problem with our Redux structure - 

**The container of competition makes 3 calls to fetch:** 
1. Mine Competitions
2. All Competitions
3. Featured Competitions

Then in redux we have something called as CompetitionPager which sends allCompetitions to the component it is rendering as a prop. 

**Now the 4 different tabs - Mine, All, Featured, Archived needs allCompetitions to be loaded which takes huge amount of time**

**Comment by harshvitra** [comment]
> Then in redux we have something called as CompetitionPager which sends allCompetitions to the component it is rendering as a prop.

<img width="686" alt="Screen Shot 2019-12-02 at 2 50 50 AM" src="https://user-images.githubusercontent.com/25605193/69920668-954ef200-14b0-11ea-9e49-b65d495d8ff6.png">

**Comment by sagararyal** [comment]
@harshvitra 
competition uses paging,

This means, they are not loaded, it does not show in archived.

For this, it should use a different API call.

**Comment by harshvitra** [comment]
> For this, it should use a different API call.

Okay, 
This would help my Refresh Control PR too. 
I will update only the api which is being refreshed

**Comment by harshvitra** [comment]
I've added this in #1676

**Comment by jmiridis** [comment]
@harshvitra @sagararyal The archived competitions can now be retrieved via a separate pager.
Please check out Postman .

**Comment by harshvitra** [comment]
@jmiridis small API update needed -
Right now both APIs 
/competitionsMine and /competitions/archived

have the same id - 3, so they replace the content of each other

**Comment by harshvitra** [comment]
Now this is fixed
