### ISSUE TITLE
EXC_BREAKPOINT in _mh_execute_header

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1687]
## Error in Plant-for-the-Planet App

**EXC_BREAKPOINT** in **_mh_execute_header**

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5de3b4503b48b0001963780e?event_id=5de3b4500053a8281bba0000&i=gh&m=ci)

## Stacktrace

    TreecounterApp:0 - _mh_execute_header

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5de3b4503b48b0001963780e?event_id=5de3b4500053a8281bba0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
native error, cannot debug
