### ISSUE TITLE
World Tree Map/ apparently there is something wrong with some coordinates in the map

### ISSUE THREAD

**Issue by otmezger** [Plant-for-the-Planet-org/treecounter-app#1688]
It looks like there is an error with some coordinates. Is it a displaying error or are the coordinates stored incorrectly? 

<img width="698" alt="World_Tree_Map___Trillion_Tree_Campaign" src="https://user-images.githubusercontent.com/2758346/69917371-46c83600-1465-11ea-972a-abd9032e9d18.png">

<img width="673" alt="World_Tree_Map___Trillion_Tree_Campaign" src="https://user-images.githubusercontent.com/2758346/69917383-7f680f80-1465-11ea-89a9-02dd8c696cdd.png">

**Comment by sagararyal** [comment]
@otmezger I believe these are some inconsistencies caused because our project location has issues sometime in 2018.

These contributions should be updated after verifying the coordinates of projects donations were made to.

I'd consider a task to do once maps are integrated in the app.

**Comment by sagararyal** [comment]
We should plan to fix this in next few weeks:

- [ ] Identify which project have these coordinates.

- [ ] ask the projects to provide correct coordinates. Max

- [ ] Re Sync or overwrite the contribution with the correct coordinates from the project

@jmiridis any thoughts?
Esri Map list might still have a different numbers, we have to update that as well.

**Comment by norbertschuler** [comment]
Looking at the current live map, the wrong data seemed to have been fixed: https://trilliontrees.maps.arcgis.com/home/webmap/viewer.html?webmap=d601683709dc415b99ddc1bc66a6d8eb

@sagararyal Can we close this P1 issue?
