### ISSUE TITLE
On web app: the progress bar display does not work well when project > 100%

### ISSUE THREAD

**Issue by otmezger** [Plant-for-the-Planet-org/treecounter-app#1689]
In the project page it works well: https://www.trilliontreecampaign.org/t/wells-for-zoe

but in the donation page it does not: 

<img width="618" alt="Select_Project___Trillion_Tree_Campaign" src="https://user-images.githubusercontent.com/2758346/69938123-c6451c00-14dc-11ea-90b2-3af71d64596b.png">

the iOS app shows it correctly:

![Bild von iOS](https://user-images.githubusercontent.com/2758346/69938144-cf35ed80-14dc-11ea-96a3-abaebca6df69.jpg)

**Comment by mahmed0715** [comment]
on it..
