### ISSUE TITLE
Staging: 500 for creating a new pledge

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1692]
**Describe the bug**
When trying to make a pledge on staging, the API returns 500 error:

Request:
POST https://staging.trilliontreecampaign.org/api/v1.3/de/pledgeEvent/esri-user-conference/eventPledge with data
```JSON
{"firstname":"Norbert","lastname":"Schuler",
"email":"norbert@epublica.de","treeCount":1000,"isAnonymous":true}
```
Response:
```
"An exception occurred while executing 'INSERT INTO event_pledge ...'"
```
Related crash issue from the backend is https://github.com/Plant-for-the-Planet-org/treecounter-platform/issues/272 - beside the database structure of an application should never be revealed in an error message to the user.

**Is it on a Production or Development Build?**
staging

**To Reproduce**
1. Go to pledge event 'ESRI User Conference'
2. Try to make a pledge

**Expected behavior**
Save the new pledge

**What actually happens**
API fails with 500

**Desktop (please complete the following information):**
- OS: latest MacOS
 - Browser latest Chrome
 - Plant-for-the-Planet App Version 1.1.1

**Comment by jmiridis** [comment]
@harshvitra @norbertschuler 
This problem was due to an error in fixture loading and therefore presented itself only on staging systems.
It has been fixed.
