### ISSUE TITLE
Remove search icon from Pledge Events

### ISSUE THREAD

**Issue by harshvitra** [Plant-for-the-Planet-org/treecounter-app#1695]
Pledge events currently has search icon, which has no purpose as of now in the Application to be on the pledge events page and create/update pledge page

**Comment by norbertschuler** [comment]
I assume this is fixed as #1697 got merged.

**Comment by harshvitra** [comment]
Can we wait for #1731 to get merged, we can leave it closed since no other page is involved in the flow
