### ISSUE TITLE
Fix projects cards layout on web: narrow on some screen

### ISSUE THREAD

**Issue by mahmed0715** [Plant-for-the-Planet-org/treecounter-app#1700]
![Screenshot from 2019-12-04 18-48-50](https://user-images.githubusercontent.com/2967789/70143834-cdc81900-16c6-11ea-90dc-8483c72c2776.png)

The card is very narrow on some screens.

**Comment by mahmed0715** [comment]
This is fixed already in this PR https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1614

**Comment by norbertschuler** [comment]
Closing as we do not support old web client anymore.
