### ISSUE TITLE
Add donations reference to Paypal payment requests

### ISSUE THREAD

**Issue by jmiridis** [Plant-for-the-Planet-org/treecounter-app#1701]
The information that is currently submitted to Paypal to capture and execute a payment, does not contain any reference to the donation and not even the fact that it was created in TrillionTreeCampaign.

We have to identify what additionals fields could be used to provide a reference to the donation so it does appear in the Paypal backend and people in the office can identify the origin of the payment.

**Comment by mahmed0715** [comment]
checking on it, will try to provide some info to the payment processor that will be sent to us back...

**Comment by mahmed0715** [comment]
Verified with @jmiridis and we get the information we need in backoffice...
That fixes it..

@norbertschuler Could you please review this PR...

**Comment by norbertschuler** [comment]
> @norbertschuler Could you please review this PR...

I also can not check if the information is going correctly into the backend as I have no access to Paypal. I can just check if the code runs.

**Comment by mahmed0715** [comment]
yes , @jmiridis confirmed this works as expected..

**Comment by mahmed0715** [comment]
@norbertschuler if you think code is okay we can merge this..

**Comment by norbertschuler** [comment]
> @norbertschuler if you think code is okay we can merge this..

I already approved it :-)
