### ISSUE TITLE
"Register Trees" API call with empty body

### ISSUE THREAD

**Issue by jmiridis** [Plant-for-the-Planet-org/treecounter-app#1702]
**Describe the bug**
Registering multiple trees frequently but not always results in a request with an empty body (see also screenshot).
`API call /api/v1.1/de/plantContributions/multiple-trees`

**Is it on a Production or Development Build?**
It happens on production

**To Reproduce**
Log in and register multiple trees in web app.

*Screenshots**
![image](https://user-images.githubusercontent.com/1295390/70167550-f9321000-1694-11ea-9baa-6a145a9dd3a5.png)

**Comment by jmiridis** [comment]
It seems that is already fixed in current develop branch, so the current position is to not hotfix, unless some requirement from the office comes in that that increases the priority.

**Comment by norbertschuler** [comment]
@jmiridis so we can close this issue?
