### ISSUE TITLE
UserProfile update wrong payload

### ISSUE THREAD

**Issue by jmiridis** [Plant-for-the-Planet-org/treecounter-app#1704]
**Describe the bug**
Updating a company profile always fails with a 400.

**Is it on a Production or Development Build?**
It happens everywhere.

**To Reproduce**
When a user with a profile of type `company` tries to update his profile, he receives a 400 form error.

**Solution**
Modify the PUT request to send the companyname under the filed name `name` instead of `companyname`.

**Create request:**

```
{
    "name": "&organics",
}
```

**Update request:**

```
{
    "companyname": "&organics",
}  
```

Both requests should user the field name `name`.

**Comment by mahmed0715** [comment]
we dont need to much worry about this,since it last happened on september 19, we can ignore this for now. if needed @jmiridis please reopen this///
