### ISSUE TITLE
Staging: After initial error automatically submitting the payment for a donation

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1705]
**Describe the bug**
On staging when I donate I get an error first and after I click “try again” the rest of the changes you see in the video happens fully automatic without me clicking anything anymore - even the payment!  

The initial error is caused by a missing donationID either at https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/9e31e98eede839836bb74f2fcb0f546acbcdb46a/app/components/Payment/PaymentSelector.js#L75 or at https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/9e31e98eede839836bb74f2fcb0f546acbcdb46a/app/components/StripePayment/CheckoutForm.js#L105

**Is it on a Production or Development Build?**
staging

**To Reproduce**
1. Go to 'Donate', 
2. Pick our default project 'Campeche Rainforest Restoration'
3. Use the default value of 50 trees

**Expected behavior**
Do the donation process as on production.

**Video**
[autopay.mp4.zip](https://github.com/Plant-for-the-Planet-org/treecounter-app/files/3925835/autopay.mp4.zip)

**Desktop (please complete the following information):**
- OS: latest MacOS
 - Browser latest Chrome
 - Plant-for-the-Planet App Version 1.1.1

**Comment by mahmed0715** [comment]
this is good that it works as the code is made to go the right place if there are some values already set...
Checking the code to fix the actual issue.. @norbertschuler
