### ISSUE TITLE
Next button stuck on gift tree

### ISSUE THREAD

**Issue by mahmed0715** [Plant-for-the-Planet-org/treecounter-app#1708]
How to reproduce:
On staging/develop branch next button on gift trees after selecting user doesnt work, just try gift trees selecting a user.

**Is it on a Production or Development Build?**
Develop branch/staging

Test works good.
Production works good.

**Comment by mahmed0715** [comment]
This is backend issue, as the suggest api does not return a treecounterid parameter, thus form validation blocked the process, 
@jmiridis could you please check this...

**Comment by norbertschuler** [comment]
This might be a duplicate of #1217.

**Comment by norbertschuler** [comment]
As we changed to https://fixtures.trilliontreecampaign.org/gift-trees this works now.
