### ISSUE TITLE
Suggestion not returning as expected.

### ISSUE THREAD

**Issue by mahmed0715** [Plant-for-the-Planet-org/treecounter-app#1709]
Suggestion either on search or on gift trees, doesnt work as expected
For example: I could not find my account on search
@jmiridis might need to check this: on test backend

Suggest api returns nothing if searched fro 'Mustak ahmed' but here is my account
![Screenshot from 2019-12-05 20-20-32](https://user-images.githubusercontent.com/2967789/70243419-beb39a80-179c-11ea-9a81-c7ea03cb7300.png)

**Comment by norbertschuler** [comment]
This is a very old issue for our staging environment #1217 which in my opinion is based upon wrong mockup data for staging.

**Comment by mahmed0715** [comment]
I am checking on test, it didnt work, but on same backend I have the account, see the screenshot.

**Comment by norbertschuler** [comment]
Maybe on the test backend the Elastic Search database which is the _database_ for the suggest API calls, is just not up to date?

**Comment by norbertschuler** [comment]
Closing this as probably always related to a Elastic search index not in sync with the linked backend.
