### ISSUE TITLE
Issues with Review Features in Develop

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1721]
- [x] Implement `In form error handling` do not send to server if the form validation is not completed.

<img width="461" alt="Screen Shot 2019-12-08 at 6 52 15 PM" src="https://user-images.githubusercontent.com/5401575/70393596-de8ccd80-19eb-11ea-8e69-b5d211fc1c8e.png">

- [x] Do not allow videos to be uploaded/ selected.

- [x] Increase image size, allow image delete option
UI like below can be used, this is from competition

![IMG_0323](https://user-images.githubusercontent.com/5401575/70393608-f5cbbb00-19eb-11ea-892a-c63c850e857f.jpg)

- [x] Reduce space between index and text
<img width="411" alt="Screen Shot 2019-12-08 at 6 54 12 PM" src="https://user-images.githubusercontent.com/5401575/70393620-23b0ff80-19ec-11ea-8f08-1cb0150c1aa0.png">

**Comment by mahmed0715** [comment]
@sagararyal fixed all those.
