### ISSUE TITLE
Gift tree issues on V1.2 release

### ISSUE THREAD

**Issue by mahmed0715** [Plant-for-the-Planet-org/treecounter-app#1726]
From slack @sagararyal 
- [x] Bug. Filling the form and releasing keyboard clears all data in gift tree page. This has to be fixed before deploying 1.2 urgent!!!
![File](https://user-images.githubusercontent.com/2967789/70594892-078ba900-1c0c-11ea-8198-24e3ded71084.jpg)

- [x] Gift initiated from the app are lost during donation process. Backend does not have any information about the gift nor the gift receipient

![File (1)](https://user-images.githubusercontent.com/2967789/70594879-fe024100-1c0b-11ea-9cb3-0fe1d91ec859.jpg)

**Comment by mahmed0715** [comment]
is this only ios issue or android also has same issue @norbertschuler

**Comment by norbertschuler** [comment]
@mahmed0715 The first bug (entering text for firstname, then release keyboard and the entered text disappears again) happens on iOS and Andrid.
