### ISSUE TITLE
License Info crashes the app

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1730]
## Error in Plant-for-the-Planet App

**TypeError** in **index.android.bundle:1888**
undefined is not an object (evaluating 'c.includes')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5df0f122e36d8a001b71cfc8?event_id=5df0f12200546c78b5090000&i=gh&m=ci)

## Stacktrace

    index.android.bundle:1888 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5df0f122e36d8a001b71cfc8?event_id=5df0f12200546c78b5090000&i=gh&m=ci)

This is probably at
https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/1ebb3c7778aa25448dac37f66161d309192cecd8/app/components/AboutUs/LicenseInfoList.native.js#L32

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
License page is crashing the app:

![Screenshot_2019-12-11-22-34-34](https://user-images.githubusercontent.com/1532418/70662462-8ad9e880-1c66-11ea-8992-727ad88b7e6e.png)

**Comment by norbertschuler** [comment]
I wonder if we can not just link to https://github.com/Plant-for-the-Planet-org/treecounter-app/network/dependencies in our app to save the overhead of the license component?

**Comment by Plant-for-the-Planet** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**TypeError** in **index.android.bundle:1888**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5df0f122e36d8a001b71cfc8?event_id=5df0f12200546c78b5090000&i=gh&m=fx)
