### ISSUE TITLE
Gift Trees: new form does not scroll for keyboard

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1735]
**Describe the bug**
Try to edit a firstname in Gift form. 

**Is it on a Production or Development Build?**
develop

**To Reproduce**
1. Go to 'Gift trees'
2. Click in field for firstname
3. See error

**Expected behavior**
Scroll the layout to always see the field to enter text for.

**What actually happens**
Does not display the input field

**Screenshots**
![Screenshot_2019-12-11-22-31-26](https://user-images.githubusercontent.com/1532418/70662627-ec01bc00-1c66-11ea-951b-709d70767135.png)

**Smartphone (please complete the following information):**
- Device: Huawei Honor 8
 - OS: Android 6
 - Plant-for-the-Planet App Version 1.1.1.1

**Comment by mahmed0715** [comment]
_think we can hide the description text when keyboard is shown. @norbertschuler @sagararyal _
