### ISSUE TITLE
API response is empty for deleting user contribution

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1747]
## Error in Plant-for-the-Planet App

**TypeError** in **app/actions/EditMyTree.js:84**
undefined is not an object (evaluating 't.response.data')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5df35ab18880aa0019fe630e?event_id=5df35ab10054d9e538c50000&i=gh&m=ci)

## Stacktrace

    app/actions/EditMyTree.js:84 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5df35ab18880aa0019fe630e?event_id=5df35ab10054d9e538c50000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
This error was raised as the response of the API call `https://staging.trilliontreecampaign.org/api/v1.1/de/plantContributions/21` is `{}` but some more information was expected by our code at https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/247d1365c7b893a28dd015fc73a25a107f9c5f52/app/actions/EditMyTree.js#L58 to be able to delete the user contribution also in our local redux data.

**Comment by norbertschuler** [comment]
@jmiridis do you know if the API call `DELETE
/api/{version}/{_locale}/plantContributions/{plantContribution}` should return some data on production?

**Comment by jmiridis** [comment]
@norbertschuler @harshvitra 
I do return a complex schema response that should match the API documentation:
https://www.trilliontreecampaign.org/api/doc/plant_contribution

**Comment by norbertschuler** [comment]
@jmiridis I just tested it on staging with `https://staging.trilliontreecampaign.org/api/v1.1/de/plantContributions/31` and got the response `{}`

**Comment by jmiridis** [comment]
This is an v1.1 call and I don't know what the application expects.
Any version > v1.1 will return a more complex schema response although I see that it might require some tweaking.
```
{
    "delete": {
        "contribution": [
            271373
        ]
    },
    "unlink": {
        "treecounter.112679.contributions": [
            271373
        ]
    },
    "merge": {
        "treecounter": [
            {
                "id": 112679,
                "displayName": "Jorgo Miridis",
                "slug": "jorgo-miridis-3",
                "countPlanted": 215.2,
                "countPersonal": 15,
                "countDonated": 2,
                "countRegistered": 13,
                "countReceived": 200.2,
                "countTarget": 1,
                "implicitTarget": 215.2,
                "targetYear": null,
                "followerIds": "91407,124188",
                "followeeIds": "91407",
                "directChildren": null,
                "userProfile": {},
                "countCommunity": "200.20",
                "contributions": {
                    "0": {},
                    "1": {},
                    "2": {},
                    "3": {},
                    "4": {},
                    "5": {},
                    "6": {},
                    "7": {},
                    "8": {},
                    "9": {},
                    "10": {},
                    "18": {},
                    "20": {}
                },
                "gifts": [
                    {},
                    {},
                    {},
                    {},
                    {}
                ],
                "competitions": [],
                "competitionEnrollments": [],
                "mayPublish": true,
                "countProjectDonated": 0
            }
        ]
    }
}
```

**Comment by norbertschuler** [comment]
@jmiridis I would be glad if the API call would return what you described. But for me it returned just `{}`. That’s my problem.
