### ISSUE TITLE
java.lang.IndexOutOfBoundsException in Collections.java:4502

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1764]
## Error in Plant-for-the-Planet App

**java.lang.IndexOutOfBoundsException** in **Collections.java:4502**
Index: 0

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5df910b22d3ed3001c466bc9?event_id=5df910b20054bf12a1d10000&i=gh&m=ci)

## Stacktrace

    Collections.java:4502 - java.util.Collections$EmptyList.get

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5df910b22d3ed3001c466bc9?event_id=5df910b20054bf12a1d10000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
framework error
