### ISSUE TITLE
Paypal payment issue : reported

### ISSUE THREAD

**Issue by mahmed0715** [Plant-for-the-Planet-org/treecounter-app#1769]
**Describe the bug**
Paypal  payment issue because of the error from paypal end, seems like paypal payment authorization method not having the payerID(paypal unique identity fir each user)

**Is it on a Production or Development Build?**
Production

**To Reproduce**
not sure, reported by user

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
![af881f83-989a-4d22-8ef0-5d1bf59320ec](https://user-images.githubusercontent.com/2967789/71268674-a8e6cd80-2377-11ea-8ebc-45cd7d42c99c.png)

**Desktop (please complete the following information):**
no information can be provided

**Comment by norbertschuler** [comment]
Solved by new payment website.
