### ISSUE TITLE
Swipe enabled project slide

### ISSUE THREAD

**Issue by mahmed0715** [Plant-for-the-Planet-org/treecounter-app#1771]
Need to develop slide for projects(single project) with swipe. @sagararyal any more details please..
https://www.loom.com/share/f3a0d5c9c67f4c239bfdf108a28ca021

**Comment by norbertschuler** [comment]
You should talk with @haideralishah to check out if you can use the same slider component `@react-native-community/viewpager` he has used in https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1710/.
