### ISSUE TITLE
Welcome Screens not localized

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1797]
**Describe the bug**
The welcome screens are not shown in German while the rest of the app is shown in German (when you switch your device to German).

**Is it on a Production or Development Build?**
develop

**To Reproduce**
1. Switch your device to German language
2. Open the app for the very first time
3. See error

**Expected behavior**
Show welcome screens in German language.

**What actually happens**
Welcome screens are shown in English.

**Smartphone (please complete the following information):**
- Device: iPhoneX Simulator
- OS: IOS 13
 - Plant-for-the-Planet App Version 1.1.1

**Additional context**
Maybe at the time the welcome screens are shown, the device has not yet retrieved its locale value.

**Comment by sagararyal** [comment]
@haideralishah please review this and push a fix asap.

**Comment by norbertschuler** [comment]
I will fix it, it's just a missing import in the German resource loader file: 9253646d935fc0da81ba3a07b7776c2b2bf52689
