### ISSUE TITLE
Remove unused WelcomeScreenModal component

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1800]
With introducing new welcome screens, the old welcome screen and component `WelcomeScreenModal` is not used any more. In order to keep our app small unused code and resources should be cleaned:
- [x] remove component source code
- [x] remove unused resources (save future translators for unnecessary work)
- [x] removed unused images

**Comment by haideralishah** [comment]
Fixed this issue in this branch
https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1803

**Comment by norbertschuler** [comment]
> Fixed this issue in this branch
> #1803

Great, can you please write „Fixes #<issuenumber>” in the description of the PR so the issue automatically gets closed when the PR gets merged.
