### ISSUE TITLE
Donate button missing if searching a TPO from a treecounter of another TPO

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1805]
**Describe the bug**

In the web client looking at the tree counter of a TPO, e.g. https://www.trilliontreecampaign.org/t/plant-for-the-planet, and then searching another TPO, e.g. "Eden" shows the project of this TPO but the "donate" button is missing.

**Is it on a Production or Development Build?**
production

**To Reproduce**
1. Go to https://www.trilliontreecampaign.org/t/plant-for-the-planet
2. Search for "Eden" and select another TPO
3. See missing button for project

**Expected behavior**
Always show the donate button.

**Screenshots**
<img width="738" alt="Bildschirmfoto 2020-01-10 um 16 10 07" src="https://user-images.githubusercontent.com/1532418/72163208-b108ba80-33c3-11ea-8ee2-fbe0a1987f02.png">

**Desktop (please complete the following information):**
- OS: latest MacOS
 - Browser: latest Chrome
 - Plant-for-the-Planet App Version 1.1.1

**Comment by mahmed0715** [comment]
on it as I was working on these components

**Comment by mahmed0715** [comment]
@norbertschuler this issue is not present  in present develop branch

**Comment by norbertschuler** [comment]
> @norbertschuler this issue is not present in present develop branch

I just tested it in the current develop branch and could still reproduce the bug (web client):
1. Search for "eden" and selected the project or open http://<devserver>/t/eden-reforestation-projects
2. Search for "plant-for" and selected the project
3. No donations button under the project listed beneath the tree counter

**Comment by mahmed0715** [comment]
Please check this, this is with production backend. with latest develop branch.
https://www.loom.com/share/e5a9a40078e94ba990d976f1711f2e5f

**Comment by norbertschuler** [comment]
> Please check this, this is with production backend. with latest develop branch. @norbertschuler
> https://www.loom.com/share/e5a9a40078e94ba990d976f1711f2e5f

In the video I only saw you searching once from the global tree counter. Please search for another TPO again to see the error.

**Comment by mahmed0715** [comment]
True, I just fixed that in the PR https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1781

**Comment by norbertschuler** [comment]
> True, I just fixed that in the PR #1781

O.k., but I don't like mixing up stuff which does not really belong to each other in one PR.
