### ISSUE TITLE
java.lang.IllegalArgumentException in EventNode.java:63

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1807]
## Error in Plant-for-the-Planet App

**java.lang.IllegalArgumentException** in **EventNode.java:63**
Animated events must have event data.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e1b66c7f525eb0019e24fdf?event_id=5e1b66c70055a44ba78f0000&i=gh&m=ci)

## Stacktrace

    EventNode.java:63 - com.swmansion.reanimated.nodes.EventNode.receiveEvent

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e1b66c7f525eb0019e24fdf?event_id=5e1b66c70055a44ba78f0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
native error
