### ISSUE TITLE
EXC_BAD_ACCESS in ___85-[NSExtension _completeRequestReturningItems:forExtensionContextWithUUID:completion:]_block_invoke

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1808]
## Error in Plant-for-the-Planet App

**EXC_BAD_ACCESS** in **___85-[NSExtension _completeRequestReturningItems:forExtensionContextWithUUID:completion:]_block_invoke**
Attempted to dereference garbage pointer 0x280d88890.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e1b841417b0cc00191021e4?event_id=5e1b84140055aa562c9d0000&i=gh&m=ci)

## Stacktrace

    Frameworks/Foundation.framework/Foundation:0 - ___85-[NSExtension _completeRequestReturningItems:forExtensionContextWithUUID:completion:]_block_invoke

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e1b841417b0cc00191021e4?event_id=5e1b84140055aa562c9d0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
native error
