### ISSUE TITLE
Updating TPO project without image gets rejected

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1816]
**Describe the bug**
While a TPO can create a project without specifying an image, the TPO can not update the project without adding an image. The specific error returned is not shown, but instead the server error message.

**Is it on a Production or Development Build?**
develop and production

**To Reproduce**
1. Go to managing TPO projects
2. Edit an existing project 
3. Select an image for the project

**Expected behavior**
Allow to update the project also without an image or make the image selection mandatory for the project in the frontend.

**What actually happens**
The API calls rejects the submit of the form with an error. The specific error returned from the backend is not displayed to the user.

**Screenshots**
<img width="1012" alt="Bildschirmfoto 2020-01-16 um 09 56 36" src="https://user-images.githubusercontent.com/1532418/72509027-053def80-3847-11ea-8f93-bcf7602ee201.png">
<img width="483" alt="Bildschirmfoto 2020-01-16 um 09 57 58" src="https://user-images.githubusercontent.com/1532418/72509046-0a9b3a00-3847-11ea-909e-e0d58b191029.png">

**Desktop (please complete the following information):**
- OS: latest MacOS
 - Browser latest Chrome
 - Plant-for-the-Planet App Version 1.1.1

**Comment by jmiridis** [comment]
The backend expects the image starting with version 1.3.
@sagararyal ist this still the desired behavior?

**Comment by norbertschuler** [comment]
Currently v1.1 is used.

**Comment by norbertschuler** [comment]
Today on the test backend I was able to edit and save a TPO project without adding an image. @jmiridis have you made any changes in the backend?

**Comment by norbertschuler** [comment]
seems to be fixed on test backend - only to big images fail with 500 error
