### ISSUE TITLE
std::__1::system_error in unknown method

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1823]
## Error in Plant-for-the-Planet App

**std::__1::system_error** in **unknown method**
mutex lock failed: Invalid argument

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e24bfa7440ed0001909836c?event_id=5e24bfa70055e2bf712e0000&i=gh&m=ci)

## Stacktrace

    unknown file:0 - unknown method

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e24bfa7440ed0001909836c?event_id=5e24bfa70055e2bf712e0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
native error
