### ISSUE TITLE
Missing error message for redeem trees with code "TEST_CODE"

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1824]
**Describe the bug**
Trying to redeem trees with the vouche code "TEST_CODE" returns an error, but missing an error message which is present for other invalid voucher codes.

**Is it on a Production or Development Build?**
develop

**To Reproduce**
1. Go to 'Redeem trees'
2. Enter "TEST_CODE" as voucher code
3. See error

**Expected behavior**
Also return an error message.

**Screenshots**
<img width="716" alt="Bildschirmfoto 2020-01-20 um 11 02 40" src="https://user-images.githubusercontent.com/1532418/72718031-6f230580-3b75-11ea-8a09-d05dcada7f98.png">

**Desktop (please complete the following information):**
- OS: latest MacOS
 - Browser latest Chrome
 - Plant-for-the-Planet App Version 1.1.1

**Smartphone (please complete the following information):**
- Device: Android and iPhone
 - Plant-for-the-Planet App Version 1.1.1

**Comment by sagararyal** [comment]
Deprecated API,
