### ISSUE TITLE
Implement Dynamic CDN, Language and Country

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1826]
@jmiridis has implemented the following:
https://www.trilliontreecampaign.org/public/v1.0/en/config

# 1
The application will need to retrieve the url for 
cdnMedia
pdfs
and attach it to the media.

In future media wont be accessible through trilliontreecampaign.org domain

# 2
if a user is not logged in, 
set locale = locale
set currency = currency
set country = country

if user signups or is logged in
[this locale, currency, and country, should be overridden by data in user-profile ]

this data can be used to pre fill forms.

**Comment by mahmed0715** [comment]
I will work on this.. @sagararyal do you want to give idea about the location currency selector for mobile app, ?

**Comment by sagararyal** [comment]
@mahmed0715 you could start the PR without changing anything. you'll receive the correct values from API.

We'll show a screen for user to confirm the locale and currency probably after welcome screen. You can already implement part 2 without worrying about the UI.
