### ISSUE TITLE
Tree registration design issues

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1835]
**Describe the feature you'd like to see included in Plant-for-the-Planet App.**

- the page title is too long and gets cut
- the register button has no margin at top
- no progress indicator is showing while waiting for uploading and registering

**Comment by sagararyal** [comment]
@harshvitra Along with your PR 

- [ ] please prepare to remove Register trees from bottom menu Item. Ask Jorgo to increase version number for menu,

- [ ] Implement clean headers in the page.

**Comment by harshvitra** [comment]
Sorry but I'm not aware of this  - Why do we need to increase the number ?

Also I think that the option to remove the item from the menu also happens from backend - Menu.yml in app/Resources/fixtures 

Setting isActive=0 for mobile_bottom_1

**Comment by harshvitra** [comment]
https://uimovement.com/design/image-recognition-1/

@sagararyal @norbertschuler  after registering the tree, we show something like this  ?

**Comment by harshvitra** [comment]
@sagararyal removing header from here would mean to remove it from every other place

**Comment by harshvitra** [comment]
Todo:
- [ ] Remove Register Tree from bottom Menu
- [ ]  Add Me in bottom menu when the user is not logged in as well.
- [ ]  Keep Gift before Donate.
- [ ]  Implement clean headers in the page.

Shifted from #1831  to here
