### ISSUE TITLE
TypeError in app/components/TreecounterGraphics/Trillion.native.js:197 - undefined is not a function (near '...t.props.pledgeEvents.pledgeEvents.map...')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1861]
## Error in Plant-for-the-Planet App

**TypeError** in **app/components/TreecounterGraphics/Trillion.native.js:197**
undefined is not a function (near '...t.props.pledgeEvents.pledgeEvents.map...')

https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/4344f9c3b064da4f6ee35b43a8857b4e3211496a/app/components/TreecounterGraphics/Trillion.native.js#L197

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e2b711e00ee80001a8bfcca?event_id=5e2b711e0055e226f3450000&i=gh&m=ci)

## Stacktrace

    app/components/TreecounterGraphics/Trillion.native.js:197 - _renderScreen

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e2b711e00ee80001a8bfcca?event_id=5e2b711e0055e226f3450000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by sagararyal** [comment]
Was generated during migration of database, maintenance mode.

**Comment by norbertschuler** [comment]
outdated bug
