### ISSUE TITLE
Crash displaying treecounter of Plant-for-the-Planet or other TPO with projects

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1863]
**Describe the bug**
https://www.trilliontreecampaign.org/t/plant-for-the-planet or https://www.trilliontreecampaign.org/t/eden-reforestation-projects or other TPO treecounter with projects crashes with

```
TypeError: Cannot read property 'taxDeduction' of null
    at PlantProjectFull.render (16.13bfd43cd30f177898c3.js:1)
    at vi (bundle.13bfd43cd30f177898c3.js:1)
    at ui (bundle.13bfd43cd30f177898c3.js:1)
    at so (bundle.13bfd43cd30f177898c3.js:1)
    at fk (bundle.13bfd43cd30f177898c3.js:1)
    at Zj (bundle.13bfd43cd30f177898c3.js:1)
    at Lj (bundle.13bfd43cd30f177898c3.js:1)
    at bundle.13bfd43cd30f177898c3.js:1
    at n.unstable_runWithPriority (bundle.13bfd43cd30f177898c3.js:1)
    at fg (bundle.13bfd43cd30f177898c3.js:1)
```
We have not release a new version of the web client, so maybe the result from the API calls changed on production?

**Is it on a Production or Development Build?**
production

**To Reproduce**
1. Go to https://www.trilliontreecampaign.org/t/plant-for-the-planet
2. See error

**Screenshots**
<img width="1078" alt="Bildschirmfoto 2020-01-25 um 10 51 44" src="https://user-images.githubusercontent.com/1532418/73119396-7aa17280-3f61-11ea-8938-d50106ab9459.png">

**Desktop (please complete the following information):**
- OS: latest MacOS
 - Browser: latest Chrome
 - Plant-for-the-Planet App Version 1.2.0

**Comment by norbertschuler** [comment]
One thing that puzzles me is that I can not find this bug in Bugsnag. 🤔

**Comment by jmiridis** [comment]
This error was due to a change I made. It should be fixed now.
Sorry for the trouble.
