### ISSUE TITLE
v1.4 To Do

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1864]
_v1.3.1 needs to be completed before these are merged to develop._
Features here can also be released under 1.3.x if completed before release of v1.4

- [x] #1958 Maps in User Profile Fixes

- [ ] Load competition tabs individually; Remove My Tab [My competitions will show up in Profile] @harshvitra 

- [x] Improve loading of competition when it has 100s of participants @harshvitra 

- [ ] Bring Donations within App [keep the PR separate until approved by Apple / Google] @mahmed0715 

- [ ] Implement Multiple Gifts within App & connect to Donation Process. @jmiridis 

- [ ] Recurring Donations #699

- [ ] Implement SEPA Direct Debits as a Payment Method in App @jmiridis @mahmed0715 

- [ ] Allow all organizations to use Plant-for-the-Planet PayPal Account @jmiridis

**Comment by norbertschuler** [comment]
@sagararyal can you update this or is this still our up to date roadmap?
