### ISSUE TITLE
undefined is not an object (evaluating 'this.props.selectedProject.id')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1877]
## Error in Plant-for-the-Planet App

**TypeError** in **MainActivity**
undefined is not an object (evaluating 'this.props.selectedProject.id')

https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/4344f9c3b064da4f6ee35b43a8857b4e3211496a/app/components/DonateTrees/index.native.js#L399

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e348ade2c7d3a001db151f9?event_id=5e348ade0055e640cdfc0000&i=gh&m=ci)

## Stacktrace

    app/components/DonateTrees/index.native.js:399 - value
    app/components/DonateTrees/index.native.js:201 - value
    app/components/DonateTrees/index.native.js:335 - _renderScene
    app/components/DonateTrees/receiptTabs.native.js:47 - onNextClickIndividual
    app/components/DonateTrees/receiptTabs.native.js:171 - onClick
    app/components/Common/Button/PrimaryButton.native.js:15 - onPress

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e348ade2c7d3a001db151f9?event_id=5e348ade0055e640cdfc0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Outdated bug, should be fixed by refactoring in #1908 - so I don't want to add any safety checks in the old codebase.
