### ISSUE TITLE
Copy/Paste Login Credentails (App)

### ISSUE THREAD

**Issue by delightedMatt** [Plant-for-the-Planet-org/treecounter-app#1893]
**Copy/Paste Login for the App**
Currently the (non-browser) Login-Screen doesn't allow for copy-pasting login credentials.
This might be bad for Accessibility and clashes with Password Managing Tools.

I couldn't find anything regarding this topic in the repository, if there already is, 
I am sorry for doubling up =)

**Comment by norbertschuler** [comment]
No login credentials any more.
