### ISSUE TITLE
Page to Select Currency

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1896]
<img width="392" alt="Screen Shot 2020-02-04 at 7 18 47 PM" src="https://user-images.githubusercontent.com/5401575/73773830-2c6f4900-4783-11ea-9310-faaf40cd3441.png">

Flags are available at: CDN URL : /media/images/flags/svg/{country}.svg
https://cdn-app.plant-for-the-planet.org/media/images/flags/svg/DE.svg

Zeplin
https://zpl.io/bzXXjy7

Goal : This should replace dropdown which is inefficient and takes quite some time to load in the pages.

**Comment by norbertschuler** [comment]
I don’t think the UI element of the Dropdown is slow as rather the way it’s used.
