### ISSUE TITLE
Button to update tree planting targets missing

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1901]
**Describe the bug**
The button to save the form to change your tree targets is missing on small (Android) devices.

**Is it on a Production or Development Build?**
production & develop

**To Reproduce**
1. Go to 'Update Target'
2. See error

**Screenshots**
![Screenshot_2020-02-05-12-41-48](https://user-images.githubusercontent.com/1532418/73839000-39d51380-4815-11ea-96d3-a873e302f21f.png)

**Smartphone (please complete the following information):**
- Device: Huawei Honor 6
 - OS: Android 6
 - Plant-for-the-Planet App Version 1.3.0

**Comment by sagararyal** [comment]
In the same PR, can we use Formik for this with new form design?

**Comment by norbertschuler** [comment]
Let’s not put too much changes in a single PR. This screen is an separate own issue.

**Comment by norbertschuler** [comment]
Also happening on Samsung Galaxy S6 Edge with Android 7.0
