### ISSUE TITLE
undefined is not an object (evaluating 't[l].category='contributions'')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1910]
## Error in Plant-for-the-Planet App

**TypeError** in **MainActivity**
undefined is not an object (evaluating 't[l].category='contributions'')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e3cf5a1f84d93001ac114b7?event_id=5e3cf5a10055f330e3a40000&i=gh&m=ci)

## Stacktrace

    app/selectors/index.js:214 - 
    app/containers/UserHome/index.js:61 - 
    app/actions/EditMyTree.js:86 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e3cf5a1f84d93001ac114b7?event_id=5e3cf5a10055f330e3a40000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
This is also because of not checking wrong or incompatible results returned from API calls:

<img width="577" alt="Bildschirmfoto 2020-04-01 um 21 31 23" src="https://user-images.githubusercontent.com/1532418/78149415-2f737680-7460-11ea-9e77-675b3c844563.png">

**Comment by norbertschuler** [comment]
Outdated bug. Not sure why a state update can result into this error. Aren't the modification in the state atomic?
