### ISSUE TITLE
Press button twice to show second page of treecounter

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1914]
On the "Me" screen, you have to press the button to go to the second page of the treecounter twice before it works:

![Screenshot_20200207-141402](https://user-images.githubusercontent.com/1532418/74032503-6a06e880-49b4-11ea-9a93-79ce112c0a96.png)

(Issue already on production)

**Comment by haideralishah** [comment]
@norbertschuler  nothing navigation done by this button only toggling the view.
I need more information.
![image](https://user-images.githubusercontent.com/9020813/79207328-07214a00-7e5a-11ea-9833-1025941d38a8.png)

**Comment by norbertschuler** [comment]
@haideralishah Your screen shot show exactly the "second page of the treecounter" I was referring to. Maybe my term to describe it was not very good. But can you reproduce it took two clicks on the arrow button to switch to the second view?

**Comment by norbertschuler** [comment]
This error resulted from using a state that already has been changed. Since state changes happen asynchronously the error happened depending on the speed the state changed.
