### ISSUE TITLE
Persist support state if a user came from /support/slug

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1918]
Currently it is possible for user to arrive using a support link,
eg: https://trilliontreecampaign.org/support/felix-finkbeiner-1
and make a donation that will increase B value [supported trees] of  [felix-finkbeiner-1]

However, if the user clicks any other link in the page, example Login, Signup, Home, Donate, this state is lost.

This task should:

- [ ] Store the support slug locally and persist the state

If a use visits, Explore and comes back to Donate, they would still see the option to Support [felix-finkbeiner-1]

- [ ] If the user signs up, --> Automatically set the supported tree-counter to: [felix-finkbeiner-1]

- [ ] If the user logs in and does not have supported tree counter, --> automatically set supported tree counter to [felix-finkbeiner-1]

- [ ] If the user has a supported tree counter, do not override the supported tree counter but instead make a one time override on the Donation process so the trees are supported to [felix-finkbeiner-1]

**Comment by norbertschuler** [comment]
Closing as we do not support old web client anymore.
