### ISSUE TITLE
Review functionality missing in the app

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1922]
**Describe the bug**
In the project details, the review score, a link to review the app or list the reviews cannot be found any more.

**Is it on a Production or Development Build?**
develop

**To Reproduce**
1. Go to our default projects and display the details
2. See error

**Expected behavior**
Show a link to go to the reviews and also the current review score.

**What actually happens**
Nothing about the reviews is shown anymore.

**Comment by harshvitra** [comment]
<img width="828" alt="Screenshot 2020-02-26 at 4 06 06 AM" src="https://user-images.githubusercontent.com/25605193/75294143-b1fb8b80-584d-11ea-93df-6878cae3ce75.png">

The score is available and I cannot replicate the issue. 

The 'Write a Review' Button is only for userProfile with isReviewer set to true 

@norbertschuler if please tell us in which environment are you getting this issue

**Comment by norbertschuler** [comment]
You're right, I just tested with the wrong data (test backend). So I close this issue.
