### ISSUE TITLE
Follow function does not exists any more in the app

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1923]
**Describe the bug**
On the treecounter screen you can not see the follower state or follow/unfollow a treecounter.

**Is it on a Production or Development Build?**
develop

**To Reproduce**
1. Go to a treecounter. 
2. See error

**Expected behavior**
Allow a user to follow or unfollow a treecounter and see the follower status.

**What actually happens**
Nothing is shown any more.

**Comment by sagararyal** [comment]
not a bug, intentionally removed
