### ISSUE TITLE
Separate URL for API and website in config/environment

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1927]
In order to be able to host the API at a different location as the website, the application should be changed so the URL for the API calls differ from the URL of the website in the application. You have to figure our where to use the website URL and where to use the API URL in our application. Also please check not getting CORS issues (eventually the backend has to add something to the server configuration).

**Comment by norbertschuler** [comment]
Eventually this issue should wait until https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1840 is done.

**Comment by sagararyal** [comment]
@norbertschuler can't this be done by updating the host value?

What would be the way to move forward with this?

If a transition to Heroku is possible in a week or two, we could already support this.

**Comment by norbertschuler** [comment]
@sagararyal nothing should stop someone implementing this now. Just find someone who wants to do it :-)
