### ISSUE TITLE
Design issues on "Leaderboard", "Competitions" and "Challenge"

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1940]
I got a few design issues on iOS with my iPhoneX:

- [x] third tab item is cut for "Leaderboard" (same as #1906):

![IMG_7269](https://user-images.githubusercontent.com/1532418/74419856-d1a4b400-4e4a-11ea-8403-a8435e1f77cf.PNG)

- [x] content loader for "Competitions" is positioned to far at the top (not checking for safe area):

![IMG_7267](https://user-images.githubusercontent.com/1532418/74419970-f9941780-4e4a-11ea-9a1c-ef882b2f5f90.PNG)

- [x] text on the buttons on the page to challenge your friends is cut:

![IMG_7261](https://user-images.githubusercontent.com/1532418/74420032-14ff2280-4e4b-11ea-9950-277d85dd0136.PNG)

**Comment by norbertschuler** [comment]
- [ ] text on the buttons on the page to challenge your friends is still cut for me using iPhone 11 simulator:

![Simulator Screen Shot - iPhone 11 - 2020-03-14 at 12 15 53](https://user-images.githubusercontent.com/1532418/76680937-8fa79300-65ed-11ea-9905-3f2cf687075f.png)

**Comment by haideralishah** [comment]
Actually these are the lists of filter which is scrollable in future we can add more filter so it should be scrollable 

![image](https://user-images.githubusercontent.com/9020813/76729376-d5de2d00-677a-11ea-89c4-6b75fe45e5f7.png)

**Comment by haideralishah** [comment]
@norbertschuler 
text cutting issue on challenge friend screen is now fixed.
Check this out.

![image](https://user-images.githubusercontent.com/9020813/76966134-4b96f400-6947-11ea-83fd-318b385a1957.png)

![image](https://user-images.githubusercontent.com/9020813/76966265-839e3700-6947-11ea-8e5c-234d37a6e6ac.png)

**Comment by norbertschuler** [comment]
Closing this as it seems to be done.
