### ISSUE TITLE
TypeError in /register-trees - Cannot read property 'getValue' of null

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1942]
## Error in Plant-for-the-Planet App

**TypeError** in **/register-trees**
Cannot read property 'getValue' of null

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e4530430dffd2001907af47?event_id=5e4530430056052e899a0000&i=gh&m=ci)

## Stacktrace

https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/f956bb0ca0450cc3b3565f9b1ea3bb800001c1a3/app/components/RegisterTrees/index.js#L145

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e4530430dffd2001907af47?event_id=5e4530430056052e899a0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
@sanjayradadiya Do you have an idea, if your latest changes to the register trees function could have this side effect on registering trees in the web client?

**Comment by norbertschuler** [comment]
seems to be fixed
