### ISSUE TITLE
TypeError in /leaderboard/country - 'ht.default.notify' is undefined

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1946]
## Error in Plant-for-the-Planet App

**TypeError** in **/leaderboard/country**
ht.default.notify is not a function. (In 'ht.default.notify(j,(function(j){j.metadata={info:q}}))', 'ht.default.notify' is undefined)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e4579adaf15de0019dceed7?event_id=5e4579ad0055eaa197830000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/bundle.91a2e587b376b59ae06b.js:1 - componentDidCatch

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e4579adaf15de0019dceed7?event_id=5e4579ad0055eaa197830000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Result of `ChunkLoadError`
