### ISSUE TITLE
UnhandledRejection of Promise

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1947]
## Error in Plant-for-the-Planet App

**UnhandledRejection** in **/login /explore /signup /password-sent /manage-projects /redeem /donate-tress and more**
Rejection reason was not an Error. See "Promise" tab for more detail.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e458a2b4a84b400188ffe49?event_id=5e458a2b0055e8ccea230000&i=gh&m=ci)

## Stacktrace

    unknown file:0 - unknown method

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e458a2b4a84b400188ffe49?event_id=5e458a2b0055e8ccea230000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Promise returns rejection reason Timeout or `
{
  "isTrusted": true
}
`
