### ISSUE TITLE
Error in /account-activation - email not in localStorage

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1948]
## Error in Plant-for-the-Planet App

**Error** in **/account-activation**
email not in localStorage

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e46410b3b523c001941f0a7?event_id=5e46410b0055ed803fc50000&i=gh&m=ci)

## Stacktrace

    app/containers/Authentication/ActivateAccountContainer.js:19 - ActivateAccountContainer._callee$

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e46410b3b523c001941f0a7?event_id=5e46410b0055ed803fc50000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Not checking the case the value does not exist:

<img width="598" alt="Bildschirmfoto 2020-04-01 um 21 56 40" src="https://user-images.githubusercontent.com/1532418/78152213-b24a0080-7463-11ea-90c5-4dda710fa62a.png">
