### ISSUE TITLE
TypeError in /register-trees - null is not an object (evaluating 'e.getDate')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1950]
## Error in Plant-for-the-Planet App

**TypeError** in **/register-trees**
null is not an object (evaluating 'e.getDate')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e469eb5f5f83e001a7547cc?event_id=5e469eb50055e637cae10000&i=gh&m=ci)

## Stacktrace

    app/helpers/utils.js:157 - formatDateToMySQL
    app/components/Templates/DatePickerTemplate.js:32 - onChange

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e469eb5f5f83e001a7547cc?event_id=5e469eb50055e637cae10000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Missing check for valid date value:

<img width="557" alt="Bildschirmfoto 2020-04-01 um 21 58 12" src="https://user-images.githubusercontent.com/1532418/78152398-f0472480-7463-11ea-8eb1-07e2148bdf49.png">

**Comment by norbertschuler** [comment]
This bug got already fixed.
