### ISSUE TITLE
TypeError in /signup/vodafone - undefined is not an object (evaluating 'href.value.charAt')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1951]
## Error in Plant-for-the-Planet App

**TypeError** in **/signup/vodafone**
undefined is not an object (evaluating 'href.value.charAt')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e46a6ba61b70c001ac0f613?event_id=5e46a6ba005603d80f6c0000&i=gh&m=ci)

## Stacktrace

    jquery-3.2.1.js:362 - each

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e46a6ba61b70c001ac0f613?event_id=5e46a6ba005603d80f6c0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
I wonder if this only happened while the Vodafone campaign running and if it might be related with the Cloudflare modifications done by this addon:

<img width="720" alt="Bildschirmfoto 2020-04-12 um 22 47 35" src="https://user-images.githubusercontent.com/1532418/79073337-2f9d2d00-7d10-11ea-8ac9-bf6161fc16a4.png">

As this does not happen any more for now, I will close it now.
