### ISSUE TITLE
Direct donation to project from treecounter fails

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1957]
**Describe the bug**
If you open a TPO treecounter and want to donate using the button with the amount per tree, the next page stays blank. 

**Is it on a Production or Development Build?**
Production 

**To Reproduce**
1. Go to a TPO treecounter 
2. Click on button with amount of money per tree to donate
3. See blank page

**Screenshots**

![1454A452-EAF5-4659-9C1B-B26EF55E05BE](https://user-images.githubusercontent.com/1532418/74593686-20f70a00-502e-11ea-8279-bd7d8d3105f7.png)

![AEE6C1C0-53D3-4AF5-BD66-6F833CEB76ED](https://user-images.githubusercontent.com/1532418/74593683-1e94b000-502e-11ea-95c2-5d31b83a533f.jpeg)
![6C08B0A5-39E8-4EE7-9138-1AF4FB4B64B2](https://user-images.githubusercontent.com/1532418/74593685-205e7380-502e-11ea-8039-34fc72a0fc0d.png)

**Smartphone (please complete the following information):**
- Device: iPhone X
 - OS: iOS 13.x
 - Plant-for-the-Planet App Version 1.3.1

**Additional context**
If you load the project first it works.

**Comment by norbertschuler** [comment]
We should test if this also is fixed by https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1997?

**Comment by norbertschuler** [comment]
> We should test if this also is fixed by #1997?

No, this ain't fixed. Seems to be another error.

**Comment by norbertschuler** [comment]
I tried to find out the different ways the properties `onSelectClickedFeaturedProjects` and `selectProject` of the components `PlantProjectSnippet` and `PlantProjectSnippetDetails` are set, but you get into property hell quiet quickly ;-)

<img width="440" alt="Bildschirmfoto 2020-02-26 um 16 52 47" src="https://user-images.githubusercontent.com/1532418/75362029-71852780-58b8-11ea-82f0-59c8a70f0792.png">

Mostly the next page for `onSelectClickedFeaturedProjects` is loaded by calling `updateStaticRoute('app_donate_detail', ...);`, but there are many variants how this is used:

<img width="440" alt="Bildschirmfoto 2020-02-26 um 16 58 20" src="https://user-images.githubusercontent.com/1532418/75362567-38998280-58b9-11ea-859b-1cd5e1f44cf8.png">

**Comment by mahmed0715** [comment]
checking on it.

**Comment by norbertschuler** [comment]
If you add some logging (e.g. debug(this.props)) here you can see not useful information in passed to this container in order to load a project and show the component: https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/1e47f900a218fd6b85b13b16294054676a94d959/app/containers/DonateTrees/index.js#L74
