### ISSUE TITLE
Show Private Label for Leaderboard entries with maypublish = false

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1959]
In Leaderboard,
If someone tries to open a profile for a `user without a slug` or user who has `maypublish=false`

Show the following label:
<img width="475" alt="Screen Shot 2020-02-15 at 8 58 17 PM" src="https://user-images.githubusercontent.com/5401575/74594385-06289380-5036-11ea-8259-5ca0fbdd4df6.png">

Note that, label `should not show` initially when the leaderboard tab is loaded.

https://zpl.io/V4dLEEJ

**Comment by sagararyal** [comment]
Reopening this issue as 
Requirements has not been met and not according to design

Note that, label `should not show` initially when the leaderboard tab is loaded; and only show when user tries to tap/click on the profile.

**Comment by sagararyal** [comment]
Design
<img width="287" alt="Screen Shot 2020-02-20 at 1 52 06 PM" src="https://user-images.githubusercontent.com/5401575/74935245-38e0dc00-53e8-11ea-909c-060d442f1044.png">

Implementation
<img width="463" alt="Screen Shot 2020-02-20 at 1 51 59 PM" src="https://user-images.githubusercontent.com/5401575/74935211-2bc3ed00-53e8-11ea-974d-543ba7bee974.png">

**Comment by norbertschuler** [comment]
@sagararyal Sorry, this is my fault as I reviewed and merged the PR #1975 though it was still a DRAFT. For the future I will not change any more any draft to "ready for review" as that is of course the responsibility  of the author of the PR.
