### ISSUE TITLE
TypeError in /register-trees - Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1960]
## Error in Plant-for-the-Planet App

**TypeError** in **/register-trees**
Cannot read property 'includes' of undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e4879254b2d7f001bbfe872?event_id=5e4879250055fd552af70000&i=gh&m=ci)

## Stacktrace

    app/helpers/utils.js:221 - 
    app/helpers/utils.js:219 - mergeContributionImages
    app/containers/RegisterTrees/index.js:34 - Object.onSubmit
    app/components/RegisterTrees/index.js:143 - RegisterTrees.onSubmitClick

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e4879254b2d7f001bbfe872?event_id=5e4879250055fd552af70000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Maybe a wrong safety check?

<img width="666" alt="Bildschirmfoto 2020-04-01 um 22 05 32" src="https://user-images.githubusercontent.com/1532418/78153249-0dc8be00-7465-11ea-9836-14409823fa9c.png">
