### ISSUE TITLE
TypeError in app/components/Competition/Tabs/closed.native.js:59 - undefined is not an object (evaluating 't.endDate')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1967]
## Error in Plant-for-the-Planet App

**TypeError** in **app/components/Competition/Tabs/closed.native.js:59**
undefined is not an object (evaluating 't.endDate')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e494aecc48d6e001e4d8e3d?event_id=5e494aec00560423294e0000&i=gh&m=ci)

## Stacktrace

    app/components/Competition/Tabs/closed.native.js:59 - 
    app/components/Competition/Tabs/closed.native.js:58 - 
    app/components/Competition/Tabs/closed.native.js:56 - value
    app/actions/competition.js:241 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e494aecc48d6e001e4d8e3d?event_id=5e494aec00560423294e0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
This has happened as I deleted an old archived competition and navigated to the list of competitions while the delete API call was still processing in the background.

**Comment by harshvitra** [comment]
@norbertschuler we might remove the option to see the archived competitions. 
@sagararyal can you confirm ?

**Comment by sagararyal** [comment]
@harshvitra this is possible, as old competitions still appear in My Competitions page.

**Comment by harshvitra** [comment]
@norbertschuler I tried to replicate this 

This doesn't happen anymore, but what happens is that the competition still appears in the list. Creating a new issue for that
