### ISSUE TITLE
TypeError in /manage-plant-projects - Cannot read property 'includes' of null

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1972]
## Error in Plant-for-the-Planet App

**TypeError** in **/manage-plant-projects**
Cannot read property 'includes' of null

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e4a7451d465bd001908d6ae?event_id=5e4a74510055e7087f8b0000&i=gh&m=ci)

## Stacktrace

    app/components/ManageProjects/index.js:162 - 
    app/components/ManageProjects/index.js:161 - ManageProjects.mergeProjectImages
    app/components/ManageProjects/index.js:186 - ManageProjects.handleSaveProjectClick
    app/components/ManageProjects/index.js:253 - onClick

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e4a7451d465bd001908d6ae?event_id=5e4a74510055e7087f8b0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Maybe a missing safety check?

<img width="706" alt="Bildschirmfoto 2020-04-01 um 22 11 03" src="https://user-images.githubusercontent.com/1532418/78153839-b24b0000-7465-11ea-8587-bf00d68038e7.png">

**Comment by norbertschuler** [comment]
fixed by https://github.com/Plant-for-the-Planet-org/treecounter-app/commit/546385094731b51f9a88311493920111d94cc7b8
