### ISSUE TITLE
TypeError in /explore

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1973]
## Error in Plant-for-the-Planet App

**TypeError** in **/explore**
window.navigator.getGamepads is not a function

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e4a934ac82b6b001a86d140?event_id=5e4a934a0055f8f30b860000&i=gh&m=ci)

## Stacktrace

    https://js.arcgis.com/4.14/esri/views/MapView.js:300 - esri/views/input/gamepad/GamepadSource/</q</d.prototype.forEachGamepad

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e4a934ac82b6b001a86d140?event_id=5e4a934a0055f8f30b860000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
can fix problem in external codebase
