### ISSUE TITLE
ReferenceError in /donate-trees

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1977]
## Error in Plant-for-the-Planet App

**ReferenceError** in **/donate-trees**
chrome is not defined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e4cf844552b3c00191d8c53?event_id=5e4cf8440055fe9a6f300000&i=gh&m=ci)

## Stacktrace

    eval:1 - e

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e4cf844552b3c00191d8c53?event_id=5e4cf8440055fe9a6f300000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Calling https://weplant.app/donate-trees is obviously not yet supported.
