### ISSUE TITLE
undefined is not an object (evaluating 'u.refs.targetContainer.refs')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1989]
## Error in Plant-for-the-Planet App

**TypeError** in **MainActivity**
undefined is not an object (evaluating 'u.refs.targetContainer.refs')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e50f1b31eba7c00194dc950?event_id=5e50f1b30055f985dcc80000&i=gh&m=ci)

## Stacktrace

    app/containers/TargetContainer/index.js:21 - onSubmitTarget
    app/components/Common/Button/PrimaryButton.native.js:15 - onPress

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e50f1b31eba7c00194dc950?event_id=5e50f1b30055f985dcc80000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Maybe a missing safety check for `this.refs.targetContainer.refs`?

<img width="627" alt="Bildschirmfoto 2020-04-02 um 12 23 33" src="https://user-images.githubusercontent.com/1532418/78213423-cb42c800-74dc-11ea-9229-10b3437337bd.png">

**Comment by norbertschuler** [comment]
Referencing a form by e.g. `this.refs.targetContainer.refs.setTargetForm.validate()` does not always seem to work. Therefore we already started to get form references by changing the reference handling like this: https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/2b968b0636cbc2c44a5d28ce2fe4361fef23eb0b/app/components/EditUserContribution/index.js#L110 

Next time we receive this bug, we should also change this form this way.
