### ISSUE TITLE
Error in /gift-trees - No response from window - cleaned up

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1996]
## Error in Plant-for-the-Planet App

**Error** in **/gift-trees**
No response from window - cleaned up

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e53d577c9368f001a28604d?event_id=5e53d5770055e72e37b70000&i=gh&m=ci)

## Stacktrace

    app/components/Payment/PaymentSelector.js:65 - decorateSuccess
    app/components/Payment/PaymentSelector.js:284 - onSuccess
    app/components/Payment/Gateways/Paypal.js:112 - onCancel
    src/button/component.jsx:805 - decorateOnCancel

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e53d577c9368f001a28604d?event_id=5e53d5770055e72e37b70000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Same as #1943

**Comment by norbertschuler** [comment]
Duplicate of #1943

**Comment by Plant-for-the-Planet** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Error** in **/support/youtopia**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e53d577c9368f001a28604d?event_id=5f74b1fd0060b73e5fd40000&i=gh&m=ra)

**Comment by norbertschuler** [comment]
Related to #2725
