### ISSUE TITLE
TypeError in /edit-profile - null is not an object (evaluating 't.password.first')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1998]
## Error in Plant-for-the-Planet App

**TypeError** in **/edit-profile**
null is not an object (evaluating 't.password.first')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e54f231676fe0001843deee?event_id=5e54f23100560492fd770000&i=gh&m=ci)

## Stacktrace

    app/components/EditUserProfile/index.js:313 - onClick

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e54f231676fe0001843deee?event_id=5e54f23100560492fd770000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
May need more safety checks (e.g. for `value.password `)?

<img width="641" alt="Bildschirmfoto 2020-04-02 um 12 32 18" src="https://user-images.githubusercontent.com/1532418/78213861-0396d600-74de-11ea-8f95-688261720893.png">

**Comment by norbertschuler** [comment]
Same problem as in https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1989#issuecomment-647382520 referencing forms by `this.refs.` which probably does not always work well and should be replace by another solution.
