### ISSUE TITLE
Error in /pledge/jubilaum-stephan-heinrich - pledgedEvent not in localStorage

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2012]
## Error in Plant-for-the-Planet App

**Error** in **/pledge/jubilaum-stephan-heinrich**
pledgedEvent not in localStorage

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e58c3fbc078a2001815722e?event_id=5e58c3fb00567866f3fc0000&i=gh&m=ci)

## Stacktrace

   https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/d71a787a22972d61f5ad9c7de75b326d5023f31f/app/containers/Pledge/index.js#L34

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e58c3fbc078a2001815722e?event_id=5e58c3fb00567866f3fc0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
None existing storage values should be taken care of by our code.

**Comment by norbertschuler** [comment]
@harshvitra can you make the loading of values from local storage more failsafe (in case the user cleared his browser and expected value do not exist anymore)?

**Comment by norbertschuler** [comment]
Fixed correctly catching the promise rejection myself with https://github.com/Plant-for-the-Planet-org/treecounter-app/compare/0b2cdf1f6d85...b453cacf2c67
