### ISSUE TITLE
Error in /pledge/jubilaum-stephan-heinrich

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2013]
## Error in Plant-for-the-Planet App

**Error** in **/pledge/jubilaum-stephan-heinrich**
pledgedEvent not in localStorage

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e58c3fb88afa900193f7dde?event_id=5e58c3fb00567866f3f10000&i=gh&m=ci)

## Stacktrace

    app/containers/Pledge/index.js:55 - componentDidUpdate

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e58c3fb88afa900193f7dde?event_id=5e58c3fb00567866f3f10000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Duplicate of #2013

**Comment by Plant-for-the-Planet** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Error** in **/pledge/mandoki-soulmates**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e58c3fb88afa900193f7dde?event_id=5e9082f60059ae58cc840000&i=gh&m=ra)

**Comment by norbertschuler** [comment]
Duplicate of #2012
