### ISSUE TITLE
TypeError in /edit-trees/286117 - Cannot read property 'getValue' of undefined

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2015]
## Error in Plant-for-the-Planet App

**TypeError** in **/edit-trees/286117**
Cannot read property 'getValue' of undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e58f2d96dd463001ccd4c31?event_id=5e58f2d900567dc2a5fb0000&i=gh&m=ci)

## Stacktrace

    app/components/EditUserContribution/index.js:92 - EditUserContribution.onSubmitClick

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e58f2d96dd463001ccd4c31?event_id=5e58f2d900567dc2a5fb0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Maybe add some safety check of the form object exists?

<img width="694" alt="Bildschirmfoto 2020-04-02 um 12 38 37" src="https://user-images.githubusercontent.com/1532418/78214231-e44c7880-74de-11ea-9e25-aa77b653462e.png">
