### ISSUE TITLE
EXC_BAD_ACCESS in JSC::SlotVisitor::drain(WTF::MonotonicTime)::$_3::operator()(JSC::MarkStackArray&) const

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2017]
## Error in Plant-for-the-Planet App

**EXC_BAD_ACCESS** in **JSC::SlotVisitor::drain(WTF::MonotonicTime)::$_3::operator()(JSC::MarkStackArray&) const**
Attempted to dereference garbage pointer 0x40.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e5b8eced4219c001a714f72?event_id=5e5b8ece00566f979d940000&i=gh&m=ci)

## Stacktrace

    Frameworks/JavaScriptCore.framework/JavaScriptCore:0 - JSC::SlotVisitor::drain(WTF::MonotonicTime)::$_3::operator()(JSC::MarkStackArray&) const

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e5b8eced4219c001a714f72?event_id=5e5b8ece00566f979d940000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
can not fix native error
