### ISSUE TITLE
Missing Profile Donate Button - iOS

### ISSUE THREAD

**Issue by delightedMatt** [Plant-for-the-Planet-org/treecounter-app#2020]
**There is no _Donate_ button on other user's tree counters (unlike in Android)**
When wanting to donate trees to someone already on the app, one can't do this via their profile on iOS - since the Donate Button doesn't show up.

**Importance:**
Of course iOS users can still gift trees in other ways. 
But the way via the User Profile is very intuitive and one of the main ways companies/events tell users to support them (because the users then also see how many trees the tree counter already collected).

**Current behavior**
1. iOS Device
2. Look at someone else's tree counter
3. No donate button shows up

**Expected behavior**
1. iOS Device
2. Look at someone else's tree counter
3. The same donate button as in Android shows up

**Smartphone**
- Unknown at the moment - will be followed up on

**Screenshot iOS**

![iOS_donate-button_bug](https://user-images.githubusercontent.com/18365824/75660847-94269000-5c6c-11ea-867b-881fbc0a3938.jpeg)

**Screenshot Android**

![android_donate-button](https://user-images.githubusercontent.com/18365824/75661852-5f1b3d00-5c6e-11ea-95b2-e8c95b3d3582.jpg)

**Comment by norbertschuler** [comment]
In the latest iOS version 1.49.4.17 of our app on my iPhone X I can see the donate button:

![IMG_7342](https://user-images.githubusercontent.com/1532418/75662957-4e6bc680-5c70-11ea-9f37-525fa7dc7c9b.PNG)

What version of the app (see "Me"->Settings-Icon->Information) is this screen shot made with?

**Comment by delightedMatt** [comment]
I got an update:
The user did have an older version.

Smartphone Data:
OS: iOS 13.3.1
Plant-for-the-Planet App version: 1.49.3.16
