### ISSUE TITLE
Deep Link to tree counter opens App but not tree counter (android only)

### ISSUE THREAD

**Issue by delightedMatt** [Plant-for-the-Planet-org/treecounter-app#2021]
**Opening links to tree counters with the App closed only opens the app, not the specified tree counter (on android only).**
If the App is opened before opening the link, it does open the specified tree counter in the App.

**Enhancement**:
Would it be possible to change it, so that the link **opens the app on the specified tree counter**?

**To Reproduce**
Steps to reproduce the current behavior:
1. Download Plant-for-the-Planet App on android device
2. **Close App**
2. Klick on Link to www.TrillionTreeCampaign.org/t/passionswald
(or another tree counter)
3. Link causes the App to open on the main page

**Expected behavior**
1. Download Plant-for-the-Planet App on mobile device
2. **Close App**
2. Klick on Link to www.TrillionTreeCampaign.org/t/passionswald
(or another tree counter)
3. Link causes the **App to open on the specified tree counter** (here: passionswald)

**Smartphone**
- Device: Samsung Galaxy S7
- Android 8.0.0
- Plant-for-the-Planet App Version: 1.3.1.900025

- on iOS 13.3.1 it does open the app on the specified tree counter

**Context**
The chocolate team uses a QR-Code for the upcomming Passionsspiele Event leading to the Passionsspiele tree counter:
![qr-code-clean](https://user-images.githubusercontent.com/18365824/75674130-bd531a80-5c84-11ea-87d8-14fbe2936053.png)

**Comment by norbertschuler** [comment]
With removing the old header from the treecounter screen in the native app, we also removed the possibility to share any treecounter with the native app (you can only more share you own treecounter from the "Me" screen).

**Comment by norbertschuler** [comment]
- [ ] Test for iOS with `xcrun simctl openurl booted https://www.trilliontreecampaign.org/t/passionswald`.
- [ ] Test for Android with `adb shell am start -W -a android.intent.action.VIEW -d "https://www.trilliontreecampaign.org/t/passionswald"`

**Comment by norbertschuler** [comment]
If the iOS isn't started before (kill it by opening the task list and swipe it up), it also does not open the treecounter on my simulator with the link.

**Comment by norbertschuler** [comment]
- [ ] for Android I found this discussion of the problem. Obviously it still exists and is not solved yet: https://github.com/facebook/react-native/issues/25675

**Comment by norbertschuler** [comment]
We could try out this solution: https://github.com/facebook/react-native/issues/25675#issuecomment-612249911
