### ISSUE TITLE
First Project (Yucatán) doesn't show (android)

### ISSUE THREAD

**Issue by delightedMatt** [Plant-for-the-Planet-org/treecounter-app#2022]
**When going to _Donate_ Yucatán doesn't show up in Featured**

When you go to Featured Yucatán is not one of the Projects being presented.
If you scroll all the way down and then scroll up again, it will show up.

Samsung Galaxy S7
Android: 8.0
App version: 1.3.1.900025

**Comment by delightedMatt** [comment]
It's showing up fine now.
I didn't change anything on my side (same App version, same Phone, same software).
It also didn't show up to Sagar this morning. 
Unsure what caused this.

**Comment by norbertschuler** [comment]
I can not reproduce this with a freshly installed app from the Google Play Store. The Yucatán project is shown as the first project in the list of featured projects for me.

**Comment by delightedMatt** [comment]
@norbertschuler 
Thanks for trying, though!

**Comment by haideralishah** [comment]
@norbertschuler I think this issue has been fixed so I m closing.
