### ISSUE TITLE
Change access to legal and general information without login

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#2023]
Currently the users of the native app can only access the **imprint** or **privacy policy**  (also the **FAQ** and general information) when they are registered and logged in as the user menu is only more accessible from the "Me" screen. 

- [ ] These data should also be directly available for non registered or logged in users.

- [ ] Also the privacy policy usually should be linked on the login or register form.

Update: As the users can access the site navigation with swiping at least a possibility for access is granted.

**Comment by haideralishah** [comment]
1. these three buttons (imprint,  privacy policy & FAQ) are already available for registered or non-registered users.
2. @norbertschuler is there any design where we should put these buttons  (imprint,  privacy policy & FAQ) in Login & Sign Up Screen?

**Comment by norbertschuler** [comment]
As far as I know these three screens are only accessible by the user menu as following (**imprint** and **privacy policy** by opening the **information**):

![Simulator Screen Shot - iPhone 11 - 2020-03-19 at 17 59 31](https://user-images.githubusercontent.com/1532418/77060748-b14cb400-6a0b-11ea-97f3-f44242e4f9b1.png)

The icon to open the user menu is only visible on the "Me" screen which again is currently only accessible for a logged in user, right?

I don't know where these screens are also linked yet, but @sagararyal wanted to make a concept how to make them accessible for non registered users. But I am not sure if there is a design available yet.

**Comment by harshvitra** [comment]
@norbertschuler the user's have the access to the left menu via swiping. We dont have a button for not registered users

@sagararyal can you provide a design or other solution here ?

**Comment by norbertschuler** [comment]
> @norbertschuler the user's have the access to the left menu via swiping. We dont have a button for not registered users

@harshvitra Thank you for the tip. I did not know that feature as probably our users won't note, but it's good to know this is possibly so the app maybe fits the legal requirements having an imprint also for logged out users.
