### ISSUE TITLE
TypeError in /pledge/klima-check-up-lippe - l.response is undefined

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2026]
## Error in Plant-for-the-Planet App

**TypeError** in **/pledge/klima-check-up-lippe**
l.response is undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e5fc00ac7e1290017536a6c?event_id=5e5fc00a005778361d5b0000&i=gh&m=ci)

## Stacktrace

    app/actions/pledgeAction.js:74 - postPledge/</<

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e5fc00ac7e1290017536a6c?event_id=5e5fc00a005778361d5b0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
The current source code probably cannot handle wrong answers from the API:

<img width="418" alt="Bildschirmfoto 2020-04-02 um 12 42 26" src="https://user-images.githubusercontent.com/1532418/78214449-7785ae00-74df-11ea-98d1-7567d4336c88.png">

**Comment by norbertschuler** [comment]
Outdated bug, normally the API shows an error in `response.data.message`. We will wait if this happens again to check if this API call returns a different answer.
