### ISSUE TITLE
Unexpected input given to normalize. Expected type to be "object", found "string"

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2029]
## Error in Plant-for-the-Planet App

**Error** in **/**
Unexpected input given to normalize. Expected type to be "object", found "string".

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e619607b1bc8400171b9836?event_id=5e619607005856be66d30000&i=gh&m=ci)

## Stacktrace

    app/actions/treecounterLookupAction.js:33 - treecounterLookupAction/</</<
    app/actions/treecounterLookupAction.js:31 - promise callback*treecounterLookupAction/</<
    app/actions/treecounterLookupAction.js:16 - treecounterLookupAction/<
    app/containers/PublicTreeCounterContainer/index.js:40 - fetchAndSetSearchResult
    app/containers/PublicTreeCounterContainer/index.js:51 - componentWillMount
    index.web.js:2 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e619607b1bc8400171b9836?event_id=5e619607005856be66d30000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Error resulting from not being able to cope with unexpected results from the API.

**Comment by norbertschuler** [comment]
Outdated
