### ISSUE TITLE
Multiple tree registration doesn't work with image

### ISSUE THREAD

**Issue by Chiagozie-Udeh** [Plant-for-the-Planet-org/treecounter-app#2031]
**Error in Register tree**
*A clear and concise description of what the bug is.*

When user attempts to register “multiple trees” no changes are made, rather it returns to the original page

**Is it on a Production or Development Build?**
Production 

**To Reproduce**
1. Go to 'register trees'
2. Click on 'Many trees, enter details and add image'
3. Scroll down to 'Add trees'

**Expected behavior**
*A new page will open that will show tree registration processing.*

**Returns to the original register tree page**
*All entered details blank out and it returns to original page*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- Windows 10
 - Browser Chrome
 - Plant-for-the-Planet App Version [e.g. 1.0.3]

**Smartphone (please complete the following information):**
 - Plant-for-the-Planet App Version [e.g. 1.0.3]

**Additional context**
*Add any other context about the problem here.*

**Comment by norbertschuler** [comment]
@Chiagozie-Udeh can you try again with some smaller image as I once found it depends on the size of the images used?

**Comment by Chiagozie-Udeh** [comment]
@norbertschuler , It still doesn't work yet

**Comment by Chiagozie-Udeh** [comment]
Anyone able to sort this out? Problem persists.
