### ISSUE TITLE
TypeError in app/actions/EditMyTree.js:59 - undefined is not an object (evaluating 't.response.data')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2032]
## Error in Plant-for-the-Planet App

**TypeError** in **app/actions/EditMyTree.js:59**
undefined is not an object (evaluating 't.response.data')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e66297d501e47001724a374?event_id=5e66297d005802fc97980000&i=gh&m=ci)

## Stacktrace

    app/actions/EditMyTree.js:59 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e66297d501e47001724a374?event_id=5e66297d005802fc97980000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Error resulting from not being able to cope with unexpected results from the API.
