### ISSUE TITLE
Error in /donate-trees/125 - Unexpected input given to normalize. Expected type to be "object", found "string"

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2033]
## Error in Plant-for-the-Planet App

**Error** in **/donate-trees/125**
Unexpected input given to normalize. Expected type to be "object", found "string".

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e66578eba6f4f0017df59ba?event_id=5e66578e0058aeb8f82e0000&i=gh&m=ci)

## Stacktrace

    app/actions/loadTposAction.js:61 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e66578eba6f4f0017df59ba?event_id=5e66578e0058aeb8f82e0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Error resulting from not being able to cope with unexpected results from the API.

**Comment by norbertschuler** [comment]
Outdated
