### ISSUE TITLE
TypeError in /donate-trees - undefined is not an object (evaluating 'a.data.merge.plantProjectPager')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2035]
## Error in Plant-for-the-Planet App

**TypeError** in **/donate-trees**
undefined is not an object (evaluating 'a.data.merge.plantProjectPager')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e665841966d910017209c8c?event_id=5e665841005831e2aa6f0000&i=gh&m=ci)

## Stacktrace

    app/actions/loadTposAction.js:32 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e665841966d910017209c8c?event_id=5e665841005831e2aa6f0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by harshvitra** [comment]
Again cannot replicate this 

`normalize(res.data.merge.plantProjectPager[0].entities`

Mostly the 'res' was not sent to the user 

We need to check the response at production sessions with time - Mar 9th, 14:52:49 UTC
For this api - https://www.trilliontreecampaign.org/public/v1.1/de/plantProjects/featured

**Comment by norbertschuler** [comment]
The API call loadTposAction should be deprecated after the next release.

**Comment by norbertschuler** [comment]
Error resulting from not being able to cope with unexpected results from the API.

**Comment by norbertschuler** [comment]
Outdated
