### ISSUE TITLE
SecurityError in /Users/jacknikogosian/Desktop/Save/www.trilliontreecampaign.org.html

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2040]
## Error in Plant-for-the-Planet App

**SecurityError** in **/Users/jacknikogosian/Desktop/Save/www.trilliontreecampaign.org.html**
The operation is insecure.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e68b13f3bd45e0018fd79c6?event_id=5e68b13f00582bcd88010000&i=gh&m=ci)

## Stacktrace

    file:///Users/jacknikogosian/Desktop/Save/www.trilliontreecampaign.org_files/bundle.js:1 - wrapHistoryFn/q[$]

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e68b13f3bd45e0018fd79c6?event_id=5e68b13f00582bcd88010000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
No, our app can not be stored and run locally in a browser.
