### ISSUE TITLE
Location of Eden Reforestation Project differs between web and native apps?

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#2044]
The coordinates of this project are located in Russia, so the project is listet in Russia and all user contributions also are listed in Russia for our users - is the location correct as it might irritate users?

<img width="817" alt="Bildschirmfoto 2020-02-06 um 11 50 34" src="https://user-images.githubusercontent.com/1532418/73930777-6a7d8180-48d7-11ea-84b3-3c8273f3be1a.png">
<img width="594" alt="Bildschirmfoto 2020-02-06 um 11 51 27" src="https://user-images.githubusercontent.com/1532418/73930783-6d787200-48d7-11ea-98fa-3c0d58658571.png">

In the web client Russia is not shown when viewing the project, e.g. with https://www.trilliontreecampaign.org/t/eden-reforestation-projects

<img width="1677" alt="Bildschirmfoto 2020-03-12 um 12 19 13" src="https://user-images.githubusercontent.com/1532418/76516485-cc438500-645b-11ea-87d2-4c261f64afdc.png">

Our native apps show the project located in Russia despite getting the same result from the API, so the problem is the native apps interpret the returned data differently then the web client:

![Simulator Screen Shot - iPhone 11 - 2020-03-12 at 12 30 56](https://user-images.githubusercontent.com/1532418/76517291-56401d80-645d-11ea-9953-70a64a05ecfa.png)

**Comment by sagararyal** [comment]
We've notified Eden Reforestation Projects several times about this issue.
We can batch update existing coordinates once they can provide us with correct coordinates.

Users who donate to Eden will see a similar message in Single Contribution Page.

**Comment by norbertschuler** [comment]
My point was maybe change the native app code to show the same as the web client?

**Comment by harshvitra** [comment]
<img width="322" alt="Screenshot 2020-03-13 at 12 45 38 AM" src="https://user-images.githubusercontent.com/25605193/76558817-fa5caf80-64c3-11ea-83b2-2eef44916f61.png">

We recently changed the project api, in App it uses the country geolocation and finds the country name to show. There is no location field. 
@mahmed0715 might be needed here

**Comment by norbertschuler** [comment]
Projects got updated.
