### ISSUE TITLE
TypeError in /gift-trees - e.onClick is not a function

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2045]
## Error in Plant-for-the-Planet App

**TypeError** in **/gift-trees**
e.onClick is not a function

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e6a3c9249e7650017e6fb30?event_id=5e6a3c920058360498110000&i=gh&m=ci)

## Stacktrace

    app/components/GiftTrees/index.js:366 - validated

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e6a3c9249e7650017e6fb30?event_id=5e6a3c920058360498110000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Plant-for-the-Planet** [comment]
that was me doing deep link tests

Comment added in Bugsnag by Norbert Schuler
[**TypeError** in **/gift-trees**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e6a3c9249e7650017e6fb30?event_id=5e6a3c920058360498110000&i=gh&m=cm)

**Comment by harshvitra** [comment]
Cannot Replicate this

tried to replicate these events like the user did

<img width="476" alt="Screenshot 2020-03-13 at 12 14 25 AM" src="https://user-images.githubusercontent.com/25605193/76556482-a780f900-64bf-11ea-8c91-7c0fac50ca84.png">

**Comment by norbertschuler** [comment]
<img width="644" alt="Bildschirmfoto 2020-04-02 um 12 59 35" src="https://user-images.githubusercontent.com/1532418/78215504-d64c2700-74e1-11ea-86d6-3b0a7bfe4339.png">

**Comment by norbertschuler** [comment]
Currently the NextArrow does not seem to be visible any more. Maybe this bug will just vanish with https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1908.

**Comment by norbertschuler** [comment]
Outdated
