### ISSUE TITLE
TypeError in /donate-trees - a.data.merge is undefined

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2053]
## Error in Plant-for-the-Planet App

**TypeError** in **/donate-trees**
a.data.merge is undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e6fc0b7ab106f0017e68389?event_id=5e6fc0b70058d88e80350000&i=gh&m=ci)

## Stacktrace

    app/actions/loadTposAction.js:20 - loadProjects/</</<

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e6fc0b7ab106f0017e68389?event_id=5e6fc0b70058d88e80350000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Error resulting from not being able to cope with unexpected results from the API.

**Comment by norbertschuler** [comment]
Outdated
