### ISSUE TITLE
ReferenceError in / - PrepareForElementCapture is not defined

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2054]
## Error in Plant-for-the-Planet App

**ReferenceError** in **/**
PrepareForElementCapture is not defined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e724717d728d400171f4106?event_id=5e7247170058e1b78c010000&i=gh&m=ci)

## Stacktrace

    about:blank:1 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e724717d728d400171f4106?event_id=5e7247170058e1b78c010000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by kradical** [comment]
@norbertschuler Hello! we are seeing this error in some of our web app logs and google leads me here.. Do you know if this is a third party error? Or do you ship a chrome extension and the error could be happening in there?

I am really interested in where this is coming from!

**Comment by norbertschuler** [comment]
@kradical I don’t know what’s causing this bug yet. There is not very much additional information in our bug tracker for this. Just some breadcrumbs showing that we got an error somewhere in our code that’s making one of our dynamically loaded chunks of the JavaScript bundles (we use webpack with code splitting) fail to load:

**Comment by kradical** [comment]
Ahh we have a similar thing happening, this makes me think it is related to webpack chunk loading. I'm going to spend a bit of time today digging into this. I'll update you later. Here is a screenshot from our bug tracker:

<img width="1157" alt="Screen Shot 2020-04-01 at 9 24 33 AM" src="https://user-images.githubusercontent.com/9980985/78155867-3c11b380-73fb-11ea-820f-76d0b12ac973.png">

(some things removed for anonymity, most likely not relevant).

Our websockets failed to connect which means it is most likely someone who has no / poor internet. But we do handle chunk load errors and display an error page.. so I can't help but think it is a webpack bug or something?

**Comment by romainmenke** [comment]
We also see this error and do not have chunk loading enabled. We also do not see any reference of `PrepareForElementCapture` in our bundles so to us looks like an external thing, unrelated to webpack. Could be wrong :/

**Comment by kradical** [comment]
I did a search of our whole project, including prod build and came up with nothing. I also loaded up the site in chrome an searched the "loaded js" in developer tools. Also nothing.

Third part tools we are loading through script tags rather than node_modules:
Rollbar 
stripe
Google places
Intercom
Hub spot
Elevio
Inline manual

Is there any overlap with any of your services? Otherwise I'm pretty lost.

**Comment by romainmenke** [comment]
No overlap

**Comment by nickpell** [comment]
@kradical I have seen the error in the logs for one of my projects today. We are using Intercom.

**Comment by norbertschuler** [comment]
Closing this as not captured any further issues of this.
