### ISSUE TITLE
Issue with PR1792

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#2057]
On web app, loading:
http://localhost:8080/donate-trees for the first time, [try incognito]
only one project shows up.

It activates the project selection, without user selecting it.

https://drive.google.com/file/d/1C2YJsovCK7oaswtbI0nSl7Owpo5dZjsc/view?usp=sharing

I've reverted the merge from develop, and reopened the branch.
This needs to be checked carefully.

**Comment by norbertschuler** [comment]
Sorry, I can not reproduce this error with the current `develop` branch yet.
