### ISSUE TITLE
Add donate button to single project page on the web

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#2059]
Currently the single project page (after https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/2058 got merged) shown in the web client for the shared project url, e.g. "Plant trees with Plant-for-the-Planet at https://test.trilliontreecampaign.org/project/1", does not display a "**donate**" button. We will have to add that in the future, so the user can donate to a project from the single project page.

Compare the discussion in the original pull request here https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1792#issuecomment-598349859

**Comment by norbertschuler** [comment]
After I saw all the issues in #2066 the page https://www.trilliontreecampaign.org/donate-trees/1 still has, I think it also no good idea to use it as a replacement for https://www.trilliontreecampaign.org/project/1, so I would close this PR again.

**Comment by harshvitra** [comment]
Closing issue as we do not support old web
