### ISSUE TITLE
Open other project on single donate project page fails

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#2066]
**Describe the bug**
Empty Page when selecting select different project from a single donation project page.

**Is it on a Production or Development Build?**
production

**To Reproduce**
1. Go to https://www.trilliontreecampaign.org/donate-trees/1
2. Click on 'Select Different Project'
3. See error

**Expected behavior**
Open the project list.

**Screenshots**
<img width="1265" alt="Screen Shot 2020-03-23 at 5 06 35 PM" src="https://user-images.githubusercontent.com/5401575/77337053-adc96d80-6d28-11ea-996d-f49d56fd327b.png">

**Desktop (please complete the following information):**
- OS: MacOS
 - Browser Chrome
 - Plant-for-the-Planet App Version 1.3.1

**Comment by norbertschuler** [comment]
This bug happens as the direct link to one project for donation is a _hack_ and was not intended when the DonationContainer and Donation component had been initially designed. Normally a list of project is shown and a single one can be selected and when the button is pressed, the full list is shown again by clearing out the filter which only shows one project. This does not yet work when we show a single project directly.

**Comment by norbertschuler** [comment]
- [ ] Using the url https://www.trilliontreecampaign.org/donate-trees/1 also does not allow to switch to the full project list by clicking "Donate trees" which changes the url to https://www.trilliontreecampaign.org/donate-trees but does not load the page for new with all the projects.
- [ ] Using the url https://www.trilliontreecampaign.org/donate-trees/1 also does allow the donation process to run correctly due to missing data.

**Comment by harshvitra** [comment]
Closing issue as we do not support old web
