### ISSUE TITLE
undefined is not an object (evaluating 'o.refs.signupForm.getValue')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2078]
## Error in Plant-for-the-Planet App

**TypeError** in **MainActivity**
undefined is not an object (evaluating 'o.refs.signupForm.getValue')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e7c49008c1d1000175b0b66?event_id=5e7c4900005921bf15be0000&i=gh&m=ci)

## Stacktrace

    app/containers/Authentication/ForgotPasswordContainer.js:10 - onPress

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e7c49008c1d1000175b0b66?event_id=5e7c4900005921bf15be0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
This stack trace seems to be wrong, but it's probably about a missing form object.
