### ISSUE TITLE
Error in /donate-trees - No response from window - cleaned up

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2082]
## Error in Plant-for-the-Planet App

**Error** in **/donate-trees**
No response from window - cleaned up

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e7e695c1b92b70018db991c?event_id=5e7e695c00594cd8e7790000&i=gh&m=ci)

## Stacktrace

    node_modules/post-robot/src/clean.js:19 - cleanUpWindow

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e7e695c1b92b70018db991c?event_id=5e7e695c00594cd8e7790000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Outdated
