### ISSUE TITLE
Token refreshToken is missing a parameter

### ISSUE THREAD

**Issue by jmiridis** [Plant-for-the-Planet-org/treecounter-app#2083]
**Describe the bug**

The application does not provide the refresh token in the API call which results in a 400 response status.

![image](https://user-images.githubusercontent.com/1295390/77842395-385e0280-7157-11ea-9928-afaa23e3dbbf.png)

**Comment by niteshgrg** [comment]
@jmiridis Do we have particular steps to reproduce this because in normal case refresh_token is supplied to the api ?

**Comment by norbertschuler** [comment]
Maybe related to https://github.com/Plant-for-the-Planet-org/treecounter-platform/issues/293

**Comment by norbertschuler** [comment]
The issue https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/2203 might help to find out what's wrong with the refreshToken sometimes.

**Comment by norbertschuler** [comment]
@jmiridis I found out that the client expects the API call https://app-development.plant-for-the-planet.org/api/token/refresh?version=v1.1&_locale=de to return a new `refresh_token` next to a new `token` the same as the API call https://app-development.plant-for-the-planet.org/api/login_check - so after the first refresh API call the old refresh token got dismissed and was undefined to the next refresh API call. I wrote a patch to keep the old refresh token in case no new refresh_token is given. But please check if the current behavior of the API call to refresh a token is acting as it should be now.
