### ISSUE TITLE
undefined is not an object (evaluating 'l.refs.EditUserProfileContainer.refs')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2085]
## Error in Plant-for-the-Planet App

**TypeError** in **MainActivity**
undefined is not an object (evaluating 'l.refs.EditUserProfileContainer.refs')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e82503cc2b2ce001736971a?event_id=5e82503c005948ca3c0c0000&i=gh&m=ci)

## Stacktrace

    app/containers/EditUserProfile/index.js:194 - onSave
    app/components/EditUserProfile/index.native.js:265 - onClick
    app/components/Common/Button/PrimaryButton.native.js:15 - onPress

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e82503cc2b2ce001736971a?event_id=5e82503c005948ca3c0c0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Maybe add safety check for `this.refs.EditUserProfileContainer.refs`?

<img width="597" alt="Bildschirmfoto 2020-04-02 um 13 43 18" src="https://user-images.githubusercontent.com/1532418/78218405-ef57d680-74e7-11ea-97c6-85249364a0a3.png">

**Comment by norbertschuler** [comment]
Outdated
