### ISSUE TITLE
undefined is not an object (evaluating 'o.refs.signupForm.getValue')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2089]
## Error in Plant-for-the-Planet App

**TypeError** in **MainActivity**
undefined is not an object (evaluating 'o.refs.signupForm.getValue')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e835cfd98b3cd00186ce8fc?event_id=5e835cfd0059aac5c2b50000&i=gh&m=ci)

## Stacktrace

    app/components/Authentication/SignUp/SignUp.native.js:45 - onSignUpClicked
    app/components/Authentication/SignUp/SignUp.native.js:94 - onClick
    app/components/Common/Button/PrimaryButton.native.js:15 - onPress

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e835cfd98b3cd00186ce8fc?event_id=5e835cfd0059aac5c2b50000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Form object seems to be missing.

**Comment by Plant-for-the-Planet** [comment]
An error linked to this issue has been reopened in Bugsnag
[**TypeError** in **app/components/Authentication/SignUp/SignUp.native.js:45**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e835cfd98b3cd00186ce8fc?event_id=5eb4e8cc005b2e10ee180000&i=gh&m=ra)

**Comment by norbertschuler** [comment]
old version 1.3.2 reopening the issue

**Comment by Plant-for-the-Planet** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**TypeError** in **app/components/Authentication/SignUp/SignUp.native.js:45**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e835cfd98b3cd00186ce8fc?event_id=5eb4e8cc005b2e10ee180000&i=gh&m=fx)
