### ISSUE TITLE
Errornode_modules/axios/lib/core/buildFullPath.js:16 - Network Error

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2090]
## Error in Plant-for-the-Planet App

**Error** in **MainActivity**
Network Error

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e847bc5d39c8d0019b68606?event_id=5e847bc50059a4eff2810000&i=gh&m=ci)

## Stacktrace

    node_modules/axios/lib/core/buildFullPath.js:16 - exports

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e847bc5d39c8d0019b68606?event_id=5e847bc50059a4eff2810000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
network server error

**Comment by Plant-for-the-Planet** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Error** in **node_modules/axios/lib/core/buildFullPath.js:16**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e847bc5d39c8d0019b68606?event_id=5ebbdc77005b2f10a7050000&i=gh&m=ra)

**Comment by norbertschuler** [comment]
network error still not captured

**Comment by Plant-for-the-Planet** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Error** in **node_modules/axios/lib/core/buildFullPath.js:16**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e847bc5d39c8d0019b68606?event_id=5f4a1689005dee85ec270000&i=gh&m=ra)

**Comment by Plant-for-the-Planet** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Error** in **node_modules/axios/lib/core/buildFullPath.js:16**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e847bc5d39c8d0019b68606?event_id=5f4a16f5005e02f53b370000&i=gh&m=fx)
