### ISSUE TITLE
TypeError in /login - null is not an object (evaluating 'y.I.then')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2091]
## Error in Plant-for-the-Planet App

**TypeError** in **/login**
null is not an object (evaluating 'y.I.then')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e848f8e8b30d40017a30204?event_id=5e848f8e0059a40c7f8d0000&i=gh&m=ci)

## Stacktrace

    https://www.gstatic.com/recaptcha/releases/P6KLRNy7h3K160ZmYNUOAce7/recaptcha__pt_br.js:520 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e848f8e8b30d40017a30204?event_id=5e848f8e0059a40c7f8d0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Outdated
