### ISSUE TITLE
window.onerror in /home

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2102]
## Error in Plant-for-the-Planet App

**window.onerror** in **/home**
Syntax error

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e872bba57a9e20017b554a3?event_id=5e872bba0059ab9bb80c0000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/31.0957ddf2ffc7c4d5544d.js:1 - onerror

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e872bba57a9e20017b554a3?event_id=5e872bba0059ab9bb80c0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
This is a file from the former client version not existing any more. I would like to purge index.html on Cloudflare to get rid of this error.
