### ISSUE TITLE
TypeError in /login - null is not an object (evaluating 'D.C.then')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2116]
## Error in Plant-for-the-Planet App

**TypeError** in **/login**
null is not an object (evaluating 'D.C.then')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e87647ff408640018fbefbe?event_id=5e87647f0059b6c4f3570000&i=gh&m=ci)

## Stacktrace

    https://www.gstatic.com/recaptcha/releases/OOKISvkNnVD_m_9dreR_1S0n/recaptcha__de.js:517 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e87647ff408640018fbefbe?event_id=5e87647f0059b6c4f3570000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Outdated
