### ISSUE TITLE
SecurityError in /donate-trees

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2154]
## Error in Plant-for-the-Planet App

**SecurityError** in **/donate-trees**
Blocked a frame with origin "https://www.trilliontreecampaign.org" from accessing a cross-origin frame. Protocols, domains, and ports must match.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e89c71b328a890018f21ad2?event_id=5e89c71b0059b620096d0000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/login:15 - extractFormsAndFormElements_

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e89c71b328a890018f21ad2?event_id=5e89c71b0059b620096d0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Happened only once for one user. Cannot reproduce.
