### ISSUE TITLE
TypeError in app/containers/Authentication/SignUpContainer.js:35 - u is not a function. (In 'u()', 'u' is undefined)

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2155]
## Error in Plant-for-the-Planet App

**TypeError** in **app/containers/Authentication/SignUpContainer.js:35**
u is not a function. (In 'u()', 'u' is undefined)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e8a07f546407600175f6565?event_id=5e8a07f50059a237934b0000&i=gh&m=ci)

## Stacktrace

    app/containers/Authentication/SignUpContainer.js:35 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e8a07f546407600175f6565?event_id=5e8a07f50059a237934b0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Outdated
