### ISSUE TITLE
TypeError in /login - window.grecaptcha.execute is not a function

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2157]
## Error in Plant-for-the-Planet App

**TypeError** in **/login**
window.grecaptcha.execute is not a function

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e8aed9855af540018a68659?event_id=5e8aed9800599613c78b0000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/27.4fb8d652b5daf11a62d8.js:1 - value

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e8aed9855af540018a68659?event_id=5e8aed9800599613c78b0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Outdated
