### ISSUE TITLE
Optimize release process

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#2165]
While copying the newly build web client from the CircleCI deployment server to the DF server, the website is showing an internal server error. This must be optimized, e.g. copying the files to the server and then swapping them against the old files to avoid a time where files are missing on the server:

<img width="682" alt="Bildschirmfoto 2020-04-07 um 21 23 51" src="https://user-images.githubusercontent.com/1532418/78681122-8670c400-7916-11ea-99ab-e00a7f31dfae.png">

An adaption to the CircleCI deployment scripts should be able to do this.

**Comment by sagararyal** [comment]
@norbertschuler buddy.works has a workflow for Atomic deployment that works with SSH should we try that?

**Comment by norbertschuler** [comment]
I think I made some nice change where in the end only a folder gets renamed.

**Comment by norbertschuler** [comment]
https://github.com/Plant-for-the-Planet-org/treecounter-app/commit/b9262776cf5f7d831c16ccd62117064e9856d15d
