### ISSUE TITLE
Gift Message is not being sent in Emails

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#2190]
This is an issue on either Backend or Email Template and needs to be looked thoroughly.

Both Web and Mobile apps send the Gift Message in API when creating the donation.

**Comment by norbertschuler** [comment]
These are gift related templates on the production backends - which template do your refer to?

<img width="1348" alt="Bildschirmfoto 2020-04-08 um 21 27 48" src="https://user-images.githubusercontent.com/1532418/78796008-f434f280-79df-11ea-96eb-034c2ac84293.png">
<img width="1353" alt="Bildschirmfoto 2020-04-08 um 21 27 27" src="https://user-images.githubusercontent.com/1532418/78796018-f8611000-79df-11ea-8938-9ea758abe800.png">
