### ISSUE TITLE
NS_ERROR_FILE_CORRUPTED in /

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2193]
## Error in Plant-for-the-Planet App

**NS_ERROR_FILE_CORRUPTED** in **/**
[no error message]

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e8e0a49d7340c00182e408c?event_id=5e8e0a490059b4919c470000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/bundle.0a248b0f93ca8877f26b.js:1 - saveItem

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e8e0a49d7340c00182e408c?event_id=5e8e0a490059b4919c470000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
https://stackoverflow.com/questions/18877643/error-in-local-storage-ns-error-file-corrupted-firefox
