### ISSUE TITLE
TypeError in app/utils/getRandomImage.js:15 - null is not an object (evaluating 't.name.charAt')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2194]
## Error in Plant-for-the-Planet App

**TypeError** in **app/utils/getRandomImage.js:15**
null is not an object (evaluating 't.name.charAt')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e8f36bb4786d70018e7182e?event_id=5e8f36bb0059935bd6760000&i=gh&m=ci)

## Stacktrace

    app/utils/getRandomImage.js:15 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e8f36bb4786d70018e7182e?event_id=5e8f36bb0059935bd6760000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Bug is caused in Leaderboard this way:

[RPReplay_Final1586570950.zip](https://github.com/Plant-for-the-Planet-org/treecounter-app/files/4463911/RPReplay_Final1586570950.zip)

**Comment by norbertschuler** [comment]
@haideralishah can you have a look. See my zipped video above on how this error is happening in the app.

**Comment by norbertschuler** [comment]
I fixed this myself. Looks like a company with an empty or non existent name registered causing massive app crashes for other users looking at the leaderboard.
