### ISSUE TITLE
SIGABRT in _mh_execute_header

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2195]
## Error in Plant-for-the-Planet App

**SIGABRT** in **_mh_execute_header**

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e8f774bcdfd380017f5c774?event_id=5e8f774b0059a266ef730000&i=gh&m=ci)

## Stacktrace

    TreecounterApp:0 - _mh_execute_header

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e8f774bcdfd380017f5c774?event_id=5e8f774b0059a266ef730000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Cannot read due to missing Dsym
