### ISSUE TITLE
Show bigger image of donation projects pictures

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#2201]
**Describe the feature you'd like to see included in Plant-for-the-Planet App.**
Currently you cannot view bigger versions of the images displayed for a project.

**What are the use cases for this feature?**
We list images for donation projects, but the user can not click on them to view a bigger version. 

<img width="1680" alt="Bildschirmfoto 2020-04-13 um 13 04 00" src="https://user-images.githubusercontent.com/1532418/79096562-bccf9880-7d87-11ea-912d-52799f428ac3.png">

**Comment by harshvitra** [comment]
Closing issue as we do not support old web
