### ISSUE TITLE
TypeError in app/actions/loadTposAction.js:33 - undefined is not an object (evaluating 'c.data.merge.plantProjectPager')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2202]
## Error in Plant-for-the-Planet App

**TypeError** in **app/actions/loadTposAction.js:33**
undefined is not an object (evaluating 'c.data.merge.plantProjectPager')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e94b15c263e720017319d30?event_id=5e94b15c0059a30c8c590000&i=gh&m=ci)

## Stacktrace

    app/actions/loadTposAction.js:33 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e94b15c263e720017319d30?event_id=5e94b15c0059a30c8c590000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
App is not able to deal with unexpected results from API request.

**Comment by norbertschuler** [comment]
Duplicate of #2418
