### ISSUE TITLE
TypeError in app/components/Common/CurrencySelectorList.native.js:54 - undefined is not an object (evaluating 'Object.keys(this.props.currencies.currencies.currency_names)')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2204]
## Error in Plant-for-the-Planet App

**TypeError** in **app/components/Common/CurrencySelectorList.native.js:54**
undefined is not an object (evaluating 'Object.keys(this.props.currencies.currencies.currency_names)')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e9889127db96800185ddc11?event_id=5e9889120059ea5598130000&i=gh&m=ci)

## Stacktrace

    app/components/Common/CurrencySelectorList.native.js:54 - value
    app/components/Common/CurrencySelectorList.native.js:162 - value
    app/actions/currencies.js:21 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e9889127db96800185ddc11?event_id=5e9889120059ea5598130000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Maybe happening if API returns an unexpected results. Should use some safety checks.

**Comment by norbertschuler** [comment]
Hopefully fixes with next release.
