### ISSUE TITLE
Error in /manage-plant-projects - invalid argument

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2207]
## Error in Plant-for-the-Planet App

**Error** in **/manage-plant-projects**
Ungültiges Argument.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e99a880dfc5d70018345c0c?event_id=5e99a8800059e2d482200000&i=gh&m=ci)

## Stacktrace

    app/components/ManageProjects/index.js:64 - onDragStart

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e99a880dfc5d70018345c0c?event_id=5e99a8800059e2d482200000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
<img width="561" alt="Bildschirmfoto 2020-04-17 um 20 34 56" src="https://user-images.githubusercontent.com/1532418/79574827-f50a0a80-80ea-11ea-8348-96c725fdbf01.png">

**Comment by norbertschuler** [comment]
Web client is abandoned.
