### ISSUE TITLE
Uploading images for registered trees is broken

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#2210]
**Describe the bug**
Uploading an image for registered trees does not work anymore either when adding new trees or when editing existing trees.

**Is it on a Production or Development Build?**
production

**To Reproduce**
1. Go to 'Register tree' or 'My forest'->'Update'
2. Choose an image
3. See error

**Expected behavior**
Upload new images.

**What actually happens**
The form is submitted, but the image is not updated.

**Desktop (please complete the following information):**
- OS: latest MacOS
 - Browser latest Chrome
 - Plant-for-the-Planet App Version 1.3.2

**Comment by jmiridis** [comment]
I have tried to upload an image and got a 500 error. There was an error in the code that I have hot-fixed.
Then I tried again and this time the update was successful but no image was created.
Looking into the request there is no image data.

![image](https://user-images.githubusercontent.com/1295390/79679305-6ec4f580-81ca-11ea-8be5-4dc4258a8bd5.png)
