### ISSUE TITLE
TPO can try to register trees without a project

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#2214]
**Describe the bug**
Currently a TPO can use the function to register trees before he added a project. The backend is prohibiting this by throwing an error, but unfortunately only the “Validation Failed” error message is displayed to the user.

<img width="1680" alt="Bildschirmfoto 2020-04-18 um 16 08 56" src="https://user-images.githubusercontent.com/1532418/79686022-5eaf2380-8267-11ea-8556-d69fdecfc13e.png">

The usage of the registration function should be prohibited if not project was added (just like the native app is doing it).

**Is it on a Production or Development Build?**
production and develop

**To Reproduce**
1. Go to 'Register tree'
2. Fill the form and register
3. See error

**Expected behavior**
Do not be allowed to register trees without a project.

**Desktop (please complete the following information):**
- OS: latest MacOS
 - Browser: latest Chrome
 - Plant-for-the-Planet App Version 1.3.2

**Comment by harshvitra** [comment]
Closing issue as we do not support old web
