### ISSUE TITLE
Enable Portuguese (Brazil) Translation in App and Backend

### ISSUE THREAD

**Issue by Chiagozie-Udeh** [Plant-for-the-Planet-org/treecounter-app#2215]
**Enable Portuguese (Brazil) Translation in App and Backend.**
*I had recently given Flavia access to translate into Portuguese and added the Portuguese (Brazil) which she translated to*

**What are the use cases for this feature?**
*Translate the App to Portuguese for our Portuguese speaking users etc.*

**Examples of this feature or functionality.**
*We just had the Spanish translation done and it looks good too*

**Comment by norbertschuler** [comment]
The release of the Spanish version got stuck as there are some issues not yet solved (needs some decisions and actions to be done): https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/2074

I would like to add another language only if 99% done as we cannot disable it when we want to do a release and unfinished language would block the release.
