### ISSUE TITLE
undefined is not an object (evaluating 'u.refs.targetContainer.refs')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2216]
## Error in Plant-for-the-Planet App

**TypeError** in **MainActivity**
undefined is not an object (evaluating 'u.refs.targetContainer.refs')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e9daf73e77d2200199794fa?event_id=5e9daf73005a22aec2620000&i=gh&m=ci)

## Stacktrace

    app/containers/TargetContainer/index.js:23 - onSubmitTarget
    app/components/Common/Button/PrimaryButton.native.js:15 - onPress

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e9daf73e77d2200199794fa?event_id=5e9daf73005a22aec2620000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Again a problem to access a form by using `refs`:

<img width="572" alt="Bildschirmfoto 2020-04-20 um 21 48 53" src="https://user-images.githubusercontent.com/1532418/79765396-c55c3c00-8350-11ea-9b92-9fa31bf68709.png">
