### ISSUE TITLE
Error in / - Minified React error #327;

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2221]
## Error in Plant-for-the-Planet App

**Error** in **/**
Minified React error #327; visit https://reactjs.org/docs/error-decoder.html?invariant=327 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ea03b9352ca1d00173d65ab?event_id=5ea03b93005a66a2cadd0000&i=gh&m=ci)

## Stacktrace

    index.web.js:2 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ea03b9352ca1d00173d65ab?event_id=5ea03b93005a66a2cadd0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Request from https://app.plant-for-the-planet.org/
