### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException in :com.google.android.gms.dynamite_mapsdynamite@201515062@20.15.15 (100304-0):9

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2227]
## Error in Plant-for-the-Planet App

**java.lang.ArrayIndexOutOfBoundsException** in **:com.google.android.gms.dynamite_mapsdynamite@201515062@20.15.15 (100304-0):9**
length=1; index=12

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ea1f0e1b9f8400017059cf5?event_id=5ea1f0e1005a77f1091c0000&i=gh&m=ci)

## Stacktrace

    :com.google.android.gms.dynamite_mapsdynamite@201515062@20.15.15 (100304-0):9 - com.google.maps.api.android.lib6.gmm6.vector.ct.<init>

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ea1f0e1b9f8400017059cf5?event_id=5ea1f0e1005a77f1091c0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by saiskee** [comment]
https://issuetracker.google.com/issues/154820090

**Comment by Eramirez06** [comment]
did you find workaround this?

**Comment by norbertschuler** [comment]
We have not yet done anything about this bug in this project. Better follow the linked issue above.

**Comment by saiskee** [comment]
I believe that the issue has been resolved by the google team. You shouldn't be getting this error anymore.

**Comment by norbertschuler** [comment]
Thanks. I will close this issue then.
