### ISSUE TITLE
EXC_BAD_ACCESS in ___CFBasicHashDrain

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2228]
## Error in Plant-for-the-Planet App

**EXC_BAD_ACCESS** in **___CFBasicHashDrain**
Attempted to dereference garbage pointer 0x141a80020.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ea1f54d37ba4d0017b96fac?event_id=5ea1f54d005a6bbe10cf0000&i=gh&m=ci)

## Stacktrace

    /usr/lib/libobjc.A.dylib:0 - _objc_release

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ea1f54d37ba4d0017b96fac?event_id=5ea1f54d005a6bbe10cf0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
do not fix native bugs yet
