### ISSUE TITLE
EXC_BREAKPOINT in gmscore::renderer::Behavior::HasHigherPriority(gmscore::base::reffed_ptr<gmscore::renderer::Behavior> const&, gmscore::base::reffed_ptr<gmscore::renderer::Behavior> const&)

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2229]
## Error in Plant-for-the-Planet App

**EXC_BREAKPOINT** in **gmscore::renderer::Behavior::HasHigherPriority(gmscore::base::reffed_ptr<gmscore::renderer::Behavior> const&, gmscore::base::reffed_ptr<gmscore::renderer::Behavior> const&)**

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ea1f986c09df500188fd907?event_id=5ea1f986005a79a429e50000&i=gh&m=ci)

## Stacktrace

    TreecounterApp:0 - gmscore::renderer::Behavior::HasHigherPriority(gmscore::base::reffed_ptr<gmscore::renderer::Behavior> const&, gmscore::base::reffed_ptr<gmscore::renderer::Behavior> const&)
    TreecounterApp:0 - gmscore::renderer::Behavior::HasHigherPriority(gmscore::base::reffed_ptr<gmscore::renderer::Behavior> const&, gmscore::base::reffed_ptr<gmscore::renderer::Behavior> const&)
    TreecounterApp:0 - void gmscore::renderer::RenderBin::PerformDraw<std::__1::__list_iterator<gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity>, void*> >(std::__1::__list_iterator<gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity>, void*>, std::__1::__list_iterator<gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity>, void*>, gmscore::renderer::EntityRenderer*, bool)
    TreecounterApp:0 - gmscore::renderer::ProxySortedRenderBin<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> >, std::__1::less<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> > > >::RemoveEntity(gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&)
    TreecounterApp:0 - gmscore::renderer::ProxySortedRenderBin<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> >, std::__1::less<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> > > >::RemoveEntity(gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&)
    TreecounterApp:0 - gmscore::renderer::ProxySortedRenderBin<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> >, std::__1::less<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> > > >::OrderingWrapper(gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&, gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&)
    TreecounterApp:0 - gmscore::renderer::ProxySortedRenderBin<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> >, std::__1::less<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> > > >::OrderingWrapper(gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&, gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&)
    TreecounterApp:0 - facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)
    TreecounterApp:0 - facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)
    TreecounterApp:0 - facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)
    TreecounterApp:0 - facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)
    TreecounterApp:0 - _mh_execute_header

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ea1f986c09df500188fd907?event_id=5ea1f986005a79a429e50000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
do not fix native bugs yet
