### ISSUE TITLE
EXC_BAD_ACCESS in gmscore::renderer::ProxySortedRenderBin<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> >, std::__1::less<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> > > >::OrderingWrapper(gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&, gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&)

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2230]
## Error in Plant-for-the-Planet App

**EXC_BAD_ACCESS** in **gmscore::renderer::ProxySortedRenderBin<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> >, std::__1::less<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> > > >::OrderingWrapper(gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&, gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&)**
Attempted to dereference garbage pointer 0x241a80000.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ea1fc07853a600017a7a571?event_id=5ea1fc07005a8865d3770000&i=gh&m=ci)

## Stacktrace

    TreecounterApp:0 - gmscore::renderer::ProxySortedRenderBin<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> >, std::__1::less<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> > > >::OrderingWrapper(gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&, gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&)
    TreecounterApp:0 - gmscore::renderer::ProxySortedRenderBin<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> >, std::__1::less<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> > > >::OrderingWrapper(gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&, gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&)
    TreecounterApp:0 - gmscore::renderer::ProxySortedRenderBin<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> >, std::__1::less<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> > > >::OrderingWrapper(gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&, gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&)
    TreecounterApp:0 - gmscore::renderer::ProxySortedRenderBin<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> >, std::__1::less<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> > > >::OrderingWrapper(gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&, gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&)
    TreecounterApp:0 - gmscore::renderer::ProxySortedRenderBin<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> >, std::__1::less<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> > > >::OrderingWrapper(gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&, gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&)
    TreecounterApp:0 - gmscore::renderer::ProxySortedRenderBin<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> >, std::__1::less<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> > > >::OrderingWrapper(gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&, gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&)
    TreecounterApp:0 - gmscore::renderer::ProxySortedRenderBin<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> >, std::__1::less<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> > > >::OrderingWrapper(gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&, gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&)
    TreecounterApp:0 - gmscore::renderer::ProxySortedRenderBin<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> >, std::__1::less<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> > > >::OrderingWrapper(gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&, gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&)
    TreecounterApp:0 - gmscore::renderer::ProxySortedRenderBin<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> >, std::__1::less<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> > > >::OrderingWrapper(gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&, gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&)
    TreecounterApp:0 - gmscore::renderer::ProxySortedRenderBin<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> >, std::__1::less<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> > > >::OrderingWrapper(gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&, gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&)
    TreecounterApp:0 - gmscore::renderer::ProxySortedRenderBin<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> >, std::__1::less<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> > > >::OrderingWrapper(gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&, gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&)
    TreecounterApp:0 - gmscore::renderer::ProxySortedRenderBin<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> >, std::__1::less<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> > > >::OrderingWrapper(gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&, gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&)
    TreecounterApp:0 - gmscore::renderer::ProxySortedRenderBin<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> >, std::__1::less<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> > > >::OrderingWrapper(gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&, gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&)
    TreecounterApp:0 - gmscore::renderer::ProxySortedRenderBin<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> >, std::__1::less<std::__1::tuple<unsigned int, unsigned long, unsigned int, gmscore::base::reffed_ptr<gmscore::renderer::Entity> > > >::OrderingWrapper(gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&, gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity> const&)

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ea1fc07853a600017a7a571?event_id=5ea1fc07005a8865d3770000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
do not fix native bugs yet
