### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2233]
## Error in Plant-for-the-Planet App

**java.lang.ArrayIndexOutOfBoundsException** in **MainActivity**
length=1; index=12

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ea206e5274ff80017c2723f?event_id=5ea206e5005a84bbef2d0000&i=gh&m=ci)

## Stacktrace

    :com.google.android.gms.dynamite_mapsdynamite@201216067@20.12.16 (100408-0):9 - com.google.maps.api.android.lib6.gmm6.vector.ct.<init>

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ea206e5274ff80017c2723f?event_id=5ea206e5005a84bbef2d0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by soshial** [comment]
https://www.reddit.com/r/androiddev/comments/g6t8fu/google_maps_sdk_error_started_popping_on_last_hour/

**Comment by norbertschuler** [comment]
cannot reproduce
