### ISSUE TITLE
Error in /donate-trees - No response from window - cleaned up

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2234]
## Error in Plant-for-the-Planet App

**Error** in **/donate-trees**
No response from window - cleaned up

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ea21402d4351c00189764f5?event_id=5ea21402005a84ce92fd0000&i=gh&m=ci)

## Stacktrace

    https://www.paypalobjects.com/api/checkout.js:5543 - cleanUpWindow

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ea21402d4351c00189764f5?event_id=5ea21402005a84ce92fd0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Duplicate of #1943

**Comment by Plant-for-the-Planet** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Error** in **/donate-trees**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ea21402d4351c00189764f5?event_id=5f0cf78e005b769e03260000&i=gh&m=ra)

**Comment by norbertschuler** [comment]
Duplicate of #1943
