### ISSUE TITLE
User contribution: project data of newly registered tree not displayed

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#2236]
**Describe the bug**
When you register a new tree or multiple trees for a TPO the related project is not shown if you look at the user contribution details - you have to reload the app in order to see the data being displayed:

![Simulator Screen Shot - iPhone 11 - 2020-04-24 at 17 55 33](https://user-images.githubusercontent.com/1532418/80206395-69e2c480-8656-11ea-9436-edcadf68eee4.png)

**Is it on a Production or Development Build?**
develop

**To Reproduce**
1. Go to 'Me' screen
2. Register a new tree for as a TPO
3. Open the new user contribution to view the details

**Smartphone (please complete the following information):**
- Device: iPhoneX simulator
 - OS: 13.4.x
 - Plant-for-the-Planet App Version 1.3.2

**Comment by norbertschuler** [comment]
This probably happens as in the result of the API call PUT https://development.trilliontreecampaign.org/api/v1.3/en/plantContributions/single-tree
we are not getting `planProjectId` in the `merge` object:

![image](https://user-images.githubusercontent.com/1532418/80338589-de9c4580-8886-11ea-8081-4b3e08c33eda.png)

**Comment by jmiridis** [comment]
I have added it to development system. Please confirm.

**Comment by norbertschuler** [comment]
This issue got fixed by a backend change: https://github.com/Plant-for-the-Planet-org/treecounter-platform/commit/14c63fb4fd2dcfc54342d5bfa6ad12a4e2053972
