### ISSUE TITLE
Measurement of tree height differs between web and native app

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#2239]
**Describe the bug**
In the native app, the tree height is entered in meter and displayed in meters. In the web client the form to enter the values does not say anything about the units and displays the entered values as if the height was entered in centi meter.
And sometimes the measurement is not shown at all despite it exists. Probably the web client is broken for registration of trees and displaying them and need some refactoring quickly to avoid data corruption.

Web client:

<img width="619" alt="Bildschirmfoto 2020-04-24 um 20 52 07" src="https://user-images.githubusercontent.com/1532418/80220342-dc12d380-866d-11ea-9710-8581f8229233.png">

Native apps:

![Simulator Screen Shot - iPhone 11 - 2020-04-24 at 20 51 37](https://user-images.githubusercontent.com/1532418/80220366-e46b0e80-866d-11ea-85c4-d93914ae8ff9.png)

**Comment by harshvitra** [comment]
@norbertschuler can you please share if this is on Production or Develop ?

**Comment by norbertschuler** [comment]
> @norbertschuler can you please share if this is on Production or Develop ?

This is on production and develop.

**Comment by norbertschuler** [comment]
@jmiridis Can you help me to find out how much of the data in production is storing height of registered trees (measurements) in meter and how often it got stored in centimeter? I think we would just have to test how much rows with a height above 40 exists. (I would expect no self-planted tree registered by our users is already above 40 meters and we could cross-check with the diameter.)
