### ISSUE TITLE
EXC_BAD_ACCESS in _mh_execute_header

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2242]
## Error in Plant-for-the-Planet App

**EXC_BAD_ACCESS** in **_mh_execute_header**
Attempted to dereference garbage pointer 0x241a80000.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ea35b61ca4b670017dd714b?event_id=5ea35b61005ab1e17bc30000&i=gh&m=ci)

## Stacktrace

    TreecounterApp:0 - _mh_execute_header

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ea35b61ca4b670017dd714b?event_id=5ea35b61005ab1e17bc30000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
do not fix native bugs yet
