### ISSUE TITLE
Future end date for competitions not accepted

### ISSUE THREAD

**Issue by Kodde2011** [Plant-for-the-Planet-org/treecounter-app#2245]
The app don't accept an end date in future in creating a challenge.

**Comment by sagararyal** [comment]
@Kodde2011 could you share more information like what did did you try to enter? 
iOS or Android?

You can also share your username to support@plant-for-the-planet.org and we can check what went wrong.

**Comment by Kodde2011** [comment]
I tried on both, iOs and Android to create/edit a competition. On both systems the calender opens to choose the enddate. At iOs the three wheels to choose date. When i choose "Ok" the date shown under enddate is the current date and not the date i chose seconds before.

**Comment by Kodde2011** [comment]
![Screenshot_20200425_230310_org pftp](https://user-images.githubusercontent.com/58151492/80290889-04bbcb80-8749-11ea-94d3-f109fb5f34cd.jpg)
![Screenshot_20200425_230305_org pftp](https://user-images.githubusercontent.com/58151492/80290891-05ecf880-8749-11ea-8f24-8ed232d3134d.jpg)

**Comment by Kodde2011** [comment]
This is for Android
