### ISSUE TITLE
Competition can not be edited loading for the first time

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#2251]
**Describe the bug**
When you try to edit a competition for the first time, all the first stay empty. When you cancel the edit dialog and try again, the existing values are shown and you can edit them.

Update: This bug only happens if try to edit the competition from the edit buttom in a list. If you open it before and then edit it, the bug does not happen.

**Is it on a Production or Development Build?**
develop

**To Reproduce**
1. Go to 'Competition' and edit one of your own competitions
2. See error

**Screenshots**
![Simulator Screen Shot - iPhone 11 - 2020-04-28 at 11 50 24](https://user-images.githubusercontent.com/1532418/80448593-fe933e00-8946-11ea-8a01-23b8fa18b7b7.png)

**Smartphone (please complete the following information):**
- Device: iPhone 11 simulator
 - OS: iOS 13.4.x
 - Plant-for-the-Planet App Version 1.3.2

**Comment by norbertschuler** [comment]
I would assume the problem is that `EditCompetition` is programmed as a function in https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/95cf124bc6f4d705e39794b552b9a8fdd26466a6/app/components/Competition/EditCompetition.native.js#L13 instead of a `React.Component` and the async loading of the competition at https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/95cf124bc6f4d705e39794b552b9a8fdd26466a6/app/components/Competition/EditCompetition.native.js#L37 is not quick enough to get the results in https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/95cf124bc6f4d705e39794b552b9a8fdd26466a6/app/components/Competition/EditCompetition.native.js#L46-L49.

`EditCompetition` could be rewritten as a component to solve this.

**Comment by harshvitra** [comment]
@norbertschuler there was an easy way around - used props.competitionDetails instead of formValue to load the values.
