### ISSUE TITLE
window.onerror in / - ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2253]
## Error in Plant-for-the-Planet App

**window.onerror** in **/**
ResizeObserver loop limit exceeded

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ea845fc2d38600017b3e63a?event_id=5ea845fc005b3d8aa4e30000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/:0 - onerror

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ea845fc2d38600017b3e63a?event_id=5ea845fc005b3d8aa4e30000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded
