### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2254]
## Error in Plant-for-the-Planet App

**java.lang.ArrayIndexOutOfBoundsException** in **MainActivity**
length=1; index=12

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ea8878d5ec2fc00179cd05b?event_id=5ea8878d005b25f6bb280000&i=gh&m=ci)

## Stacktrace

    :com.google.android.gms.dynamite_mapsdynamite@201216081@20.12.16 (120400-0):9 - com.google.maps.api.android.lib6.gmm6.vector.ct.<init>

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ea8878d5ec2fc00179cd05b?event_id=5ea8878d005b25f6bb280000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Duplicate of #2227
