### ISSUE TITLE
Help Desk icon hides Privacy Terms icon

### ISSUE THREAD

**Issue by enoralecuyer** [Plant-for-the-Planet-org/treecounter-app#2255]
**Describe the bug**
The question mark icon of the help desk hides the privacy terms when I am about to login (bottom right corner).

**Is it on a Production or Development Build?**
Production.

**To Reproduce**
1. Go to https://www.trilliontreecampaign.org/ without being logged in.
2. Click on 'Set Target' or 'Register Tree'
3. See error on the bottom right corner.

**Expected behavior**
I expected to only see the Help Desk, and not necessary a button to link to privacy terms.

**What actually happens**
The question mark icon of the help desk was on top of the privacy terms

**Screenshots**
![privacyterms](https://user-images.githubusercontent.com/48727972/80530531-00accb00-894e-11ea-8bca-1f3afc6e19a4.png)

**Desktop (please complete the following information):**
- OS: Windows 10
 - Browser: Firefox
 - Plant-for-the-Planet App Version. live

**Comment by norbertschuler** [comment]
This help icon is added by Cloudflare injecting code dynamically. It’s not part of our own source code. I think @sagararyal added it for a Jira integration.

**Comment by enoralecuyer** [comment]
In this case, should we off-center the privacy terms icon?

**Comment by sagararyal** [comment]
@norbertschuler @enoralecuyer 
I'd postpone/cancel this task, as we won't be using ReCaptcha in future. (The privacy and terms there is from Google ReCaptcha)

As we are planning to move authentication with Auth0, the login page here will be completely redesigned.

**Comment by harshvitra** [comment]
Closing issue as we do not support old web
