### ISSUE TITLE
The 4th tab of a project on the 'donate trees' page doesn't work

### ISSUE THREAD

**Issue by enoralecuyer** [Plant-for-the-Planet-org/treecounter-app#2257]
**Describe the bug**
When I click on the 4th tab/circle under the title of a project, it appears blank for 2 seconds, then redirects me to the 3rd tab/circle, which is the donor details.

**Is it on a Production or Development Build?**
Production

**To Reproduce**

1. Go to https://www.trilliontreecampaign.org/donate-trees (without being logged in)
2. Click on the button 'donate trees'
3. Under the 'project' title, click on the 4rd circle.
4. See error with a blank page, before being automatically redirected to 3rd tab/circle.

**Expected behavior**
I expected to see more information about the project, or to not see a 4rd tab/circle.

**What actually happens**
The page appears blank for 2 seconds, then redirect me to the 3rd tab/circle, which is the donor details.

**Screenshots**
![donatetrees](https://user-images.githubusercontent.com/48727972/80532790-82522800-8951-11ea-957e-64bd534e2f46.png)

**Desktop (please complete the following information):**
- OS: Windows 10
 - Browser: Firefox
 - Plant-for-the-Planet App Version: live

**Additional context**
I was not logged in.

**Comment by sagararyal** [comment]
Todo:

- [ ] Disable clicking on the circles, as it seems to be misleading.

Context:
The fourth page in this case gets only populated after a donation is created from the backend. So the user shouldn't be able to reach there without entering the donation details.

**Comment by mahmed0715** [comment]
on it.
