### ISSUE TITLE
Accessibility - Hovering over 'View More' doesn't change cursor to type pointer.

### ISSUE THREAD

**Issue by enoralecuyer** [Plant-for-the-Planet-org/treecounter-app#2258]
**Describe the feature you'd like to see included in Plant-for-the-Planet App.**
When I want to see more photos of a project, I click on 'View More', but the cursor doesn't change to a type pointer. 

**What are the use cases for this feature?**
Increase accessibility and a better experience for the end user. 

**To Reproduce**
1. Go to https://www.trilliontreecampaign.org/donate-trees
2. Scroll down and click on '++see more'
3. Attempt to click on View More, next to the existing photos
4. See the issue

**Screenshot**
![hoverimages](https://user-images.githubusercontent.com/48727972/80533433-774bc780-8952-11ea-8fe5-6bd099b91c2d.png)

**Comment by harshvitra** [comment]
Closing issue as we do not support old web
