### ISSUE TITLE
Hovering over the categories of the 'Explore' page doesn't change cursor type to pointer

### ISSUE THREAD

**Issue by enoralecuyer** [Plant-for-the-Planet-org/treecounter-app#2259]
**Describe the feature you'd like to see included in Plant-for-the-Planet App.**
When I explore the different categories of the 'Explore' page, I click on 'Countries', 'Organizations', but the cursor doesn't change to a type pointer, which makes it difficult to understand that those icons are clickable and contain more information.

**What are the use cases for this feature?**
Increase accessibility and a better experience for the end user.

**To Reproduce**

1. Go to https://www.trilliontreecampaign.org/explore
2. Click on the 'Leaderboard' tab
3. Click on one of the icons 'Education', 'Companies'...
4. See the issue

**Screenshot**
![explore](https://user-images.githubusercontent.com/48727972/80534973-e9bda700-8954-11ea-8ecb-bc72b3077ca7.png)

**Comment by harshvitra** [comment]
Closing issue as we do not support old web
