### ISSUE TITLE
Could not allocate java pixel ref.

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2262]
## Error in Plant-for-the-Planet App

**java.lang.RuntimeException** in **MainActivity**
Could not allocate java pixel ref.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ea9e10aa3be6200172fcc63?event_id=5ea9e10a005b3ec7ac2a0000&i=gh&m=ci)

## Stacktrace

    Bitmap.java:-2 - android.graphics.Bitmap.nativeCreateFromParcel

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ea9e10aa3be6200172fcc63?event_id=5ea9e10a005b3ec7ac2a0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
do not fix native bugs yet
