### ISSUE TITLE
Upload APK and IPA to Browserstack

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#2263]
We can upload the apk and ipa generated by Github Actions to browserstack.

Please find the details below:

https://www.browserstack.com/app-live/rest-api

This might help speed the test process as we can simply use BrowserStack to test it.

**Comment by norbertschuler** [comment]
Solved by https://github.com/Plant-for-the-Planet-org/treecounter-app/commit/1e7bfbdee0b74846ffd3772bce475ff53a4acc21
