### ISSUE TITLE
Feature Improvements to Competitions

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#2264]
- [x] If a user `is a participant` of the competition remove Support Button in the Competition List
![Screen Shot 2020-04-30 at 12 08 17 PM](https://user-images.githubusercontent.com/5401575/80698858-5793db00-8adb-11ea-8a77-4475abdee2df.png)

- [x] Add a card under Join/ Edit/ Leave button:

![Screen Shot 2020-04-30 at 12 13 32 PM](https://user-images.githubusercontent.com/5401575/80699577-7e9edc80-8adc-11ea-8a14-3e03970efac8.png)

Text alt:
_If Register Only:_ 
Please plant a tree yourself and register them to support this competition
Button: Register Trees

_If Donation Only:_
Please choose from 100+ projects and make a donation to support this competition.
Button: Donate Now

_If Specific Project:_
Donate to _Eden Reforestation Project_ to support this competition.
Button: Donate Now

_If all:_
Plant a tree or choose from 100+ projects and make a donation to support this competition.
Button: Donate Now

**Comment by harshvitra** [comment]
> _If Register Only:_
> Please plant a tree yourself and register them to support this competition
> Button: Register Trees
> 
> _If Donation Only:_
> Please choose from 100+ projects and make a donation to support this competition.
> Button: Donate Now
> 
> _If Specific Project:_
> This competition supports _Eden Reforestation Project_ in Kenya
> Button: Donate Now

@sagararyal 
These 3 conditions which you have mentioned, how do we get these ? 
Also how are we going to link the donated and registered trees to the competition ? 

If the user has joined the competition, we can link all his donated and registered trees to the competition

If not then what do we do ? Automatically join the user to the competition ? 
OR maybe show this card only if user has joined the competition

**Comment by sagararyal** [comment]
@harshvitra `filtertype` field is available in the api
 "filterType": "donations",
  "filterType": "all",
  "filterType": "registered",


Please confirm with @jmiridis if specific project Id is available

**Comment by harshvitra** [comment]
> @harshvitra `filtertype` field is available in the api
> "filterType": "donations",
> "filterType": "all",
> "filterType": "registered",
> 
> Please confirm with @jmiridis if specific project Id is available

@jmiridis can you help here ? I can see filterType = all

**Comment by harshvitra** [comment]
<img width="349" alt="Screenshot 2020-05-03 at 1 58 23 AM" src="https://user-images.githubusercontent.com/25605193/80891434-96937d80-8ce1-11ea-9852-b9984c6d2058.png">

@sagararyal we have these
