### ISSUE TITLE
RCTFatalException: Exception '-[NSNull length]: unrecognized selector sent to instance 0x1c84afad8'

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2266]
## Error in Plant-for-the-Planet App

**RCTFatalException: Exception '-[NSNull length]: unrecognized selector sent to instance 0x1c84afad8' was thrown while invoking multiSet on target AsyncLocalStorage with params (         (                 (             "refresh_token",             "<null>"         )     ),     97 ) callstack: ( 	0   CoreFoundation                      0x0000000187fb8604 409609CD-8410-38E1-BA5D-BDED609D2018 + 1222148 	1   libobjc.A.dylib                     0x0000000187cdabcc objc_exception_throw + 56 	2   CoreF...** in **facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)**
Exception '-[NSNull length]: unrecognized selector sent to instance 0x1c84afad8' was thrown while invoking multiSet on target AsyncLocalStorage with params (
        (
       ...

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eabf1e7ab313d00189068d2?event_id=5eabf1e7005b48bdc87b0000&i=gh&m=ci)

## Stacktrace

    TreecounterApp:0 - facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)
    TreecounterApp:0 - facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)
    TreecounterApp:0 - facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eabf1e7ab313d00189068d2?event_id=5eabf1e7005b48bdc87b0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
do not fix native bugs yet
