### ISSUE TITLE
Compete "Guest" Login Failure on Select devices

### ISSUE THREAD

**Issue by Chiagozie-Udeh** [Plant-for-the-Planet-org/treecounter-app#2271]
**When signing in as a guest, the compete feature does not allow the guest to put password on some devices**
*After the sign in as a guest page, in compete feature, it will ask for your email and password. When you enter the email, the password space is not functional. It not allow you to input anything in it. It happens in iPhone 11, 11 Max, 11 Pro, iPhone 8 (12), iPhone XS (13)and iPhone 6S. You can't proceed to the compete page*

**Production**

**To Reproduce**
1. Go to 'Continue as Guest'
2. Click on 'Compete'
3. Scroll down to 'Password'
4. See error (no specific error message just that you can't proceed to the next page)

**Expected behavior**
*When you go to compete after choosing "continue as a guest", you enter your email and the password and then click login which will take you to the competition page*

**You can't enter the password and remain stuck on that page**
*Instead of the space for password being clickable and allowing one to type in, it is dormant and doesn't accept any input.*

**Screenshots**

<img width="146" alt="test1" src="https://user-images.githubusercontent.com/57354853/80873659-6d132b80-8cba-11ea-957c-9920cf840588.PNG">

**Desktop (please complete the following information):**
 - Plant-for-the-Planet App Version [e.g. 1.0.3]

**Smartphone (please complete the following information):**
- Device: [e.g.  iPhone 11, 11 Max, 11 Pro, iPhone 8 (12), iPhone XS (13)and iPhone 6S]
 - Browser [Browser stack]
 - Plant-for-the-Planet App Version [e.g. 1.0.3]

**Additional context**
*Add any other context about the problem here.*

**Comment by norbertschuler** [comment]
@Chiagozie-Udeh I tested with an iPhone 8 (iOS 12) and iPhone 11 (iOS 13) simulator, but cannot reproduce this issue. Any further hint what you did, e.g. more detailed steps?

**Comment by norbertschuler** [comment]
@Chiagozie-Udeh: From your screenshot I could guess you are using Browserstack. I tested the app on Browserstack too and recognized you can enter your password, but the device jut does not show any dots for it. But the password gets entered, you can see it by the Login button being enabled after typing the first character and also the label turning green. If you use "Show" to enter the password without hiding it, it also shows the characters entered. I think Browserstack just does not show the dots for hidden entered password for some reason I don't know.
