### ISSUE TITLE
TypeError in /my-trees - Cannot read property '_avast_submit' of undefined

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2275]
## Error in Plant-for-the-Planet App

**TypeError** in **/my-trees**
Cannot read property '_avast_submit' of undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eaedf69c8eadf00176b6713?event_id=5eaedf69005b324f808c0000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/my-trees:3 - _submitInjector

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eaedf69c8eadf00176b6713?event_id=5eaedf69005b324f808c0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Browser Plugin error

**Comment by Plant-for-the-Planet** [comment]
An error linked to this issue has been reopened in Bugsnag
[**TypeError** in **/account-activation**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eaedf69c8eadf00176b6713?event_id=5eb65c87005b386c09c90000&i=gh&m=ra)

**Comment by norbertschuler** [comment]
Browser Plugin error
