### ISSUE TITLE
Deleted competition still appears in the list

### ISSUE THREAD

**Issue by harshvitra** [Plant-for-the-Planet-org/treecounter-app#2276]
**Describe the bug**

Deleted competition still appears in the list until you reload the entire app

**Is it on a Production or Development Build?**
This is in #2068 

**To Reproduce**
1. Go to your competition
2. Click on edit and delete your competition
3. Check if your deleted competition still exist

**Expected behavior**
The deleted competition should not exist

**Comment by sanjayradadiya** [comment]
- [ ] @jmiridis can you please check this While adding competition Request URL: https://app-development.plant-for-the-planet.org/api/v1.1/en/competitionsMine
End point sending multiple merge data
**Response**
`{"merge":{"competitionPager":[{"id":3,"category":"mine","orderBy":"recent","currentPage":1,"maxPerPage":2,"nbPages":1,"nbResults":2,"nbShowing":2,"nbRemaining":0,"nbNextResults":0,"competitions":[{"id":257,"slug":"fghfg","name":"Fghfg","ownerTreecounterId":156687,"ownerName":"sanjay radadiya","ownerAvatar":null,"access":"request","endDate":"2020-05-14","goal":2500.0,"score":0.0,"image":null,"competitorCount":0,"topEnrollments":[{"id":2455,"treecounterId":156687,"treecounterSlug":"sanjay-radadiya","treecounterDisplayName":"sanjay radadiya","treecounterAvatar":null,"score":0.0}],"filterType":"all"},{"id":256,"slug":"vxcvx","name":"Vxcvx","ownerTreecounterId":156687,"ownerName":"sanjay radadiya","ownerAvatar":null,"access":"request","endDate":"2020-05-14","goal":2500.0,"score":0.0,"image":null,"competitorCount":0,"topEnrollments":[{"id":2454,"treecounterId":156687,"treecounterSlug":"sanjay-radadiya","treecounterDisplayName":"sanjay radadiya","treecounterAvatar":null,"score":0.0}],"filterType":"all"}]}]}}`

- [ ] While delete competition merge object not available using this end point Request URL: https://app-development.plant-for-the-planet.org/api/v1.1/en/competition/256
**Response**
`{"delete":{"competition":[256]},"unlink":{"treecounter.156687.competitions":[256],"competitionPager.1.competitions":[256],"competitionPager.2.competitions":[256],"competitionPager.3.competitions":[256]}}`
