### ISSUE TITLE
SyntaxError in / - Unexpected identifier loading https://weplant.app

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2279]
## Error in Plant-for-the-Planet App

**SyntaxError** in **/**
Unexpected identifier

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eb0bf3498e63c0017f7eff3?event_id=5eb0bf34005b319126e90000&i=gh&m=ci)

## Stacktrace

    https://weplant.app/:30 - XMLHttpRequest.r.onload

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eb0bf3498e63c0017f7eff3?event_id=5eb0bf34005b319126e90000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Problem with https://weplant.app

**Comment by norbertschuler** [comment]
<img width="703" alt="Bildschirmfoto 2020-06-22 um 19 01 42" src="https://user-images.githubusercontent.com/1532418/85285286-d7766a00-b4ba-11ea-9e0e-d02ff22be759.png">
