### ISSUE TITLE
User defined currency not selected in currency chooser

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#2280]
**Describe the bug**
In the native apps, the currency chooser is showing the currency returned in the config API call https://app-development.plant-for-the-planet.org/public/v1.1/de/config and not the currency returned in the user profile, e.g. with the loadUserProfile API call https://app-development.plant-for-the-planet.org/api/v1.1/de/loadUserProfile.

**Is it on a Production or Development Build?**
production and develop

**To Reproduce**
1. Go to 'Me' screen and open settings
2. See wrong flag and wrong currency selected if opening currency selector

**Expected behavior**
Show the currency the user has selected last, not the currency returned by the config API call.

**Screenshots**
![Simulator Screen Shot - iPhone 11 - 2020-05-05 at 13 28 21](https://user-images.githubusercontent.com/1532418/81040103-c9519780-8ed4-11ea-9365-9cbc00b0eefa.png)
<img width="255" alt="Bildschirmfoto 2020-05-05 um 13 34 52" src="https://user-images.githubusercontent.com/1532418/81040275-3bc27780-8ed5-11ea-8401-607ed8c5a630.png">
<img width="320" alt="Bildschirmfoto 2020-05-05 um 13 33 53" src="https://user-images.githubusercontent.com/1532418/81040281-3fee9500-8ed5-11ea-8fb7-3aed3dcffd14.png">

**Smartphone (please complete the following information):**
- Device: iPhone 11 simulator
 - OS: iOS 13.2.x
 - Plant-for-the-Planet App Version 1.3.2

**Comment by norbertschuler** [comment]
This also happens for the web client:#

<img width="248" alt="Bildschirmfoto 2020-05-07 um 20 50 11" src="https://user-images.githubusercontent.com/1532418/81302332-72022180-90a4-11ea-85d6-35cf9ed9507f.png">

**Comment by norbertschuler** [comment]
My first idea was to overwrite the currency retrieved with the config API call with the currency retrieved by the user profile API call: https://github.com/Plant-for-the-Planet-org/treecounter-app/commit/c5b61abd048adc45befeb60a18c636419dc222d6

But I currently don't know the logic behind using the currency value from (1) the user profile, (2) the backend config or (3) the environment variable in our context and also how to use the locally stored redux state vs. the value stored as `preferredCurrency` in the local browser storage.

**Comment by mahmed0715** [comment]
@norbertschuler found the issue on app, but can not see issue with web client
Can you get the way to reproduce on web please...
Checking on app to fix..

**Comment by norbertschuler** [comment]
@mahmed0715 I tested on production and developemt. It does not happen to me in the web client, when I use German language (you see my user profile country is 'DE' and currency 'EUR'), but it happens if I change to English or Spanish language. And it also happens as the config API call returns country 'TH' and currency 'THB' for me. If you try the same setup, you should be able to reproduce it.
