### ISSUE TITLE
Error in /donate-trees/1 - Unexpected input given to normalize. Expected type to be "object", found "string".

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2329]
## Error in Plant-for-the-Planet App

**Error** in **/donate-trees/1**
Unexpected input given to normalize. Expected type to be "object", found "string".

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eb65370cb1cb90017fd493a?event_id=5eb65370005b3790a32e0000&i=gh&m=ci)

## Stacktrace

    app/actions/loadTposAction.js:62 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eb65370cb1cb90017fd493a?event_id=5eb65370005b3790a32e0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Problem got raised at May 17th:

<img width="1260" alt="Bildschirmfoto 2020-05-22 um 09 34 25" src="https://user-images.githubusercontent.com/1532418/82625492-76cfe500-9c0f-11ea-98c3-aba8562d4542.png">

**Comment by norbertschuler** [comment]
I wonder if the `plantProjectSchema` and all the other schemas defined in https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/develop/app/schemas/index.js still match the data model of the backend or are already outdated:

https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/069898284b7eb4d77c0582080df3af6f89e59d0c/app/schemas/index.js#L53-L57

**Comment by norbertschuler** [comment]
Hopefully fixes with next release.

**Comment by norbertschuler** [comment]
Hopefully fixes with next release.
