### ISSUE TITLE
RCTFatalException: Exception '-[NSNull length]: unrecognized selector

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2334]
## Error in Plant-for-the-Planet App

**RCTFatalException: Exception '-[NSNull length]: unrecognized selector sent to instance 0x1d20dc0b0' was thrown while invoking multiSet on target RNCAsyncStorage with params (         (                 (             "refresh_token",             "<null>"         )     ),     101 ) callstack: ( 	0   CoreFoundation                      0x0000000193bb8980 DC2C95C6-B954-39E8-86A2-5E0AF8801E87 + 1255808 	1   libobjc.A.dylib                     0x00000001938d1028 objc_exception_throw + 60 	2   CoreFo...** in **facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)**
Exception '-[NSNull length]: unrecognized selector sent to instance 0x1d20dc0b0' was thrown while invoking multiSet on target RNCAsyncStorage with params (
        (
         ...

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eb7a1b80879c8001772a114?event_id=5eb7a1b8005b3a359a7b0000&i=gh&m=ci)

## Stacktrace

    TreecounterApp:0 - facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)
    TreecounterApp:0 - facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)
    TreecounterApp:0 - facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eb7a1b80879c8001772a114?event_id=5eb7a1b8005b3a359a7b0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
cannot fix native error
