### ISSUE TITLE
TypeError in /donate-trees - undefined is not an object (evaluating 'e.checkValidation[e.currentSlide].call')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2337]
## Error in Plant-for-the-Planet App

**TypeError** in **/donate-trees**
undefined is not an object (evaluating 'e.checkValidation[e.currentSlide].call')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eb817a3ba8a7a00184935cd?event_id=5eb817a3005b4b4f8f8f0000&i=gh&m=ci)

## Stacktrace

    app/components/DonateTrees/index.js:335 - validated

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eb817a3ba8a7a00184935cd?event_id=5eb817a3005b4b4f8f8f0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
again properties of NextArrow button of Slider not accessable
