### ISSUE TITLE
TypeError in app/components/UserContributions/ContributionCard.native.js:305 - n.props.onPressSingleContribution is not a function.

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2338]
## Error in Plant-for-the-Planet App

**TypeError** in **app/components/UserContributions/ContributionCard.native.js:305**
n.props.onPressSingleContribution is not a function. (In 'n.props.onPressSingleContribution(l)', 'n.props.onPressSingleContribution' is undefined)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eb8587ea0e8e60017bf6ca3?event_id=5eb8587e005b28f8cc750000&i=gh&m=ci)

## Stacktrace

    app/components/UserContributions/ContributionCard.native.js:305 - onPress

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eb8587ea0e8e60017bf6ca3?event_id=5eb8587e005b28f8cc750000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Plant-for-the-Planet** [comment]
An error linked to this issue has been reopened in Bugsnag
[**TypeError** in **app/components/UserContributions/ContributionCard.native.js:305**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eb8587ea0e8e60017bf6ca3?event_id=5ef76144005b7ce6bd100000&i=gh&m=ra)

**Comment by norbertschuler** [comment]
already fixed
