### ISSUE TITLE
TypeError in /register-trees - Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2343]
## Error in Plant-for-the-Planet App

**TypeError** in **/register-trees**
Cannot read property 'includes' of undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eb9409bab98760017d4c496?event_id=5eb9409b005b353633690000&i=gh&m=ci)

## Stacktrace

    app/helpers/utils.js:228 - 
    app/helpers/utils.js:226 - mergeContributionImages
    app/containers/RegisterTrees/index.js:33 - Object.onSubmit
    app/components/RegisterTrees/index.js:142 - RegisterTrees.onSubmitClick
    app/components/Common/Button/PrimaryButton.js:12 - PrimaryButton.$.default.createElement.onClick

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eb9409bab98760017d4c496?event_id=5eb9409b005b353633690000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
fixed by 2b968b0636cbc2c44a5d28ce2fe4361fef23eb0b
