### ISSUE TITLE
Redemption API call response ignored

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#2344]
**Describe the bug**

The code of https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/develop/app/actions/redemptionAction.js completely ignores the response from the API calls and therefore:
- misses to show the proper error or failure messages returned by the API call 
- misses to update the clients state with the resulting `gift` and `treecounter` objects and therefore not adding new user contribution into the client until it got restarted (users say they can not see the trees they just redeemed their vouchers for)

**Is it on a Production or Development Build?**
both

**To Reproduce**
1. Go to 'Me' and choose 'Redeem' button
2. Enter a valid code (get examples from backend)
3. Redeem the voucher code (also enter wrong code to see error results)

**Expected behavior**
Check API call response and react on it correctly.

**What actually happens**
Response of API call is ignored.

**Screenshots**
<img width="812" alt="Bildschirmfoto 2020-05-12 um 09 12 45" src="https://user-images.githubusercontent.com/1532418/81630872-e1736a80-9430-11ea-8f6c-edcfca62c557.png">

**Comment by norbertschuler** [comment]
Btw. there are also other API calls in https://github.com/Plant-for-the-Planet-org/treecounter-app/tree/develop/app/actions where the response is ignored!

**Comment by mahmed0715** [comment]
yah almost, one thing is messing up is the gift, when we are merging the treecounter entity in redux, the gift array get messed up. dont know how to avoid it. you can check the webclient and watch the redux change in treecounter entity. @norbertschuler

**Comment by mahmed0715** [comment]
From my side I think we unnecessarily made the data structure complex.

**Comment by norbertschuler** [comment]
> yah almost, one thing is messing up is the gift, when we are merging the treecounter entity in redux, the gift array get messed up. dont know how to avoid it. you can check the webclient and watch the redux change in treecounter entity. @norbertschuler
> FYI i dont see any issue with frontend, ui gets updated as expected, the counter gets updated.

You just merged `treecounter`, but it only contains a link to the new gift entity returned as `gift` - I am not sure how to merge both into our state correctly:

<img width="368" alt="Bildschirmfoto 2020-05-22 um 10 16 00" src="https://user-images.githubusercontent.com/1532418/82627943-c1ecf680-9c15-11ea-918b-c0f57eb571a0.png">

**Comment by mahmed0715** [comment]
I see the problem is not that simple, I found that the exiting gift data is overwritten by the only {id: 121221} like entity. 
Dont know what to do, what I can do is only update the treecount in the treecounter, right?

**Comment by norbertschuler** [comment]
> I see the problem is not that simple, I found that the exiting gift data is overwritten by the only {id: 121221} like entity.
> Dont know what to do, what I can do is only update the treecount in the treecounter, right?

I thought we could just use the given entity and merge it into the treecounter, but I missed that the gifts array within the treecounter has completely different data:

<img width="339" alt="Bildschirmfoto 2020-05-22 um 12 42 54" src="https://user-images.githubusercontent.com/1532418/82635241-f8347100-9c29-11ea-9d74-b57afe988e55.png">

So until the API call got changed and returning suitable objects to merge, your solution with just loading the user profile again was the only right one. Please go back to your former solution.

**Comment by norbertschuler** [comment]
Just for fun: If the objects would have been compatible, this code would have worked (I tested it, but throwing it away again now):

<img width="711" alt="Bildschirmfoto 2020-05-22 um 12 46 01" src="https://user-images.githubusercontent.com/1532418/82635506-890b4c80-9c2a-11ea-8929-262844a6e3a8.png">
