### ISSUE TITLE
NetworkError in /

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2347]
## Error in Plant-for-the-Planet App

**NetworkError** in **/**
Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://www.trilliontreecampaign.org/assets/coast-228x228.png'.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ebab2b2f16e550017db111a?event_id=5ebab2b2005b35e6be790000&i=gh&m=ci)

## Stacktrace

    about:blank:18 - FetchUrl

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ebab2b2f16e550017db111a?event_id=5ebab2b2005b35e6be790000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Chunk loading error
