### ISSUE TITLE
Disable Survival Rate on Web

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#2348]
In the app the survival rate of the trees is not visible anymore. This was removed as we do not have a way to confirm it for many new projects right now. So also need to remove the survival rate from the web app.
  
<img width="1004" alt="Screen Shot 2020-05-12 at 5 28 03 PM" src="https://user-images.githubusercontent.com/5401575/81713304-f9b9a880-9475-11ea-8d85-3771256cd7b9.png">

**Comment by norbertschuler** [comment]
@sagararyal wouldn‘t it ne better to disable sending the rates to the clients by the backend as if we ever want to enable this feature again we have to change the client code and make a new release? Also we might forget how this was implemented. Removing it from the client code makes only sense if we are sure we don’t want to enable this again for quite some time.

**Comment by norbertschuler** [comment]
The source code is still filled with `survivalRate`:
<img width="526" alt="Bildschirmfoto 2020-05-30 um 18 18 30" src="https://user-images.githubusercontent.com/1532418/83326949-4e488a80-a2a2-11ea-8695-0151e3ffadb7.png">
