### ISSUE TITLE
Error in app/actions/loadTposAction.js:62 - Unexpected input given to normalize. Expected type to be "object", found "string"

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2349]
## Error in Plant-for-the-Planet App

**Error** in **app/actions/loadTposAction.js:62**
Unexpected input given to normalize. Expected type to be "object", found "string".

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ebb4b02c178e100176eae6b?event_id=5ebb4b02005b285461ea0000&i=gh&m=ci)

## Stacktrace

    app/actions/loadTposAction.js:62 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ebb4b02c178e100176eae6b?event_id=5ebb4b02005b285461ea0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Code cannot deal with wrong API response.

**Comment by norbertschuler** [comment]
Duplicate of #2329
