### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException in TextLine.java:316

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2351]
## Error in Plant-for-the-Planet App

**java.lang.ArrayIndexOutOfBoundsException** in **TextLine.java:316**
length=54; index=54

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ebc362e33da980017fa1243?event_id=5ebc362e005b287fc32e0000&i=gh&m=ci)

## Stacktrace

    TextLine.java:316 - android.text.TextLine.measure

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ebc362e33da980017fa1243?event_id=5ebc362e005b287fc32e0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
cannot fix native error
