### ISSUE TITLE
Connect with Stripe

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#2352]
This feature would add the following:

**Connect with Stripe** button  for Tree Planting Organization that uses the link below:
https://dashboard.stripe.com/oauth/authorize?response_type=code&client_id=ca_D4u4TGpPZk1glMQwtZetnoQ3RV062x4b&scope=read_write
<img width="219" alt="Screen Shot 2020-05-14 at 1 34 22 PM" src="https://user-images.githubusercontent.com/5401575/81929624-a1a2b380-95e7-11ea-804b-85805287ee41.png">

Button should go centered on bottom of  Manage Projects Page for TPOs.

Details on Integration is available at: https://stripe.com/docs/connect/standard-accounts

An API might be necessary to supply the account ID retrieved from Stripe to the backend. @jmiridis

**Comment by jmiridis** [comment]
The backend will handle the event `account.updated` via webhooks and automatically create the corresponding payment account. It can then be associated with the TPO by someone in the office.

**Comment by harshvitra** [comment]
Closing issue as we do not support old web
