### ISSUE TITLE
Unable to open URL: mailto:info...

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2353]
## Error in Plant-for-the-Planet App

**Error** in **app/components/PlantProjects/HelperComponents/AccordionContactInfo.native.js:141**
Unable to open URL: mailto:info@plant-for-the-planet.org?subject=Re:Plant-for-the-Planet%20at%20Plant-for-the-Planet%20App

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ebd51f59cd3040017d46ff0?event_id=5ebd51f5005b294747e80000&i=gh&m=ci)

## Stacktrace

    app/components/PlantProjects/HelperComponents/AccordionContactInfo.native.js:141 - onPress

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ebd51f59cd3040017d46ff0?event_id=5ebd51f5005b294747e80000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
<img width="819" alt="Bildschirmfoto 2020-05-14 um 21 44 45" src="https://user-images.githubusercontent.com/1532418/81948642-257e8f00-962c-11ea-94ca-9e9d888b31a8.png">

**Comment by norbertschuler** [comment]
Duplicate of #2910
