### ISSUE TITLE
TypeError in app/components/TreecounterGraphics/Trillion.native.js:241 - undefined is not a function (near '...t.props.pledgeEvents.pledgeEvents.map...')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2354]
## Error in Plant-for-the-Planet App

**TypeError** in **app/components/TreecounterGraphics/Trillion.native.js:241**
undefined is not a function (near '...t.props.pledgeEvents.pledgeEvents.map...')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ebd919f67de0d001712611d?event_id=5ebd919f005b3b7b16500000&i=gh&m=ci)

## Stacktrace

    app/components/TreecounterGraphics/Trillion.native.js:241 - 
    app/components/TreecounterGraphics/Trillion.native.js:77 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ebd919f67de0d001712611d?event_id=5ebd919f005b3b7b16500000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
@harshvitra I do not find this bug, but it happens again and again with every version of our app. Can you image why this happens?
