### ISSUE TITLE
TypeError in /home - a[b].target.className.indexOf is not a function. (In 'a[b].target.className.indexOf(ac)', 'a[b].target.className.indexOf' is undefined)

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2356]
## Error in Plant-for-the-Planet App

**TypeError** in **/home**
a[b].target.className.indexOf is not a function. (In 'a[b].target.className.indexOf(ac)', 'a[b].target.className.indexOf' is undefined)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ebdaa7177a8b9001727a06e?event_id=5ebdaa71005b2d256f190000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/account-activated:412 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ebdaa7177a8b9001727a06e?event_id=5ebdaa71005b2d256f190000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
cannot reproduce
