### ISSUE TITLE
Auth0 Implementation

### ISSUE THREAD

**Issue by jmiridis** [Plant-for-the-Planet-org/treecounter-app#2358]
The back-end implementation on `https://app-fixtures.plant-for-the-planet.org` now supports API authentication via Auth0 JWTs.

Login, password forgotten/reset etc. can be removed from the client code base and replaced with a corresponding Auth0 library implementation.

A description of how to use the server API can be found here:
https://treecounter-docs.herokuapp.com/system/authentication/ClientAPIAuthentication.html

Whoever will pick up the task, should contact me first.

**Comment by norbertschuler** [comment]
I am not sure, if we can pickup the old work of @crucialfelix. There is still a project https://github.com/Plant-for-the-Planet-org/treecounter-app/projects/5 and also a very old PR https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1375.

**Comment by crucialfelix** [comment]
Auth0 have newer libraries and recommended auth flow. The branch I did has long since expired.

**Comment by crucialfelix** [comment]
Oh I just remembered. Last month i did a sketch for a rebuild of trilliontrees. It has Auth0 code in it. It may serve as a reference point

https://github.com/crucialfelix/repot-trilliontrees
