### ISSUE TITLE
TypeError in /signup/vodafone - this.props.onProfileClick is not a function

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2359]
## Error in Plant-for-the-Planet App

**TypeError** in **/signup/vodafone**
this.props.onProfileClick is not a function

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ec4db3d695356001839cd35?event_id=5ec4db3d005b76462f7b0000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/19.a773eaf50b0127ee38d7.js:1 - SignUpType.OnProfileClick

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ec4db3d695356001839cd35?event_id=5ec4db3d005b76462f7b0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
fixed by 546385094731b51f9a88311493920111d94cc7b8
