### ISSUE TITLE
TypeError in /t/communaute-villageaoise-de-melombo-okekat-et-faekele - a[b].target.className.indexOf is not a function. (In 'a[b].target.className.indexOf(Zb)', 'a[b].target.className.indexOf' is undefined)

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2360]
## Error in Plant-for-the-Planet App

**TypeError** in **/t/communaute-villageaoise-de-melombo-okekat-et-faekele**
a[b].target.className.indexOf is not a function. (In 'a[b].target.className.indexOf(Zb)', 'a[b].target.className.indexOf' is undefined)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ec4e59859224000174fe6a4?event_id=5ec4e598005b8ba947480000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/t/communaute-villageaoise-de-melombo-okekat-et-faekele:401 - ki

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ec4e59859224000174fe6a4?event_id=5ec4e598005b8ba947480000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
cannot reproduce
