### ISSUE TITLE
NSRangeException in _mh_execute_header

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2363]
## Error in Plant-for-the-Planet App

**NSRangeException** in **_mh_execute_header**
*** -[NSBigMutableString substringWithRange:]: Range {3, 2} out of bounds; string length 4

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ec73141a771ad0017e51e96?event_id=5ec73141005b8a2831b40000&i=gh&m=ci)

## Stacktrace

    TreecounterApp:0 - _mh_execute_header

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ec73141a771ad0017e51e96?event_id=5ec73141005b8a2831b40000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
cannot fix native error
