### ISSUE TITLE
Mark outdated app versions and notify the user

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#2370]
We want to mark older app version as outdated. We could use the already existing response from the config API call already existing:

```json
{
  "appVersions": {
    "ios": [

    ],
    "android": [

    ]
  },
  ...
}
```
@jmiridis how is the above information meant to be used inside the apps?

1. We can write some code as following using the above array if it include all valid app versions - but then the backend has to know and return **all** valid versions:
```javascript
if (!appVersions.ios.includes(package.version)) {
   // show the user an information that the app is outdate and a link to the app stores
}
```
2. We can write some code to check if the app version is less then the supported version (so the API call has only to return the lowest supported version and does not need an array):
```javascript
if (package.version < appVersions.ios[0]) {
   // show the user an information that the app is outdate and a link to the app stores
}
```
3. We can send the app version as payload to the config API call to let the backend do the check and afterwards just return the information if the calling app is outdated or not (new boolean flag in the response).

We could use the design from https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1376 for this.

**Comment by jmiridis** [comment]
AFAIK the decision process to determine that a version is unsupported has not been defined.

I would assume that if a certain version number is not supported anymore, all lower versions are also not supported, so option (2) would be my choice.

Option (3) is basically the implementation of the comparison server-side. Could of course  be done as well. It seems to me that the user should not be aware of supported version numbers only with the fact that he has to update. If this is the case, this options is feasible as well.

**Comment by norbertschuler** [comment]
@jmiridis Thank you for the feedback. Then I would choose option (2) because ...
- it does not matter if the user knowns about the supported version numbers (we are open source),
- It gives the frontend developers transparency of what valid versions are configured in the backend without having to check the backend code. So let's start with adding a least supported version now as following (maybe just the next release version):
```json
  "appVersions": {
    "ios": "1.3.4",
    "android": "1.3.4"
  },
  ...
```

We will also have to think about how to get older app versions upgraded which have no check implemented. With above change the older versions < "1.3.4" will just continue to work as they have no check implemented.
The only solution I can think of now is to upgrade **all of our API requests** with the next release to version number `1.4`, e.g. https://app.plant-for-the-planet.org/public/v1.4/en/config and stop supporting the older API versions at a given time (we can decide later on). Thus the apps would not work any more. This is not very nice as users might think the app is broken, but I don't know a better way to stop older apps from being used, do you?

**Comment by norbertschuler** [comment]
@jmiridis can you change the config API call to return the following version numbers in a `v1.2` version of this API call, e.g. for https://app.plant-for-the-planet.org/public/v1.2/en/config:

```json
  "appVersions": {
    "ios": ["1.3.5"],
    "android": ["1.3.5"]
  },
  ...
```

That would be required to make my PR https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/2466 work.
