### ISSUE TITLE
TypeError in app/actions/EditMyTree.js:60 - undefined is not an object (evaluating 't.response.data')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2376]
## Error in Plant-for-the-Planet App

**TypeError** in **app/actions/EditMyTree.js:60**
undefined is not an object (evaluating 't.response.data')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ed10322e7c40f0017a9a1e6?event_id=5ed10322005b8b2fbc290000&i=gh&m=ci)

## Stacktrace

    app/actions/EditMyTree.js:60 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ed10322e7c40f0017a9a1e6?event_id=5ed10322005b8b2fbc290000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
fixed by e457e98862c305ef7d47ea05a7dfe5633a673c0f
