### ISSUE TITLE
Error in / - Should not already be working

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2378]
## Error in Plant-for-the-Planet App

**Error** in **/**
Minified React error #327; visit https://reactjs.org/docs/error-decoder.html?invariant=327 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ed44a74dc21080017e6f693?event_id=5ed44a74005b764068fd0000&i=gh&m=ci)

## Stacktrace

    https://trilliontree.org/bundle.a773eaf50b0127ee38d7.js:2 - yj()

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ed44a74dc21080017e6f693?event_id=5ed44a74005b764068fd0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Duplicate of #2221
