### ISSUE TITLE
Error in /donate-trees - Axios error not handled

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2381]
## Error in Plant-for-the-Planet App

**Error** in **/donate-trees**
Request aborted

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ed65007bca4cd001831f011?event_id=5ed65007005b797914ca0000&i=gh&m=ci)

## Stacktrace

    node_modules/axios/lib/core/createError.js:16 - createError

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ed65007bca4cd001831f011?event_id=5ed65007005b797914ca0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
network error in axios modules, shouldn't be tracked as bug, but handled in the app
