### ISSUE TITLE
TypeError in /edit-trees/314763 - e.response is undefined

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2383]
## Error in Plant-for-the-Planet App

**TypeError** in **/edit-trees/314763**
e.response is undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ed92f537e92a30017e896cc?event_id=5ed92f53005b8bf64a050000&i=gh&m=ci)

## Stacktrace

    app/actions/EditMyTree.js:59 - editTree/</<

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ed92f537e92a30017e896cc?event_id=5ed92f53005b8bf64a050000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
fixed by 271c1803fde156daadc2ea6e76ba588890a92663
