### ISSUE TITLE
TypeError in /signup/vodafone - undefined is not an object (evaluating 'href.value.charAt')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2384]
## Error in Plant-for-the-Planet App

**TypeError** in **/signup/vodafone**
undefined is not an object (evaluating 'href.value.charAt')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ed935361ff540001786fb5e?event_id=5ed93536005b6b394ab10000&i=gh&m=ci)

## Stacktrace

    jquery-3.2.1.js:362 - each

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ed935361ff540001786fb5e?event_id=5ed93536005b6b394ab10000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
out of reach

**Comment by Plant-for-the-Planet** [comment]
An error linked to this issue has been reopened in Bugsnag
[**TypeError** in **/signup/vodafone**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ed935361ff540001786fb5e?event_id=5f1e77e4005b6e9da5900000&i=gh&m=ra)
