### ISSUE TITLE
Error in /donate-trees - Target window is closed

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2385]
## Error in Plant-for-the-Planet App

**Error** in **/donate-trees**
Target window is closed

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eda4923527f39001761aa25?event_id=5eda4923005b79f607820000&i=gh&m=ci)

## Stacktrace

    https://www.paypalobjects.com/api/checkout.js:5296 - request/<

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eda4923527f39001761aa25?event_id=5eda4923005b79f607820000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
related to #1943

**Comment by Plant-for-the-Planet** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Error** in **/gift-trees**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eda4923527f39001761aa25?event_id=5f496b2f005e0264d3630000&i=gh&m=ra)
