### ISSUE TITLE
window.onerror in /donate-trees/1 - TypeError: At.default.notify is not a function. (In 'At.default.notify(E,(function(E){E.metadata={info:j}}))', 'At.default.notify' is undefined)

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2388]
## Error in Plant-for-the-Planet App

**window.onerror** in **/donate-trees/1**
TypeError: At.default.notify is not a function. (In 'At.default.notify(E,(function(E){E.metadata={info:j}}))', 'At.default.notify' is undefined)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5edb80657340c40017008d4d?event_id=5edb8065005b8153840f0000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/bundle.a773eaf50b0127ee38d7.js:1 - onerror

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5edb80657340c40017008d4d?event_id=5edb8065005b8153840f0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Result of ChunkLoadError: Loading chunk 20 failed

**Comment by Plant-for-the-Planet** [comment]
An error linked to this issue has been reopened in Bugsnag
[**window.onerror** in **/donate-trees**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5edb80657340c40017008d4d?event_id=5efa7f9d005b7a438ed70000&i=gh&m=ra)
