### ISSUE TITLE
TypeError in /donate-trees - Cannot redefine property: googletag

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2391]
## Error in Plant-for-the-Planet App

**TypeError** in **/donate-trees**
Cannot redefine property: googletag

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eddd795c4ec140017c9ff14?event_id=5eddd795005b6b0cfacb0000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/donate-trees:1 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eddd795c4ec140017c9ff14?event_id=5eddd795005b6b0cfacb0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
cannot reproduce
