### ISSUE TITLE
Error in /edit-profile - Network Error

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2417]
## Error in Plant-for-the-Planet App

**Error** in **/edit-profile**
Network Error

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ede27329ed89c0017f9247e?event_id=5ede2732005b7670840c0000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/bundle.aadf72caf807716c6723.js:1 - createError

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ede27329ed89c0017f9247e?event_id=5ede2732005b7670840c0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
network error
