### ISSUE TITLE
TypeError in /donate-trees - Cannot read property 'plantProjectPager' of undefined

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2418]
## Error in Plant-for-the-Planet App

**TypeError** in **/donate-trees**
Cannot read property 'plantProjectPager' of undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ede505e838a3a0018a6f595?event_id=5ede505e005b6d3b32540000&i=gh&m=ci)

## Stacktrace

    app/actions/loadTposAction.js:33 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ede505e838a3a0018a6f595?event_id=5ede505e005b6d3b32540000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
<img width="626" alt="Bildschirmfoto 2020-06-10 um 13 54 06" src="https://user-images.githubusercontent.com/1532418/84236464-df7cf400-ab21-11ea-9b5c-8ac8a6d1296f.png">

**Comment by norbertschuler** [comment]
Hopefully fixes with next release.
