### ISSUE TITLE
TypeError in /donate-trees/1 - undefined is not an object (evaluating 'e.checkValidation[e.currentSlide].call')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2455]
## Error in Plant-for-the-Planet App

**TypeError** in **/donate-trees/1**
undefined is not an object (evaluating 'e.checkValidation[e.currentSlide].call')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ee166b9c884850018cdbcd8?event_id=5ee166b9005b6ba2d0df0000&i=gh&m=ci)

## Stacktrace

    app/components/DonateTrees/index.js:345 - validated

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ee166b9c884850018cdbcd8?event_id=5ee166b9005b6ba2d0df0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Problem with accessing properties of NextArrow of Slider.

**Comment by norbertschuler** [comment]
Web client abandoned.
