### ISSUE TITLE
TypeError in /donate-trees - Cannot read property 'plantProjectPager' of undefined

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2459]
## Error in Plant-for-the-Planet App

**TypeError** in **/donate-trees**
Cannot read property 'plantProjectPager' of undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ee2c9e7fb3f4a00178d0d7b?event_id=5ee2c9e7005b693206690000&i=gh&m=ci)

## Stacktrace

    app/actions/loadTposAction.js:21 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ee2c9e7fb3f4a00178d0d7b?event_id=5ee2c9e7005b693206690000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Duplicate of #2418
