### ISSUE TITLE
TypeError in /manage-plant-projects - Unable to get property 'includes' of undefined or null reference

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2463]
## Error in Plant-for-the-Planet App

**TypeError** in **/manage-plant-projects**
Unable to get property 'includes' of undefined or null reference

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ee62c6dd9e6d10018eaad80?event_id=5ee62c6d005b7790f2e90000&i=gh&m=ci)

## Stacktrace

    app/components/ManageProjects/index.js:162 - Anonymous function
    app/components/ManageProjects/index.js:172 - mergeProjectImages
    app/components/ManageProjects/index.js:186 - Anonymous function
    app/components/ManageProjects/index.js:253 - onClick

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ee62c6dd9e6d10018eaad80?event_id=5ee62c6d005b7790f2e90000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
<img width="700" alt="Bildschirmfoto 2020-06-14 um 20 58 30" src="https://user-images.githubusercontent.com/1532418/84595394-d83b4a80-ae81-11ea-9b93-cacbd22b7934.png">

**Comment by norbertschuler** [comment]
fixed by 2b968b0636cbc2c44a5d28ce2fe4361fef23eb0b
