### ISSUE TITLE
window.onerror in / - SecurityError: DOM Exception 18: An attempt was made to break through the security policy of the user agent

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2464]
## Error in Plant-for-the-Planet App

**window.onerror** in **/**
SecurityError: DOM Exception 18: An attempt was made to break through the security policy of the user agent.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ee999fb9ff3f1001745e656?event_id=5ee999fb005b68a4eb780000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/bundle.8aff6290fd07f2539028.js:1 - onerror

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ee999fb9ff3f1001745e656?event_id=5ee999fb005b68a4eb780000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Closing this as we cannot do anything about it.
