### ISSUE TITLE
TypeError in /donate-trees/1 - undefined is not a function

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2467]
## Error in Plant-for-the-Planet App

**TypeError** in **/donate-trees/1**
undefined is not a function

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eea896fcb568a00172554e6?event_id=5eea896f005b7974f1770000&i=gh&m=ci)

## Stacktrace

    [native code]:1 - performIteration

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eea896fcb568a00172554e6?event_id=5eea896f005b7974f1770000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
cannot reproduce

**Comment by Plant-for-the-Planet** [comment]
An error linked to this issue has been reopened in Bugsnag
[**TypeError** in **/donate-trees**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eea896fcb568a00172554e6?event_id=5f3a6e65005b6b7799310000&i=gh&m=ra)
