### ISSUE TITLE
IPStack backend API call fails

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#2468]
**Describe the bug**
https://app-development.plant-for-the-planet.org/public/v1.1/de/ipstack returns 
```
{"country_code":null,"location":{"geoname_id":null,"capital":null,"languages":null,"country_flag":null,"country_flag_emoji":null,"country_flag_emoji_unicode":null,"calling_code":null,"is_eu":null}}
```

https://app.plant-for-the-planet.org/public/v1.1/de/ipstack returns
```
{"country_code":null,"location":{"geoname_id":null,"capital":null,"languages":null,"country_flag":null,"country_flag_emoji":null,"country_flag_emoji_unicode":null,"calling_code":null,"is_eu":null}}
```

This is the fallback call to retrieve a currency for the user (by retrieving the country code and looking up a currency from local JSON files) if the config API call does not contain any currencey, but it does not seem to work anymore.

**Is it on a Production or Development Build?**
production and develop

**Comment by sagararyal** [comment]
This should be disabled anyway.
If the currency is not retrieved on the config call; the default currency EUR should be used.

**Comment by norbertschuler** [comment]
I disabled using the fallback with this API call in my PR https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/2466
