### ISSUE TITLE
SyntaxError in /donate-trees - Unexpected identifier

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2469]
## Error in Plant-for-the-Planet App

**SyntaxError** in **/donate-trees**
Unexpected identifier

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eec1fd53238fa001867c739?event_id=5eec1fd5005b6b8d87bc0000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/1.8aff6290fd07f2539028.js:1 - onerror

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eec1fd53238fa001867c739?event_id=5eec1fd5005b6b8d87bc0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
cannot reproduce
