### ISSUE TITLE
window.onerror in /donate-trees - SyntaxError: Unexpected EOF

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2470]
## Error in Plant-for-the-Planet App

**window.onerror** in **/donate-trees**
SyntaxError: Unexpected EOF

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eed208054220300181d122b?event_id=5eed2080005b7b1442b60000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/15.8aff6290fd07f2539028.js:1 - onerror

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eed208054220300181d122b?event_id=5eed2080005b7b1442b60000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
This is the result of an unexpected network error while doing an API call.
