### ISSUE TITLE
TypeError in node_modules/reactotron-react-native/node_modules/query-string/index.js:166 - undefined is not an object (evaluating 't.selectedProject.paymentSetup.gateways[L].stripe.stripePublishableKey')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2473]
## Error in Plant-for-the-Planet App

**TypeError** in **node_modules/reactotron-react-native/node_modules/query-string/index.js:166**
undefined is not an object (evaluating 't.selectedProject.paymentSetup.gateways[L].stripe.stripePublishableKey')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eedce4a7b22c3001782c081?event_id=5eedce4a005b7dc303540000&i=gh&m=ci)

## Stacktrace

    node_modules/reactotron-react-native/node_modules/query-string/index.js:166 - getHash

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eedce4a7b22c3001782c081?event_id=5eedce4a005b7dc303540000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
<img width="785" alt="Bildschirmfoto 2020-06-20 um 19 33 28" src="https://user-images.githubusercontent.com/1532418/85201901-fcd56d80-b32c-11ea-8b69-cd522151529e.png">

**Comment by norbertschuler** [comment]
cannot reproduce

**Comment by Plant-for-the-Planet** [comment]
An error linked to this issue has been reopened in Bugsnag
[**TypeError** in **node_modules/reactotron-react-native/node_modules/query-string/index.js:166**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5eedce4a7b22c3001782c081?event_id=5ef9f367005b6a79af460000&i=gh&m=ra)
