### ISSUE TITLE
Invalid code in browser of users after a new release

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2484]
## Error in Plant-for-the-Planet App

**SyntaxError** in **/explore**
Unexpected token '<'

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ef1c3604995ab0017b6e89c?event_id=5ef1c360005b7a32c3450000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/18.aadf72caf807716c6723.js:1 - onerror

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ef1c3604995ab0017b6e89c?event_id=5ef1c360005b7a32c3450000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
This file does not exists any more on the server as it was part of an older release:
```
$ ls -l 18.aadf72caf807716c6723.js
ls: cannot access '18.aadf72caf807716c6723.js': No such file or directory
```
How can we make sure these files get marked as outdated in the browser of our users?

**Comment by norbertschuler** [comment]
Currently the response header for loading our JavaScript client codes look like this with several headers specifying the age:
- age: 6560
- alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
- cache-control: max-age=1800
- expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"

I wonder what we can do avoid getting these errors after a release. Just invalidate the index.html at Cloudflare or changing any of these headers?

```
Request URL: https://www.trilliontreecampaign.org/
Request Method: GET
Status Code: 200 

Response Headers:
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
cf-cache-status: DYNAMIC
cf-ray: 5a7d08da9a00d9dc-SIN
cf-request-id: 038203dc9a0000d9dce01bc200000001
content-encoding: br
content-type: text/html
date: Tue, 23 Jun 2020 09:03:13 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
last-modified: Wed, 10 Jun 2020 11:28:49 GMT
server: cloudflare
status: 200
vary: Accept-Encoding
via: 1.1 vegur
X-DNS-Prefetch-Control: off
```

```
Request URL: https://www.trilliontreecampaign.org/bundle.8aff6290fd07f2539028.js
Request Method: GET
Status Code: 200 

Response Headers:
age: 6560
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
cache-control: max-age=1800
cf-bgj: minify
cf-cache-status: HIT
cf-polished: origSize=1744806
cf-ray: 5a7d08e2fafcd9dc-SIN
cf-request-id: 038203e1df0000d9dce0207200000001
content-encoding: br
content-type: application/javascript
date: Tue, 23 Jun 2020 09:03:14 GMT
etag: W/"1a9fa6-5a7b925b35620"
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
last-modified: Wed, 10 Jun 2020 11:28:46 GMT
server: cloudflare
status: 200
vary: Accept-Encoding
via: 1.1 vegur
```

**Comment by norbertschuler** [comment]
@sagararyal do you have any idea if it make sense to check if we can adapt Cloudflare caching for this once more?

**Comment by sagararyal** [comment]
@norbertschuler I think we should only purge cache for index.html

This way cf still would have cache of older files.

**Comment by norbertschuler** [comment]
> @norbertschuler I think we should only purge cache for index.html
> 
> 
> 
> This way cf still would have cache of older files.

I will do for the next release 1.3.5. Before I did not even purged index.html at Cloudflare.

**Comment by norbertschuler** [comment]
Web client abandoned.
