### ISSUE TITLE
SecurityError in /donate-trees/1 - Failed to execute 'sendBeacon' on 'Navigator' 

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2502]
## Error in Plant-for-the-Planet App

**SecurityError** in **/donate-trees/1**
Failed to execute 'sendBeacon' on 'Navigator': sendBeacon() with a Blob whose type is not any of the CORS-safelisted values for the Content-Type request header is disabled temporarily. See http://crbug.com/490015 for details.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ef83ff3a67787001727e7d1?event_id=5ef83ff3005b8a1199270000&i=gh&m=ci)

## Stacktrace

https://static.cloudflareinsights.com/beacon.min.js:1:5002 Object.i [as sendObjectBeacon]	
```
if(navigator&&"function"==typeof navigator.sendBeacon&&i){var a={type:"application/json"};navigator.sendBeacon(o,new Blob([r],a))}else{var c=new XMLHttpRequest;n&&(c.onreadystatechange=function(){4==t
```
https://static.cloudflareinsights.com/beacon.min.js:1:4355 m	
```
on(){var e=r(t,n,i,c);e.resources=[],delete e.tempResources,e.eventType=u.EventType.Additional,i&&d.sendObjectBeacon("req_id="+i.rayId,e,function(){},!0)},y=function(){a=!0;var t=window.__cfRl&&window
```
https://static.cloudflareinsights.com/beacon.min.js:1:3762 HTMLDocument.<anonymous>	
```
nt.addEventListener("visibilitychange",function(){"hidden"===document.visibilityState&&!o&&a&&(o=!0,m())});var c={lcp:void 0,cls:void 0,fid:void 0},s=function(t){"CLS"===t.name?c.cls=t.value:"FID"===t
```
https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js:1:9383 HTMLDocument.c	
```
{var s=f(r);"function"==typeof s?(c=function(n){if(e.bypassEventsInProxies||a.indexOf(t)<0)return s.call(this,n)},Object.defineProperty(r,"__rocketLoaderProxiedHandler",{value:c})):c=r}n.call.apply(n,
Event
```
[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ef83ff3a67787001727e7d1?event_id=5ef83ff3005b8a1199270000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Duplicate of #2627
