### ISSUE TITLE
Error in node_modules/lodash/_hashGet.js:10 - Request failed with status code 404

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2505]
## Error in Plant-for-the-Planet App

**Error** in **node_modules/lodash/_hashGet.js:10**
Request failed with status code 404

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ef9f452a806a10017d2d100?event_id=5ef9f452005b73853bba0000&i=gh&m=ci)

## Stacktrace

    node_modules/lodash/_hashGet.js:10 - exports

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ef9f452a806a10017d2d100?event_id=5ef9f452005b73853bba0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
no strack trace given to find out where the 404 happens
