### ISSUE TITLE
Maximum update depth exceeded

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2506]
## Error in Plant-for-the-Planet App

**Error** in **node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:5390**
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ef9f468dc16af00174c0332?event_id=5ef9f468005b75d4d80e0000&i=gh&m=ci)

## Stacktrace

    node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:5390 - scheduleUpdateOnFiber

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ef9f468dc16af00174c0332?event_id=5ef9f468005b75d4d80e0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Unfortunately I do not know how to find out where this is happening.
