### ISSUE TITLE
undefined is not an object (evaluating 't.paymentSetup.gateways[t.context.donationDetails.selectedTaxCountry].stripe.stripePublishableKey')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2507]
## Error in Plant-for-the-Planet App

**TypeError** in **index.android.bundle:2731**
undefined is not an object (evaluating 't.paymentSetup.gateways[t.context.donationDetails.selectedTaxCountry].stripe.stripePublishableKey')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ef9fce063fdf90017e0680a?event_id=5ef9fce0005b78772aae0000&i=gh&m=ci)

## Stacktrace

    index.android.bundle:2731 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5ef9fce063fdf90017e0680a?event_id=5ef9fce0005b78772aae0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Duplicate of #2473
