### ISSUE TITLE
window.onerror in /donate-trees - SyntaxError: Unexpected end of script

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2508]
## Error in Plant-for-the-Planet App

**window.onerror** in **/donate-trees**
SyntaxError: Unexpected end of script

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5efa7be9b413e300183a0544?event_id=5efa7be9005b74806cf70000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/20.8aff6290fd07f2539028.js:1 - onerror

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5efa7be9b413e300183a0544?event_id=5efa7be9005b74806cf70000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
problem loading our scripts
