### ISSUE TITLE
TypeError in app/components/DonateTrees/receiptTabs.native.js:171 - null is not an object (evaluating 't._formRef.current.getValue')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2509]
## Error in Plant-for-the-Planet App

**TypeError** in **app/components/DonateTrees/receiptTabs.native.js:171**
null is not an object (evaluating 't._formRef.current.getValue')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5efb8cb5c85d06001783fc0e?event_id=5efb8cb5005b850d238a0000&i=gh&m=ci)

## Stacktrace

    app/components/DonateTrees/receiptTabs.native.js:171 - onClick
    app/components/Common/Button/PrimaryButton.native.js:16 - onPress

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5efb8cb5c85d06001783fc0e?event_id=5efb8cb5005b850d238a0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
This also does not always seem to work:

<img width="611" alt="Bildschirmfoto 2020-07-01 um 12 46 45" src="https://user-images.githubusercontent.com/1532418/86207526-f2bb3680-bb98-11ea-8464-df39f97fced3.png">
