### ISSUE TITLE
Missing translation for error message on password change

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#2511]
**Describe the bug**
The API call to change a password https://app-development.plant-for-the-planet.org/api/v1.1/de/profilePasswordUpdate returns an non translated error message for entering the old password wrongly.

**Is it on a Production or Development Build?**
production and develop

**To Reproduce**
1. Go to user profile change
2. Enter wrong data for old password 
3. Enter a valid new password and correctly repeat it to avoid an error message for the new password

**Expected behavior**
Error in user language should be returned.

**What actually happens**
English error is returned.

**Screenshots**
<img width="560" alt="Bildschirmfoto 2020-07-02 um 13 37 16" src="https://user-images.githubusercontent.com/1532418/86324847-5d3ba780-bc69-11ea-8157-e204b94ac8df.png">

**Desktop (please complete the following information):**
- OS: latest MacOS
- Browser: latest Chrome
- Plant-for-the-Planet App Version 1.3.4

**Comment by norbertschuler** [comment]
The backend added a resource with https://github.com/Plant-for-the-Planet-org/treecounter-platform/pull/332/files, but we still need to export the resources newly from the source code in order to do the translation in LingoHub.

**Comment by jmiridis** [comment]
https://github.com/Plant-for-the-Planet-org/treecounter-platform/pull/332/files

**Comment by norbertschuler** [comment]
should be fixed with new release 1.3.5
