### ISSUE TITLE
Crash changing the TPO to dedicate donated trees to

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2534]
## Error in Plant-for-the-Planet App

**Error** in **/home**
Request failed with status code 500

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f112eab25353b0017517123?event_id=5f112eab005b8e9319ec0000&i=gh&m=ci)

## Stacktrace

    node_modules/axios/lib/core/createError.js:16 - createError

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f112eab25353b0017517123?event_id=5f112eab005b8e9319ec0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
```
Request URL: https://app-development.plant-for-the-planet.org/api/v1.1/de/profileDedication
Request Method: PUT
Status Code: 500 

"An exception occurred while executing 
'SELECT MAX(e0_.version) AS sclr_0 FROM ext_log_entries e0_ WHERE e0_.object_id = ? AND e0_.object_class = ?' with params [\"37141\", \"App\\\\Entity\\\\Treedonor\"]:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'primary_app_db.ext_log_entries' doesn't exist"
```
