### ISSUE TITLE
TypeError in /login - window.grecaptcha.execute is not a function

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2538]
## Error in Plant-for-the-Planet App

**TypeError** in **/login**
Cannot read property 'execute' of undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f1209e6bfb8c30017d7b487?event_id=5f1209e6005b695d16670000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/27.8aff6290fd07f2539028.js:1 - t.value

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f1209e6bfb8c30017d7b487?event_id=5f1209e6005b695d16670000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
400 error on POST https://app.plant-for-the-planet.org/api/login_check

**Comment by norbertschuler** [comment]
This shouldn't be caught by bugsnag as it's just a normal error when logging in with the wrong credentials.

**Comment by Plant-for-the-Planet** [comment]
An error linked to this issue has been reopened in Bugsnag
[**TypeError** in **/login**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f1209e6bfb8c30017d7b487?event_id=5f59456a005dec064b3d0000&i=gh&m=ra)

**Comment by norbertschuler** [comment]
Bugsnag changed the linked issue.
