### ISSUE TITLE
undefined is not an object (evaluating 'Object.keys(this.props.currencies.currencies.currency_names)')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2549]
## Error in Plant-for-the-Planet App

**TypeError** in **app/components/Common/CurrencySelectorList.native.js:71**
undefined is not an object (evaluating 'Object.keys(this.props.currencies.currencies.currency_names)')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f1b453d22257400175a10f5?event_id=5f1b453d005b8ef045060000&i=gh&m=ci)

## Stacktrace

    app/components/Common/CurrencySelectorList.native.js:71 - value
    app/components/Common/CurrencySelectorList.native.js:179 - value
    app/actions/currencies.js:21 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f1b453d22257400175a10f5?event_id=5f1b453d005b8ef045060000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
replaced by empty response error
