### ISSUE TITLE
Re-Opened Bug - Register - "Add a Tree" Button broken

### ISSUE THREAD

**Issue by delightedMatt** [Plant-for-the-Planet-org/treecounter-app#2555]
Nearly the same as this old issue: [https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/2161]

**After filling out register form, clicking 'Add a Tree' doesn't trigger any events**
This is the case for Single tree and Many Trees.

**This is a bug on the production app. The Web-App doesn't have this issue. iOS I am unsure about.**

**To Reproduce**

  1. Go to "Me"
  2. Click on "Register Tree"
  3. Enter information and choose location
  4. Press Button: Add a Tree
  5. Nothing happens

**Expected behavior**
Either one:
 1. A message telling me that my input was wrong
 2. It adding the tree(s) to my trees

**Smartphone:**
    Device: Samsung Galaxy S7
    OS: Android 8.0.0
    Samsung Experience version: 9.0
    Plant-for-the-Planet App Version **1.3.4.900030**

Thanks for your time!

**Comment by delightedMatt** [comment]
@norbertschuler I am not sure why this bug persists. Maybe your fix got lost?

**Comment by norbertschuler** [comment]
@delightedMatt sorry, that it is really broken on Android. Maybe @sanjayradadiya can help who also has worked on this.

**Comment by delightedMatt** [comment]
@norbertschuler Thanks Norbert for confirmation, labeling and info!! 

 @sanjayradadiya Do you have any idea what might be cuasing this?

**Comment by norbertschuler** [comment]
I just tested it myself and found out, the button functionality sometimes can be activated again by switching between the single and multi tree tab, but I do not know what's causing it. Also the overall performance of the tree registration page is very slow.

**Comment by norbertschuler** [comment]
While testing this on my Nexus 4 API 27 emulator I also got this error when clicking on the "Add a Tree" button for single tree registration:

![Screenshot_1596001304](https://user-images.githubusercontent.com/1532418/88761332-2342c000-d199-11ea-93f9-5af8891d86a9.png)

**Comment by delightedMatt** [comment]
Thanks a lot for the quick fix! That bug was very close to some anroid users' hearts (mine included).
