### ISSUE TITLE
All WebApp Maps broken - ArcGIS API 

### ISSUE THREAD

**Issue by delightedMatt** [Plant-for-the-Planet-org/treecounter-app#2556]
**All WebApp Maps fail to load the ArcGIS API.**

This is the Production WebApp.

**To Reproduce**
Go to a WebApp Map:

https://www.trilliontreecampaign.org/explore
https://www.trilliontreecampaign.org/register-trees
https://www.trilliontreecampaign.org/my-trees

**Expected behavior**
A Map shows up (the my-trees Map is expected to show up devoid of markers - which is expected but non-optimal).

**What actually happens**
Dialogue window asks for ArcGis credentials.
If closed the Map doesn't load.

**Desktop:**
- Firefox 78.0.2 (64-Bit)

**Screenshots**
![maps_seem_broken_arcgis_api](https://user-images.githubusercontent.com/18365824/88780922-fb009480-d18b-11ea-987e-2ba999372860.PNG)
![maps_seem_broken_register_trees](https://user-images.githubusercontent.com/18365824/88780924-fb992b00-d18b-11ea-9ce6-83a41eafd139.PNG)
![maps_seem_broken_my_trees](https://user-images.githubusercontent.com/18365824/88780928-fc31c180-d18b-11ea-94b6-5efcb8b3b2e5.PNG)

**Comment by norbertschuler** [comment]
We already know about this and @sagararyal has contacted ArcGIS/ESRI about it. We hope to restore the normal functionality as fast as possible.

**Comment by delightedMatt** [comment]
Damn, you are fast Norbert =D
Thanks!

**Comment by norbertschuler** [comment]
Maps are back!
