### ISSUE TITLE
WebApp - Leaderboard - Target Column Values wrong

### ISSUE THREAD

**Issue by delightedMatt** [Plant-for-the-Planet-org/treecounter-app#2557]
**The "Target" Values of entities shown in the Leaderboard are wrong.**
(the screenshot shows this)

**This problem exists on the current production WebApp.**

**To Reproduce**
https://app.plant-for-the-planet.org/leaderboard/company?orderBy=planted&period=1y
https://app.plant-for-the-planet.org/leaderboard/individual?orderBy=planted&period=1w
https://app.plant-for-the-planet.org/leaderboard/education?orderBy=planted&period=1w
https://app.plant-for-the-planet.org/leaderboard/organization?orderBy=planted&period=1y
https://app.plant-for-the-planet.org/leaderboard/country?orderBy=planted&period=1w

The picked Category does not matter much.
Countries behave differently though, than actual tree counters.

The picked Time does not matter.

**Expected behavior**
Either have no "target" column, like in the mobile App.
Or showing the number the Tree Counter shows.
(Breaking the target down to the same time-frame as you want to see the leaderboard of seems also like a solution, but a confusing one)

**What actually happens**
The numbers seem to either be 0, if the entity does not have a tree counter (Countries) 
or the numbers are the same as the planted trees.

**Desktop:**
    Firefox 78.0.2 (64-Bit)

**Screenshots**
![person_target_wrong](https://user-images.githubusercontent.com/18365824/88822280-f0fa8800-d1c3-11ea-95a9-caa8198316d5.PNG)

**Comment by norbertschuler** [comment]
This seems to be a backend problem as the data directly comes from the API call e.g. https://app.plant-for-the-planet.org/public/v1.1/de/exploreQuery/education?orderBy=planted&period=1w resulting into:

```
{
  "data": [
    {
      "contributorType": "education",
      "treecounterId": 141860,
      "contributorSlug": "gymnasium-neubiberg",
      "contributorAvatar": null,
      "planted": 720.0,
      "target": 720.0,
      "mayPublish": true,
      "caption": "Gymnasium Neubiberg",
      "uri": "/t/gymnasium-neubiberg"
    },
    {
      "contributorType": "education",
      "treecounterId": 161323,
      "contributorSlug": "kunstschule-illingen",
      "contributorAvatar": null,
      "planted": 355.0,
      "target": 355.0,
      "mayPublish": true,
      "caption": "Kunstschule Illingen",
      "uri": "/t/kunstschule-illingen"
    }
  ]
}

```
<img width="1317" alt="Bildschirmfoto 2020-07-30 um 13 50 32" src="https://user-images.githubusercontent.com/1532418/88890372-bea46580-d26b-11ea-86f3-bf52436ae195.png">

So the leadership data seems to be wrong and must be updated. The data in the single treecounters is still correct, e.g. https://app.plant-for-the-planet.org/public/v1.1/de/treecounter/gymnasium-neubiberg returning:

```
{
  "id": 141860,
  "displayName": "Gymnasium Neubiberg",
  "slug": "gymnasium-neubiberg",
  "countPlanted": 721.0,
  "countPersonal": 721.0,
  "countReceived": 0.0,
  "countTarget": 1000.0,
  "implicitTarget": 1000.0,
   ...
```

**Comment by delightedMatt** [comment]
@norbertschuler Thanks Norbert! I will post an Issue in the Backend Git

**Comment by harshvitra** [comment]
Closing issue as we do not support old web
