### ISSUE TITLE
SecurityError in /login - Permission denied to access property "dispatchEvent" on cross-origin object

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2558]
## Error in Plant-for-the-Planet App

**SecurityError** in **/login**
Permission denied to access property "dispatchEvent" on cross-origin object

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f22e2122ec8980017320c0c?event_id=5f22e212005b8953b84c0000&i=gh&m=ci)

## Stacktrace

    moz-extension://b02965de-a5cd-49af-aa6f-8e37b54c2904/js/inject.js:65 - onUserInput/<

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f22e2122ec8980017320c0c?event_id=5f22e212005b8953b84c0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
cross-origin problems with Firefox 79.0.0 on Windows 10?

**Comment by norbertschuler** [comment]
Maybe only because of a Firefox extension used: https://stackoverflow.com/questions/55069224/should-i-be-concerned-by-securityerror-permission-denied-to-access-property-on

**Comment by norbertschuler** [comment]
Duplicate of #2661
