### ISSUE TITLE
SecurityError in /donate-trees - Failed to execute 'sendBeacon' on 'Navigator'

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2559]
## Error in Plant-for-the-Planet App

**SecurityError** in **/donate-trees**
Failed to execute 'sendBeacon' on 'Navigator': sendBeacon() with a Blob whose type is not any of the CORS-safelisted values for the Content-Type request header is disabled temporarily. See http://crbug.com/490015 for details.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f2516a25c5e5300170e604e?event_id=5f2516a2005b7ca8d0830000&i=gh&m=ci)

## Stacktrace

    https://static.cloudflareinsights.com/beacon.min.js:1 - Object.i [as sendObjectBeacon]

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f2516a25c5e5300170e604e?event_id=5f2516a2005b7ca8d0830000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Related to #2502

**Comment by norbertschuler** [comment]
Duplicate of #2627

**Comment by Plant-for-the-Planet** [comment]
An error linked to this issue has been reopened in Bugsnag
[**SecurityError** in **/donate-trees**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f2516a25c5e5300170e604e?event_id=5f4e1915005dec37a2bd0000&i=gh&m=ra)

**Comment by norbertschuler** [comment]
CORS issue
