### ISSUE TITLE
Unable to create layer for ReactHorizontalScrollContainerView

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2560]
## Error in Plant-for-the-Planet App

**java.lang.IllegalStateException** in **MessageQueue.java:330**
Unable to create layer for ReactHorizontalScrollContainerView

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f2698122fb3fb001984f855?event_id=5f269812005b6cbe9e6c0000&i=gh&m=ci)

## Stacktrace

    MessageQueue.java:-2 - android.os.MessageQueue.nativePollOnce

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f2698122fb3fb001984f855?event_id=5f269812005b6cbe9e6c0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by fcheong3b** [comment]
Any update about this issue. is it solved in any release? I'm facing this issue in production.

**Comment by norbertschuler** [comment]
> Any update about this issue. is it solved in any release? I'm facing this issue in production.

Sorry, we have not actively tried to find out the reason for this issue in this project.
