### ISSUE TITLE
TypeError in app/components/Authentication/SignUp/SignUp.native.js:45 - null is not an object (evaluating 'o.signupForm.getValue')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2566]
## Error in Plant-for-the-Planet App

**TypeError** in **app/components/Authentication/SignUp/SignUp.native.js:45**
null is not an object (evaluating 'o.signupForm.getValue')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f2e4a0e8b048000198d05aa?event_id=5f2e4a0e005b7597984a0000&i=gh&m=ci)

## Stacktrace

    app/components/Authentication/SignUp/SignUp.native.js:45 - onSignUpClicked
    app/components/Authentication/SignUp/SignUp.native.js:94 - onClick
    app/components/Common/Button/PrimaryButton.native.js:16 - onPress

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f2e4a0e8b048000198d05aa?event_id=5f2e4a0e005b7597984a0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Related to #2663
