### ISSUE TITLE
Error in /home - MetaMask detected another web3

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2572]
## Error in Plant-for-the-Planet App

**Error** in **/home**
MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f323aec2881110017951277?event_id=5f323aec005b6ab769a10000&i=gh&m=ci)

## Stacktrace

    moz-extension://b1f20472-c6e0-4bb9-8426-ebcf5d515af6/inpage.js:1 - [1]</<

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f323aec2881110017951277?event_id=5f323aec005b6ab769a10000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
won't fix bugs with web browser extensions
