### ISSUE TITLE
TypeError in /leaderboard/country - undefined is not an object (evaluating 't.options[t.selectedIndex].value')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2574]
## Error in Plant-for-the-Planet App

**TypeError** in **/leaderboard/country**
undefined is not an object (evaluating 't.options[t.selectedIndex].value')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f32f47b90100e0018b226d1?event_id=5f32f47b005b7e6440540000&i=gh&m=ci)

## Stacktrace

    app/components/Leaderboard/index.js:29 - 
    app/components/Leaderboard/index.js:24 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f32f47b90100e0018b226d1?event_id=5f32f47b005b7e6440540000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Problem with this.refs

**Comment by norbertschuler** [comment]
Web client abandoned.
