### ISSUE TITLE
SecurityError in /donate-trees -Failed to execute 'sendBeacon' on 'Navigator': sendBeacon

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2627]
## Error in Plant-for-the-Planet App

**SecurityError** in **/donate-trees**
Failed to execute 'sendBeacon' on 'Navigator': sendBeacon() with a Blob whose type is not any of the CORS-safelisted values for the Content-Type request header is disabled temporarily. See http://crbug.com/490015 for details.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f3e0075bf4ea40017ee4120?event_id=5f3e0075005e013031b80000&i=gh&m=ci)

## Stacktrace

    https://static.cloudflareinsights.com/beacon.min.js:1 - Object.i [as sendObjectBeacon]

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f3e0075bf4ea40017ee4120?event_id=5f3e0075005e013031b80000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
CORS issue
