### ISSUE TITLE
TypeError in /edit-profile - Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2628]
## Error in Plant-for-the-Planet App

**TypeError** in **/edit-profile**
Cannot read property 'data' of undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f3e41f59db7c50017f0ea9f?event_id=5f3e41f5005e0163987c0000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/28.8f6fd118dff9c3fa204b.js:1 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f3e41f59db7c50017f0ea9f?event_id=5f3e41f5005e0163987c0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
cannot reproduce due to missing source map
