### ISSUE TITLE
Error in /donate-trees - data of response if empty

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2640]
## Error in Plant-for-the-Planet App

**Error** in **/donate-trees**
```
response: 
{
  "data": "",
  "status": 200,
  "statusText": "OK",
  "headers": {
    "cache-control": "max-age=0, must-revalidate, private",
    "cf-cache-status": "DYNAMIC",
    "cf-ray": "5c73dbf0c9340faa-VIE",
    "cf-request-id": "04bc47ca8000000faa7301a200000001",
    "connection": "keep-alive",
    "content-encoding": "br",
    "content-type": "application/json",
    "date": "Sun, 23 Aug 2020 09:38:10 GMT",
    "expect-ct": "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
    "expires": "Sun, 23 Aug 2020 09:38:10 GMT",
    "server": "cloudflare",
    "transfer-encoding": "chunked",
    "vary": "Accept-Encoding",
    "via": "1.1 vegur"
  },
  "config": {
    "url": "https://app.plant-for-the-planet.org/public/v1.1/en/plantProjects/featured",
    "method": "get",
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "X-SESSION-ID": "5b7fffc2-e524-11ea-939b-bbf499b1cc2f"
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1
  },
  "request": {
    "BS~~U": "https://app.plant-for-the-planet.org/public/v1.1/en/plantProjects/featured",
    "BS~~M": "GET",
    "BS~~S": true
  }
}

```
[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f4239032369020017866124?event_id=5f423903005dfe014dcb0000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/bundle.ee141c985c359aa36486.js:1 - checkStatus

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f4239032369020017866124?event_id=5f423903005dfe014dcb0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
![image](https://user-images.githubusercontent.com/1532418/91226458-58551a80-e725-11ea-8195-d55406cab9dd.jpeg)

No more errors since August 24th.

**Comment by norbertschuler** [comment]
Currently the errors are tracked in the linked issue https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/2615

**Comment by norbertschuler** [comment]
While this error soon will reach the 10.000th event, I recognized the API calls are now mostly https://app.plant-for-the-planet.org/public/v1.1/en/plantProjects/featured or https://app.plant-for-the-planet.org/public/v1.1/en/currencies while the config API call has vanished from the events since me moved it to Cloudflare. And the request for which the API calls failed is still mostly https://www.trilliontreecampaign.org/donate-trees.

**Comment by norbertschuler** [comment]
It seems every failed call of https://app.plant-for-the-planet.org/public/v1.1/en/plantProjects/featured also shows a failed call to https://app.plant-for-the-planet.org/public/v1.1/en/currencies in his breadcrumbs (but not the other way round):
<img width="1374" alt="Bildschirmfoto 2020-09-30 um 10 55 14" src="https://user-images.githubusercontent.com/1532418/94664774-7ff75e00-0335-11eb-8cb1-3052151bde4c.png">

**Comment by norbertschuler** [comment]
This error probably resulted from only a few bot systems of https://zulu5.com/ checking https://www.trilliontreecampaign.org/donate-trees and not supporting CORS correctly.
