### ISSUE TITLE
SecurityError in /login - Permission denied to access property "dispatchEvent" on cross-origin object

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2661]
## Error in Plant-for-the-Planet App

**SecurityError** in **/login**
Permission denied to access property "dispatchEvent" on cross-origin object

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f4357a6d5c22e001775a520?event_id=5f4357a6005df4683e680000&i=gh&m=ci)

## Stacktrace

    moz-extension://74e539bd-4575-43c3-88bc-461f1d80333a/js/inject.js:65 - onUserInput/<

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f4357a6d5c22e001775a520?event_id=5f4357a6005df4683e680000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Maybe only because of a Firefox extension used: https://stackoverflow.com/questions/55069224/should-i-be-concerned-by-securityerror-permission-denied-to-access-property-on
