### ISSUE TITLE
TypeError in /donate-trees/1 - undefined is not an object (evaluating 'window.webkit.messageHandlers')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2672]
## Error in Plant-for-the-Planet App

**TypeError** in **/donate-trees/1**
undefined is not an object (evaluating 'window.webkit.messageHandlers')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f454ec400127f0019a095ff?event_id=5f454ec4005dfd65f0c90000&i=gh&m=ci)

## Stacktrace

    user-script:1:25 - sendWebKitMessage

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f454ec400127f0019a095ff?event_id=5f454ec4005dfd65f0c90000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Looks like a bug in a user-script.
