### ISSUE TITLE
TypeError in /signup - Q.$ is null

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2674]
## Error in Plant-for-the-Planet App

**TypeError** in **/signup**
Q.$ is null

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f46a0a15a49260018bf48ec?event_id=5f46a0a1005dfe32ef7a0000&i=gh&m=ci)

## Stacktrace

    node_modules/react-native/Libraries/Performance/SamplingProfiler.js:39 - J</</l<

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f46a0a15a49260018bf48ec?event_id=5f46a0a1005dfe32ef7a0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
another form a recaptcha error which we already have in other issue as #2706
