### ISSUE TITLE
ReferenceError in /donate-trees/1 - Can't find variable: Intl

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2683]
## Error in Plant-for-the-Planet App

**ReferenceError** in **/donate-trees/1**
Can't find variable: Intl

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f482c430afe7d00179fae53?event_id=5f482c43005e04fd3e560000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/15.ee141c985c359aa36486.js:1 - getMonthsForLocale

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f482c430afe7d00179fae53?event_id=5f482c43005e04fd3e560000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
source map missing
