### ISSUE TITLE
TypeError in /explore - undefined is not an object (evaluating 'e.state.mapDescriptionInfoMap[t].description')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2685]
## Error in Plant-for-the-Planet App

**TypeError** in **/explore**
undefined is not an object (evaluating 'e.state.mapDescriptionInfoMap[t].description')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f48d1be6dd99d0018b57d52?event_id=5f48d1be005dfd40329c0000&i=gh&m=ci)

## Stacktrace

https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/1ea6b63f7faecce0f5a6c77600af37b670fc2ac4/app/components/Leaderboard/MapTab.js#L67

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f48d1be6dd99d0018b57d52?event_id=5f48d1be005dfd40329c0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
This happens when navigating from the _Map_ to the _Leaderboard_ and back to the _Map_. The preselected checkbox has changed from "Planted trees" to "Current forests" and if you click on "Planted trees" against the web client crashes.

**Comment by norbertschuler** [comment]
Bug seems to have been introduced by https://github.com/Plant-for-the-Planet-org/treecounter-app/commit/b384e2a72360bf1e1a4cd8f8642e36718ecbbd74#diff-fd1b8534ef691d31eee163d53289f8ccL27 by modifying the properties instead of getting the values of it.
