### ISSUE TITLE
TypeError in / - Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2690]
## Error in Plant-for-the-Planet App

**TypeError** in **/**
Cannot read property 'replace' of undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f4940902d51300017769583?event_id=5f494090005debd762160000&i=gh&m=ci)

## Stacktrace

    app/components/Menu/index.js:287 - Menu.render
    app/containers/Menu/SideMenuContainer.js:42 - SafeSubscriber._next
    app/layouts/sideMenu.js:12 - 

https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/d7820a24a1bb4fba6c82f6ac2401418e58bc3b59/app/components/Menu/index.js#L287

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f4940902d51300017769583?event_id=5f494090005debd762160000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Probably getLocale() has not been able to retrieve a locale value. A default value should always be returned to avoid such crashes as this one.

**Comment by norbertschuler** [comment]
Usually the getLocal() function for the web client is not working asynchronously and therefore should always return a local or 'en' as default. I can not reproduce how `undefined` can be returned.

**Comment by norbertschuler** [comment]
Trying to make it more failsafe with https://github.com/Plant-for-the-Planet-org/treecounter-app/commit/f5646861c8544abaf1d0f4f531c28f876a995835
