### ISSUE TITLE
Support for iOS <10 and older Samsung browser? (Object.values, Intl.DateTimeFormat and Intl.NumberFormat)

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2693]
## Error in Plant-for-the-Planet App

**TypeError** in **/**
Object.values is not a function. (In 'Object.values(t)', 'Object.values' is undefined)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f49de6b48495900174449a7?event_id=5f49de6b005dfe7e9f360000&i=gh&m=ci)

## Stacktrace

    app/components/Common/SvgContainer.js:124 - componentDidMount
    app/components/TreecounterGraphics/Trillion.js:33 - 

https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/d7820a24a1bb4fba6c82f6ac2401418e58bc3b59/app/components/Common/SvgContainer.js#L124

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f49de6b48495900174449a7?event_id=5f49de6b005dfe7e9f360000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
This error might also be because of problem with `this.refs` at https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/d7820a24a1bb4fba6c82f6ac2401418e58bc3b59/app/components/Common/SvgContainer.js#L109 and therefore related to the issue https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/2479.

**Comment by Plant-for-the-Planet** [comment]
Maybe window.Intl is not defined on iOS 9.3?

Comment added in Bugsnag by Norbert Schuler
[**TypeError** in **/**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f49de6b48495900174449a7?event_id=5f7a04ee0061680e143b0000&i=gh&m=cm)

**Comment by norbertschuler** [comment]
Error happening only on older devices (Android 5.1, 6.0, iOS 9.3):
<img width="486" alt="Bildschirmfoto 2020-10-13 um 09 10 46" src="https://user-images.githubusercontent.com/1532418/95827410-ea5cc500-0d5d-11eb-8768-9d3f47baa9b7.png">

**Comment by norbertschuler** [comment]
Probably `Object.values` (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values) is not defined on older devices, e.g. iOS 9.3 resulting into our website to fail to load on older devices not compatible:

<img width="416" alt="Bildschirmfoto 2020-10-18 um 13 35 10" src="https://user-images.githubusercontent.com/1532418/96366278-de636f80-1170-11eb-8c2c-9d7d3d854131.png">

**Comment by norbertschuler** [comment]
Intl (https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Intl) is also not defined on iOS 9.3 - we are using `Intl.DateTimeFormat` and `Intl.NumberFormat` in our current source code.
