### ISSUE TITLE
Error in /treecounter-widget/js/pftpTreeCounterWidget - Request aborted

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2717]
## Error in Plant-for-the-Planet App

**Error** in **/treecounter-widget/js/pftpTreeCounterWidget**
Request aborted

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f5bb16a6cab2a0017640f4f?event_id=5f5bb16a005df29733ef0000&i=gh&m=ci)

## Stacktrace

    https://app-development.plant-for-the-planet.org/bundle.2b5f3080a1febedd9ed2.js:2 - createError

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f5bb16a6cab2a0017640f4f?event_id=5f5bb16a005df29733ef0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
probably temporarily error due to change in backend
