### ISSUE TITLE
TypeError in /donate-trees - undefined is not an object (evaluating 'j.name.toLowerCase')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2721]
## Error in Plant-for-the-Planet App

**TypeError** in **/donate-trees**
undefined is not an object (evaluating 'j.name.toLowerCase')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f5e5ed14ae28800187bd3d5?event_id=5f5e5ed1005e0170afd20000&i=gh&m=ci)

## Stacktrace

    app/containers/SelectPlantProject/index.js:140 - mapStateToProps
    app/actions/loadTposAction.js:31 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f5e5ed14ae28800187bd3d5?event_id=5f5e5ed1005e0170afd20000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Probable a project without a name was returned by the API. I will close this for now and see if it happens again (issue would be automatically reopened).
