### ISSUE TITLE
Error in /donate-trees - out of memory

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2726]
## Error in Plant-for-the-Planet App

**Error** in **/donate-trees**
out of memory

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f617af8a7fbce001a4c0a51?event_id=5f617af8005df3969d570000&i=gh&m=ci)

## Stacktrace

    app/components/ErrorBoundry/bodyErrorBoundry.js:48 - componentDidCatch
    app/containers/SelectPlantProject/index.js:66 - _callee2$

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f617af8a7fbce001a4c0a51?event_id=5f617af8005df3969d570000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Can not help oom problem.
