### ISSUE TITLE
EXC_BAD_ACCESS in gmscore::renderer::TextureState::InitTextureStrategy::InitTextureAndUploadImageData(gmscore::base::reffed_ptr<gmscore::renderer::ImageData> const&, unsigned int) const

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2733]
## Error in Plant-for-the-Planet App

**EXC_BAD_ACCESS** in **gmscore::renderer::TextureState::InitTextureStrategy::InitTextureAndUploadImageData(gmscore::base::reffed_ptr<gmscore::renderer::ImageData> const&, unsigned int) const**
Attempted to dereference garbage pointer 0x41a80008.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f687106c1396400172f3447?event_id=5f687106005defc2cfa30000&i=gh&m=ci)

## Stacktrace

    TreecounterApp:0 - gmscore::renderer::TextureState::InitTextureStrategy::InitTextureAndUploadImageData(gmscore::base::reffed_ptr<gmscore::renderer::ImageData> const&, unsigned int) const
    TreecounterApp:0 - gmscore::renderer::TextureState::Initialize(gmscore::renderer::TextureState::InitTextureStrategy const&)
    TreecounterApp:0 - gmscore::renderer::TextureState::TextureState(gmscore::base::reffed_ptr<gmscore::renderer::ImageData> const&, gmscore::renderer::TextureState::WrapMode, gmscore::renderer::TextureState::WrapMode)
    TreecounterApp:0 - -[GMSVectorMapSharedResources routeTextureState]
    TreecounterApp:0 - -[GMSVectorMapSharedResources init]
    TreecounterApp:0 - -[GMSVectorMapSharedResourceCache resources]
    TreecounterApp:0 - __39-[GMSVectorMapSharedResourceCache init]_block_invoke

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f687106c1396400172f3447?event_id=5f687106005defc2cfa30000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
cannot fix native crash
