### ISSUE TITLE
Do not allow to donate to project with allowdonations flag set to false

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#2737]
**Describe the bug**

In the TTC client the projects returned by https://app.plant-for-the-planet.org/public/v1.1/en/plantProjects?loadAll=true&limit=100 do not get checked for the flag `allowdonations` not being `false` to avoid donating to unwanted projects not allowed to.

**Is it on a Production or Development Build?**
production

**To Reproduce**
1. Go to https://www.trilliontreecampaign.org/donate-trees (make sure projects with `"allowdonations":false` are part of the list)
2. Try to donate

**Expected behavior**
Check the `allowdonations` field of the response.

**Comment by jmiridis** [comment]
Has this been fixed client side? Trying to replicate the error using Weforest
https://development.trilliontreecampaign.org/t/weforest
does not take me to the donation page anymore.

**Comment by norbertschuler** [comment]
> Has this been fixed client side? Trying to replicate the error using Weforest
> 
> https://development.trilliontreecampaign.org/t/weforest
> 
> does not take me to the donation page anymore.

The TTC client has not been changed.

**Comment by jmiridis** [comment]
Backend will return 400 when project does not allow donations.
Fixed here:
https://github.com/Plant-for-the-Planet-org/treecounter-platform/commit/c48dc833137def4d3865e711df0a7522acd5fce4

**Comment by norbertschuler** [comment]
https://app.plant-for-the-planet.org/public/v1.1/en/plantProjects?loadAll=true&limit=100 is currently not returning any projects with `"allowdonations": false`.
