### ISSUE TITLE
SecurityError in /support/youtopia - Permission denied to access property "dispatchEvent" on cross-origin object

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2753]
## Error in Plant-for-the-Planet App

**SecurityError** in **/support/youtopia**
Permission denied to access property "dispatchEvent" on cross-origin object

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f74f72bbe59fc00170a0286?event_id=5f74f72b00611799af270000&i=gh&m=ci)

## Stacktrace

    moz-extension://0aba6152-bf19-4899-9c56-6715fca78718/js/inject.js:65 - onUserInput/<

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f74f72bbe59fc00170a0286?event_id=5f74f72b00611799af270000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Problem with Firefox 81.0.0
