### ISSUE TITLE
TypeError in index.android.bundle:1 - Object is not a function (onPanResponderMove)

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2759]
## Error in Plant-for-the-Planet App

**TypeError** in **index.android.bundle:1**
Object is not a function

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f77acb871e76d001750b898?event_id=5f77acb8006169c669ae0000&i=gh&m=ci)

## Stacktrace

    index.android.bundle:1 - onPanResponderMove

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f77acb871e76d001750b898?event_id=5f77acb8006169c669ae0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
This error must happen in one of the used npm modules as we have no source map to identify it:

<img width="568" alt="Bildschirmfoto 2020-10-18 um 14 30 21" src="https://user-images.githubusercontent.com/1532418/96367496-626d2580-1178-11eb-8a86-1bc3fd5c3dca.png">

**Comment by Plant-for-the-Planet** [comment]
An error linked to this issue has been reopened in Bugsnag
[**TypeError** in **index.android.bundle:1**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f77acb871e76d001750b898?event_id=600859960069a7dedbcf0000&i=gh&m=ra)

**Comment by Plant-for-the-Planet** [comment]
An error linked to this issue has been reopened in Bugsnag
[**TypeError** in **index.android.bundle:1**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f77acb871e76d001750b898?event_id=6112acae007f9b3dcd1b0000&i=gh&m=ra)

**Comment by Plant-for-the-Planet** [comment]
An error linked to this issue has been reopened in Bugsnag
[**TypeError** in **index.android.bundle:1**](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f77acb871e76d001750b898?event_id=613a19f900808d9cab570000&i=gh&m=ra)
