### ISSUE TITLE
ChunkLoadError in /login

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2765]
## Error in Plant-for-the-Planet App

**ChunkLoadError** in **/login**
Loading chunk 27 failed.
(error: https://www.weplant.app/27.ee141c985c359aa36486.js)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f7846fc12d32e0017502562?event_id=5f7846fc00615bba89ed0000&i=gh&m=ci)

## Stacktrace

    app/components/App/TreeCounter.js:38 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f7846fc12d32e0017502562?event_id=5f7846fc00615bba89ed0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
ChunkLoadError
