### ISSUE TITLE
TypeError in /donate-trees - Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2776]
## Error in Plant-for-the-Planet App

**TypeError** in **/donate-trees**
Cannot read property 'toLowerCase' of undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f7d2ac5410867001899fc2f?event_id=5f7d2ac500614de293c50000&i=gh&m=ci)

## Stacktrace

    app/components/SelectPlantProject/index.js:117 - 
    app/components/SelectPlantProject/index.js:114 - SelectPlantProject.onInputChange

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f7d2ac5410867001899fc2f?event_id=5f7d2ac500614de293c50000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
same as #2721
