### ISSUE TITLE
SecurityError in /C:/Users/croco/Downloads/B%C3%A4ume%20spenden%20Trillion%20Tree%20Campaign.html

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2777]
## Error in Plant-for-the-Planet App

**SecurityError** in **/C:/Users/croco/Downloads/B%C3%A4ume%20spenden%20Trillion%20Tree%20Campaign.html**
The operation is insecure.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f7dcbb53ad886001822399f?event_id=5f7dcbb500616a1dc8510000&i=gh&m=ci)

## Stacktrace

    file:///C:/Users/croco/Downloads/B%C3%A4ume%20spenden%20Trillion%20Tree%20Campaign-Dateien/bundle.js:2 - wrapHistoryFn/q[$]

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f7dcbb53ad886001822399f?event_id=5f7dcbb500616a1dc8510000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
User tries to run our source locally - probably saved the website from the browser.
