### ISSUE TITLE
Error in / - crypto.getRandomValues() not supported

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2793]
## Error in Plant-for-the-Planet App

**Error** in **/**
crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f83e4a5717a66001748eb85?event_id=5f83e4a500615996977d0000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/bundle.ee141c985c359aa36486.js:1 - rng

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f83e4a5717a66001748eb85?event_id=5f83e4a500615996977d0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
For our native app I added the solution suggested in the above link, but the the web client I do not know what polyfill to use to solve this compatibility issue.
