### ISSUE TITLE
DataCloneError in / The object can not be cloned.

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2801]
## Error in Plant-for-the-Planet App

**DataCloneError** in **/**
The object can not be cloned.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f84c02d81b1ba0018d9cd43?event_id=5f84c02d00615fa0dad10000&i=gh&m=ci)

## Stacktrace

    [native code]:0 - postMessage

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f84c02d81b1ba0018d9cd43?event_id=5f84c02d00615fa0dad10000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Sorry. Cannot support user scripts.
