### ISSUE TITLE
SecurityError in /Users/jenscarstengebhardt/Desktop/Willkommen%20%7C%20Trillion%20Tree%20Campaign.webarchive

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2824]
## Error in Plant-for-the-Planet App

**SecurityError** in **/Users/jenscarstengebhardt/Desktop/Willkommen%20%7C%20Trillion%20Tree%20Campaign.webarchive**
Blocked attempt to use history.pushState() to change session history URL from file:///Users/jenscarstengebhardt/Desktop/Willkommen%20%7C%20Trillion%20Tree%20Campaign.webarchive to file:///donate-trees. Paths and fragments must match for a sandboxed document.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f8fe628ff39ab00172d4558?event_id=5f8fe62800616204652f0000&i=gh&m=ci)

## Stacktrace

    [native code]:1 - pushState

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f8fe628ff39ab00172d4558?event_id=5f8fe62800616204652f0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Cannot supported locally saved application.
