### ISSUE TITLE
TypeError in /donate-trees/1 - AppJsInterface.isMediaInterceptInjectAlreadyDone is not a function

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2831]
## Error in Plant-for-the-Planet App

**TypeError** in **/donate-trees/1**
AppJsInterface.isMediaInterceptInjectAlreadyDone is not a function

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f9489936e2ba400172dac8e?event_id=5f9489930062273591e90000&i=gh&m=ci)

## Stacktrace

    global code:103 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f9489936e2ba400172dac8e?event_id=5f9489930062273591e90000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Web client abandoned.
