### ISSUE TITLE
TypeError in /donate-trees/1 - null is not an object (evaluating 'document.getElementById('og_head').style')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2832]
## Error in Plant-for-the-Planet App

**TypeError** in **/donate-trees/1**
null is not an object (evaluating 'document.getElementById('og_head').style')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f975c466bb5f000184ecfd0?event_id=5f975c460062214581f20000&i=gh&m=ci)

## Stacktrace

    src/main/resources/embeddable/widget/embed.ts:20 - 
    src/main/resources/embeddable/widget/embed.ts:9 - t
    src/main/resources/embeddable/widget/embed.ts:78 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f975c466bb5f000184ecfd0?event_id=5f975c460062214581f20000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Web client abandoned.
