### ISSUE TITLE
RangeError in /donate-trees - Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2833]
## Error in Plant-for-the-Planet App

**RangeError** in **/donate-trees**
Maximum call stack size exceeded

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f97c71ca1f22200184ac91a?event_id=5f97c71c006229128d4b0000&i=gh&m=ci)

## Stacktrace

    node_modules/react-slick/lib/inner-slider.js:390 - InnerSlider.Array.forEach.call.e.onclick

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f97c71ca1f22200184ac91a?event_id=5f97c71c006229128d4b0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Web client abandoned.
