### ISSUE TITLE
points vanishing at given zoom level of the explore map

### ISSUE THREAD

**Issue by sthenault** [Plant-for-the-Planet-org/treecounter-app#2834]
I wish to look up fo the restoration opportunities near my home in France (in Nailloux, near Toulouse) through the explore map (https://www.trilliontreecampaign.org/explore), but when I reach a given zoom level, points on the map are vanishing. 

**To Reproduce**
1. Go to https://www.trilliontreecampaign.org/explore)
2. Select  current forest and restoration opportunities as well
3. Scroll down to level 6
4. Only planted tree remains, both current forest and restoration opportunities points disappears 

**Desktop (please complete the following information):**
- OS: linux
- Browser: chrome / firefox

**Comment by norbertschuler** [comment]
@sthenault I can reproduce this behavior:

(1) last zoom level showing restoration opportunities:

<img width="812" alt="Bildschirmfoto 2020-10-27 um 09 43 37" src="https://user-images.githubusercontent.com/1532418/97277669-587bae80-186b-11eb-998f-1c86b2cc7943.png">

(2) not showing any more restoration opportunities:

<img width="813" alt="Bildschirmfoto 2020-10-27 um 09 43 47" src="https://user-images.githubusercontent.com/1532418/97277690-616c8000-186b-11eb-893a-8cfca97246da.png">

Probably this is defined at the used ARCGis map https://trilliontrees.maps.arcgis.com/home/item.html?id=d601683709dc415b99ddc1bc66a6d8eb - I think the data is not that detailed, so it is just shown for the zoom level the data can still support. @jmiridis @sagararyal  do you know more?

**Comment by norbertschuler** [comment]
Closing as we do not support old web client anymore.
