### ISSUE TITLE
ReferenceError in /donate-trees/1 - customDispatchEvent is not defined

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2837]
## Error in Plant-for-the-Planet App

**ReferenceError** in **/donate-trees/1**
customDispatchEvent is not defined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f99871e0e0fe0001768bfc8?event_id=5f99871e00622d4de3ed0000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/donate-trees/1:40 - HTMLIFrameElement.elm.onload

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f99871e0e0fe0001768bfc8?event_id=5f99871e00622d4de3ed0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Web client abandoned.
