### ISSUE TITLE
Error in /donate-trees - TypeError: undefined is not an object (evaluating 'n.manager')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2839]
## Error in Plant-for-the-Planet App

**Error** in **/donate-trees**
TypeError: undefined is not an object (evaluating 'n.manager')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f9ae07a5733880018b874e9?event_id=5f9ae07a006222c5baf90000&i=gh&m=ci)

## Stacktrace

    [native code]:1 - dispatchEvent

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f9ae07a5733880018b874e9?event_id=5f9ae07a006222c5baf90000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Web client abandoned.
