### ISSUE TITLE
TypeError in /donate-trees - Cannot read property 'paymentMethods' of undefined

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2840]
## Error in Plant-for-the-Planet App

**TypeError** in **/donate-trees**
Cannot read property 'paymentMethods' of undefined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f9c313fc807590017b9e3b9?event_id=5f9c313f006279f6b3830000&i=gh&m=ci)

## Stacktrace

    app/components/DonateTrees/index.js:431 - DonateTrees.render

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5f9c313fc807590017b9e3b9?event_id=5f9c313f006279f6b3830000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Probably the project returned by the API is missing payment methods for the chosen currency/country combination:
https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/f5646861c8544abaf1d0f4f531c28f876a995835/app/components/DonateTrees/index.js#L432

**Comment by norbertschuler** [comment]
Web client abandoned.
