### ISSUE TITLE
java.lang.IndexOutOfBoundsException in MainActivity - getChildDrawingOrder() returned invalid index 25 (child count is 25)

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2844]
## Error in Plant-for-the-Planet App

**java.lang.IndexOutOfBoundsException** in **MainActivity**
getChildDrawingOrder() returned invalid index 25 (child count is 25)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5fa3dd4cfdc90a0017300b56?event_id=5fa3dd4c006218e5eeeb0000&i=gh&m=ci)

## Stacktrace

    ViewGroup.java:1988 - android.view.ViewGroup.getAndVerifyPreorderedIndex

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5fa3dd4cfdc90a0017300b56?event_id=5fa3dd4c006218e5eeeb0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by vincentssn** [comment]
Hi，May I have a question for: Have this prob been solved? And how to solve this prob? We met the same prob in our proj.

**Comment by norbertschuler** [comment]
> Hi，May I have a question for: Have this prob been solved? And how to solve this prob? We met the same prob in our proj.

Sorry, no. We closed it without solving.
