### ISSUE TITLE
TypeError in app/components/DonateTrees/index.native.js:309 - undefined is not an object (evaluating 'p.currency_rates[c.currency].rates')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#3005]
## Error in Plant-for-the-Planet App

**TypeError** in **app/components/DonateTrees/index.native.js:309**
undefined is not an object (evaluating 'p.currency_rates[c.currency].rates')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/6083b7d6c1dffc0007f8666c?event_id=6083b7d60077bd8a04d50000&i=gh&m=ci)

## Stacktrace

    app/components/DonateTrees/index.native.js:309 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/6083b7d6c1dffc0007f8666c?event_id=6083b7d60077bd8a04d50000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Make it more failsafe: https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/0b651e7ff50affd56010385e5dcb12973429dee0/app/components/DonateTrees/index.native.js#L309
