### ISSUE TITLE
Challenge friends does not work any more

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#3059]
**Describe the bug**
Challenging a fried currently does not work any more with the development backend as the API responses with a 400 error:

```
# HTTP request for app-development.plant-for-the-planet.org/api/v1.1/de/challenge (ID: -1580440978003816000)
  ## Request
  HTTP POST https://app-development.plant-for-the-planet.org/api/v1.1/de/challenge
  User-Agent: TreecounterApp/ios/1.4.3
Accept: application/json, text/plain, */*
Authorization: Bearer ***
x-session-id: 3e8352b0-cf4c-11eb-943f-eff52a8dc1af
Content-Type: application/json;charset=utf-8

{"challenged":91407,"endDate":2022,"challengeMethod":"direct","goal":1000}

  ## Response
  HTTP 400 bad request
  Content-Type: application/json
Alt-Svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400, h3=":443"; ma=86400
Via: 1.1 vegur
Server: cloudflare
Expires: Thu, 15 Jul 2021 13:05:43 GMT
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Cache-Control: max-age=0, must-revalidate, private
Date: Thu, 15 Jul 2021 13:05:43 GMT
Strict-Transport-Security: max-age=2592000; includeSubDomains; preload
cf-ray: 66f334309969417a-HAM
Vary: Accept-Encoding

{"code":400,"message":"Validation Failed","errors":{"children":{"goal":{"errors":["Missing donation receipt"]},"endDate":{},"message":{},"challengeMethod":{},"challenged":{},"invitee":{"children":{"firstname":{},"lastname":{},"email":{}}}}}}
```
Challenging a user by entering name and mail manually still works.

**Is it on a Production or Development Build?**
develop

**To Reproduce**
1. Go to 'Challenge'
2. Select a user to challenge
3. Enter tree amount and select country
4. Click the button
5. See error

**Screenshots**
![Simulator Screen Shot - iPhone 11 - 2021-07-15 at 15 06 16](https://user-images.githubusercontent.com/1532418/125793519-cea15725-6cbd-4015-a360-323277383552.png)

**Smartphone (please complete the following information):**
- Device: iPhone 11 Simulator
- OS: latest iOS
- Plant-for-the-Planet App Version: 1.4.3

**Comment by jmiridis** [comment]
The error message is not related to the error, apparently this is code copied from some other place. Sins from the past 🤕 
![image](https://user-images.githubusercontent.com/1295390/126036458-f4ffbae0-6b96-4a0b-a1e8-01a391b4d451.png)

On the other hand, the validation itself seems to be correct, it is just the misleading messages that throw the client off.
