### ISSUE TITLE
android.util.AndroidRuntimeException in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#3092]
## Error in Plant-for-the-Planet App

**android.util.AndroidRuntimeException** in **MainActivity**
android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/611a31673bc4ff00089a0882?event_id=611a3167007f8315c84c0000&i=gh&m=ci)

## Stacktrace

    WebViewFactory.java:435 - android.webkit.WebViewFactory.getProviderClass

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/611a31673bc4ff00089a0882?event_id=611a3167007f8315c84c0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Our app does not work without a WebView.
