### ISSUE TITLE
NSInvalidArgumentException in _CFThrowFormattedException

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#3149]
## Error in Plant-for-the-Planet App

**NSInvalidArgumentException** in **_CFThrowFormattedException**
*** -[__NSDictionaryM setObject:forKey:]: object cannot be nil (key: title)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/61e2c8122302000008367e7d?event_id=61e2c812008c2e8704260000&i=gh&m=ci)

## Stacktrace

    Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation:0 - __exceptionPreprocess

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/61e2c8122302000008367e7d?event_id=61e2c812008c2e8704260000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Crashed on MacBookPro17,1
