### ISSUE TITLE
Documentation for MyTrees Cards

### ISSUE THREAD

**Issue by jmiridis** [Plant-for-the-Planet-org/treecounter-app#416]
Contributions and Gifts are different entities and therefore stored separately in Redux store.
When retrieved to be displayed to the user, they must be merged into a single array, sorted by date and extended with a property `category` with value `contribution` or `gift` so they can be distinguished in the rendering code.

The following tables show the data provided by the APIs and the data which must be rendered based on that data. 

![image](https://user-images.githubusercontent.com/1295390/48093595-c8578100-e1dd-11e8-998a-802071edb109.png)

![image](https://user-images.githubusercontent.com/1295390/48093612-d3121600-e1dd-11e8-9aa4-49d32c6aff6e.png)

![image](https://user-images.githubusercontent.com/1295390/48093632-e45b2280-e1dd-11e8-9ded-496f5a006dad.png)

**Comment by sagararyal** [comment]
Reopening the issue for Implementation in Mobile.

**Comment by norbertschuler** [comment]
Save in https://github.com/Plant-for-the-Planet-org/treecounter-app/wiki/MyTrees-Cards
