### ISSUE TITLE
Currency is being cut off, despite screen having a lot of white space.

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#471]
In the screen below.

Currency is being cut off. It should show to two decimal points.
The Currency dropdown, needs to be a dropdown, it is not intuitive at all.

![img_cd3f5a4aca9e-2](https://user-images.githubusercontent.com/5401575/48671636-c53c8900-eb2b-11e8-82dd-f66150dff0f4.jpeg)

**Comment by norbertschuler** [comment]
@sagararyal I remember I already once changed the layout of this page (only a little bit). Can you have a look at decide if it already resolves this issue?
