### ISSUE TITLE
Treecounter shows wrong data

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#487]
To produce it,
Visit https://www.trilliontreecampaign.org/t/don-charlotte-macken
Search: sagar aryal
 and click on it.

you"ll get something like below.

<img width="1665" alt="screen shot 2018-11-19 at 2 43 25 pm" src="https://user-images.githubusercontent.com/5401575/48710781-bb895300-ec09-11e8-9bc4-497ee3be007f.png">

Instead it should show like below: 

<img width="1043" alt="screen shot 2018-11-19 at 2 46 48 pm" src="https://user-images.githubusercontent.com/5401575/48710887-04410c00-ec0a-11e8-8816-b198961dffdd.png">

**Comment by norbertschuler** [comment]
Confirmed the error still exists.
