### ISSUE TITLE
Connect with Stripe Button

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#512]
Jorgo has worked on a button that will allow TPOs to connect with Stripe so they can start receiving donations.

For now, keep this button in Edit Profile for TPOs

Once the TPO Dashboard is ready in January we will put it there.

Please speak with Jorgo for details.

Here's docs he has prepared:
https://github.com/Plant-for-the-Planet-org/treecounter-platform/issues/200

**Comment by norbertschuler** [comment]
@sagararyal Is this still an issue? I do not see any button in Edit Profile for TPOs.
