### ISSUE TITLE
Back does not really take back

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#568]
medium priority iOS

https://trilliontrees.slack.com/files/UC52TRSH2/FEEFK8GQJ/back_does_not_really_take_back.mov

https://trilliontrees.slack.com/files/UC52TRSH2/FEDT9EGSV/back_does_not_really_take_back_v2.mov

**Comment by norbertschuler** [comment]
@sagararyal still and issue or should be closed?

**Comment by norbertschuler** [comment]
This can become part of a general refactoring of the navigation of the app.

**Comment by sagararyal** [comment]
Lets close this, this has been rethought in most new designs.
