### ISSUE TITLE
App text cut in real iphone

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#600]
Could be a responsive issue, when iPhone is used in zoom mode.

pictures below: for version 1.0.1

![20181202_094729](https://user-images.githubusercontent.com/5401575/49439936-acd29c80-f7c2-11e8-9a8a-d2dcbe7819bd.jpg)
![20181202_094723](https://user-images.githubusercontent.com/5401575/49439937-acd29c80-f7c2-11e8-8376-8498ea8aa25d.jpg)
![20181202_094716](https://user-images.githubusercontent.com/5401575/49439938-acd29c80-f7c2-11e8-8634-76dd5359082f.jpg)
![20181202_094710](https://user-images.githubusercontent.com/5401575/49439941-ad6b3300-f7c2-11e8-9673-b6fea25f4285.jpg)

**Comment by norbertschuler** [comment]
If the user decides to increase the font size on its iPhone using a really large font there isn't very much we can do - other app layouts are destroyed too. We probably can only support a certain font size. @sagararyal I would like to close this issue.

![Simulator Screen Shot - iPhone X - 2019-09-23 at 15 47 04](https://user-images.githubusercontent.com/1532418/65431258-74678200-de19-11e9-9f40-3e04f1deb2f8.png)
![Simulator Screen Shot - iPhone X - 2019-09-23 at 15 47 19](https://user-images.githubusercontent.com/1532418/65431260-74678200-de19-11e9-973f-3dfa1dff4e60.png)
![Simulator Screen Shot - iPhone X - 2019-09-23 at 15 47 25](https://user-images.githubusercontent.com/1532418/65431262-74678200-de19-11e9-9b80-df17b1bd6e20.png)
