### ISSUE TITLE
Web: User Home + My Trees Page

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#839]
OLD :: Design is available at: https://zpl.io/bA7XZAP

New Design: 
https://zpl.io/VK6P6jE
https://zpl.io/Vxrl4Z3

You may want to review http://trilliontreecampaign.org/home 
https://www.trilliontreecampaign.org/my-trees

Recurrent Donations API is not yet available. You can still create UI.

for `All Contributions` there is an API, you can copy implementation from `My Trees` Page

All the contribution cards can be clicked, it will take user to a different page with details about the contribution.

Delete shows up a popup, (there should be preexisting popup component) (implemented in My Trees Page)
Edit should redirect user to new page to edit (currently exists).

**Comment by mahmed0715** [comment]
@sagararyal writing some more explanations to the ticket would help. Thanks

**Comment by mahmed0715** [comment]
@sagararyal is there other issues with fonts or css? I knew there we should show the scrollbar in right side to make the height of both side same..

**Comment by mahmed0715** [comment]
@sagararyal still need the details UI design.

**Comment by mahmed0715** [comment]
@sagararyal please link up the designs,

**Comment by Plant-for-the-Planet** [comment]
https://zpl.io/VK6P6jE
https://zpl.io/Vxrl4Z3

**Comment by mahmed0715** [comment]
@sagararyal I need some information about some concepts,
Like what are dedicated/gifted/planted/donated etc

Contributors are the person who has given(donation/gift etc) to the certain user tree counter? we need to find out from the contributions list, right?

And the last part is Tree planting Projects , there are no list or anything in the design. can you please let me know more about all those.. Please
