### ISSUE TITLE
Translation: Home - not enough space for text (formerly missing translations)

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#848]
I am missing translation resources for `label.dedicate_trees`, `label.dedicate_tootltip` and `label.pick_profile` as seen in the following screenshot:

<img width="1177" alt="Bildschirmfoto 2019-05-31 um 14 30 49" src="https://user-images.githubusercontent.com/6512255/58705879-c559f300-83b0-11e9-94a4-0f7a1b8ab02e.png">

**Comment by norbertschuler** [comment]
Seems to be fixed:
<img width="318" alt="Bildschirmfoto 2019-08-29 um 13 44 03" src="https://user-images.githubusercontent.com/1532418/63937626-19817b80-ca63-11e9-9005-1c1e00ac3e3c.png">
