### ISSUE TITLE
Translation: My Trees - English translation instead of German

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#853]
The word "gift" is not translated into German:

<img width="1177" alt="Bildschirmfoto 2019-05-31 um 15 04 00" src="https://user-images.githubusercontent.com/6512255/58707516-7e223100-83b5-11e9-8fef-4a85209369ad.png">

**Comment by mahmed0715** [comment]
#839 we were doing more modifications on those cards and that will fix all these issue I hope.

**Comment by jmiridis** [comment]
@sagararyal I need to know how detailed we want to expose the type of gift (coupon, voucher, direct gift, etc.) This is a UI decision in the first place.
