### ISSUE TITLE
Add dropdown to change locale

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#869]
Implement dropdown in the left menu to change user locale.

Save the locale to user profile.
@jmiridis --> provide a field in User Profile to set the current locale.

When user is logged in and changes the locale, the language has to be changed.

Example Web:
<img width="260" alt="Screen Shot 2019-06-04 at 10 14 51 AM" src="https://user-images.githubusercontent.com/5401575/58862737-a2ca2180-86b1-11e9-949d-f2c2247dd977.png">

If a user from German Browser visits `app.org/_locale=en` or `?noredirect`

The user has to see the English site, and future all links will be in English.
--> this has to be set either in User table or browser cookie.

However in a new session, language is determined by the browser.

**In addition**

Make Active Language API dependent

Jorgo will provide a list of languages that are available for user to choose.
Only those language should be used by client while looking for language files.

**Comment by jmiridis** [comment]
For now, language switching will be done on client side only.
Using the language drop-down will simply modify a variable in local storage that is used to set the locale in API calls.
The locales currently supported are `en` and `de`.

**Comment by rarawal** [comment]
saving language to user profile is not part of requirement. Please create a seperate github requirement so we dont lose the requirement in future if we close this on completion of this feature

**Comment by norbertschuler** [comment]
Also seems to be done.
