### ISSUE TITLE
Manage Plant Projects Page

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#870]
**1. Add a Card in Homepage**
<img width="368" alt="Screen Shot 2019-07-09 at 8 30 54 PM" src="https://user-images.githubusercontent.com/6512255/60913827-83ae4900-a288-11e9-8cdd-9fa101008f9b.png">

**2. Add Side Menu Item**
`Manage Projects`

**3. Create a Page to show projects**
You can reuse the Project Components used in other places.

**4. Add Plant Project Page**
<img width="412" alt="Screen Shot 2019-07-09 at 8 32 45 PM" src="https://user-images.githubusercontent.com/6512255/60913924-b7896e80-a288-11e9-8cde-cfd10636fe53.png">

**4. Edit Plant Project Page**
Option to Delete the Project from top menu

Designs are available at:
https://app.zeplin.io/project/5cad97d9b33d0b5931d90a9b/dashboard?seid=5d24dbeacc80634fa24616b4

**Comment by norbertschuler** [comment]
There is also a whole list of issues on the web version of plant project management:
- https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/955
- https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1172
- https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1817
- https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/2214
