### ISSUE TITLE
Translation: localized number formatting

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#880]
All numeric values should be displayed localized, e.g.

English: 0.2 Trees
German: 0,2 Bäume

English: 12,200,302 Trees
German: 12.200.302 Bäume

The same for amount of currency. There are libs for that purpose.

**Comment by mahmed0715** [comment]
PR created.

**Comment by mahmed0715** [comment]
updated pr as a feature branch. @norbertschuler

**Comment by norbertschuler** [comment]
Localization of the web client was successfully finished. Now only more some localization for the native apps is missing, e.g. in these components I want to add here from Slack as a small reminder:

<img width="403" alt="Bildschirmfoto 2019-08-20 um 15 34 42" src="https://user-images.githubusercontent.com/1532418/63424147-1a386300-c40e-11e9-8967-df8901532c10.png">

**Comment by mahmed0715** [comment]
I am working on Native part of this task.

**Comment by norbertschuler** [comment]
@mahmed0715 can you please use my work in progress for this page (I tried to make the styles much simpler as they have been now):

https://github.com/Plant-for-the-Planet-org/treecounter-app/tree/feature/880_number_format

![Simulator Screen Shot - iPhone X - 2019-08-21 at 15 57 31](https://user-images.githubusercontent.com/1532418/63438762-2aac0600-c42d-11e9-8f88-a4fc4f94bf00.png)
![Simulator Screen Shot - iPhone X - 2019-08-21 at 15 58 34](https://user-images.githubusercontent.com/1532418/63438763-2aac0600-c42d-11e9-8578-d46a433dbc2e.png)
