### ISSUE TITLE
Translation: localize all images with text

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#885]
There a some images used with English text in the image. We either need to have images without text or localized images for every supported language:
Logos:
![TTC_footer_logos](https://user-images.githubusercontent.com/1532418/59025864-6800ee80-8855-11e9-9ca0-f09dca98cf36.png)

Legend 1:
![Legend_Trees](https://user-images.githubusercontent.com/1532418/59025866-6800ee80-8855-11e9-90b8-15f4f6109e41.png)

Legend 2:
![Legend_TreeDensity](https://user-images.githubusercontent.com/1532418/59025868-6800ee80-8855-11e9-936b-9d62d32f3b96.png)

Legend 3:
![Legend_Restoration](https://user-images.githubusercontent.com/1532418/59025869-6800ee80-8855-11e9-80ac-13ddfcb7b75a.png)

**Comment by sagararyal** [comment]
https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1293 is related

**Comment by norbertschuler** [comment]
Old webapp is deprecated, so this is no more relevant.
