### ISSUE TITLE
Plant Projects Ordering (Featured, List, Price, Country)

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#888]
To be applied automatically when the page loads:

Featured : Load by Oldest to Newest
List: Sort alphabetically A - Z
Price: Sort by Low to High
Country: Sort alphabetically by Country (A - Z)

**Comment by sagararyal** [comment]
Reopening this, as web part needs to implemented as well ( for Featured)

**Comment by hkurra** [comment]
@sagararyal Acknowledged

**Comment by norbertschuler** [comment]
@sagararyal Seems to be solved. I see the three featured projects in the same order in the iOS app and the web client. Please close if solved.

**Comment by mahmed0715** [comment]
if this issue is not visible anymore we can close this ? @sagararyal
