### ISSUE TITLE
Make Gender field a Dropdown in Edit Profile

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#890]
Instead of text field, make gender field a dropdown.
Applies to both web and mobile apps

<img width="357" alt="Screen Shot 2019-06-07 at 10 03 26 AM" src="https://user-images.githubusercontent.com/5401575/59089939-a5c04e80-890b-11e9-95c5-506cb69147b0.png">

**Comment by norbertschuler** [comment]
O.k., I just checked it again and it looks good:

<img width="732" alt="Bildschirmfoto 2019-07-10 um 12 29 41" src="https://user-images.githubusercontent.com/1532418/60943030-eba77280-a30e-11e9-8301-4b353e60744a.png">

![IMG_8E238A2AADB9-1](https://user-images.githubusercontent.com/1532418/60943035-eba77280-a30e-11e9-9965-7d814943e9ed.jpeg)
