### ISSUE TITLE
Map Components for Mobile

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#896]
Develop Map Components for Mobile to display geojson features inc. Polygon and Coordinates.

Components need to be added as cards in Single Plant Project Page, Single Contribution page and User home

If the project/contribution has geojson with ndvi =available or stale capability
show two maps,

Based on user input from a dropdown, these maps will load the tile as returned by third party API.

Designs available at:
https://app.zeplin.io/project/5cad97d9b33d0b5931d90a9b/dashboard?seid=5cfa38636e245a5d9ad7860c

**Comment by norbertschuler** [comment]
Abandoned.
