### ISSUE TITLE
Prepare for SCA Update

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#897]
Prepare the client for SCA.

A two factor credit card authentication.
<img width="536" alt="Screen Shot 2019-06-07 at 1 03 19 PM" src="https://user-images.githubusercontent.com/5401575/59099862-ac0ef480-8924-11e9-9025-93d8328e612e.png">

Stripe has a helpful guide 
https://stripe.com/en-de/payments/strong-customer-authentication
Need Implementation to all clients by September 14, 2019.

**Comment by niteshgrg** [comment]
@sagararyal as for this we would be updating to payment intents. @jmiridis has added support for recurring donations as well with this update in backend support.

Do we have a UI for it as well. @sagararyal

**Comment by rarawal** [comment]
@sagararyal

**Comment by sagararyal** [comment]
@niteshgrg this work item does not deal with recurrence. Rest you can discuss with @rarawal or @himpatel

**Comment by norbertschuler** [comment]
Seems to be done.
