### ISSUE TITLE
Error in SvgContainer

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#927]
## Error in Plant-for-the-Planet App

**TypeError** in **/login**
Unable to get property 'length' of undefined or null reference

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d0535ad6b53ca0019b926c5?event_id=5d08f37c00443a602acf0000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/bundle.js:39 - value

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d0535ad6b53ca0019b926c5?event_id=5d08f37c00443a602acf0000&i=gh&m=ci)

*Created by Norbert Schuler via Bugsnag*

**Comment by crucialfelix** [comment]
Note: Errors still happening, but they are all app versions 1.0.3 or earlier
