### ISSUE TITLE
Error /

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#934]
## Error in Plant-for-the-Planet App

**Error** in **/**
Request failed with status code 404

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d0551c6bd8eaa001aa19219?event_id=5d08cda400442ea25dc70000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/bundle.js:28 - exports

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d0551c6bd8eaa001aa19219?event_id=5d08cda400442ea25dc70000&i=gh&m=ci)

*Created by Norbert Schuler via Bugsnag*

**Comment by norbertschuler** [comment]
closed as not happening since a week
