### ISSUE TITLE
Sort My Trees, by Added on Date

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#949]
In Mobile Apps,

Sort My Trees by Added on Date.

![Screenshot_20190621-111601_Plant](https://user-images.githubusercontent.com/5401575/59912360-302da580-9416-11e9-987b-c0df4add7dd6.jpg)

**Comment by norbertschuler** [comment]
related to https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1436 (getting null dates from the API for some results)

**Comment by sagararyal** [comment]
Closing this, as My Trees will use new design in Mobile
