### ISSUE TITLE
TPO Dashboard Progress is lost in case of error

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#955]
When creating / saving a Plant Project,
if error shows up eg: Network Error or anything related,

All progress and Text is Lost.

<img width="1431" alt="Screen Shot 2019-06-21 at 11 54 37 AM" src="https://user-images.githubusercontent.com/5401575/59914823-7f2a0980-941b-11e9-9db9-c5e4dff146bb.png">

**Comment by norbertschuler** [comment]
Closing as related to old web client.
