### ISSUE TITLE
Feature: Review Plant Projects

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#958]
The feature allows selected users (often Scientists, and Forestry Students) to review a Tree Planting Projects.

Reviews are accessible by anyone who visits the app/project. The goal of this feature is to add crowdsourced authenticity to the Plant Projects.

Reviews are accessible from Single Plant Project Page:
<img width="303" alt="Screen Shot 2019-06-21 at 1 20 22 PM" src="https://user-images.githubusercontent.com/5401575/59919318-66bfec00-9427-11e9-9e30-01061e7e454a.png">

**Preview Component in Single Plant Project Page**
`canReview` = A user has permissions to write a review
details on UI are available in Zeplin.

Case 1. canReview and no reviews exist
Show the card with the button

Case 2. canReview and reviews exist
Show the second card

Case 3. can'tReview and reviews exist
Show third Card

Case 4. can'tReview and no reviews exist
Do not show the Card.

##Page Community Reviews

Designs are available in Zeplin.
https://app.zeplin.io/project/5cad97d9b33d0b5931d90a9b/dashboard?seid=5d2c932da1f25163f007d9cb

**Comment by norbertschuler** [comment]
@sagararyal decide about closing or not.
