### ISSUE TITLE
TypeError in /pledge/kirchentag

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#965]
## Error in Plant-for-the-Planet App

**TypeError** in **/pledge/kirchentag**
undefined is not an object (evaluating 'e.response.data')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d0d2d34369c44001b09a3e6?event_id=5d0d2d340044e230af2c0000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/bundle.js:329 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d0d2d34369c44001b09a3e6?event_id=5d0d2d340044e230af2c0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
similar to #966

**Comment by norbertschuler** [comment]
expired
