### ISSUE TITLE
window.onerror in /explore

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#968]
## Error in Plant-for-the-Planet App

**window.onerror** in **/explore**
Uncaught ReferenceError: Map is not defined

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d0dedcc6c5dcf00199b3728?event_id=5d0dedcc0044663671440000&i=gh&m=ci)

## Stacktrace

    blob:https%3A//www.trilliontreecampaign.org/3efe9749-8bf3-455b-8281-6966481559f6:4 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d0dedcc6c5dcf00199b3728?event_id=5d0dedcc0044663671440000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
another argis error, but without tracktrace, closing it
