### ISSUE TITLE
Error in /pledge/kirchentag

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#972]
## Error in Plant-for-the-Planet App

**Error** in **/pledge/kirchentag**
Network Error

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d10a78314724a0019403f79?event_id=5d10a783004463d07ff00000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/bundle.js:28 - e.exports

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d10a78314724a0019403f79?event_id=5d10a783004463d07ff00000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
network error already discussed - closing this
