### ISSUE TITLE
InternalError in /donate-trees

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#978]
## Error in Plant-for-the-Planet App

**InternalError** in **/donate-trees**
too much recursion

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d10fcf2a2fcfc0018a62555?event_id=5d10fcf200446a4271140000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/bundle.js:325 - InnerSlider/n.checkImagesLoad/</e.onclick

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d10fcf2a2fcfc0018a62555?event_id=5d10fcf200446a4271140000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Can not any more be reproduced or debugged as Bugsnag issue got deleted automatically.
